Malabranch
EbookFoundation/free-programming-books pull request #10014
Opened 2023-10-08 16:56 UTC by Bib711

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2023-10-08 16:57 UTC, Bib711 commented
Translated HOWTO.md to MALAYALAM

2023-10-09 02:47 UTC, eshellman commented
also need to add link in README

2023-10-09 02:58 UTC, Bib711 commented
What link?

2023-10-09 03:08 UTC, eshellman commented
link to the adde file

2023-10-09 03:56 UTC, gaurovgiri approved these changes

2023-10-09 05:17 UTC, rashivkp requested changes
PR seems like word by word translation. :smile:   Anyway trying to improve it a bit.

2023-10-09 05:17 UTC, rashivkp commented on docs/HOWTO-ml.md
> +ചോദ്യങ്ങൾ ചോദിക്കാൻ മടിക്കരുത്; എല്ലാ സംഭാവകരും ഒരു ആദ്യ PR-ൽ ആരംഭിച്ചു. അതിനാൽ... എന്തുകൊണ്ട് നമ്മുടെ [വലിയ, വളരുന്ന](https://www.apiseven.com/en/contributor-graph?chart=contributorOverTime&repo=ebo
```suggestion
ചോദ്യങ്ങൾ ചോദിക്കാൻ മടിക്കരുത്; എല്ലാ സംഭാവകരും തുടങ്ങിയത് ഒരു ആദ്യ PR കൊണ്ടാണ്. അതിനാൽ... എന്തുകൊണ്ട് നമ്മുടെ [വലിയ, വളരുന്ന](https://www.apiseven.com/en/contributor-graph?chart=contributorOverTime&repo=ebookfoundation/free-programming-books) സമൂഹത്തിൽ ചേരുന്നില്ല.
```

2023-10-09 05:17 UTC, rashivkp commented on docs/HOWTO-ml.md
> +നിങ്ങൾ അനുഭവപരിചയമുള്ള ഒരു ഓപ്പൺ സോഴ്‌സ് സംഭാവകനാണെങ്കിൽ പോലും, നിങ്ങളെ ഞെരുക്കിയേക്കാവുന്ന ചില കാര്യങ്ങളുണ്ട്. നിങ്ങളുടെ പിആർ സമർപ്പിച്ചുകഴിഞ്ഞാൽ,***GitHub പ്രവർത്തനങ്ങൾ* ഒരു *ലിന്റർ* പ്രവർത്തിപ്പിക
```suggestion
നിങ്ങൾ അനുഭവപരിചയമുള്ള ഒരു ഓപ്പൺ സോഴ്‌സ് സംഭാവകനാണെങ്കിൽ പോലും, ചില കാര്യങ്ങള്‍ നിങ്ങളെ പ്രയാസപ്പെടുത്തിയേക്കാം. നിങ്ങളുടെ പിആർ സമർപ്പിച്ചുകഴിഞ്ഞാൽ,***GitHub Actions* ഒരു *ലിന്റർ* പ്രവർത്തിപ്പിക്കും, പലപ്പോഴും സ്പെയ്സിംഗിലോ അക്ഷരമാലാക്രമത്തിലോ ചെറിയ പ്രശ്നങ്ങൾ കണ്ടെത്തും**. നിങ്ങൾക്ക് ഒരു പച്ച ബട്ടൺ ലഭിക്കുകയാണെങ്കിൽ, എല്ലാം അവലോകനത്തിന് തയ്യാറാണ്; ഇല്ലെങ്കിൽ, ലിന്ററിന് ഇഷ്ടപ്പെടാത്തത് എന്താണെന്ന്  മനസ്സിലാക്കാന്‍ ചെക്കിന് താഴെയുള്ള "വിശദാംശങ്ങൾ" ക്ലിക്ക് ചെയ്യുക, കൂടാതെ നിങ്ങളുടെ പിആർ തുറന്ന ബ്രാഞ്ചിലേക്ക് ഒരു പുതിയ commit ചേര്‍ത്ത് പ്രശ്നം പരിഹരിക്കുക.
```

2023-10-09 05:17 UTC, rashivkp commented on docs/HOWTO-ml.md
> +• [YouTube - മാർക്ക്ഡൗൺ ക്രാഷ് കോഴ്സ്](https://www.youtube.com/watch?v=HUBNt18RFbo)
```suggestion
• [YouTube - Markdown ക്രാഷ് കോഴ്സ്](https://www.youtube.com/watch?v=HUBNt18RFbo)
```

2023-10-10 02:03 UTC, Bib711 commented
Ok

2023-12-10 04:24 UTC, Vaporjawn commented
@eshellman I've addressed the comments with [this PR](https://github.com/EbookFoundation/free-programming-books/pull/11000), if you'd like to move along with this instead

2023-12-10 09:51 UTC, felixdiria commented
Diff

2023-12-12 17:49 UTC, eshellman commented
closed following #11000

2023-12-12 17:49 UTC, closed without merging