(COURSES) : Added courses links for the Marathi language
EbookFoundation/free-programming-books pull request #10094
Opened 2023-10-10 05:06 UTC by Atharva1723

## What does this PR do?
Created a new markdown file for the new language Marathi.Added links to programming free courses
## For resources
Youtube playlists
### Why is this valuable (or not)?
Yes, this is valuable as the free courses for Marathi languages were not added before.
### How do we know it's really free?
You can test those links 
### For book lists, is it a book? For course lists, is it a course? etc.
The markdown file I created is for courses
## Checklist:
- [ ✓ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ✓ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ✓ ] Include author(s) and platform where appropriate.
- [ ✓ ] Put lists in alphabetical order, correct spacing.
- [ ✓ ] Add needed indications (PDF, access notes, under construction).
- [ ✓ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2023-10-10 05:10 UTC, Atharva1723 commented
@eshellman I have added one more Indian language Marathi. Please review this pr and let me know if there are changes required!

2023-10-10 21:08 UTC, eshellman requested changes
nice job, just one nit

2023-10-10 21:08 UTC, eshellman commented on courses/free-courses-mr.md
> +* [HTML | HTML For Beginners | Krushna Pise | Marathi Programmer](https://youtube.com/playlist?list=PLWSZr_wlNWaw8_iFhKvrPKp1Uh2S1dXHk) - MaRaTHi ProGrammer
escape the `|`

2023-10-11 16:44 UTC, Atharva1723 commented
@eshellman I have made the necessary changes

2023-10-11 18:47 UTC, eshellman commented on courses/free-courses-mr.md
> +* [Angular Tutorials in Marathi](https://youtube.com/playlist?list=PLMs908ICeVMEBw4CevNdPvvIJDaQV1ISN) - Developers Marathi
sorry, one more nit. could you switch the order of the Angular course so it's alphabetical? thanks

2023-10-12 02:15 UTC, closed without merging