add courses of sass, logic and bootstrap
EbookFoundation/free-programming-books pull request #10137
Opened 2023-10-11 00:23 UTC by priscillatrevizan

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2023-10-11 17:03 UTC, eshellman requested changes
Programming logic? Could that be Algorithms?

2023-10-11 17:03 UTC, eshellman commented on courses/free-courses-pt_BR.md
> +* [Curso de Sass](https://www.youtube.com/playlist?list=PL97KElaimHeGRtfkksKwxg6IGVZi_cR7J) - Amanda Vilela (YouTube)
```suggestion
* [Curso de Sass](https://www.youtube.com/playlist?list=PL97KElaimHeGRtfkksKwxg6IGVZi_cR7J) - Amanda Vilela
```

2023-10-11 17:03 UTC, eshellman commented on courses/free-courses-pt_BR.md
> +### Lógica de Programação
It's usually not helpful to add a category for a single resource. Try to find another category, or see if there are other books in our lists that would fit into your category.

2023-10-11 17:03 UTC, eshellman commented on courses/free-courses-pt_BR.md
> +* [Curso de HTML, CSS e Bootstrap](https://www.youtube.com/playlist?list=PL8iIphQOyG-Cv3auRYoZtbvzJJrsvdMy-) - Michelli Brito (YouTube)
```suggestion
* [Curso de HTML, CSS e Bootstrap](https://www.youtube.com/playlist?list=PL8iIphQOyG-Cv3auRYoZtbvzJJrsvdMy-) - Michelli Brito
```
For youtube, we prefer "playlist" links and the name of the producer/creator. docs/CONTRIBUTING.md#platforms-and-access-notes

2023-10-11 19:43 UTC, priscillatrevizan commented
@eshellman 
changes made, ready for code review

2023-10-12 00:24 UTC, eshellman commented on courses/free-courses-pt_BR.md
> +* [Curso de HTML, CSS e Bootstrap - Aula 1 de 6 ](https://www.youtube.com/watch?v=QZ8mu8vuOpg&list=PL8iIphQOyG-Cv3auRYoZtbvzJJrsvdMy-&index=1) - Michelli Brito (YouTube)
is there no playlist we can use for this?
For youtube, we prefer "playlist" links and the name of the producer/creator. docs/CONTRIBUTING.md#platforms-and-access-notes
Maybe we should find a different link for the Gustavo Guanabara modules.

2023-11-09 22:30 UTC, closed without merging