Update free-programming-books-langs.md
EbookFoundation/free-programming-books pull request #10170
Opened 2023-10-11 13:43 UTC by hriprsd

Added jenkins ebooks pdf links

## What does this PR do?
Add resource(s) 

## For resources
### Description

### Why is this valuable (or not)?
Solves #10031 

### How do we know it's really free?
I have used it before and also, its from trusted free use sources.

### For book lists, is it a book? For course lists, is it a course? etc.
These are books that guide reader through Jenkins learning.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2023-10-11 18:30 UTC, eshellman requested changes

2023-10-11 18:30 UTC, eshellman commented on books/free-programming-books-langs.md
> +* [Jenkins Starter Guide](https://bugfender.com/wp-content/themes/bugfender-wordpress-theme/assets/docs/Jenkins-Starter-Guide-Ebook.pdf) (PDF)
```suggestion
* [Jenkins Starter Guide Ebook](https://bugfender.com/wp-content/themes/bugfender-wordpress-theme/assets/docs/Jenkins-Starter-Guide-Ebook.pdf) (PDF)
```
Don't invent titles! Use the title given by the resource.

2023-10-11 18:30 UTC, eshellman commented on books/free-programming-books-langs.md
> +* [Jenkins Essentials](https://raw.githubusercontent.com/rootusercop/Free-DevOps-Books-1/6dd8ee5bef93d2a1489a3761515ecbaf16c118cc/book/Jenkins%20Essentials.pdf) (PDF)
This appears not to be an authorized distribution. Please see docs/CONTRIBUTING.md guidelines. Remove it

2023-10-12 07:18 UTC, hriprsd commented on books/free-programming-books-langs.md
> +* [Learning Jenkins](https://riptutorial.com/Download/jenkins.pdf) (PDF)
Thanks for the review. Fixed review comments.

2023-10-13 01:49 UTC, eshellman commented on books/free-programming-books-langs.md
> +* [Jenkins 2: Up and Running](https://theswissbay.ch/pdf/Books/Computer%20science/jenkins2_upandrunning.pdf) (PDF)
This appears not to be an authorized distribution. Please see docs/CONTRIBUTING.md guidelines. remove it.

2023-10-14 16:58 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2023-10-14 16:58 UTC, merged