(COURSE): Added the marathi langauge courses markdown file
EbookFoundation/free-programming-books pull request #10211
Opened 2023-10-12 02:25 UTC by Atharva1723

## What does this PR do?
Added free courses to the Marathi language playlists on youtube 

## For resources
YouTube

### Description
Added some good playlists links to programming languages such as html,css, angular,python etc in marathi language

### Why is this valuable (or not)?
Yes This is valuable as the marathi language courses was not added before and this is the new pr

### How do we know it's really free?
You can test the links 
### For book lists, is it a book? For course lists, is it a course? etc.
It is a markdown file for courses 
## Checklist:
- [ ✓] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ✓] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ✓] Include author(s) and platform where appropriate.
- [ ✓] Put lists in alphabetical order, correct spacing.
- [ ✓] Add needed indications (PDF, access notes, under construction).
- [✓ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2023-10-12 02:27 UTC, Atharva1723 commented
@eshellman please review this

2023-10-12 17:40 UTC, Atharva1723 commented
@eshellman also please review the code of conduct

2023-10-13 03:43 UTC, 3R1Dev requested changes
Just a few things to change.

2023-10-13 03:43 UTC, 3R1Dev commented on courses/free-courses-mr.md
> +### <a id="csharp"></a>C
Forgot to add the #

```suggestion
### <a id="csharp"></a>C#
```

2023-10-13 03:43 UTC, 3R1Dev commented on courses/free-courses-mr.md
> +* [C#](#csharp)
Need to add C++ section

2023-10-13 03:43 UTC, 3R1Dev commented on courses/free-courses-mr.md
> +* [PLC](#plc)
This is not used, better to remove it

```suggestion
```

2023-10-13 03:48 UTC, eshellman commented
it is very difficult for the reviewers if you close the PR where the review comments have been made. Please use separate branches and separate PRs for the course list and the code of conduct, as different reviews are needed for each. Please remove code of conduct from this PR and create a fresh branch for it.

2023-10-13 04:10 UTC, Atharva1723 commented
@eshellman mb. I will make sure next time

2023-10-13 05:02 UTC, Atharva1723 commented
@eshellman  Is this okay?

2023-10-14 16:56 UTC, eshellman commented
Thank you!

2023-10-14 16:56 UTC, merged