Adding new course
EbookFoundation/free-programming-books pull request #10247
Opened 2023-10-12 19:09 UTC by Ashu104

## What does this PR do?
Add resource(s)

### Description
new free course on graph theory is added

### Why is this valuable (or not)?
design and taught by MIT professor.

### How do we know it's really free?
content freely available on MIT's OCW. 

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2023-10-13 02:03 UTC, 3R1Dev approved these changes
Everything looks good, thanks for the  PR

2023-10-13 05:50 UTC, Ashu104 commented
hi @3R1Dev .
I'm glad for your response. yah. its been nice to be part of this amazing project.

2023-10-14 17:14 UTC, eshellman requested changes

2023-10-14 17:14 UTC, eshellman commented on courses/free-courses-en.md
> +* [Graph Theory And Additive Combinatorics](https://ocw.mit.edu/courses/18-217-graph-theory-and-additive-combinatorics-fall-2019/video_galleries/video-lectures/) -Prof. Yufei Zhao (MIT)
```suggestion
* [Graph Theory And Additive Combinatorics](https://ocw.mit.edu/courses/18-217-graph-theory-and-additive-combinatorics-fall-2019/video_galleries/video-lectures/) - Prof. Yufei Zhao (MIT)
```
good addition!

2023-10-14 17:14 UTC, eshellman commented on more/free-programming-cheatsheets.md
> +* [Data Science Cheat Sheets](https://medium.com/analytics-vidhya/data-science-cheat-sheets-109ddcb1aca8) - Surya Gutta (HTML, PDF)
This is a blog post that embeds 3 cheatsheets from other sites. We prefer to link directly (and give credit to) to the original sources.

2023-10-14 17:14 UTC, eshellman commented on more/free-programming-cheatsheets.md
> +* [Data Science Cheatsheets](https://goodjob0823.github.io/Data-Science-Cheat-Sheets) - goodjob0823 (HTML, PDF)
this is a list of links to cheat sheets. Our list is not a list of lists. romove this.

2023-10-14 17:14 UTC, eshellman commented on more/free-programming-cheatsheets.md
> +* [Cheat Sheet of Machine Learning and Python (and Math) Cheat Sheets](https://medium.com/machine-learning-in-practice/cheat-sheet-of-machine-learning-and-python-and-math-cheat-sheets-a4afe4e791b6) -
this is another list. remove it.

2023-10-14 17:14 UTC, eshellman commented on more/free-programming-cheatsheets.md
> +* [Machine Learning Glossary](https://ml-cheatsheet.readthedocs.io/en/latest) - ml-cheatsheet (HTML)
```suggestion
* [Machine Learning Glossary](https://ml-cheatsheet.readthedocs.io/en/latest) - Brendan Fortuner
```

2023-10-18 04:36 UTC, Ashu104 commented
@3R1Dev 
can you please consider the changes I've made after your suggestions.

2023-10-18 16:25 UTC, eshellman requested changes

2023-10-18 16:25 UTC, eshellman commented on courses/free-courses-en.md
> +* [Graph Theory And Additive Combinatorics](https://ocw.mit.edu/courses/18-217-graph-theory-and-additive-combinatorics-fall-2019/video_galleries/video-lectures/) - Prof. Yufei Zhao (MIT)
we don't list honorifics such as "Prof."

2023-10-19 16:00 UTC, eshellman commented
it seems you are not using a fresh branch for new PRs. As a result, new problems are introduced after the reviews! Please rebase to the version  that has been reviewed.

2023-10-19 17:34 UTC, closed without merging