Update free-programming-books-langs.md
EbookFoundation/free-programming-books pull request #10259
Opened 2023-10-13 04:35 UTC by adarsh-jha-dev

## What does this PR do?
I have added a couple of free eBooks in the C++ section. 

## For resources
### Description
The books which i have added are : 

- Practical C++ Programming by Steve Oualline (https://www.mimuw.edu.pl/~mrp/cpp/SecretCPP/O'Reilly%20-%20Practical%20C++%20Programming.pdf) - Steve Oualline (PDF)
- Lecture Notes On Object Oriented Programming Using C++ (https://www.cet.edu.in/noticefiles/285_OOPS%20lecture%20notes%20Complete.pdf) - Dr. Subasish Mohapatra (PDF)

### Why is this valuable (or not)?
I have read those eBooks and it seems beneficial for beginners.

### How do we know it's really free?
I have cross-verified by checking the links and reading those books

### For book lists, is it a book? For course lists, is it a course? etc.
These are books.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [*] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [*] Include author(s) and platform where appropriate.
- [*] Put lists in alphabetical order, correct spacing.
- [*] Add needed indications (PDF, access notes, under construction).
- [*] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2023-10-13 05:09 UTC, 3R1Dev commented
Both of the added links are to sub directories from schools, the links appear to be intended for use inside class
or for students. While they can be found via web scrapping methods, the authority of sharing those links is questionable.

It is possible the school has permission to share them but unless you can know with 100% certainty it is better to not add them.

2023-10-13 06:16 UTC, adarsh-jha-dev commented
These books are publicly available on the internet so it's evident that the school doesn't care about this. Also where i got these books from, there is nothing mentioned about the School and all. Even after this if you want i can remove these books and replace with some other ones. Please do let me know about this.

2023-10-13 07:01 UTC, adarsh-jha-dev commented
I have removed that particular book which was creating problem and have replaced it with another free eBook.

2023-10-13 13:06 UTC, sohansai commented on books/free-programming-books-langs.md
> +* [Object Oriented Programming using 'C++'](https://www.ddegjust.ac.in/studymaterial/msc-cs/ms-17.pdf) - Pooja Chawla (PDF)
The link you provided isn't a book; it appears to be a study material for a university course.

2023-10-13 16:06 UTC, adarsh-jha-dev commented
I have resolved all the issues with the newly added books. I have removed those problematic ones and replaced it with some good ones.

2023-10-15 00:25 UTC, adarsh-jha-dev commented
I have resolved all the issues by replacing those books, i request you to please merge these changes after verifying the same.

2023-10-15 21:20 UTC, eshellman requested changes
the tutorialspoint book is ok, remove the others.

2023-10-15 21:20 UTC, eshellman commented on books/free-programming-books-langs.md
> +* [C++ In Action: Industrial Strength Programming Techniques](http://www.worldcolleges.info/sites/default/files/C%2B%2B_In_Action.pdf) - Bartosz Milewski (PDF)
It's published by Pearson, they don't even let the author distribute it. Also it's >25 years old. We won't bother with it..

2023-10-15 21:20 UTC, eshellman commented on books/free-programming-books-langs.md
> +* [Practical C++ Programming by Steve Oualline](https://www.mimuw.edu.pl/~mrp/cpp/SecretCPP/O'Reilly%20-%20Practical%20C++%20Programming.pdf) - Steve Oualline (PDF)
This appears not to be an authorized distribution. Please see docs/CONTRIBUTING.md guidelines.

2023-10-16 13:14 UTC, adarsh-jha-dev commented
Other than the tutorials point's one, i have removed all the unauthorized distributed books.

2023-10-16 18:13 UTC, merged