Update free-courses-hi.md
EbookFoundation/free-programming-books pull request #10255
Opened 2023-10-13 03:51 UTC by ThakareSakshi

added swift tutorial in Hindi by code cat

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description
Added swift programming course in Hindi

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2023-10-13 04:02 UTC, 3R1Dev requested changes
Update the title of the course.

2023-10-13 04:02 UTC, 3R1Dev commented on courses/free-courses-hi.md
> +* [Swift programming hindi tutorial for beginners](https://www.youtube.com/playlist?list=PLb5R4QC2DtFv3MvfG42Cd5La34Hwj4pY6) - Code Cat
Playlist check out, I would suggest changing the title to be Uppercase as in the suggestion below.

```suggestion
* [Swift Programming Hindi Tutorial for Beginners](https://www.youtube.com/playlist?list=PLb5R4QC2DtFv3MvfG42Cd5La34Hwj4pY6) - Code Cat
```

2023-10-13 06:09 UTC, 3R1Dev approved these changes
Looks good, thanks for the contribution!

2023-10-14 17:23 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2023-10-14 17:23 UTC, merged