Code of Conduct for Marathi language added .
EbookFoundation/free-programming-books pull request #10417
Opened 2023-10-17 04:40 UTC by Atharva1723

## What does this PR do?
This PR adds Code of Conduct for marathi language 

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2023-10-17 11:55 UTC, Atharva1723 commented
@eshellman Please review this PR and let me know if any changes are required?

2023-10-18 03:24 UTC, eshellman commented
will request language review

2023-10-20 12:26 UTC, Atharva1723 commented
?

2023-11-05 12:31 UTC, Atharva1723 commented
@eshellman Please merge this PR ! Thank You :)

2023-11-05 19:21 UTC, eshellman commented
perhaps @AryavT can review?

2023-11-18 10:03 UTC, Atharva1723 commented
Any update on the PR ?

2023-11-20 13:13 UTC, eshellman commented
I've added the "keep" label to this PR so It won't get marked as stale. A constructive review is worth waiting for.

2023-11-20 13:14 UTC, Atharva1723 commented
Okay thankyou

2023-11-20 15:15 UTC, rajan-31 requested changes
I have added comments for suggested changes for individual files.

2023-11-20 15:15 UTC, rajan-31 commented on docs/CODE_OF_CONDUCT-mr.md
Many changes done, you can just copy content below in place of current content of CODE_OF_CONDUCT-mr.md
---------------------------------------------------------------

# योगदानकर्ता आचरण संहिता

या प्रकल्पाचे योगदानकर्ते आणि देखरेख करणारे म्हणून, आणि खुल्या आणि स्वागतार्ह समुदायाला चालना देण्याच्या हितासाठी, आम्ही समस्यांचा अहवाल देणे, वैशिष्ट्य विनंत्या पोस्ट करणे, दस्तऐवज अद्यतनित करणे, पुल विनंत्या किंवा पॅच सबमिट करणे आणि इतर क्रियाकलापांद्वारे योगदान देणाऱ्या सर्व लोकांचा आदर करण्याचे वचन देतो.

अनुभवाची पातळी, लिंग, लिंग ओळख आणि अभिव्यक्ती, लैंगिक अभिमुखता, अपंगत्व, वैयक्तिक स्वरूप, शरीराचा आकार, वंश, वांशिकता, वय, धर्म, किंवा राष्ट्रीयत्व याची पर्वा न करता या प्रकल्पातील सहभाग हा प्रत्येकासाठी छळमुक्त अनुभव बनवण्यासाठी आम्ही वचनबद्ध आहोत.

सहभागींच्या अस्वीकार्य वर्तनाच्या उदाहरणांमध्ये हे समाविष्ट आहे:

* लैंगिक भाषा किंवा प्रतिमा वापरणे
* वैयक्तिक हल्ले
* ट्रोलिंग किंवा अपमानास्पद/मानहानीकारक टिप्पण्या
* सार्वजनिक किंवा खाजगी छळ
* स्पष्ट परवानगीशिवाय इतरांची खाजगी माहिती प्रकाशित करणे, जसे की भौतिक किंवा इलेक्ट्रॉनिक पत्ते
* इतर अनैतिक किंवा अव्यावसायिक आचरण

या आचरणसंहितेशी संरेखित नसलेल्या टिप्पण्या, कमिट, कोड, विकी संपादने, मुद्दे आणि इतर योगदान काढून टाकण्याचा, संपादित करण्याचा किंवा नाकारण्याचा किंवा अनुचित, धमकी देणारे, आक्षेपार्ह, हानिकारक वाटणाऱ्या इतर वर्तनांसाठी तात्पुरते किंवा कायमस्वरूपी बंदी घालण्याचा अधिकार प्रकल्प देखभालकर्त्यांना आहे.

या आचरणसंहितेचा अवलंब करून, प्रकल्प देखरेख करणारे या प्रकल्पाचे व्यवस्थापन करण्याच्या प्रत्येक पैलूवर ही तत्त्वे निष्पक्ष आणि सातत्यपूर्णपणे लागू करण्यासाठी स्वतःला वचनबद्ध करतात. आचरणसंहितेचे पालन न करणार्‍या किंवा त्यांची अंमलबजावणी न करणार्‍या प्रकल्प देखभाल करणार्‍यांना प्रकल्प कार्यसंघातून कायमचे काढून टाकले जाऊ शकते.

ही आचरण संहिता प्रकल्पाच्या जागेत आणि सार्वजनिक जागांवर लागू होते जेव्हा एखादी व्यक्ती प्रकल्पाचे किंवा त्याच्या समुदायाचे प्रतिनिधित्व करत असते.

अपमानास्पद, त्रासदायक किंवा अन्यथा अस्वीकार्य वर्तनाची घटना maintainer at victorfelder at gmail.com वर प्रकल्प देखभालकर्त्याशी संपर्क साधून नोंदवली जाऊ शकते. सर्व तक्रारींचे पुनरावलोकन केले जाईल आणि तपासले जाईल आणि परिणामी आवश्यक आणि परिस्थितीनुसार योग्य असा प्रतिसाद मिळेल. एखाद्या घटनेच्या रिपोर्टरच्या संदर्भात गोपनीयता राखणे देखभाल करणार्‍यांना बंधनकारक आहे.


ही आचरण संहिता [Contributor Covenant] [homepage] वरून स्वीकारली आहे, आवृत्ती १.३.०, https://contributor-covenant.org/version/1/3/0/ वर उपलब्ध आहे

[homepage]: https://contributor-covenant.org

[Translations](README.md#translations)

2023-11-20 22:19 UTC, eshellman commented
Thank you @Atharva1723 and @rajan-31 !

2023-11-20 22:19 UTC, merged