Cppcourse
EbookFoundation/free-programming-books pull request #10419
Opened 2023-10-17 06:20 UTC by Ajay-singh1

## What does this PR do?
Add resource(s) 

## For resources
Youtube
### Description
Added C++ Course in the newly created Hindi/Urdu File
### Why is this valuable (or not)?
It is very valuable for those interested in Computer Science Engineering or particularly Computer Science.
### How do we know it's really free?
Beacuse it is available on youtube
### For book lists, is it a book? For course lists, is it a course? etc.
It is a course
## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2023-10-17 06:21 UTC, Ajay-singh1 commented
@eshellman I will try to work on the Hindi/Urdu File.

2023-10-18 02:19 UTC, eshellman requested changes
if you add something here that's also in the hindu list, you should remove it from there

2023-10-18 02:19 UTC, eshellman commented on courses/free-courses-ur.md
> +### C++
need a link anchor here. see other lists

2023-10-18 02:19 UTC, eshellman commented on courses/free-courses-ur.md
> +* [C++](#cplusplus)
should be in alphabetical order

2023-10-18 02:19 UTC, eshellman commented on courses/free-courses-ur.md
> +* [Javascript Tutorials In Urdu and Hindi](https://www.youtube.com/watch?v=Lgxgm-T9cgA&list=PL0b6OzIxLPbx-BZTaWu_AF7hsKo_Fvsnf) - Yahoo Baba
For youtube, we prefer "playlist" links and the name of the producer/creator. docs/CONTRIBUTING.md#platforms-and-access-notes

2023-10-18 02:19 UTC, eshellman commented on courses/free-courses-ur.md
> +* [Learn JavaScript in Urdu & Hindi - For Beginners - Introduction](https://www.youtube.com/watch?v=NKgdmmiPVUc&list=PL52B8F99BC6AD1647) - WP Academy
For youtube, we prefer "playlist" links and the name of the producer/creator. docs/CONTRIBUTING.md#platforms-and-access-notes

2023-10-18 03:42 UTC, Ajay-singh1 commented
@eshellman Kindly Review the changes and suggest me why the lint is fauiling.

2023-10-18 04:09 UTC, Ajay-singh1 commented
@eshellman We are good to go!

2023-10-18 15:48 UTC, eshellman commented on courses/free-courses-ur.md
> +* [C++](#cplusplus)
`C` comes before `H`

2023-10-18 16:13 UTC, Ajay-singh1 commented
@eshellman I think I have opened duplicate PRs this PR will solve #10407 and #10418 , I am closing both the PRs and work on this one only.Will remind you once after the work is done.

2023-10-18 17:41 UTC, eshellman commented
Please delete the duplicate course in the hindi list

2023-10-19 00:44 UTC, Ajay-singh1 commented
@eshellman Which Course needs to be deleted kindly tell me as I have checked the Hindi List and Didn't Find Any Matching Course.

2023-10-19 01:05 UTC, Ajay-singh1 commented
@eshellman I have deleted the duplicate course of javascritp in Hindi List are we ready to merge now.

2023-10-19 14:24 UTC, Ajay-singh1 commented
@eshellman Kindly Review the PR and merge it!

2023-10-19 15:07 UTC, Ajay-singh1 commented
@Thenlie Can you review this PR and suggest any changes to be made?

2023-10-19 16:42 UTC, eshellman commented on courses/free-courses-ur.md
> +* [Programming Fundamentals With C++ Complete Course In urdu | Hindi](https://www.youtube.com/playlistlist=PL4QkPoTgwFULciDFVJEHEwOKMtf9Q_Aqh) - Kacs Learnings
```suggestion
* [Programming Fundamentals With C++ Complete Course In urdu | Hindi](https://www.youtube.com/playlist=PL4QkPoTgwFULciDFVJEHEwOKMtf9Q_Aqh) - Kacs Learnings
```

2023-10-19 16:51 UTC, Ajay-singh1 commented
@eshellman Kindly Review this! I wish to work on another issue.

2023-10-19 21:59 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2023-10-19 21:59 UTC, merged