Update free-programming-books-ar.md
EbookFoundation/free-programming-books pull request #10463
Opened 2023-10-18 07:55 UTC by Adamkaram

## What does this PR do?
Add some books for programing and sql DB from arabic authors

## For resources
### Description
A book to help people learn about programming in arabic greate resource actually.

### Why is this valuable (or not)?

People can learn how to program.

### How do we know it's really free?

arab people posting thier books for free in general  

### For book lists, is it a book? For course lists, is it a course? etc.
Books 

## Checklist:
- [✓ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ✓] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [✓ ] Include author(s) and platform where appropriate.
- [ ✓] Put lists in alphabetical order, correct spacing.
- [ ✓] Add needed indications (PDF, access notes, under construction).
- [ ✓] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2023-10-18 14:28 UTC, Ajay-singh1 commented
Fix the linter errors.

2023-10-18 16:23 UTC, Adamkaram reviewed
test if linter working

2023-10-18 16:35 UTC, Adamkaram reviewed
swap all orders for lint error order

2023-10-18 16:43 UTC, Adamkaram commented
> Fix the linter errors.
done

2023-10-18 17:24 UTC, eshellman requested changes

2023-10-18 17:24 UTC, eshellman commented on books/free-programming-books-ar.md
> +* [C++](#C++)
look at other list to see how to link to c++

2023-10-18 17:24 UTC, eshellman commented on books/free-programming-books-ar.md
> +* [Java](#Java)
```suggestion
* [Java](#java)
```

2023-10-18 17:24 UTC, eshellman commented on books/free-programming-books-ar.md
> +* [لغة ++C ](https://ketabpedia.com/%D8%AA%D8%AD%D9%85%D9%8A%D9%84/%D8%B3%D9%84%D8%B3%D9%84%D8%A9-%D8%A7%D9%84%D8%A8%D8%B1%D9%85%D8%AC%D8%A9-%D8%A7%D9%84%D9%85%D9%81%D8%AA%D9%88%D8%AD%D8%A9-%D8%A8-c/
link directly to the book

2023-10-18 17:24 UTC, eshellman commented on books/free-programming-books-ar.md
> +* [سلسلة تعلم الجافا ](https://www.noor-book.com/%D9%83%D8%AA%D8%A7%D8%A8-%D8%B3%D9%84%D8%B3%D9%84%D8%A9-%D8%AA%D8%B9%D9%84%D9%85-%D8%A7%D9%84%D8%AC%D8%A7%D9%81%D8%A7-1-pdf) - (PDF) Mahmoud safy
from internet archive. use internet archive link

2023-10-18 17:24 UTC, eshellman commented on books/free-programming-books-ar.md
> +* [قواعد البيانات](https://www.noor-book.com/%D9%83%D8%AA%D8%A7%D8%A8-%D9%82%D9%88%D8%A7%D8%B9%D8%AF-%D8%A7%D9%84%D8%A8%D9%8A%D8%A7%D9%86%D8%A7%D8%AA-pdf) - (pdf) jomaa arifa
from internet archive. use internet archive link

2023-10-19 16:07 UTC, eshellman commented
please use links from the original source; none of thes links lead to a book

2023-10-19 16:07 UTC, closed without merging

2023-10-19 18:59 UTC, Adamkaram commented
> please use links from the original source; none of thes links lead to a book

noorbook was the original source < authors them self have been posting it there