Update free-courses-ar.md
EbookFoundation/free-programming-books pull request #10465
Opened 2023-10-18 08:05 UTC by Adamkaram

some useful courses from Bigdata channel

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2023-10-18 17:02 UTC, Adamkaram commented
> Kindly read the contributing guidelines and fix all the linter errors.

done

2023-10-19 16:10 UTC, Ajay-singh1 commented
@Adamkaram Bro!You have given the individual link of the video and we need playlist link.There you go.

2023-10-19 18:46 UTC, Adamkaram commented
> @Adamkaram Bro!You have given the individual link of the video and we need playlist link.There you go.

it's a bunch of video  compressed to one video is this acceptable?

2023-10-20 00:03 UTC, eshellman requested changes
videos are long enough, OK, but please let us know in the PR description to avoid delays

2023-10-20 00:03 UTC, eshellman commented on courses/free-courses-ar.md
> +* [Docker](#Docker)
```suggestion
* [Docker](#docker)
```

2023-10-22 15:18 UTC, Adamkaram commented
done

2023-10-23 19:12 UTC, eshellman requested changes

2023-10-23 19:12 UTC, eshellman commented on courses/free-courses-ar.md
> +* [SQL for Data Analysis | شاهد كيف أصبح الفيل والدرفيل أصدقاء](https://www.youtube.com/watch?v=kb-_GbpH3sQ) -  Big Data
```suggestion
* [SQL for Data Analysis \| شاهد كيف أصبح الفيل والدرفيل أصدقاء](https://www.youtube.com/watch?v=kb-_GbpH3sQ) -  Big Data
```

2023-11-17 13:17 UTC, merged