Update free-courses-ar.md
EbookFoundation/free-programming-books pull request #10479
Opened 2023-10-18 17:18 UTC by Adamkaram

## What does this PR do?
Adding  linux system course

### Description
all about linux system from zero and i highly recommend it for anyone need to know how to deal with linux system and configure it 

### Why is this valuable (or not)?
i have learn a lot from it 

### How do we know it's really free?
it's youtube playlist 

### For book lists, is it a book? For course lists, is it a course? etc.
course

## Checklist:
- [ ✓] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ✓] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ✓] Include author(s) and platform where appropriate.
- [ ✓] Put lists in alphabetical order, correct spacing.
- [ ✓] Add needed indications (PDF, access notes, under construction).
- [ ✓] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2023-10-18 17:44 UTC, eshellman commented
It's usually not helpful to add a category for a single resource. Try to find another category, or see if there are other books in our lists that would fit into your category. Add to the Operating Systems category instead.

2023-10-18 18:43 UTC, Adamkaram commented
> It's usually not helpful to add a category for a single resource. Try to find another category, or see if there are other books in our lists that would fit into your category. Add to the Operating Systems category instead.

i will add more resource on that cat

2023-10-19 07:04 UTC, Adamkaram commented
> It's usually not helpful to add a category for a single resource. Try to find another category, or see if there are other books in our lists that would fit into your category. Add to the Operating Systems category instead.

done i've add 4 resource

2023-10-19 16:03 UTC, eshellman requested changes
Please use the "Operating Systems' Category

2023-10-19 18:57 UTC, Adamkaram commented on courses/free-courses-ar.md
> +* [Operating Systems - أنظمة التشغيل](https://www.youtube.com/playlist?list=PLxIvc-MGOs6ib0oK1z9C46DeKd9rRcSMY) - Dr.Ahmed Hagag
i have been move three of them to OS sould i leave linux with one resource?

2023-10-20 00:07 UTC, eshellman commented
linux is an operating system

2023-10-20 12:52 UTC, Adamkaram reviewed
omit linux cato

2023-10-20 13:17 UTC, closed without merging