1
EbookFoundation/free-programming-books pull request #10515
Opened 2023-10-19 18:06 UTC by huji405

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description
Added new tutorial to LUA section
### Why is this valuable (or not)?
It teaches English speakers LUA
### How do we know it's really free?
It's a Youtube video
### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2023-10-19 22:52 UTC, eshellman requested changes

2023-10-19 22:52 UTC, eshellman commented on courses/free-courses-en.md
> +* [Cloud Computing Tutorial for Beginners - Cloud Computing Explained - Cloud Computing](https://www.youtube.com/watch?v=RWgW-CgdIk0) - Simplilearn
For youtube, we prefer "playlist" links and the name of the producer/creator. docs/CONTRIBUTING.md#platforms-and-access-notes

2023-10-19 22:52 UTC, eshellman commented on courses/free-courses-en.md
> +* [Full Lua Programming Crash Course - Beginner to Advanced](https://www.youtube.com/watch?v=1srFmjt1Ib0) - Steve's teacher
For youtube, we prefer "playlist" links and the name of the producer/creator. docs/CONTRIBUTING.md#platforms-and-access-notes

2023-10-21 04:31 UTC, eshellman commented on courses/free-courses-en.md
> +* [Lua Programming Tutorials](https://youtube.com/playlist?list=PLYBJzqz8zpWavt37pA6NANJTGStIHpybU&si=DtatTyXBfJhH82CA) - Steve's teacher
```suggestion
* [Lua Programming Tutorials](https://youtube.com/playlist?list=PLYBJzqz8zpWavt37pA6NANJTGStIHpybU) - Steve's teacher
```

2023-10-21 12:52 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2023-10-23 17:44 UTC, huji405 commented
Please check my other branch named "3 changed" and leave a review. tysm

2023-11-05 17:15 UTC, Thenlie commented
@huji405 I looked at your other PR's and they seem unrelated to this. So I think this is still valid? Feel free to close it out if not.

2023-11-21 23:04 UTC, merged