Course10
EbookFoundation/free-programming-books pull request #10534
Opened 2023-10-20 04:48 UTC by AryavT

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description
Javascript tutorial in kannada
### Why is this valuable (or not)?
it will teach people who speak Kannada how to code in java script eventually making their society more advanced
### How do we know it's really free?
its is free on youtube
### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2023-10-20 11:35 UTC, Ajay-singh1 approved these changes
LGTM!

2023-10-21 13:30 UTC, eshellman commented on courses/free-courses-bn.md
> +
```suggestion
```

2023-10-23 02:24 UTC, eshellman commented
Be sure to check the free-programming-books-lint output for linter errors. Alphabetical order and spacing are the most common problems.

2023-10-26 17:23 UTC, rng70 requested changes

2023-10-26 17:23 UTC, rng70 commented on courses/free-courses-bn.md
> +* [Python Bangla Tutorial & Data Science Full Course || Full Guidelines for Python, ML, AI, DL & Django](https://www.youtube.com/watch?v=A3FKSsYy0Zg&list=PLKdU0fuY4OFcot0zyVbM1-zKf_eCUK4zQ) - Study M
swap line 276 and 275. linter issue will be solved

2023-11-17 13:43 UTC, merged