Update free-courses-hi.md
EbookFoundation/free-programming-books pull request #10549
Opened 2023-10-20 11:26 UTC by biswabaibhab007

## What does this PR do?
- Added Express.js under Javascript
- Added a video course for Express,js

## For resources
### Description
- The tutor explains various use cases of express.js like user authentication

### Why is this valuable (or not)?
- Earlier there were no resources for express.js in this repo

### How do we know it's really free?
- It's on youtube

### For book lists, is it a book? For course lists, is it a course? etc.
- It's a course

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2023-10-20 11:30 UTC, Ajay-singh1 commented
Go for it buddy fix the linter errors.

2023-10-20 11:32 UTC, biswabaibhab007 commented
> Go for it buddy fix the linter errors.

done 👍

2023-10-20 11:37 UTC, Ajay-singh1 approved these changes
LGTM!

2023-10-20 12:59 UTC, sohansai reviewed
We prefer 'playlist' links for YouTube contributions. Avoid shortened links, and keep the resource's name unchanged when contributing.

2023-10-20 16:42 UTC, biswabaibhab007 commented
> We prefer 'playlist' links for YouTube contributions. Avoid shortened links, and keep the resource's name unchanged when contributing.

@sohansai But express.js is not a big topic and this video covers everything that is actually used in real life nothing extra.

2023-10-21 04:27 UTC, eshellman commented on courses/free-courses-hi.md
> +* [Express.js - Learn What Matters](https://youtu.be/pKJ4GGyDgJo?si=YUJf86FH54wofl99) - Sheryians Coding School
we don't accept shortened links like this one. single videos are only acceptable if there is no playlist and the lengthe is longer than one hour, as this one is.
It's usually not helpful to add a category for a single resource. Try to find another category, or see if there are other books in our lists that would fit into your category. For this one, you can just add it to the javascript category

2023-10-21 04:27 UTC, eshellman commented on courses/free-courses-hi.md
> +### Express.js
```suggestion
#### Express.js
```
subcategory

2023-10-21 06:36 UTC, Ajay-singh1 approved these changes
This Looks Good By the way.

2023-10-21 07:01 UTC, Ajay-singh1 requested changes
The URl is a shortened one fix that first than add the list to the javascript section.

2023-10-21 12:43 UTC, eshellman commented on courses/free-courses-hi.md
> +* [Express.js - Learn What Matters](https://m.youtube.com/watch?v=pKJ4GGyDgJo&pp=ygUUZXhwcmVzcyBqcyBzaGVyeWlhbnM%3D) - Sheryians Coding School
```suggestion
* [Express.js - Learn What Matters](https://youtube.com/watch?v=pKJ4GGyDgJo&pp=ygUUZXhwcmVzcyBqcyBzaGVyeWlhbnM%3D) - Sheryians Coding School
```

2023-10-21 13:17 UTC, sohansai commented on courses/free-courses-hi.md
> +* [Express.js - Learn What Matters](https://www.youtube.com/watch?v=pKJ4GGyDgJo&pp=ygUUZXhwcmVzcyBqcyBzaGVyeWlhbnM%3D) - Sheryians Coding School
```suggestion
* [Express.js - Learn What Matters](https://www.youtube.com/watch?v=pKJ4GGyDgJo) - Sheryians Coding School
```

2023-10-21 13:20 UTC, biswabaibhab007 commented
Done 👍

2023-10-21 14:34 UTC, eshellman commented
Done! 
@Ajay-singh1 thanks for assistance.

2023-10-21 14:34 UTC, merged