Added books for COBOL, FORTRAN and GraphQL free-programming-books-langs.md
EbookFoundation/free-programming-books pull request #10585
Opened 2023-10-21 08:03 UTC by adarsh-jha-dev

## What does this PR do?
Add resources

## For resources
### Description
I have added the following three books 

- [Learning COBOL](https://riptutorial.com/Download/cobol.pdf)
- [Programming in Fortran 95](https://personalpages.manchester.ac.uk/staff/david.d.apsley/lectures/fortran/fortranA.pdf) -David Apsley
- [GraphQL or Bust](https://nordicapis.com/wp-content/uploads/GraphQL-or-Bust-v2.2.pdf)
### Why is this valuable (or not)?
These are very popular books for the mentioned topics and were not present in the list.

### How do we know it's really free?
I have verified by visiting the provided links for the books.

### For book lists, is it a book? For course lists, is it a course? etc.
These are books.
## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2023-10-21 13:56 UTC, eshellman requested changes

2023-10-21 13:56 UTC, eshellman commented on books/free-programming-books-langs.md
> +* [Learning COBOL](https://riptutorial.com/Download/cobol.pdf) (PDF)
Please read docs/CONTRIBUTING.md for guidelines on riptutorial attribution.

2023-10-21 13:56 UTC, eshellman commented on books/free-programming-books-langs.md
> +* [Introduction to Fortran by David Apsley](https://personalpages.manchester.ac.uk/staff/david.d.apsley/lectures/fortran/fortranA.pdf) -  David Apsley (PDF)
```suggestion
* [Fortran](https://personalpages.manchester.ac.uk/staff/david.d.apsley/lectures/fortran/fortranA.pdf) -  David Apsley (PDF)
```
Don't invent titles! Use the title given by the resource.

2023-10-21 13:56 UTC, eshellman commented on books/free-programming-books-langs.md
> +* [GraphQL or Bust](https://nordicapis.com/wp-content/uploads/GraphQL-or-Bust-v2.2.pdf) (PDF)
```suggestion
* [GraphQL or Bust](https://nordicapis.com/wp-content/uploads/GraphQL-or-Bust-v2.2.pdf) - Nordic APIs (PDF)
```
Please add author names where appropriate.

2023-10-22 03:10 UTC, adarsh-jha-dev commented
I have removed that rip tutorial's book and replaced with another book

2023-10-23 02:30 UTC, adarsh-jha-dev commented
Hey @eshellman , i have implemented the required  changes, so you can have a look at it.

2023-10-23 11:43 UTC, adarsh-jha-dev commented
Hey @eshellman , I request you to please have a look at the changes and let me know if these changes can be merged?

2023-10-24 02:20 UTC, eshellman commented
the review process rewards patience.

2023-10-24 02:20 UTC, merged

2023-10-24 02:35 UTC, adarsh-jha-dev commented
> the review process rewards patience.

really sorry for being impatient, thanks for merging.