Update free-podcasts-screencasts-en.md
EbookFoundation/free-programming-books pull request #10635
Opened 2023-10-22 03:22 UTC by Dkeys4

A podcast covering the JavaScript language and more broadly web and frontend technologies, with guests from the open-source community. It's hosted by OpenReplay, an open-source session replay tool for developers. The podcast is available on the Apple platform, Spotify, and Amazon Music. The Podcast is totally free and is for programmers of all levels and experience.

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2023-10-26 17:18 UTC, rng70 requested changes

2023-10-26 17:18 UTC, rng70 commented on casts/free-podcasts-screencasts-en.md
> +* [20 Min JS Podcast](https://20minjs.com/) - Agustinus Theodorus, Chris Bongers, Mark Volkmann, and others (podcast)
move this line to line 177

2023-10-26 17:19 UTC, rng70 commented on casts/free-podcasts-screencasts-en.md
> +* [20 Min JS Podcast](https://20minjs.com/) - Agustinus Theodorus, Chris Bongers, Mark Volkmann, and others (podcast)
linter issue will be solved

2023-10-27 15:20 UTC, rng70 requested changes

2023-10-27 15:20 UTC, rng70 commented on courses/free-courses-ne.md
you removed `#### C` which is required here. also always give two newline(linebreak) between to section.

2023-10-27 16:32 UTC, rng70 commented on casts/free-podcasts-screencasts-en.md
> +* [20 Min JS Podcast](https://20minjs.com/) - Agustinus Theodorus, Chris Bongers, Mark Volkmann, and others (podcast)
you should change this to pass linter check

2023-10-27 16:37 UTC, rng70 commented
@Dkeys4 the problem is in file [casts/free-podcasts-screencasts-en.md](https://github.com/EbookFoundation/free-programming-books/pull/10635/files/2ce0c7d3f502b0438dd859f278e30d44aa16872f#diff-89a3d7bd4411eb8f157242bae989fc4a074bc98ca67fecb3bb941baafd879cae) line 197. move that line to line 177

2023-10-27 16:45 UTC, rng70 commented
linter issue still persists. let me check on the issue and review your changes.

2023-10-27 16:59 UTC, rng70 commented
@Dkeys4 the problem is also in file `books/free-programming-books-bn.md` in your repository. please make sure that your repository is up-to-date with the upstream repository. you can sync your repository with the upstream from your GitHub UI and also from terminal. If you are not interested to sync with upstream then make the following chnages in `books/free-programming-books-bn.md`

* move line 4 to line 6
* swap line 23 and 24
* move line 60 to line 62 (means move line 61 to line 60, line 62 to  line 61 and move line 60 to line 62)

and then commit. hope it will resolve the linter issue.

**note: maybe this problem occurs due to wrong sync from the upstream(not sure what happened from your end) because that file does not appears in changed files lists so it was quite unexpected**

2023-11-17 15:04 UTC, eshellman commented on casts/free-podcasts-screencasts-en.md
> +* [20 Min JS Podcast](https://20minjs.com/) - Agustinus Theodorus, Chris Bongers, Mark Volkmann, and others (podcast)
```suggestion
```
added in #10980 from #10628

2023-11-17 15:31 UTC, eshellman commented
this PR suffered from a broken build caused when we added bangla valiidation. Sorry for the trouble! the resource is added in #10980

2023-11-17 15:31 UTC, closed without merging