Added new podcasts to english languages
EbookFoundation/free-programming-books pull request #10744
Opened 2023-10-24 16:44 UTC by Ratheshan03

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2023-10-25 02:22 UTC, eshellman requested changes

2023-10-25 02:22 UTC, eshellman commented on casts/free-podcasts-screencasts-en.md
> +* [Data Engineering Podcast](https://www.dataengineeringpodcast.com) - Tobias Macey (podcast)
just put it under data science

2023-10-26 03:05 UTC, Ratheshan03 commented on casts/free-podcasts-screencasts-en.md
> +* [Data Engineering Podcast](https://www.dataengineeringpodcast.com) - Tobias Macey (podcast)
okay sure!

2023-10-26 03:11 UTC, Ratheshan03 commented
@eshellman I made the changes 😄

2023-10-26 16:58 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2023-10-26 16:58 UTC, merged