Update free-courses-hi.md - add ethical hacking course hindi
EbookFoundation/free-programming-books pull request #10743
Opened 2023-10-24 16:39 UTC by krithikha24

## What does this PR do?
Add resource(s) | This PR adds resources for Ethical Hacking courses in Hindi.

Remove resource(s) | Add info | Improve repo

## For resources
### Description
Ethical hacking is a growing field and very useful. The course provided starts from scratch and also provides a project experience.

### Why is this valuable (or not)?
It is fully available on youtube for free.

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.
It is a course

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2023-10-24 16:54 UTC, sohansai commented on courses/free-courses-hi.md
> +* [Complete Ethical Hacking Playlist(Cyber Security in Hindi)](https://www.youtube.com/playlist?list=PLjVLYmrlmjGea8U9nphmCHGK_v6p_wq-R) - WsCube Tech
```suggestion
* [Complete Ethical Hacking Tutorial for Beginners to Pro 2022](https://www.youtube.com/playlist?list=PLjVLYmrlmjGea8U9nphmCHGK_v6p_wq-R) - WsCube Tech
```

2023-10-24 16:54 UTC, sohansai commented on courses/free-courses-hi.md
> +* [Complete Ethical Hacking Playlist(Cyber Security in Hindi)](https://www.youtube.com/playlist?list=PLjVLYmrlmjGea8U9nphmCHGK_v6p_wq-R) - WsCube Tech
use the original title from the resource and avoid inventing new ones.

2023-10-25 03:03 UTC, krithikha24 commented
Commited the changes, Please approve now!

2023-10-26 07:26 UTC, krithikha24 commented
Linter error is fixed. Please approve and merge!

2023-10-26 17:14 UTC, rng70 requested changes

2023-10-26 17:14 UTC, rng70 commented on courses/free-courses-hi.md
>  * [cyber security course for beginners - Urdu/Hindi](https://www.youtube.com/playlist?list=PLKJfBg0XdWkevCEJ64RK11LylBNX2-zbk) - hashintelligence
move line 689 to here

2023-10-26 17:14 UTC, rng70 commented on courses/free-courses-hi.md
> +* [Complete Ethical Hacking Tutorial for Beginners to Pro 2022](https://www.youtube.com/playlist?list=PLjVLYmrlmjGea8U9nphmCHGK_v6p_wq-R) - WsCube Tech
move line 689 to 686. it will resolve the linter issue

2023-10-27 11:09 UTC, krithikha24 commented
Resolved the said changes and waiting for approval

2023-10-28 02:22 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2023-10-28 02:22 UTC, merged