Added Courses
EbookFoundation/free-programming-books pull request #10753
Opened 2023-10-24 21:51 UTC by ivikashgorai

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2023-10-26 03:12 UTC, eshellman requested changes

2023-10-26 03:12 UTC, eshellman commented on courses/free-courses-en.md
> +* [Java Zero to FAANG](https://www.youtube.com/playlist?list=PL9gnSGHSqcnr_DxHsP7AW9ftq0AtAyYqJ) - Kunal Kushwaha
Don't invent titles! Use the title given by the resource.

2023-10-26 03:12 UTC, eshellman commented on courses/free-courses-hi.md
> -* [Redux Toolkit tutorial in Hindi](https://www.youtube.com/playlist?list=PLwGdqUZWnOp2nz2T6SfWX9t6D6SYn3XlN) - Vinod Bahadur Thapa (Thapa Technical)
did you mean to remove this???

2023-10-26 03:12 UTC, eshellman commented on courses/free-courses-hi.md
> +* [Redux Complete Course](https://youtube.com/playlist?list=PL8p2I9GklV47TDYUq8RmFzeI9CgOoVgpJ&si=p-4s6qJ31ReIbKqj) - Code Step by Step
Don't invent titles! Use the title given by the resource.

2023-10-27 11:38 UTC, ivikashgorai commented on courses/free-courses-hi.md
> -* [Redux Toolkit tutorial in Hindi](https://www.youtube.com/playlist?list=PLwGdqUZWnOp2nz2T6SfWX9t6D6SYn3XlN) - Vinod Bahadur Thapa (Thapa Technical)
sorry my mistake

2023-10-27 11:51 UTC, ivikashgorai commented
Please review and merge it

2023-10-28 23:57 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2023-10-28 23:57 UTC, merged