Update free-programming-books-langs.md
EbookFoundation/free-programming-books pull request #10799
Opened 2023-10-25 22:37 UTC by erfatih

[An Introduction to Statistical Learning with Applications in Python] link was changed. Existing link is dead.

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2023-10-26 12:34 UTC, rng70 requested changes

2023-10-26 12:34 UTC, rng70 commented on books/free-programming-books-langs.md
> +* [An Introduction to Statistical Learning with Applications in Python](https://www.statlearning.com/) - Gareth James, Daniela Witten, Trevor Hastie, Robert Tibshirani, Jonathan Taylor (PDF)
trailing slash no longer accpeted. For further information see [here](https://github.com/vhf/remark-lint-no-url-trailing-slash#remark-lint-no-url-trailing-slash)

change
```text
https://www.statlearning.com/
```
to
```text
https://www.statlearning.com
```

2023-10-30 16:53 UTC, rng70 commented on books/free-programming-books-langs.md
> +* [An Introduction to Statistical Learning with Applications in Python](https://www.statlearning.com/) - Gareth James, Daniela Witten, Trevor Hastie, Robert Tibshirani, Jonathan Taylor (PDF)
unless you make the suggested change linter issue won't be solved

2023-11-22 00:11 UTC, eshellman commented on books/free-programming-books-langs.md
> +* [An Introduction to Statistical Learning with Applications in Python](https://www.statlearning.com/) - Gareth James, Daniela Witten, Trevor Hastie, Robert Tibshirani, Jonathan Taylor (PDF)
```suggestion
* [An Introduction to Statistical Learning with Applications in Python](https://www.statlearning.com) - Gareth James, Daniela Witten, Trevor Hastie, Robert Tibshirani, Jonathan Taylor (PDF)
```

2023-11-22 00:16 UTC, eshellman commented
added in #10988

2023-11-22 00:16 UTC, closed without merging