[Addition]: Node.js Cheatsheet
EbookFoundation/free-programming-books pull request #10836
Opened 2023-10-27 13:18 UTC by mohdahsanrazakhan

## What does this PR do?
Introduces a Node.js cheatsheet to the repository

## For resources
### Description
This pull request introduces a Node.js cheatsheet to the repository, serving as a valuable resource for developers working with Node.js. The cheatsheet is designed to be a quick reference guide, offering essential information, best practices, and commonly used commands and concepts.

### Why is this valuable (or not)?
The Node.js cheatsheet is a valuable addition as it provides developers with a quick and accessible reference for Node.js, improving productivity and promoting best practices.

### How do we know it's really free?
Yes, it is an original link.

### For book lists, is it a book? For course lists, is it a course? etc.
For cheatsheet lists

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2023-10-27 15:02 UTC, Thenlie approved these changes

2023-10-28 02:58 UTC, eshellman requested changes

2023-10-28 02:58 UTC, eshellman commented on more/free-programming-cheatsheets.md
> +* [Node.js/Express Cheatsheet](https://courses.cs.washington.edu/courses/cse154/19su/resources/assets/cheatsheets/node-cheatsheet.pdf) - Washington CSE 154: Web Programming (PDF)
```suggestion
* [Node.js/Express Cheatsheet](https://courses.cs.washington.edu/courses/cse154/19su/resources/assets/cheatsheets/node-cheatsheet.pdf) - Melissa Hovik (PDF)
```
This is the course instructor. Please check the context to see if somebody else should be credited.

2023-10-28 02:58 UTC, eshellman commented on more/free-programming-cheatsheets.md
> +* [Node.js Cheatsheet ZTM](https://zerotomastery.io/cheatsheets/node-js-cheat-sheet) - ZeroToMastery (HTML)
```suggestion
* [Node.js Cheatsheet ZTM](https://zerotomastery.io/cheatsheets/node-js-cheat-sheet) - Zero To Mastery
```

2023-10-28 02:58 UTC, eshellman commented on more/free-programming-cheatsheets.md
> +* [Node.js Cheatsheet](https://www.codecademy.com/learn/learn-node-js/modules/intro-to-node-js/cheatsheet) - Codecademy (HTML)
```suggestion
* [Introduction to Node.js](https://www.codecademy.com/learn/learn-node-js/modules/intro-to-node-js/cheatsheet) - Codecademy
```
Don't invent titles! Use the title given by the resource.

2023-10-29 00:25 UTC, merged