added new reference books
EbookFoundation/free-programming-books pull request #10839
Opened 2023-10-27 13:56 UTC by cheta-nyadav

## What does this PR do?
Add resources to  the list.

## For resources
### added reference books

### Why is this valuable (or not)?
It can be really valuable for people getting started with programming.

### How do we know it's really free?
I have cross checked on my side, they're free!

### For book lists, is it a book? For course lists, is it a course? etc.
it is a book's pdf, ebook.

## Checklist:
- [ x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x ] Include author(s) and platform where appropriate.
- [x ] Put lists in alphabetical order, correct spacing.
- [x ] Add needed indications (PDF, access notes, under construction).
- [x ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2023-10-27 14:38 UTC, rng70 requested changes

2023-10-27 14:38 UTC, rng70 commented on books/free-programming-books-langs.md
> +* [The Complete Reference C++,Herbert Schildt](https://www.micc.unifi.it/bertini/download/labtecinf/C%2B%2B%20A%20Beginner's%20Guide%202nd%20Edition%20(2003).pdf) - Second Edition
move this line to line 550

2023-10-27 14:38 UTC, rng70 commented on books/free-programming-books-langs.md
> +* [Java,The Complete Reference](https://srikarthiks.files.wordpress.com/2016/07/java-the-complete-reference-8th-edition.pdf) - 8th edition
move this line to line 1072

2023-10-27 14:44 UTC, rng70 requested changes

2023-10-27 14:44 UTC, rng70 commented on books/free-programming-books-langs.md
> +* [The Complete Reference C++,Herbert Schildt](https://www.micc.unifi.it/bertini/download/labtecinf/C%2B%2B%20A%20Beginner's%20Guide%202nd%20Edition%20(2003).pdf) - Second Edition
You must follow the rule described [here](https://github.com/vhf/remark-lint-books-links)
For example
```test
[Another Awesome Book](http://example.com/book.pdf) - John Doe (PDF)
```
So for your case, the proper way to do this is
```text
[The Complete Reference C++ (second edition)](https://www.micc.unifi.it/bertini/download/labtecinf/C%2B%2B%20A%20Beginner's%20Guide%202nd%20Edition%20(2003).pdf) - Herbert Schildt (PDF)
```

2023-10-27 14:44 UTC, rng70 commented on books/free-programming-books-langs.md
> +* [Java,The Complete Reference](https://srikarthiks.files.wordpress.com/2016/07/java-the-complete-reference-8th-edition.pdf) - 8th edition
also, follow the same rule here

2023-10-28 07:14 UTC, cheta-nyadav commented on books/free-programming-books-langs.md
> +* [Java,The Complete Reference](https://srikarthiks.files.wordpress.com/2016/07/java-the-complete-reference-8th-edition.pdf) - 8th edition
ok, thank you so much.

2023-10-28 07:21 UTC, cheta-nyadav commented
@rng70 please check now,

2023-10-30 03:26 UTC, closed without merging