Update free-programming-books-fr.md (add missing creators, formats, typo, et al.)
EbookFoundation/free-programming-books pull request #10886
Opened 2023-10-29 16:40 UTC by Mamadou442

## What does this PR do?
Improve repo

## For resources
### Description

- change a few links of books to HTTPS.
- It specifies the creators, formats of a few books.
- change "Histoires et cultures du Libre" as archived books.
- fix typo ("Activités débranchées")

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2023-10-29 18:43 UTC, eshellman requested changes
just some tweaks, thanks!

2023-10-29 18:43 UTC, eshellman commented on books/free-programming-books-fr.md
> +* [Programmer avec SPIP](https://programmer.spip.net) - Matthieu Marcimat, collectif SPIP (HTML)
```suggestion
* [Programmer avec SPIP](https://programmer.spip.net) - Matthieu Marcimat, collectif SPIP
```

2023-10-29 18:43 UTC, eshellman commented on books/free-programming-books-fr.md
> +* [Informatique Créative](https://pixees.fr/programmation-creative-en-scratch/) - Christan Balch, Michelle Chung, Karen Brennan, `trl.:` INRIA, PROVENCE TRADUCTION (PDF, PPTX)
no ALL CAPS

2023-10-29 18:43 UTC, eshellman commented on books/free-programming-books-fr.md
> +* [Apprendre Haskell vous fera le plus grand bien !](https://lyah.haskell.fr) - Miran Lipovača, `trl.:` Valentin Robert (HTML, PDF)
```suggestion
* [Apprendre Haskell vous fera le plus grand bien !](https://lyah.haskell.fr) - Miran Lipovača, `trl.:` Valentin Robert
```
don't need format note id HTML or multiple

2023-10-29 18:43 UTC, eshellman commented on books/free-programming-books-fr.md
> +* [Guide avancé d'écriture des scripts Bash](https://abs.traduc.org/abs-fr/) - Mendel Cooper, `trl.:` Adrien Rebollo et al. (HTML)
```suggestion
* [Guide avancé d'écriture des scripts Bash](https://abs.traduc.org/abs-fr/) - Mendel Cooper, `trl.:` Adrien Rebollo et al.
```

2023-10-29 18:43 UTC, eshellman commented on books/free-programming-books-fr.md
> +* [Histoires et cultures du Libre](https://archives.framabook.org/histoiresetculturesdulibre/) - Camille Paloque-Berges, Christophe Masutti, `edt.:` Framasoft (coll. Framabook) [(HTML, PDF, EPUB, et
```suggestion
* [Histoires et cultures du Libre](https://archives.framabook.org/histoiresetculturesdulibre/) - Camille Paloque-Berges, Christophe Masutti, `edt.:` Framasoft (coll. Framabook)
```
we use the 'archived' notation for internet archive style archiving

2023-10-30 10:10 UTC, Mamadou442 commented
Tried to add all of the tweaks in a single commit. Thank for your review!

2023-10-31 01:35 UTC, merged