Included Database Management Courses
EbookFoundation/free-programming-books pull request #10901
Opened 2023-10-30 05:15 UTC by HarshRanaOC

## What does this PR do?
Add resource(s) |  Improve repo

## For resources
### Description

### Why is this valuable (or not)?
Yes
### How do we know it's really free?
Yes
### For book lists, is it a book? For course lists, is it a course? etc.
Course
## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2023-10-30 15:31 UTC, sohansai commented on courses/free-courses-en.md
> +* [Database Management System | CS & IT | GATE 2024](https://www.youtube.com/playlist?list=PLPvaSRcEQh4kfVIyezAQu9Mvj5FBk_OEN) - GATE Wallah (English)
```suggestion
* [Database Management System \| CS & IT \| GATE 2024](https://www.youtube.com/playlist?list=PLPvaSRcEQh4kfVIyezAQu9Mvj5FBk_OEN) - Gate Wallah (English)
```

2023-10-30 15:32 UTC, sohansai commented on courses/free-courses-en.md
> +* [Database Management Systems](https://www.youtube.com/playlist?list=PLZ2ps__7DhBYc4jkUk_yQAjYEVFzVzhdU) - IIT Madras - B.S. Degree Programme
```suggestion
* [Database Management Systems](https://www.youtube.com/playlist?list=PLZ2ps__7DhBYc4jkUk_yQAjYEVFzVzhdU) - IIT Madras B.S. Degree Programme
```

2023-10-30 15:52 UTC, HarshRanaOC commented
Hello @sohansai , I have made the rquired changes.
Regards

2023-10-30 22:44 UTC, eshellman requested changes

2023-10-30 22:44 UTC, eshellman commented on courses/free-courses-en.md
> +* [Database Management System \| CS & IT \| GATE 2024](https://www.youtube.com/playlist?list=PLPvaSRcEQh4kfVIyezAQu9Mvj5FBk_OEN) - Gate Wallah (English)
```suggestion
* [Database Management System \| CS & IT \| GATE 2024](https://www.youtube.com/playlist?list=PLPvaSRcEQh4kfVIyezAQu9Mvj5FBk_OEN) - Gate Wallah English
```
The parentheses get parsed as access notes

2023-10-30 22:44 UTC, eshellman commented on courses/free-courses-en.md
> +* [Database Management Systems](https://www.youtube.com/playlist?list=PLZ2ps__7DhBYc4jkUk_yQAjYEVFzVzhdU) - IIT Madras B.S. Degree Programme
```suggestion
* [Database Management Systems](https://www.youtube.com/playlist?list=PLZ2ps__7DhBYc4jkUk_yQAjYEVFzVzhdU) - Partha Pratim Das (IIT Madras B.S. Degree Programme)
```
Please add author names where appropriate.

2023-10-31 03:02 UTC, HarshRanaOC commented
Hello @eshellman,
I have implemented the changes as per your suggestions.
Regards.

2023-10-31 17:08 UTC, eshellman requested changes

2023-10-31 17:08 UTC, eshellman commented on courses/free-courses-hi.md
> +* [Playlist to Blockchain 🔥🔥](https://www.youtube.com/playlist?list=PLPIwNooIb9vgfXs-QkRYqqZbDXX-yLf59) - Perfect Computer Engineer
no emoji
```suggestion
* [Playlist to Blockchain](https://www.youtube.com/playlist?list=PLPIwNooIb9vgfXs-QkRYqqZbDXX-yLf59) - Perfect Computer Engineer
```

2023-10-31 17:08 UTC, eshellman commented on courses/free-courses-hi.md
> +* [Playlist to Artificial Intelligence 🔥🔥](https://www.youtube.com/playlist?list=PLPIwNooIb9vgB1DQEftkKA3qOdeC4vonA) - Perfect Computer Engineer
```suggestion
* [Playlist to Artificial Intelligence ](https://www.youtube.com/playlist?list=PLPIwNooIb9vgB1DQEftkKA3qOdeC4vonA) - Perfect Computer Engineer
```

2023-11-01 00:33 UTC, eshellman commented
Hacktoberfest give a few days after the month to complete a PR. It's still October here!

2023-11-01 00:33 UTC, merged