Update free-programming-books-pt_BR.md
EbookFoundation/free-programming-books pull request #10924
Opened 2023-10-31 02:13 UTC by spao234

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [X] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [X] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [X] Include author(s) and platform where appropriate.
- [X] Put lists in alphabetical order, correct spacing.
- [X] Add needed indications (PDF, access notes, under construction).
- [X] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2023-10-31 17:41 UTC, mohdahsanrazakhan requested changes

2023-10-31 17:41 UTC, mohdahsanrazakhan commented on books/free-programming-books-pt_BR.md
> +
Remove these lines

2023-10-31 17:41 UTC, mohdahsanrazakhan commented on books/free-programming-books-pt_BR.md
> +* [ C Completo e Total - Terceira Edição](https://www.inf.ufpr.br/lesoliveira/download/c-completo-total.pdf)) - Herbert Schildt (PDF)
```suggestion
* [C Completo e Total - Terceira Edição](https://www.inf.ufpr.br/lesoliveira/download/c-completo-total.pdf) - Herbert Schildt (PDF)
```

2023-11-01 06:59 UTC, mohdahsanrazakhan commented on books/free-programming-books-pt_BR.md
> +
Delete line `127` and `128`. An unnecessary lines.

2023-11-01 07:00 UTC, mohdahsanrazakhan commented
Delete line `127` and `128`. An unnecessary lines.

2023-11-21 13:43 UTC, eshellman commented on books/free-programming-books-pt_BR.md
> + C Completo e Total - Terceira Edição
```suggestion
```
misplaced text

2023-11-21 13:45 UTC, eshellman commented on books/free-programming-books-pt_BR.md
> +* [C Completo e Total - Terceira Edição](https://www.inf.ufpr.br/lesoliveira/download/c-completo-total.pdf) - Herbert Schildt (PDF)
```suggestion
* [C Completo e Total - Terceira Edição (1996)](https://www.inf.ufpr.br/lesoliveira/download/c-completo-total.pdf) - Herbert Schildt (PDF)
```

2023-11-21 13:46 UTC, eshellman commented on books/free-programming-books-pt_BR.md
```suggestion
```

2023-11-21 13:53 UTC, merged