add Feature Engineering book and Ethereum Blockchain Developer course
EbookFoundation/free-programming-books pull request #10931
Opened 2023-10-31 09:58 UTC by krz

this commit adds two entries:
- to data science section, a free book on feature engineering by Max Kuhn and Kjell Johnson
- to blockchain course section, a free course by Alchemy University on Ethereum development

2023-10-31 17:32 UTC, eshellman requested changes

2023-10-31 17:32 UTC, eshellman commented on books/free-programming-books-subjects.md
> +* [Feature Engineering an Selection](https://bookdown.org/max/FES/) - Max Kuhn, Kjell Johnson
```suggestion
* [Feature Engineering and Selection: A Practical Approach for Predictive Models](https://bookdown.org/max/FES/) - Max Kuhn, Kjell Johnson
```

2023-11-01 00:30 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2023-11-01 00:30 UTC, merged

2023-11-01 16:45 UTC, krz commented
Thanks and sorry for the typo, should not have happened ☺️