add: node js and next js 14 resource added
EbookFoundation/free-programming-books pull request #11047
Opened 2024-01-15 19:03 UTC by iamtonmoy0

## What does this PR do?
added node js and next 14 learning resources
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description
Rabbil Hasan ,Learn with sumit and Hablu Programmer is  offering new tutorial for free which i value able for new learners
### Why is this valuable (or not)?
It is valuable to learn new trending tech in native language

### How do we know it's really free?
Yes it is free of cost
### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2024-01-15 19:48 UTC, eshellman commented
Please start with a fresh branch and don't change the formatting of the entire index

2024-02-15 07:26 UTC, 3R1Dev requested changes
Please review the comments and make the appropriate changes.

2024-02-15 07:26 UTC, 3R1Dev commented on courses/free-courses-bn.md
> +- [WordPress](#wordpress)
You need to start fresh and don't edit this. This is already formatted as it is intended to be. If you are going to add an index or subindex it needs to follow the already established format.

If you keep changing this then the pull request will be rejected.

2024-02-15 07:26 UTC, 3R1Dev commented on courses/free-courses-bn.md
> +* [Next JS  14 Full Course in bangla](https://www.youtube.com/watch?v=XnIm8mb7WOw&list=PLNMnAEqLBwmqt3wGvc_JMqFobBZBcpv8c) - Hablu Programmer
This needs to be alphabetical order, based on the tittle you might need to add it in the beginning and not the end.

2024-02-15 07:26 UTC, 3R1Dev commented on courses/free-courses-bn.md
> +* [Node.js Tutorial Bangla | Express.js Tutorial Bangla](https://www.youtube.com/playlist?list=PLkyGuIcLcmx2qXaZkjCL8-P78i2J5rDOa)-Rabbil Hasan
This also needs to be in alphabetical order, try swapping this with line 225.

2024-06-05 00:12 UTC, closed without merging