Added new freecodecamp links
EbookFoundation/free-programming-books pull request #11115
Opened 2024-04-05 07:08 UTC by PiousSutherland

AWS one I removed was 3 years old and needed updating. Added new neural net course as well.

2024-04-05 16:02 UTC, eshellman requested changes

2024-04-05 16:02 UTC, eshellman commented on courses/free-courses-en.md
> +* [Understanding AI from Scratch – Neural Networks Course](https://www.youtube.com/watch?v=VgzHT9quo5c) - Dr Radu (freecodecamp)
```suggestion
* [Understanding AI from Scratch – Neural Networks Course](https://www.youtube.com/watch?v=VgzHT9quo5c) - Radu (FreeCodeCamp)
```
We do not include honorifics.

2024-04-08 12:06 UTC, PiousSutherland commented on courses/free-courses-en.md
> +* [AWS Certified Cloud Practitioner Course (CLF-C02)](https://www.youtube.com/watch?v=NhDYbskXRgc&t=7s&pp=ygUQZnJlZWNvZGVjYW1wIGF3cw%3D%3D) - Andrew Brown (freecodecamp)
This is 14 hours...
It _definitely_ counts as a course.

Honest mistake.

2024-04-08 12:07 UTC, PiousSutherland commented on courses/free-courses-en.md
> -* [AWS Certified Cloud Practitioner Course](https://www.youtube.com/playlist?list=PLt1SIbA8guuvfvUDVLpJepmbnYpOfYCIB) - Stephane Maarek
Is its being outdated not a valid argument?

2024-04-09 18:09 UTC, eshellman commented on courses/free-courses-en.md
> -* [AWS Certified Cloud Practitioner Course](https://www.youtube.com/playlist?list=PLt1SIbA8guuvfvUDVLpJepmbnYpOfYCIB) - Stephane Maarek
You could provide example of why the older one is no longer useful. Or you may also add a year to help disambiguate:
[AWS Certified Cloud Practitioner Course (YYYY)]

2024-04-09 18:12 UTC, eshellman commented on courses/free-courses-en.md
> +* [AWS Certified Cloud Practitioner Course (CLF-C02)](https://www.youtube.com/watch?v=NhDYbskXRgc&t=7s&pp=ygUQZnJlZWNvZGVjYW1wIGF3cw%3D%3D) - Andrew Brown (freecodecamp)
you didn't view it, did you?

2024-04-10 12:35 UTC, eshellman commented on courses/free-courses-en.md
> +* [AWS Certified Cloud Practitioner Course (CLF-C02)](https://www.youtube.com/watch?v=NhDYbskXRgc&t=7s&pp=ygUQZnJlZWNvZGVjYW1wIGF3cw%3D%3D) - Andrew Brown (freecodecamp)
Sorry, I think the lead-in ad fooled me on the timing.

2024-04-10 12:35 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2024-04-10 12:36 UTC, merged

2024-04-10 14:07 UTC, PiousSutherland commented
Thanks! I hope to contribute more soon, within the rules, of course.