Add Online Playground of Programiz PRO for Python and C
EbookFoundation/free-programming-books pull request #11136
Opened 2024-05-14 08:02 UTC by awalrujaa

## What does this PR do?
Add resource(s)

## For resources
### Description
Add Online C Playground

This commit introduces an Online Python Playground and C Playground that allows users to write, edit, and run code directly in their browsers. This feature supports real-time coding and debugging, enhancing learning and development flexibility.

### Why is this valuable (or not)?
This allows users to write, edit, and run code directly in their browsers without the need of downloading or installation of other software. This saves time and helps you focus on learning. 
### How do we know it's really free?
Anybody can access it. It is an absolutely free resource.

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2024-05-15 17:45 UTC, eshellman commented
These additions appear to be duplicates. Is it just the url changing?

2024-05-16 00:47 UTC, awalrujaa commented
No, Programiz Online Compiler and online Playground are two different things with different benefits for users.
While users can only run the code in Online Compiler, Programiz PRO's online playground is a platform where users can upload files, create projects, save, and share them for **free**.
Hence, the additions are not duplicates, rather these two are very different.
You can try Playground at: **[C Playground](https://programiz.pro/ide/c/ )** and **[Python Playground](https://programiz.pro/ide/python/9QJQ8BL19A)**
I hope this solves the confusion.

2024-05-16 16:09 UTC, eshellman requested changes
We try to use the title from the resource to more easily recognize duplicates

2024-05-16 16:09 UTC, eshellman commented on more/free-programming-playgrounds.md
> +* [C Playground - Online C Programming IDE](https://programiz.pro/ide/c)
```suggestion
* [C Playground - Online C Programming IDE](https://programiz.pro/ide/c) - Programiz Pro
```

2024-05-16 16:09 UTC, eshellman commented on more/free-programming-playgrounds.md
>  * [Programiz - Online C Compiler](https://www.programiz.com/c-programming/online-compiler/)
```suggestion
* [Online C Compiler](https://www.programiz.com/c-programming/online-compiler/) - Programiz
```

2024-05-16 16:09 UTC, eshellman commented on more/free-programming-playgrounds.md
>  * [Programiz.com](https://www.programiz.com/python-programming/online-compiler/)
```suggestion
* [Online Python Compiler](https://www.programiz.com/python-programming/online-compiler/) - Programiz
```

2024-05-21 22:22 UTC, MEETDesai011 approved these changes

2024-05-30 08:58 UTC, awalrujaa commented
Thank you for approving the PR. When will this PR get merged in the main
branch?
Please let me know when it's merged.

Sincerely,
Ruja  Awal
 Computer Engineer
Nepal
[image: facebook icon] <https://www.facebook.com/ruja.awal/>[image:
linkedin icon] <https://www.linkedin.com/in/ruja-awal-b971551aa/>
IOE,

IOE, Pulchowk Campus


On Wed, May 22, 2024 at 4:08 AM MEETDesai011 ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/EbookFoundation/free-programming-books/pull/11136#pullrequestreview-2069724446>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARSFC4JRRRXKA4NQO5KBUJLZDPCMVAVCNFSM6AAAAABHVUTQ5CVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDANRZG4ZDINBUGY>
> .
> You are receiving this because you authored the thread.Message ID:
> <EbookFoundation/free-programming-books/pull/11136/review/2069724446@
> github.com>
>

2024-05-30 15:48 UTC, eshellman requested changes
almost there!

2024-05-30 15:48 UTC, eshellman commented on more/free-programming-playgrounds.md
> +* [Python Playground](https://programiz.pro/ide/python) - by Programiz PRO
```suggestion
* [Python Playground](https://programiz.pro/ide/python) - Programiz PRO
```

2024-05-30 15:48 UTC, eshellman commented on more/free-programming-playgrounds.md
> +* [C Playground](https://programiz.pro/ide/c) - by Programiz PRO
```suggestion
* [C Playground](https://programiz.pro/ide/c) - Programiz PRO
```

2024-05-31 04:26 UTC, awalrujaa commented
@eshellman 
As per the change request, I've made the changes. Could you review?

2024-05-31 15:13 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2024-05-31 15:13 UTC, merged