Added RapberryPi , Internet-of-things , Software Engineering and Data Science HINDI courses
EbookFoundation/free-programming-books pull request #11288
Opened 2024-10-01 10:37 UTC by Nalin-khanna

Dear Repository Owner , 
I have added links to free valuable courses of RapberryPi , Internet-of-things , Software Engineering and Data Science in Hindi to make it more accessible for Hindi-speaking users.
I’d appreciate it if you could review and consider merging my changes.
- Nalin Khanna
## What does this PR do?
This PR adds additional links to Hindi-language courses for several computer science topics. The new courses aim to provide learning resources for Hindi-speaking learners, covering key areas in computer science.

### Why is this valuable ?
To make learning more accessible for Hindi speakers by offering high-quality courses in their native language.
These courses are detailed, cover core topics thoroughly, and provide clear explanations, ensuring learners receive a strong foundation.

### How do we know it's really free?
The courses do not require any hidden fees for accessing the main content . Courses are free and accessible to all. 

### For book lists, is it a book? For course lists, is it a course? etc.
It is a course 
## Checklist:
- [✅] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [✅] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [✅] Include author(s) and platform where appropriate.
- [✅] Put lists in alphabetical order, correct spacing.
- [✅]Add needed indications (PDF, access notes, under construction).
- [✅]Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2024-10-01 14:51 UTC, eshellman requested changes
we pprefer atomic changes so we can merge the correct stuff without getting delayed by other problems

2024-10-01 14:51 UTC, eshellman commented on courses/free-courses-hi.md
> +* [Raspberrypi](#raspberrypi)
```suggestion
* [Raspberry Pi](#raspberry-pi)    
```

2024-10-01 14:51 UTC, eshellman commented on courses/free-courses-hi.md
> +### Raspberrypi
```suggestion
### Raspberry Pi
```

2024-10-01 14:51 UTC, eshellman commented on courses/free-courses-hi.md
> +* [Computer Networks(Complete Playlist)](https://youtube.com/playlist?list=PLxCzCOWd7aiGFBD2-2joCpWOLUrDLvVV_&si=oZks6VlViqpdJUPt) - Gate Smashers
```suggestion
* [Computer Networks (Complete Playlist)](https://youtube.com/playlist?list=PLxCzCOWd7aiGFBD2-2joCpWOLUrDLvVV_&si=oZks6VlViqpdJUPt) - Gate Smashers
```

2024-10-01 14:51 UTC, eshellman commented on courses/free-courses-hi.md
> +* [Computer Networks : Computer Science and IT | GATE free Crash Course](https://youtube.com/playlist?list=PL3eEXnCBViH-hlNCNwdfV7VrEcTquANGa&si=T__auWK-bynzBzs6) - GATE Wallah - EE, EC, CS & IN
```suggestion
* [Computer Networks : Computer Science and IT \| GATE free Crash Course](https://youtube.com/playlist?list=PL3eEXnCBViH-hlNCNwdfV7VrEcTquANGa&si=T__auWK-bynzBzs6) - GATE Wallah 
```

2024-10-01 14:51 UTC, eshellman commented on courses/free-courses-hi.md
> +* [Cryptography and Network Security](https://youtube.com/playlist?list=PL9FuOtXibFjV77w2eyil4Xzp8eooqsPp8&si=IEisqG00PRd40nWo) - Abhishek Sharma
Don't invent titles! Use the title given by the resource.

2024-10-01 14:51 UTC, eshellman commented on courses/free-courses-hi.md
> +*[Software Engineering](https://youtube.com/playlist?list=PLPIwNooIb9vgYGBaBDqufEfJC99oD3juf&si=ORCoI-7ZG58HOXf4) - Perfect Computer Engineer
```suggestion
*[Software Engineering](https://youtube.com/playlist?list=PLPIwNooIb9vgYGBaBDqufEfJC99oD3juf) - Perfect Computer Engineer
```

2024-10-01 14:51 UTC, eshellman commented on courses/free-courses-hi.md
> +* [IOT- Internet of Things](#iot-internet-of-things)
```suggestion
* [Internet of Things](#internet-of-things)
```

2024-10-01 14:51 UTC, eshellman commented on courses/free-courses-hi.md
> +### IOT-Internet of Things
```suggestion
### Internet of Things
```

2024-10-01 16:43 UTC, Nalin-khanna commented
All the requested changes have been committed

2024-10-01 16:44 UTC, Nalin-khanna commented
> we pprefer atomic changes so we can merge the correct stuff without getting delayed by other problems

will keep that in mind 👍

2024-10-02 02:58 UTC, eshellman commented
also, we prefer "www.youtube.com" over "youtube.com"

2025-04-25 00:17 UTC, closed without merging