Add CONTRIBUTING-ta.md
EbookFoundation/free-programming-books pull request #11350
Opened 2024-10-03 17:43 UTC by Ritika-K7

## What does this PR do?
Add resource(s)| specifically, a translated version of the `CONTRIBUTING.md` file

## For resources
### Description
This PR includes a Tamil translation of the `CONTRIBUTING.md` file, making the contribution guidelines accessible to Tamil-speaking contributors.

### Why is this valuable (or not)?
This translation is valuable because it opens up the project to a broader audience, allowing Tamil speakers to understand and follow the contribution guidelines more easily. This may encourage more contributions from this community.

### How do we know it's really free?
The original `CONTRIBUTING.md` file is an open-source resource that provides contribution guidelines for the repository. The translated version adheres to the same principles of openness and accessibility.

### For book lists, is it a book? For course lists, is it a course? etc.
This PR does not add a book or course; it improves the repository by providing a translated resource.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2024-10-07 18:33 UTC, Ritika-K7 commented
Hi @eshellman @ashwingopalsamy 
I hope you're doing well. Could you please take a look at the PR I submitted? Let me know if any changes are needed.
fixing issue #11339

2024-10-13 03:13 UTC, ashwingopalsamy commented
Hey @Ritika-K7, I'd suggest fixing the formatting. I'll be adding my comments on this, in your PR.

On a side note, for everyone: going forward, please include the PR link in the comments when a review is needed. Thanks!

2024-10-13 03:22 UTC, ashwingopalsamy requested changes
🚨 I noticed a few areas where the 'Tamil' translation lacks context. While I appreciate the effort in using AI LLMs for the translation, it'd be great if you could put in a bit more work to improving the translation.

Please address them or share your improvements on the existing PR (#11356). Thanks!

2024-10-13 03:22 UTC, ashwingopalsamy commented on docs/CONTRIBUTING-ta.md
> +#பங்களிப்பாளர் உரிம ஒப்பந்தம்
Markdown Title needs to be addressed correctly here.

2024-10-13 03:22 UTC, ashwingopalsamy commented on docs/CONTRIBUTING-ta.md
> +#பங்களிப்பாளர் நடத்தை விதிகள்
Here too. Please ensure the file is well formatted, to highlight the differences between titles, sub-headings.

2024-10-13 03:22 UTC, ashwingopalsamy commented on docs/CONTRIBUTING-ta.md
> +பங்களிப்பதன் மூலம், இந்த களஞ்சியத்தின் உரிமத்திற்கு (../உரிமம்) நீங்கள் ஒப்புக்கொள்கிறீர்கள்.
There isn't any file named `../உரிமம்`. Please have a look on what and where this directory is and ensure to add the right path (in English) here.

2024-10-16 14:55 UTC, Ritika-K7 commented
Hi @eshellman @ashwingopalsamy 
I hope this message finds you well.
I have made the necessary changes to the code as you suggested. Please take a moment to review my pull request PR.
and Thank you for your guidance.

Changes made to:#11350
-Use ## for level 2 headings and ### for level 3 headings.
-Format links using square brackets.
-Used triple backticks (```) to create code blocks for any command-line instructions/code snippets.
-Used hyphens (-) followed by a space to create bullet points.

2024-10-18 15:48 UTC, Ritika-K7 commented
Hi @eshellman @ashwingopalsamy 
Sir I would appreciate it if you could review the changes I've made.
Changes made to:#11350

2024-10-20 14:23 UTC, ashwingopalsamy requested changes
I can still see a lot of room for improvements and the existing PR comments are yet to be addressed. If you need more help understanding the highlighted suggestions, please reply back in the comments.

2024-10-20 14:23 UTC, ashwingopalsamy commented on docs/CONTRIBUTING-ta.md
> +    ```
A bash script may not use 'Tamil' language. Please review your changes once again. :)

2024-10-20 14:23 UTC, ashwingopalsamy commented on docs/CONTRIBUTING-hi.md
The PR Title signifies, this pull request adds a 'CONTRIBUTING' file for 'Tamil', but I can also see a Hindi version of the same. 

I would suggest using a separate PR for adding the 'Hindi' version.

2024-10-20 14:23 UTC, ashwingopalsamy commented on docs/CONTRIBUTING-ta.md
> +##பங்களிப்பாளர் நடத்தை விதிகள்
Please format this Markdown Heading (H2) accordingly.

2024-10-20 14:25 UTC, ashwingopalsamy commented
I appreciate your efforts in translating to 'Tamil' though you aren't fluent in 'Tamil', but I would suggest to review the translation provided by the AI LLMs once before raising the PR, to save time for both of us. 😉

@Ritika-K7

2024-10-20 21:32 UTC, eshellman commented
@Ritika-K7 please follow the suggestions of @ashwingopalsamy

2025-05-24 00:16 UTC, closed without merging