Added gsap JavaScript library course in Hindi language
EbookFoundation/free-programming-books pull request #11394
Opened 2024-10-06 07:07 UTC by MOHDNEHALKHAN

## What does this PR do?
Add a javascript animation library(GSAP) course in Hindi language

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?
Yes, it is available on YouTube

### For book lists, is it a book? For course lists, is it a course? etc.
Yes, It is a course

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2024-10-06 15:33 UTC, Thenlie requested changes
Looks like a number of valid resources were removed in this PR. Please revert those deletions. Once you have made the requested changes, please update the PR title to include “(changes made)” and a reviewer will take another look as soon as they are available. Thanks!

2024-10-07 16:07 UTC, eshellman requested changes
It's usually not helpful to add a category for a single resource. Try to find another category, or see if there are other books in our lists that would fit into your category. In this case, just list in the javascript main category

2024-10-07 16:07 UTC, eshellman commented on courses/free-courses-hi.md
> +* [Animate anything with GSAP | Complete GSAP Course](https://www.youtube.com/playlist?list=PLbtI3_MArDOnIIJxB6xFtpnhM0wTwz0x6) - Sheryians Coding School
```suggestion
* [Animate anything with GSAP \| Complete GSAP Course](https://www.youtube.com/playlist?list=PLbtI3_MArDOnIIJxB6xFtpnhM0wTwz0x6) - Sheryians Coding School
```
escape pipes

2024-10-08 01:29 UTC, MOHDNEHALKHAN commented
@eshellman , please merge this PR

2024-10-08 01:51 UTC, eshellman commented
It's usually not helpful to add a category for a single resource. Try to find another category, or see if there are other books in our lists that would fit into your category. In this case, just list in the javascript main category

2024-10-08 04:15 UTC, MOHDNEHALKHAN commented
@eshellman , can i add more gsap courses in hindi language as gsap is also js library and i just want to add the courses not the books

2024-10-08 15:33 UTC, eshellman commented
sure, 2 courses is enough for a new category

2024-10-09 18:14 UTC, merged