Add: Assembly Language Course
EbookFoundation/free-programming-books pull request #11404
Opened 2024-10-06 21:05 UTC by maruf-pfc

## What does this PR do?
**Assembly Language Bangla Course**  added to the course file.

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2024-10-08 01:43 UTC, eshellman commented on courses/free-courses-bn.md
> +* [Assembly Language Bangla Tutorial](https://youtube.com/playlist?list=PLEYW3pZS6IQ8UMvusEVnIJ2dDieXKyKRM&si=TWVqCXX-SJ5clOYU) - Maruf Sarker
```suggestion
* [Assembly Language Bangla Tutorial](https://youtube.com/playlist?list=PLEYW3pZS6IQ8UMvusEVnIJ2dDieXKyKRM) - Maruf Sarker
```

2024-10-27 19:54 UTC, maruf-pfc commented
Finally fix the linter error 😀.

2024-10-27 22:38 UTC, eshellman requested changes
It's best to use separate braches for each PR

2024-10-27 22:38 UTC, eshellman commented on courses/free-courses-bn.md
> +* [Electron JS Bangla Tutorials](https://youtube.com/playlist?list=PL_XxuZqN0xVDgr7KreI5PaVZuG8Sx3L2c&si=FOsXyD-fC87a45YJ) - Stack Learner
```suggestion
* [Electron JS Bangla Tutorials](https://www.youtube.com/playlist?list=PL_XxuZqN0xVDgr7KreI5PaVZuG8Sx3L2c&si=FOsXyD-fC87a45YJ) - Stack Learner
```

2024-10-27 22:38 UTC, eshellman commented on courses/free-courses-bn.md
> +* [Standard Template Library of C++ (STL) [Bangla]](https://youtube.com/playlist?list=PLoa_roVVsxA0D1Kv_T7rbGHtSdYIUo4f5) - CPS Academy
```suggestion
* [Standard Template Library of C++ (STL)](https://www.youtube.com/playlist?list=PLoa_roVVsxA0D1Kv_T7rbGHtSdYIUo4f5) - CPS Academy
```

2024-10-27 22:38 UTC, eshellman commented on courses/free-courses-bn.md
> +* [Assembly Language Bangla Tutorial](https://youtube.com/playlist?list=PLEYW3pZS6IQ8UMvusEVnIJ2dDieXKyKRM) - Maruf Sarker
```suggestion
* [Assembly Language Bangla Tutorial](https://www.youtube.com/playlist?list=PLEYW3pZS6IQ8UMvusEVnIJ2dDieXKyKRM) - Maruf Sarker
```

2024-10-28 13:16 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2024-10-28 13:16 UTC, merged