Add license notations for 3 books
EbookFoundation/free-programming-books pull request #11433
Opened 2024-10-08 19:53 UTC by Antrikshgwal

…petetive Programmer's Handbook

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2024-10-08 22:10 UTC, eshellman requested changes
we're not tracking version numbers

Please document in the PR description where you found the license statement

2024-10-08 22:10 UTC, eshellman commented on books/free-programming-books-subjects.md
> +* [Grokking Bitcoin](https://rosenbaum.se/book/) - Kalle Rosenbaum (HTML) (CC BY-NC-SA 4.0)
```suggestion
* [Grokking Bitcoin](https://rosenbaum.se/book/) - Kalle Rosenbaum (HTML) (CC BY-NC-SA)
```

2024-10-08 22:10 UTC, eshellman commented on books/free-programming-books-subjects.md
> +* [Competitive Programmer's Handbook](https://cses.fi/book/book.pdf) - Antti Laaksonen (PDF) (CC-BY-NC-SA 4.0)
```suggestion
* [Competitive Programmer's Handbook](https://cses.fi/book/book.pdf) - Antti Laaksonen (PDF) (CC BY-NC-SA)
```

2024-10-08 22:10 UTC, eshellman commented on books/free-programming-books-subjects.md
> +* [Mastering Bitcoin - Unlocking digital currencies (2017), 2nd Edition](https://github.com/bitcoinbook/bitcoinbook) - Andreas M. Antonopoulos (AsciiDoc) (CC-BY-NC-ND)
```suggestion
* [Mastering Bitcoin - Unlocking digital currencies (2017), 2nd Edition](https://github.com/bitcoinbook/bitcoinbook) - Andreas M. Antonopoulos (AsciiDoc) (CC BY-NC-ND)
```

2024-10-09 18:04 UTC, eshellman commented
`\`  (CC BY )\`` means to literally use ` (CC BY)`, not `\`  (CC BY )\``

2025-01-23 18:50 UTC, Antrikshgwal commented
Hey!! @eshellman 
Can you review these changes and let me know if something has to be changed.

2025-01-25 16:04 UTC, Antrikshgwal commented
Hey @eshellman 
Just the made changes as told by you, please let me if something else still has to be made. Thanks!!

2025-01-26 00:20 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2025-01-26 00:20 UTC, merged