3 Books License Added
EbookFoundation/free-programming-books pull request #11449
Opened 2024-10-09 11:42 UTC by Aryan9inja

## What does this PR do?
Add info

## For resources
### Description
Add License Notes to following Books:

1. [Eloquent JavaScript 3rd edition](http://eloquentjavascript.net) - Marijn Haverbeke (HTML, PDF, EPUB, MOBI)

### License Line Found Under The Book Image On Site
"Licensed under a [Creative Commons attribution-noncommercial license](https://creativecommons.org/licenses/by-nc/3.0/)."

2. [Introduction to Scientific Programming with Python](https://library.oapen.org/bitstream/id/56d27e73-e92a-4398-8198-239be7aacc93/2020_Book_IntroductionToScientificProgra.pdf) - Joakim Sundnes (PDF)

### License Line Found On Page 5 Of PDF
"This book is licensed under the terms of the Creative Commons Attribution 4.0
International License (http://creativecommons.org/licenses/by/4.0/)"

3. [Think Python 2nd Edition](https://greenteapress.com/wp/think-python-2e/) - Allen B. Downey (3.x) (HTML, PDF)

### License Line Found On Page 4 Of PDF
"Permission is granted to copy, distribute, and/or modify this document under the terms of the
Creative Commons Attribution-NonCommercial 3.0 Unported License, which is available at http:
//creativecommons.org/licenses/by-nc/3.0/"

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x ] Include author(s) and platform where appropriate.
- [x ] Put lists in alphabetical order, correct spacing.
- [ x] Add needed indications (PDF, access notes, under construction).
- [ x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2024-10-09 18:28 UTC, eshellman requested changes
use the specified licenses!

2024-10-09 18:28 UTC, eshellman commented on books/free-programming-books-langs.md
> +* [Eloquent JavaScript 3rd edition](http://eloquentjavascript.net) - Marijn Haverbeke (HTML, PDF, EPUB, MOBI) (CC BY-NC-ND)
wrong license

2024-10-09 18:28 UTC, eshellman commented on books/free-programming-books-langs.md
> +* [Introduction to Scientific Programming with Python](https://library.oapen.org/bitstream/id/56d27e73-e92a-4398-8198-239be7aacc93/2020_Book_IntroductionToScientificProgra.pdf) - Joakim Sundnes (PDF)
wrong license

2024-10-09 18:28 UTC, eshellman commented on books/free-programming-books-langs.md
> +* [Think Python 2nd Edition](https://greenteapress.com/wp/think-python-2e/) - Allen B. Downey (3.x) (HTML, PDF) (CC BY-NC-ND)
wrong license

2024-10-10 02:15 UTC, Aryan9inja commented
Sir I have added changes.

2024-10-10 14:12 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2024-10-10 14:12 UTC, merged