Added license notes to 3 books and added type of book (pdf) for one
EbookFoundation/free-programming-books pull request #11479
Opened 2024-10-10 17:42 UTC by manvith12

## What does this PR do?
Add info based on #11355

### For resources
#### Description
This PR adds license notes to the following books located at books:

1. **A Complete Guide to Standard C++ Algorithms**  
   License Line found on Page 4 of the PDF.  
   "This work may be distributed and/or modified under the conditions of the CC-BY-NC-SA license."  
   Added (CC-BY-NC-SA)

2. **C++ GUI Programming with Qt 3**  
   License Line found on Page 4 of the PDF.  
   "This material may only be distributed subject to the terms and conditions set forth in the Open Publication License, v1.0 or later."  
   Added (OPl)

3. **C++ Notes for Professionals**  
   License Line found on Page 19 of the PDF.  
   "The content is written by the beautiful people at Stack Overflow. Text content is released under Creative Commons BY-SA."  
   Added (CC BY-SA)

this pr also added info on type of book :

1. **C++ Language**
    checked the  book and added (HTML)

#### Why is this valuable (or not)?
This information clarifies the licensing for these resources, ensuring users understand the terms under which they can use, modify, and distribute the content.

#### How do we know it's really free?
The licenses clearly state that the materials can be used freely within the specified conditions, which aligns with the principles of open educational resources.

#### For book lists, is it a book? For course lists, is it a course? etc.
It's a book.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up
- Check the status of GitHub Actions and resolve any reported warnings!

2024-10-10 17:51 UTC, manvith12 commented
i dont understand whats the lint error , could anyone please explain

2024-10-11 16:47 UTC, eshellman requested changes
the extra space shoul satisfy the linter

2024-10-11 16:47 UTC, eshellman commented on books/free-programming-books-langs.md
> +* [A Complete Guide to Standard C++ Algorithms](https://github.com/HappyCerberus/book-cpp-algorithms) - Šimon Tóth (PDF, LaTeX)(CC BY-NC-SA) *(:construction: in process)*
```suggestion
* [A Complete Guide to Standard C++ Algorithms](https://github.com/HappyCerberus/book-cpp-algorithms) - Šimon Tóth (PDF, LaTeX) (CC BY-NC-SA) *(:construction: in process)*
```

2024-10-11 16:47 UTC, eshellman commented on books/free-programming-books-langs.md
> +* [C++ GUI Programming With Qt 3](https://ptgmedia.pearsoncmg.com/images/0131240722/downloads/blanchette_book.pdf) - Jasmin Blanchette, Mark Summerfield (PDF)(OPL)
OPL is deprecated. We are not supporting it by adding license annotations.

2024-10-12 04:40 UTC, manvith12 reviewed
made the changes asked for

2024-10-12 15:53 UTC, eshellman commented on books/free-programming-books-langs.md
> +* [C++ Notes for Professionals] (https://goalkicker.com/CPlusPlusBook) - Compiled from StackOverflow Documentation (PDF) (CC BY-SA)
```suggestion
* [C++ Notes for Professionals](https://goalkicker.com/CPlusPlusBook) - Compiled from StackOverflow Documentation (PDF) (CC BY-SA)
```

2024-10-14 16:06 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2024-10-14 16:06 UTC, merged