Add Comprehensive Free Resources for Algorithms and System Design.
EbookFoundation/free-programming-books pull request #11494
Opened 2024-10-11 10:28 UTC by shreykumar33

This pull request enhances our repository by including essential educational materials in both English and Hindi. It features the renowned algorithms textbook, "Introduction to Algorithms" (CLRS), alongside several free courses on Data Structures and Algorithms (DSA) and System Design.

## What does this PR do?
Adds educational resources: Includes the PDF version of "Introduction to Algorithms" by Cormen et al., along with various DSA and System Design courses.

## For resources
### Description
Description
Book: "Introduction to Algorithms" (PDF) by Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, and Clifford Stein.
Courses:
System Design: "System Design Roadmap with Videos for SDEs" - Striver.
Algorithms:
"Striver's DSA Playlist" - Striver.
"Complete C++ Placement DSA Course" - Love Babbar.

### Why is this valuable (or not)?
These resources are crucial for learners seeking to deepen their understanding of algorithms and system design, which are foundational for software development and technical interviews. They are reputable within the programming community, providing high-quality education at no cost.

### How do we know it's really free?
All resources listed are freely accessible online. The book is available in PDF format on platforms like the Internet Archive, ensuring that anyone can access it without financial constraints [1](https://archive.org/details/introduction-to-algorithms-third-edition-2009)[2](https://dl.ebooksworld.ir/books/Introduction.to.Algorithms.4th.Leiserson.Stein.Rivest.Cormen.MIT.Press.9780262046305.EBooksWorld.ir.pdf).

### For book lists, is it a book? For course lists, is it a course? etc.
Book: Yes, "Introduction to Algorithms" is a textbook.
Courses: Yes, the provided links lead to legitimate online courses.

## Checklist:
- [ Yes] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [Yes ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [Yes] Include author(s) and platform where appropriate.
- [Yes ] Put lists in alphabetical order, correct spacing.
- [Yes] Add needed indications (PDF, access notes, under construction).
- [Yes] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2024-10-11 10:46 UTC, shreykumar33 reviewed
fixed lines

2024-10-11 16:30 UTC, shreykumar33 commented
> Linter failed, fix the error(s):
> 
> ```
> free-programming-books/courses/free-courses-ur.md
> 65:1-66:3  warning  Incorrect number of blank lines between last section and next heading  blank-lines-1-0-2  remark-lint
> ```

Fixed

2024-10-11 16:30 UTC, shreykumar33 commented
> Linter failed, fix the error(s):
> 
> ```
> free-programming-books/courses/free-courses-ur.md
> 65:1-66:3  warning  Incorrect number of blank lines between last section and next heading  blank-lines-1-0-2  remark-lint
> ```

Fixed

2024-10-11 16:31 UTC, shreykumar33 reviewed
All resources checked and issues fixed. Kindly review

2024-10-11 17:40 UTC, eshellman requested changes

2024-10-11 17:40 UTC, eshellman commented on courses/free-courses-ur.md
> +* [Complete C++ Placement DSA Course](https://www.youtube.com/watch?v=WQoB2z67hvY&list=PLDzeHZWIZsTryvtXdMr6rPh4IDexB5NIA) - Love Babbar
For youtube, we prefer "playlist" links and the name of the producer/creator. docs/CONTRIBUTING.md#platforms-and-access-notes

2024-10-11 17:40 UTC, eshellman commented on courses/free-courses-ur.md
> +* [Striver's DSA playlist](https://takeuforward.org/array/top-array-interview-questions-structured-path-with-video-solutions/) - Striver
not urdu

2024-10-11 17:40 UTC, eshellman commented on courses/free-courses-ur.md
> +* [System Design Roadmap with Videos for SDEs](https://takeuforward.org/system-design/complete-system-design-roadmap-with-videos-for-sdes/) - Striver
not urdu

2024-10-12 15:36 UTC, eshellman commented
all our other takeuforward items are in the problem sets/competitive programming list, including items that seem very close to these. Please consider using that list instead of the courses list.

2024-10-12 16:29 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2024-10-12 16:30 UTC, merged