Fix case. Php < PHP
EbookFoundation/free-programming-books pull request #11572
Opened 2024-10-15 12:40 UTC by hstsethi

## What does this PR do?
Fixes case of "PHP" in Hindi booklist.

## For resources
### Description

### Why is this valuable (or not)?

I believe it is. 

### How do we know it's really free?

Not applicable

### For book lists, is it a book? For course lists, is it a course? etc.

Not applicable

## Checklist:
- [X ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [X] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [X] Include author(s) and platform where appropriate.
- [X] Put lists in alphabetical order, correct spacing.
- [X ] Add needed indications (PDF, access notes, under construction).
- [X] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2024-10-15 14:43 UTC, Ajay-singh1 approved these changes
LGTM!Wait for Eric.

2024-10-15 22:20 UTC, hstsethi commented
> agreed, but the rest of the titles don't match

I am sorry, but I don't understand. Do you mean the heading?

2024-10-16 02:36 UTC, eshellman requested changes
Don't invent titles! Use the title given by the resource.

2024-10-16 02:36 UTC, eshellman commented on books/free-programming-books-hi.md
> +* [PHP \| Hindi](https://www.learnhindituts.com/php) - LearnHindiTuts.com
title appears to be "PHP Tutorials In Hindi"

2024-10-16 02:36 UTC, eshellman commented on books/free-programming-books-hi.md
> +* [PHP Hindi Tutorial \| Hindi](http://tutorialsroot.com/php/index.html) - TutorialsRoot.com
title appears to be "PHP in Hindi Tutorial"

2024-10-16 02:46 UTC, hstsethi commented
> Don't invent titles! Use the title given by the resource.

I am really sorry for the inconvenience caused. I have followed your suggestions. Please review.

2024-10-16 02:51 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2024-10-16 02:51 UTC, merged