Fixed React and react native contents
EbookFoundation/free-programming-books pull request #11581
Opened 2024-10-16 04:52 UTC by manvith12

## What does this PR do? 
Add resource(s) | Remove resource(s) 
resolves issue #11570 

## For resources
### removed "react tutorial" from the subheading "react native" and instead added it under "react"

### It is valuable because it maintains the order and subheadings

### How do we know it's really free?
 it is

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2024-10-16 10:54 UTC, Ajay-singh1 requested changes

2024-10-16 10:54 UTC, Ajay-singh1 commented on courses/free-courses-en.md
> +* [React Tutorial for Beginners](https://www.youtube.com/playlist?list=PLC3y8-rFHvwgg3vaYJgHGnModB54rxOk3) - codevolution
```suggestion
* [ReactJS Tutorial for Beginners](https://www.youtube.com/playlist?list=PLC3y8-rFHvwgg3vaYJgHGnModB54rxOk3) - codevolution
```

2024-10-16 10:54 UTC, Ajay-singh1 commented on courses/free-courses-en.md
> +manvith12/free-programming-books### Index
```suggestion
### Index
```

2024-10-16 10:54 UTC, Ajay-singh1 commented on courses/free-courses-en.md
> +manvith12/free-programming-books### Index
Delete this

2024-10-16 10:56 UTC, Ajay-singh1 commented on courses/free-courses-en.md
> +* [React Tutorial for Beginners](https://www.youtube.com/playlist?list=PLC3y8-rFHvwgg3vaYJgHGnModB54rxOk3) - codevolution
Fix the title and fix the linter error.

2024-10-16 12:31 UTC, manvith12 commented
lint satisfied successfully uff

2024-10-16 21:17 UTC, eshellman commented
why not move it to the React section?

2024-10-17 04:47 UTC, manvith12 commented
> why not move it to the React section?
there was a existing section named react native , should i remove the section and merge both react and react native?

2024-10-17 14:46 UTC, eshellman commented
> > why not move it to the React section?
> > there was a existing section named react native , should i remove the section and merge both react and react native?

My understanding was that you think a React resource doesn't belong in the React Native section. Fine, so move it to the React section.

2024-10-18 03:21 UTC, manvith12 commented
> > > why not move it to the React section?
> > > there was a existing section named react native , should i remove the section and merge both react and react native?
> 
> My understanding was that you think a React resource doesn't belong in the React Native section. Fine, so move it to the React section.
completed

2024-10-18 14:42 UTC, eshellman commented
it's not added

2024-12-20 12:48 UTC, closed without merging