Added neovim resources
EbookFoundation/free-programming-books pull request #11582
Opened 2024-10-16 05:15 UTC by manvith12

## What does this PR do?
Add resource

## For resources
Added neovim book , [learn neovim]( https://ofirgall.github.io/learn-nvim/)
resolves issue #11569 

### Why is this valuable (or not)?
adds books to neovim language

### How do we know it's really free?
its maintained by a github repo 

### For book lists, is it a book? For course lists, is it a course? etc.
yes its a book

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2024-10-16 11:13 UTC, Ajay-singh1 requested changes
No need to create a new section add it under the IDE and Editors Section

2024-10-16 11:48 UTC, manvith12 reviewed
did the above cited suggestions

2024-10-16 12:00 UTC, manvith12 commented
cant find the linter error T-T

2024-10-16 12:38 UTC, manvith12 commented
lint left yayy

2024-10-16 21:20 UTC, eshellman requested changes

2024-10-16 21:20 UTC, eshellman commented on books/free-programming-books-langs.md
> +* [GNU Emacs Lisp Reference Manual](http://www.gnu.org/software/emacs/manual/elisp.html)
you've added a duplicate

2024-10-16 21:20 UTC, eshellman commented on books/free-programming-books-langs.md
> +* [Learn Neovim](https://ofirgall.github.io/learn-nvim/) (HTML)
should go in the IDE and Editors section

2024-10-17 02:25 UTC, Ajay-singh1 commented
@manvith12 Kindly close this PR We have got a PR merged for #11569 by #11586.Thank you.

2024-10-17 02:29 UTC, closed without merging