Removed React Native video and added React Native playlist
EbookFoundation/free-programming-books pull request #11584
Opened 2024-10-16 07:32 UTC by Taussy10

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?
There was video of React Native but React Native playlist needed so I added it.
 
### How do we know it's really free?
It's publicly available on Youtube

### For book lists, is it a book? For course lists, is it a course? etc.
It's a course of React Native

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2024-10-16 20:49 UTC, eshellman requested changes

2024-10-16 20:49 UTC, eshellman commented on courses/free-courses-en.md
> +* [React Native Tutorial for Beginners](https://youtube.com/playlist?list=PLC3y8-rFHvwhiQJD1di4eRVN30WWCXkg1&si=GkIhiqpFQTQkBrJ8) - codevolution
```suggestion
* [React Native Tutorial for Beginners](https://www.youtube.com/playlist?list=PLC3y8-rFHvwhiQJD1di4eRVN30WWCXkg1) - codevolution
```

2024-10-16 20:49 UTC, eshellman commented on courses/free-courses-en.md
> -* [React Tutorial for Beginners](https://www.youtube.com/playlist?list=PLC3y8-rFHvwgg3vaYJgHGnModB54rxOk3) - codevolution
move to react section

2024-10-23 02:16 UTC, Thenlie commented
Closing as duplicate of #11571.

2024-10-23 02:16 UTC, closed without merging