Update free-programming-books-langs.md
EbookFoundation/free-programming-books pull request #11645
Opened 2024-10-22 13:42 UTC by MrCyGuy

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

Add resources

## For resources
### Description

I wanted to include more free books on COBOL, so that's just what I did. I added 5 free books about programming in COBOL.

### Why is this valuable (or not)?

I've nearly doubled the amount of resources there are now for COBOL. This expands the amount of learning, which is the purpose of this repository. 

### How do we know it's really free?

I can access these books for free without any information inputs or money paid.

### For book lists, is it a book? For course lists, is it a course? etc.

All my added resources are books. I have only included books.

## Checklist:
- [X] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [X] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [X] Include author(s) and platform where appropriate.
- [X] Put lists in alphabetical order, correct spacing.
- [X] Add needed indications (PDF, access notes, under construction).
- [X] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2024-10-22 18:44 UTC, eshellman requested changes
good additions, but get the authors right!

2024-10-22 18:44 UTC, eshellman commented on books/free-programming-books-langs.md
> +* [Learn COBOL Programming](https://riptutorial.com/Download/cobol.pdf) - Michael Coughlan (PDF)
not the author. see attributions for other riptutorial resources

2024-10-22 18:44 UTC, eshellman commented on books/free-programming-books-langs.md
> +* [A Guide to COBOL Programming](https://www.ibm.com/docs/en/ssw_ibm_i_71/rzase/sc092540.pdf) - David E. Woolbright (PDF)
not the author

2024-10-22 18:44 UTC, eshellman commented on books/free-programming-books-langs.md
> +* [COBOL: A Self Instructional Manuel](https://babel.hathitrust.org/cgi/pt?id=mdp.39015000482466&view=1up&seq=14&skin=2021) - James A. Saxon
fix spelling.

2024-10-22 18:44 UTC, eshellman commented on books/free-programming-books-langs.md
> +* [COBOL Programmer's Guide and Reference](https://www.microfocus.com/documentation/orbix/orbixfm62/pdfdoc/cobol_guide_and_ref.pdf) - Micro Focus (PDF)
that's not the author

2024-10-23 15:57 UTC, eshellman requested changes
unauthorized distributions tend to disappear, so we don't allow them

2024-10-23 15:57 UTC, eshellman commented on books/free-programming-books-langs.md
> +* [Cobol: From Micro To Mainframe](https://vdoc.pub/download/cobol-from-micro-to-mainframe-3rd-edition-5t4osmo5p540) - Robert T. Grauer, Carol Vazquez Villar, Arthur R. Buss (PDF)
This appears not to be an authorized distribution. Please see docs/CONTRIBUTING.md guidelines.

2024-10-23 15:57 UTC, eshellman commented on books/free-programming-books-langs.md
> +* [Sams Teach Yourself COBOL in 21 Days](http://testa.roberta.free.fr/My%20Books/Mainframe/Cobol/Teach%20Yourself%20Cobol%20In%2021%20Days%20(2nd%20Ed).pdf) - Mo Budlong (PDF)
This appears not to be an authorized distribution. Please see docs/CONTRIBUTING.md guidelines.

2024-10-23 15:57 UTC, eshellman commented on books/free-programming-books-langs.md
> +* [COBOL: A Self Instructional Manual](https://babel.hathitrust.org/cgi/pt?id=mdp.39015000482466&view=1up&seq=14&skin=2021) - James A. Saxon
```suggestion
* [COBOL: A Self Instructional Manual](https://babel.hathitrust.org/cgi/pt?id=mdp.39015000482466&view=1up&seq=9&skin=2021) - James A. Saxon 
```

2024-10-24 03:19 UTC, MrCyGuy commented
So I removed the unauthorized distribution books and instead replaced them with additions in Python, Pascal, and CSS. I hope this works! Please let me know if it doesn't and thank you for helping me get these right!

2024-10-24 12:43 UTC, eshellman requested changes
remove the python book and you're good to go

2024-10-24 12:43 UTC, eshellman commented on books/free-programming-books-langs.md
> +* [Computational Physics with Python](https://belglas.com/wp-content/uploads/2018/03/cpwp.pdf) - Eric Ayars (PDF)
There's no indications that this is an authorized distribution. Please see docs/CONTRIBUTING.md guidelines.

2024-10-25 03:00 UTC, MrCyGuy commented
Hey can you review if my PR is good to go?

2024-10-26 16:52 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2024-10-26 16:52 UTC, merged