Add files via upload
EbookFoundation/free-programming-books pull request #11668
Opened 2024-10-24 17:57 UTC by Mahesh-Vijaykumar

Added c ,c# and c++ books

2024-10-24 18:08 UTC, Mahesh-Vijaykumar commented
Added a few PDF links

2024-10-26 16:03 UTC, eshellman requested changes

2024-10-26 16:03 UTC, eshellman commented on books/free-programming-books-de.md
> +* [FUNDAMENTALS OF COMPUTER PROGRAMMING WITH C#](https://introprogramming.info/wp-content/uploads/2013/07/Books/CSharpEn/Fundamentals-of-Computer-Programming-with-CSharp-Nakov-eBook-v2013.pdf) (PDF)
Also, this a book in English, not german. move it to the english list.

2024-10-26 16:03 UTC, eshellman commented on books/free-programming-books-de.md
> +* [A Complete Guide to Programming in C++](https://www.idpoisson.fr/volkov/C++.pdf) (PDF)
This appears not to be an authorized distribution. Please see docs/CONTRIBUTING.md guidelines.

2024-11-30 06:26 UTC, closed without merging