Added Linux books in Tamil language
EbookFoundation/free-programming-books pull request #11663
Opened 2024-10-24 05:14 UTC by 0xParcival

## What does this PR do?

      Added Linux Tamil books 

## For resources

      https://freetamilebooks.com/ebooks/

### Description

         It about Linux Fundamentals

### Why is this valuable (or not)?
         it about Linux in Tamil language

### How do we know it's really free?
        it is under cc license
   
### For book lists, is it a book? For course lists, is it a course? etc.
          it's book
      

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2024-10-24 12:46 UTC, eshellman requested changes

2024-10-24 12:46 UTC, eshellman commented on books/free-programming-books-ta.md
> +* [Linux](#liunx)
spelling

2024-10-24 12:46 UTC, eshellman commented on books/free-programming-books-ta.md
> +*[Learn GNU Linux in Tamil - Part 1](https://freetamilebooks.com/ebooks/learn-gnulinux-in-tamil-part1/) - து.நித்யா (PDF)
need a space after '*'
Don't invent titles! Use the title given by the resource.

2024-10-24 12:46 UTC, eshellman commented on books/free-programming-books-ta.md
> +*[Learn GNU Linux in Tamil - Part 2](https://freetamilebooks.com/ebooks/learn-gnulinux-in-tamil-part2/) - து.நித்யா (PDF)
need a space after '*'
Don't invent titles! Use the title given by the resource.

2024-10-25 01:53 UTC, 0xParcival reviewed
I changed as Per your request

2024-10-26 16:04 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2024-10-26 16:04 UTC, merged

2024-10-28 05:24 UTC, 0xParcival commented
> Thanks, and welcome to free-programming-books!

Thanks