Added 5 more Next.js courses to free-courses-hi.md
EbookFoundation/free-programming-books pull request #11736
Opened 2024-10-30 22:48 UTC by Akshat3144

## What does this PR do?
Add resource(s)

## For resources
### Description
Added 5 more Next.js courses to the `free-courses-hi.md` file.

### Why is this valuable (or not)?
These additional resources provide more options for learning Next.js in Hindi, catering to a wider audience.

### How do we know it's really free?
All the added courses are available for free on YouTube.

### For book lists, is it a book? For course lists, is it a course? etc.
These are video courses.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up
- Check the status of GitHub Actions and resolve any reported warnings!

2024-10-31 14:40 UTC, eshellman requested changes
can't see the content changes through the forest of formatting changes.

2024-10-31 14:40 UTC, eshellman commented on courses/free-courses-hi.md
> +  * [Soft Computing](#soft-computing)
remove the format changes

2024-10-31 14:40 UTC, eshellman commented on courses/free-courses-hi.md
> +* [Complete C++ DSA Course \| Data Structures &amp; Algorithms Playlist](https://www.youtube.com/playlist?list=PLfqMhTWNBTe137I_EPQd34TsgV6IO55pt) - Apna College
markdown, not html

2024-10-31 17:00 UTC, Akshat3144 commented
Thanks sir, All requested changes Done, please check.

2024-10-31 20:30 UTC, eshellman commented on courses/free-courses-hi.md
> +---
please remove these

2024-10-31 21:10 UTC, Akshat3144 commented
requested change done, sir, please check.

2024-11-01 01:07 UTC, eshellman requested changes
For youtube, we prefer "playlist" links and the name of the producer/creator. docs/CONTRIBUTING.md#platforms-and-access-notes
"watch" links are ok if they are more than an hour and have outlines. To make it easier for the reviewers, please note this in your PR description.

2024-11-01 01:07 UTC, eshellman commented on courses/free-courses-hi.md
> +* [Learn NextJS with Aceternity UI library](https://www.youtube.com/watch?v=cVKB5NQPiFA&t=744s) - Chai aur Code
Don't invent titles! Use the title given by the resource.

2024-11-01 05:21 UTC, Akshat3144 commented
Added the official titles and updated the description of the pull request.

2024-11-01 12:41 UTC, merged

2024-11-01 15:43 UTC, Akshat3144 commented
Hey, could you add hacktoberfest label over it because apparently, its not updated there. Thanks

2024-11-02 20:21 UTC, eshellman commented
the whole repo has the label