Add solidity course
EbookFoundation/free-programming-books pull request #11740
Opened 2024-10-31 10:57 UTC by anand-242003

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2024-10-31 20:29 UTC, eshellman commented
please remove the package-lock file (use a .gitignore file)

2024-11-01 02:58 UTC, eshellman commented
hmm the linter doesn't like adding that to .gitignore 
instead, just remove the file from your repo; we'll figure out how to manage changes to gitignore separately

2024-11-01 04:30 UTC, anand-242003 commented
I've removed package-lock.json from the repository as the linter didn't approve of adding it to .gitignore. Could you please guide me on the next steps or any further changes needed?

2024-11-01 12:38 UTC, eshellman commented
maybe you need to push your commits

2024-11-01 15:34 UTC, anand-242003 commented
I've made the changes and pushed them again. Let me know if there's anything else I should adjust .

2024-11-02 20:20 UTC, eshellman commented
I see the problem. you ned to undo your change to .gitignore

2024-11-07 04:28 UTC, Ajay-singh1 requested changes

2024-11-07 04:28 UTC, Ajay-singh1 commented on .gitignore
> +package-lock.json
```suggestion
```

2024-11-07 04:28 UTC, Ajay-singh1 commented on .gitignore
> +package-lock.json
Just commit these changes.

2025-05-22 00:17 UTC, closed without merging