Added a playground for Ionic
EbookFoundation/free-programming-books pull request #11781
Opened 2024-12-08 07:59 UTC by Ajay-singh1

## What does this PR do?
Add resource(s) 

## For resources
Playground
### Description
Added an Ionic Playground
### Why is this valuable (or not)?
Yes
### How do we know it's really free?
It is free
### For book lists, is it a book? For course lists, is it a course? etc.
Playground
## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2024-12-09 16:18 UTC, eshellman commented on more/free-programming-playgrounds.md
> +* [GDB](https://www.onlinegdb.com/online_csharp_compiler)
also, a duplicate. This is why we want to use name from source.

2024-12-09 16:21 UTC, eshellman commented on more/free-programming-playgrounds.md
> +* [myCompiler](https://www.mycompiler.io/online-csharp-compiler)
```suggestion
* [Online C# Compiler](https://www.mycompiler.io/online-csharp-compiler) - myCompiler
```

2024-12-09 16:25 UTC, eshellman commented on more/free-programming-playgrounds.md
> +* [Scholarhat](https://www.scholarhat.com/compiler/csharp)
```suggestion
* [C# Online Compiler](https://www.scholarhat.com/compiler/csharp) - ScholarHat
```

2024-12-09 16:26 UTC, eshellman commented on more/free-programming-playgrounds.md
> +* [Sharplab](https://sharplab.io)
```suggestion
* [SharpLab](https://sharplab.io)
```

2024-12-09 16:28 UTC, eshellman commented on more/free-programming-playgrounds.md
> +* [W3Schools](https://www.w3schools.com/cs/cs_compiler.php)
```suggestion
* [C# Online Compiler](https://www.w3schools.com/cs/cs_compiler.php) - W3Schools
```

2024-12-09 16:30 UTC, eshellman commented on more/free-programming-playgrounds.md
> +* [Codeapi](https://git-school.github.io/visualizing-git)
```suggestion
* [Visualizing Git](https://git-school.github.io/visualizing-git)
```

2024-12-09 16:35 UTC, eshellman commented on more/free-programming-playgrounds.md
> +* [Codepen](https://codepen.io/ajp8164/pen/zrLQYP)
looks like sample code, not a playground as such

2024-12-19 20:58 UTC, ehis-042 commented
Please what is the problem of this project

2024-12-20 10:42 UTC, Ajay-singh1 commented
@ehis-042 I will fix this today!

2024-12-20 19:41 UTC, eshellman requested changes
still have duplcate resources!

2024-12-20 19:41 UTC, eshellman commented on more/free-programming-playgrounds.md
> +* [Programiz - Online Compiler](https://www.programiz.com/csharp-programming/online-compiler)
Why are you changing it?

2024-12-20 19:41 UTC, eshellman commented on more/free-programming-playgrounds.md
> +* [Visualizing Git](https://git-school.github.io/visualizing-git)
the resource on lines 174 and line 176 are duplicates

2024-12-21 02:04 UTC, Ajay-singh1 commented
> still have duplcate resources!

I have to delete it and re-add it because the lint was failing

2024-12-21 23:30 UTC, merged

2025-03-09 10:56 UTC, HSUYATANG reviewed
@@ -92,8 +92,15 @@
 
 ### C#
 
+* [C# Online Compiler](https://www.scholarhat.com/compiler/csharp) - ScholarHat
+* [C# Online Compiler](https://www.w3schools.com/cs/cs_compiler.php) - W3Schools
+* [C# playground](https://codapi.org/csharp) - Codeapi
+* [OneCompiler](https://onecompiler.com/csharp/3wv9zujyk)
+* [Online C# Compiler](https://www.mycompiler.io/online-csharp-compiler) - myCompiler
+* [Online C# Compiler IDE](https://www.jdoodle.com/compile-c-sharp-online) - JDoodle
 * [OnlineGDB](https://www.onlinegdb.com/online_csharp_compiler)
-* [Programiz - Online Compiler](https://www.programiz.com/csharp-programming/online-compiler/)
+* [Programiz - Online Compiler](https://www.programiz.com/csharp-programming/online-compiler)
+* [SharpLab](https://sharplab.io)
 * [SoloLearn](https://code.sololearn.com/csharp)
 
@@ -164,7 +171,8 @@
 
 ### Git
 
-* [Git](https://learngitbranching.js.org/?NODEMO)
+* [Git-school](https://git-school.github.io/visualizing-git)
+* [Learn Git Branching](https://learngitbranching.js.org/?NODEMO)
 
 ### Go