add nim books
EbookFoundation/free-programming-books pull request #4078
Opened 2020-10-14 10:44 UTC by me7

## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s)

## For resources
More book on Nim language

### Description 
This PR add more resource of Nim book, both online and PDF

### Why is this valuable (or not)?
New book have sample application created with Nim language, the old one is not

### How do we know it's really free?
Specify in resource

### For book lists, is it a book? For course lists, is it a course? etc.
Yes, it's book

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

2020-10-14 14:34 UTC, eshellman requested changes
Titles should be taken from the book itself - otherwise we can't identify duplicates.

2020-10-14 14:34 UTC, eshellman commented on free-programming-books.md
> +* [Nim Basic (for beginner, PDF available)](https://narimiran.github.io/nim-basics/) - narimiran
please don't invent titles

2020-10-14 14:34 UTC, eshellman commented on free-programming-books.md
> +* [Nim by Example](https://nim-by-example.github.io/) - Flaviu Tamas
interesting that the linter doesn't flag the trailing slash here.

2020-10-14 14:34 UTC, eshellman commented on free-programming-books.md
> +* [Nim Days - Book teach to create several Nim app](https://xmonader.github.io/nimdays/) - Ahmed Thabet
again, don't invent titles

2020-10-15 03:30 UTC, me7 commented
Thanks for review, I've change per your comment

2020-11-06 18:07 UTC, eshellman commented
seems this failed because another merge broke the build.

2020-11-06 18:17 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2020-11-06 18:17 UTC, merged