Added an android book and a Python playground
EbookFoundation/free-programming-books pull request #4156
Opened 2020-10-15 17:06 UTC by Bhaskar-maity

## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s) | Remove Resource(s) | Add info | Improve Repo

## For resources
### Description 
Added an android book and a Python playground.
### Why is this valuable (or not)?
These websites are genuinely free.
### How do we know it's really free?
It shows ads and popular websites.
### For book lists, is it a book? For course lists, is it a course? etc.
1. android Book: javatpoint
2. python playground: Repl.it
### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

2020-10-15 18:45 UTC, eshellman requested changes

2020-10-15 18:45 UTC, eshellman commented on free-programming-playgrounds.md
> +* [Repl.it playground](https://repl.it/repls/NiceDualPoint#main.py)
don't invent titles. This one titles itself "repl.it - NiceDualPoint"

2020-10-15 18:45 UTC, eshellman commented on free-programming-books.md
> +* [Javatpoint Android Tutorial](https://www.javatpoint.com/android-tutorial)
belongs in tutorials

2020-10-15 19:44 UTC, Bhaskar-maity commented
I resolved it

2020-10-16 01:42 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2020-10-16 01:42 UTC, merged