Added Laravel, React Tutorial
EbookFoundation/free-programming-books pull request #4308
Opened 2020-10-17 11:08 UTC by endrose

## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s) | Remove Resource(s) | Add info | Improve Repo

## For resources
### Description 

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

### Checklist:
- [ ] Not a duplicate
- [ ] Included author(s) if appropriate
- [ ] Lists are in alphabetical order
- [ ] Needed indications added (PDF, access notes, under construction)

2020-10-17 14:00 UTC, endrose commented
fixing

2020-10-17 14:00 UTC, endrose commented
fixing

2020-10-22 21:27 UTC, SethiPandi requested changes
Please also ensure you have all lists and categories in alphabetical order, and then you always have _exactly_ two line breaks above a new section.

You also need to resolve merge conflicts!

You can get more guidance on the formatting and conventions of this repository by checking out the [contribution guide](https://www.github.com/EbookFoundation/free-programming-books/tree/master/CONTRIBUTING.md).

You can also click on the failed checks to get more information on any check failures. You'll be able to see exactly what was wrong and how to fix it!

2020-10-22 21:27 UTC, SethiPandi commented on free-courses-en.md
> +* [Introduction to Scripting in Python Specialization](https://www.coursera.org/specializations/introduction-scripting-in-python) (coursera)
Please write the name of the Coursera with the correct capitalization.

```suggestion
* [Introduction to Scripting in Python Specialization](https://www.coursera.org/specializations/introduction-scripting-in-python) (Coursera)
```

2020-10-22 21:27 UTC, SethiPandi commented on free-courses-id.md
> +* [Tutorial React js Indonesia](https://www.youtube.com/watch?v=mDNj800bjWQ&list=PLx4zY98IACXiMJTmFk_hyBOg6P1lEWHso&ab_channel=TahuCoding) - Tahu Coding
* Please use a link from the playlist endpoint, not the watch endpoint.
* Please name the resource after the source.
* There is no need to specify the language, after all this entire file is for that language.

```suggestion
* [React.js Fundamental](https://www.youtube.com/playlist?list=PLx4zY98IACXiMJTmFk_hyBOg6P1lEWHso) - Tahu Coding
```

2020-11-21 20:29 UTC, closed without merging