Create free-courses-th.md
EbookFoundation/free-programming-books pull request #4367
Opened 2020-10-18 11:21 UTC by siriwatw

## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s) 

## For resources
### This is Thai programming course list.

### Course in this list help improve programming skill.

### You can start to learn without credit cards or other payment method

### This is course list.

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

2020-10-18 21:38 UTC, SethiPandi commented
You only need 1 line break under the first line, and you only need 2 line breaks above each new section or subsection.

Could you please update your PR so the line breaks /spacing is standardised?

You can check out the contribution guidelines (CONTRIBUTE.md) for more information on formatting and other guidelines for this repository. You can click on the failed check below and head to Travis CI to see exactly what was wrong with your PR and how to fix it!

2020-10-20 13:37 UTC, SethiPandi requested changes
~~I've dropped a few comments which is more clear on which lines should be removed!~~

Apparently, I reviewed the first version. :thinking: 
I'll do that again, sorry.

2020-10-20 13:37 UTC, SethiPandi commented on free-courses-th.md
> +
Remove one line break from here, please. There should only be 2!

2020-10-20 13:37 UTC, SethiPandi commented on free-courses-th.md
> +
Remove one line break from here, please. There should only be 2!

2020-10-20 13:37 UTC, SethiPandi commented on free-courses-th.md
> +
Remove one line break from here, please. There should only be 2!

2020-10-20 13:37 UTC, SethiPandi commented on free-courses-th.md
> +
Remove one line break from here, please. There should only be 2!

2020-10-20 13:37 UTC, SethiPandi commented on free-courses-th.md
> +
Remove one line break from here, please. There should only be 2!

2020-10-20 13:37 UTC, SethiPandi commented on free-courses-th.md
> +
Remove one line break from here, please. There should only be **1**!

2020-10-20 13:44 UTC, SethiPandi requested changes
I've left some comments on the correct place this time, not sure how I did the other one before.

Could you please also ensure all lists are in alphabetical order!

2020-10-20 13:44 UTC, SethiPandi commented on free-courses-th.md
> +* [สอน Node.js เบื้องต้น](https://www.youtube.com/playlist?list=PLoTScYm9O0GERtEdsPHK5Q-cdor5ADnyM)  (pracertcbs)
Please add a line break between line 49 and 50.

2020-10-20 13:44 UTC, SethiPandi commented on free-courses-th.md
> +* [สอน React.JS Tutorial](https://www.youtube.com/playlist?list=PLjPfp4Ph3gBo5SmWJXwv4oKDfeTXA7xgw)  (CMDev)
Please add a line break between line 54 and 55.

2020-10-20 13:44 UTC, SethiPandi commented on free-courses-th.md
> +* [สอนเขียน VueJS](https://www.youtube.com/playlist?list=PLjPfp4Ph3gBry3sJDNrbqor5ikjwGDJ_7)  (CMDev)
Please add a line break between line 58 and 59.

2020-10-20 13:44 UTC, SethiPandi commented on free-courses-th.md
> +* [บทเรียนภาษา Javascript](http://marcuscode.com/lang/javascript) (MarcusCode)
On the website the resource is called: `ภาษา JavaScript` on the website.
Could we please use the name as described there?

2020-10-20 14:07 UTC, SethiPandi commented on free-courses-th.md
> +* [บทเรียนภาษา Javascript](http://marcuscode.com/lang/javascript) (MarcusCode)
Could you please write `JavaScript` with a capital S, the same way that it is on the website?
Java**S**cript is the correct spelling for it anyway.

2020-10-21 00:44 UTC, eshellman commented
Wow, nice effort!
Thanks, and welcome to free-programming-books!

2020-10-21 00:44 UTC, merged

2020-10-21 00:47 UTC, eshellman commented
Now you need to add a link from README.md (I should have flagged that before merging.)