Update free-courses-hi.md
EbookFoundation/free-programming-books pull request #4409
Opened 2020-10-19 05:31 UTC by Anandpskerala

## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s) | Remove Resource(s) | Add info | Improve Repo

## For resources
### Description 

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

### Checklist:
- [ ] Not a duplicate
- [ ] Included author(s) if appropriate
- [ ] Lists are in alphabetical order
- [ ] Needed indications added (PDF, access notes, under construction)

2020-10-19 08:04 UTC, SethiPandi requested changes
You can read the contribution guidelines (CONTRIBUTING.md) for more information on formatting for the repository. Or click the failed check below and go to Travis CI to see exactly what was wrong with your PR and how to resolve the issue in future.

2020-10-19 08:04 UTC, SethiPandi commented on free-courses-hi.md
> +## Index
There should be 3 # symbols here.

2020-10-19 08:04 UTC, SethiPandi commented on free-courses-hi.md
> -
Add this line break back.

2020-10-19 08:04 UTC, SethiPandi commented on free-courses-hi.md
Add a line break here, there should be two.

2020-10-19 08:06 UTC, SethiPandi requested changes
Noticed after the first review, sorry! Also isn't in alphabetical order.

2020-10-19 08:06 UTC, SethiPandi commented on free-courses-hi.md
> +* [Python Basic in Hindi](https://masterprograming.com/python/)
This isn't in alphabetical order, B is before T.

2020-10-21 14:36 UTC, eshellman commented
please resolve conflicts.

2020-10-21 14:41 UTC, closed without merging