Update FORTRAN free-programming-books.md
EbookFoundation/free-programming-books pull request #4437
Opened 2020-10-19 14:05 UTC by tanaynayak

## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s) | Remove Resource(s) | Add info | Improve Repo

## For resources
### Description 

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

### Checklist:
- [ ] Not a duplicate
- [ ] Included author(s) if appropriate
- [ ] Lists are in alphabetical order
- [ ] Needed indications added (PDF, access notes, under construction)

2020-10-19 14:11 UTC, alvaroartano commented
Pleas

> ## Hacktoberfest notes:
> * due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
> * please read our [contributing guidelines](/CONTRIBUTING.md)
> * be sure to check the output of Travis-CI for linter errors
> * if this is your first open source contribution, make sure it's not your last!
> 
> ## What does this PR do?
> Add Resource(s) | Remove Resource(s) | Add info | Improve Repo
> 
> ## For resources
> ### Description
> ### Why is this valuable (or not)?
> ### How do we know it's really free?
> ### For book lists, is it a book? For course lists, is it a course? etc.
> ### Checklist:
> * [ ]  Not a duplicate
> * [ ]  Included author(s) if appropriate
> * [ ]  Lists are in alphabetical order
> * [ ]  Needed indications added (PDF, access notes, under construction)

Please you must complete the template

2020-10-19 17:19 UTC, ecrax commented on free-programming-books.md
> +* [Object-oriented programming via Fortran 90-95](http://87.120.36.5/main/1000/2d996a202fdd840e79a791a4eb854432/Ed%20Akin%20-%20Object-oriented%20programming%20via%20Fortran%2090-95-Cambridge%20Unive
Switch those two lines :D

2020-10-19 18:52 UTC, alvaroartano approved these changes

2020-10-19 18:53 UTC, alvaroartano requested changes
Change the lines pointing to a IP

2020-10-21 14:36 UTC, eshellman commented
In general, we do not link to file sharing sites.

2020-10-21 14:36 UTC, closed without merging