Added Django for Everybody and Restructuring of Python topic
EbookFoundation/free-programming-books pull request #4473
Opened 2020-10-19 18:32 UTC by BasilVictor

## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s) , Improve Repo

## For resources
### Description 
Add Resource(s) - Added Django for Everybody (by Charles R. Severance) open source materials of the Coursera course
Improve Repo - Restructured Python category and added Django and Flask as sub topics

### Why is this valuable (or not)?
It is a great place for Django beginners

### How do we know it's really free?
It is a `Copyright Creative Commons Attribution 3.0` website.

### For book lists, is it a book? For course lists, is it a course? etc.
It is a course

![image](https://user-images.githubusercontent.com/26377114/96496808-5744f300-1267-11eb-85eb-24b8de92eb6f.png)

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

2020-10-19 21:18 UTC, SethiPandi requested changes
I left some comments for you that should hopefully help address the formatting issues.

You can check out the contribution guide (CONTRIBUTING.md) for more information on formatting and other guidelines for this repository. You can click on the failed check below and head to Travis CI to see exactly what was wrong with your PR and how to fix it!

Edit: I originally left two comments, but deleted one as it was a non-issue as I simply miss read your change. Sorry about that!

2020-10-19 21:18 UTC, SethiPandi commented on free-courses-en.md
> +#### Flask
There should be a line break under here.

2020-10-19 21:18 UTC, SethiPandi commented on free-courses-en.md
> +* [Django for Everybody](https://dj4e.sites.uofmhosting.net/lessons) (Coursera Reading Materials with YouTube Videos)
Please keep lists in alphabetical order.
D is before F.

2020-10-21 02:40 UTC, BasilVictor commented
@SethiPandi  resolved

2020-10-21 13:44 UTC, eshellman commented
Thanks! Opinions on #4573 welcome.

2020-10-21 13:44 UTC, merged

2024-10-08 13:15 UTC, PawaN-kingS approved these changes