Added vue.js course pt_BR
EbookFoundation/free-programming-books pull request #4488
Opened 2020-10-20 02:08 UTC by VictorSega

## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s) | Remove Resource(s) | Add info | Improve Repo

## For resources
### Description 
Basic Vue.js course for beginners.

### Why is this valuable (or not)?
It's simple and good for beginners.

### How do we know it's really free?
Need only to enter on site and watch course.

### For book lists, is it a book? For course lists, is it a course? etc.

### Checklist:
- [X] Not a duplicate
- [X] Included author(s) if appropriate
- [X] Lists are in alphabetical order
- [ ] Needed indications added (PDF, access notes, under construction)

2020-10-20 22:43 UTC, SethiPandi requested changes
I've left you some comments!

You can get more guidance on the formatting and conventions in this repository by checking out the contribution guide (CONTRIBUTING.md).

You can also click on the failed checks below to get more information on any check failures. You'll be able to see exactly what was wrong and how to fix it!

2020-10-20 22:43 UTC, SethiPandi commented on free-courses-pt_BR.md
> +* [Vue.js](#vue.js)
Can you remove the dot from the URL. ie `#vuejs`.

Also please slot Vue.js in alphabetical order in the table of contents.

2020-10-20 22:43 UTC, SethiPandi commented on free-courses-pt_BR.md
> +### Vue.js
Could you please slot this category in alphabetical order in line with the rest of this document.

2020-10-21 03:04 UTC, VictorSega commented
Thanks!

I Fixed this things :)

2020-10-21 14:30 UTC, merged