Update free-programming-cheatsheets.md
EbookFoundation/free-programming-books pull request #4640
Opened 2020-10-22 23:00 UTC by Akshama

Added a Cheat Sheet for Kubernetes Beginners

## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s) | Remove Resource(s) | Add info | Improve Repo

## For resources
### Description 

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

### Checklist:
- [ ] Not a duplicate
- [ ] Included author(s) if appropriate
- [ ] Lists are in alphabetical order
- [ ] Needed indications added (PDF, access notes, under construction)

2020-10-23 01:52 UTC, kadhirash requested changes

2020-10-23 01:52 UTC, kadhirash commented on free-programming-cheatsheets.md
>  ### Clojure
Hello, your build is failing due to some small errors.

Check out the [CONTRIBUTING](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md) file to see that you need 2 blank lines between last resource and the next section.
```suggestion
* [Kubernetes](#Kubernetes)


### Clojure
```

2020-10-23 01:52 UTC, kadhirash commented on free-programming-cheatsheets.md
> +* [Kubernetes](#Kubernetes)
This Kubernetes in the Index section needs to be alphabetical, so it should be after JavaScript but before Markdown at the time of this review. After doing so in the Index section, it should also be reflected below.

2020-11-05 01:02 UTC, SethiPandi commented
Closing as this resource is already in the repository.

2020-11-05 01:02 UTC, closed without merging