added a book for graphics programming
EbookFoundation/free-programming-books pull request #4662
Opened 2020-10-23 18:30 UTC by ltwmori

## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s) | Remove Resource(s) | Add info | Improve Repo

## For resources
### Description 

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

### Checklist:
- [ ] Not a duplicate
- [ ] Included author(s) if appropriate
- [ ] Lists are in alphabetical order
- [ ] Needed indications added (PDF, access notes, under construction)

2020-10-23 18:39 UTC, SethiPandi requested changes
Just left a few comments for you!

You can get more guidance on the formatting and conventions in this repository by checking out the [contribution guide](https://www.github.com/EbookFoundation/free-programming-books/tree/master/CONTRIBUTING.md).

2020-10-23 18:39 UTC, SethiPandi commented on free-programming-books.md
> +* [Blender 3D: Noob to Pro](https://en.wikibooks.org/wiki/Blender_3D%3A_Noob_to_Pro) (Wikibooks)
Could you revert this, I believe Wikibooks was meant to be separated with a hyphen.
Please see other resources from Wikibooks on this page for examples.

```suggestion
* [Blender 3D: Noob to Pro](https://en.wikibooks.org/wiki/Blender_3D%3A_Noob_to_Pro) - Wikibooks
```

2020-10-23 18:39 UTC, SethiPandi commented on free-programming-books.md
> +* [Blender Manual](https://docs.blender.org/manual/en/latest) (Wikibooks)
This isn't on Wikibooks.

```suggestion
* [Blender Manual](https://docs.blender.org/manual/en/latest)
```

2020-10-24 18:38 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2020-10-24 18:38 UTC, merged