Adding section and a book for Blazor Framework
EbookFoundation/free-programming-books pull request #4721
Opened 2020-10-25 20:34 UTC by madhavsarpal

## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource

## For resources
### Description 
Adding a section and a book for Blazor Framework

### Why is this valuable (or not)?
Blazor is a new client side framework by Microsoft meant to replace older technologies like ASP.NET web forms. This book provides an introduction to Blazor Framework

### How do we know it's really free?
It is available for free download on Microsoft's website and can be downloaded without signing-up for anything

### For book lists, is it a book? For course lists, is it a course? etc.
It is a Book

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

2020-10-25 21:03 UTC, SethiPandi requested changes
Just a small comment!

You can get more guidance on the formatting and conventions of this repository by checking out the [contribution guide](https://www.github.com/EbookFoundation/free-programming-books/tree/master/CONTRIBUTING.md).

2020-10-25 21:03 UTC, SethiPandi commented on free-programming-books.md
> +* [Blazor for ASP.NET Web Forms Developers](https://dotnet.microsoft.com/download/e-book/blazor-for-web-forms-devs/pdf) - Daniel Roth, Jeff Fritz, Taylor Southwick
As this leads to a PDF download, could you please append (PDF) to the end of the line?

```suggestion
* [Blazor for ASP.NET Web Forms Developers](https://dotnet.microsoft.com/download/e-book/blazor-for-web-forms-devs/pdf) - Daniel Roth, Jeff Fritz, Taylor Southwick (PDF)
```

2020-10-25 23:39 UTC, eshellman commented
would more people find this if it was in the asp.net section?

2020-10-26 05:36 UTC, madhavsarpal commented
> would more people find this if it was in the asp.net section?

But Blazor is a separate technology of it own, and although the book draws paralellism between ASP.NET web forms and Blazor, it talks about Blazor separately too and the focus is on Blazor and not ASP.NET. Infact, we can use Blazor without ASP.NET with any other backend technology so I though it would be more appropriate to have a new section for that.

2020-10-26 16:19 UTC, merged