Add Single page apps in depth by Mixu
EbookFoundation/free-programming-books pull request #4874
Opened 2020-10-29 11:03 UTC by uuykay

## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s) | Remove Resource(s) | Add info | Improve Repo

## For resources
Javascript

### Description 
Add Single page apps in depth by Mixu

### Why is this valuable (or not)?
Explains SPA architecture.

### How do we know it's really free?
Mentioned by author and is on github.

### For book lists, is it a book? For course lists, is it a course? etc.

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

2020-10-29 11:50 UTC, SethiPandi commented
Hey, and welcome to free programming books! :wave:

It looks like you've let your code editor auto-format the document and break most of the repositories conventions. It's always worth giving the changes files a peek before submitting the PR! Could you please fix the formatting?

2020-10-29 12:58 UTC, uuykay commented
> Hey, and welcome to free programming books! 👋
> 
> It looks like you've let your code editor auto-format the document and break most of the repositories conventions. It's always worth giving the changes files a peek before submitting the PR! Could you please fix the formatting?

Sorry! I tried disabling Prettier in the workspace, but ended up having to just open it in Notepad to edit the original file.

2020-10-29 13:08 UTC, SethiPandi requested changes
You can get more guidance on the formatting and conventions in this repository by checking out the [contribution guide](https://www.github.com/EbookFoundation/free-programming-books/tree/master/CONTRIBUTING.md).

You can also click on the failed checks to get more information on any check failures. You'll be able to see exactly what was wrong and how to fix it!

2020-10-29 13:08 UTC, SethiPandi commented on free-programming-books.md
> +* [Single page apps in depth](http://singlepageappbook.com/) - Mixu (HTML)
For root URLs we prefer not to have a trailing slash, could you remove it, please?

```suggestion
* [Single page apps in depth](http://singlepageappbook.com) - Mixu (HTML)
```

2020-11-14 00:52 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2020-11-14 00:52 UTC, merged