added 4 free books
EbookFoundation/free-programming-books pull request #4889
Opened 2020-10-29 22:18 UTC by kri99

## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s) | Remove Resource(s) | Add info | Improve Repo

## For resources
### Description 

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

### Checklist:
- [ ] Not a duplicate
- [ ] Included author(s) if appropriate
- [ ] Lists are in alphabetical order
- [ ] Needed indications added (PDF, access notes, under construction)

2020-10-29 23:22 UTC, SethiPandi requested changes
Just left a few comments for you!

In general, we prefer HTTPS links if that's available for the webpage. Could the links that are HTTPS accessible please be updated?

2020-10-29 23:22 UTC, SethiPandi commented on free-programming-books-pl.md
> +* [O Androidzie ludzkim głosem](http://andrzejklusiewicz-android.blogspot.com/p/bezpatny-kurs-programowania-android-java.html) - Andrzej Klusiewicz
It looks like this source is accessible via HTTPS, could we please use the https:// link instead?

```suggestion
* [O Androidzie ludzkim głosem](https://andrzejklusiewicz-android.blogspot.com/p/bezpatny-kurs-programowania-android-java.html) - Andrzej Klusiewicz
```

2020-10-29 23:22 UTC, SethiPandi commented on free-programming-books-pl.md
> +* [Kurs CSS](http://webref.pl/arena/css/css_index.html) - Arkadiusz Michalski
```suggestion
* [Kurs CSS](https://webref.pl/arena/css/css_index.html) - Arkadiusz Michalski
```

2020-10-29 23:22 UTC, SethiPandi commented on free-programming-books-pl.md
> +* [Samouczek Perl](http://www.w3big.com/pl/perl/default.html)
```suggestion
* [Samouczek Perl](https://www.w3big.com/pl/perl/default.html)
```

2020-10-31 20:07 UTC, eshellman commented
3 of these are labeled as courses. Maybe they should go on the courses-pl page?

2021-08-31 18:57 UTC, davorpa approved these changes
Review of stale PR with conflicts moved to #5513

Conflicts due to repo reorganization made on Dec 2020 (#5199).

2021-09-05 01:48 UTC, closed without merging