Add Architecture Patterns with Python book
EbookFoundation/free-programming-books pull request #5220
Opened 2020-12-14 22:36 UTC by threenary

## What does this PR do?
Add resource

## For resources
### Description 

Adds a book on Python

### Why is this valuable (or not)?

This resource is valuable since it introduces topics related to modern architecture patterns that many times might be overseen or left aside when trying to dive into Python.

### How do we know it's really free?

It is published by the authors on a HTML site

### For book lists, is it a book? For course lists, is it a course? etc.

This is a book.

## Checklist:
- [ ] Read our [contributing guidelines](/CONTRIBUTING.md)
- [ ] Search for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction)

## Followup

- Check the output of Travis-CI for linter errors!

2020-12-14 22:48 UTC, Christianpixel-gif requested changes
27d62d99050465c84c860e02d98f1a8bb8afe2ce

2020-12-14 22:51 UTC, Christianpixel-gif approved these changes

2020-12-14 22:51 UTC, Christianpixel-gif commented on books/free-programming-books.md
> +* [Architecture Patterns with Python](https://www.cosmicpython.com/book/preface.html) - Harry J.W. Percival & Bob Gregory (HTML)
I

2020-12-15 15:50 UTC, eshellman commented
if our linter was working, it would complain that "architecture" should come after "A whirlwind". So to aviod breaking the build when the linter is fixed, please re-alphabetize the list.

2021-01-08 15:40 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2021-01-08 15:40 UTC, merged