Added more Python resources, updated links/info
EbookFoundation/free-programming-books pull request #5366
Opened 2021-05-06 12:04 UTC by learnbyexample

## What does this PR do?
Add resource(s) | Improve repo

## For resources
### Description

* Added more Python resources.
* Changed http to https, added/updated author/book info for some of the resources that I'm familiar with.

### Why is this valuable (or not)?

I've glanced through these resources and found them to be useful.

### How do we know it's really free?

I've checked the links before adding them.

### For book lists, is it a book? For course lists, is it a course? etc.

Newly added links are all books.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists  in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction)

## Followup

- Check the output of Travis-CI for linter errors!

2021-05-06 15:42 UTC, eshellman requested changes
These are outstanding additions! The two courses just need to be moved to the courses list.

2021-05-06 15:42 UTC, eshellman commented on books/free-programming-books.md
> +* [Practical Python Programming](https://dabeaz-course.github.io/practical-python/) - David Beazley (3.6)
The author describes this as a course, so we should list it a a course.

2021-05-06 15:42 UTC, eshellman commented on books/free-programming-books.md
> +* [Python Pandas For Your Grandpa](https://www.gormanalysis.com/blog/python-pandas-for-your-grandpa/) - Ben Gorman
Also a course.

2021-05-07 04:26 UTC, learnbyexample commented
Sorry about that! I've removed those two resources, will make a separate courses PR later.

2021-05-07 13:34 UTC, merged