Update free-programming-interactive-tutorials-en.md
EbookFoundation/free-programming-books pull request #5373
Opened 2021-05-08 11:22 UTC by tutlane

Added good resources to learn c#, python, bootstrap, node.js, etc. Please check it, if it is good, keep it in the list.

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [ ] Search for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists  in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction)

## Followup

- Check the output of Travis-CI for linter errors!

2021-05-08 11:44 UTC, SethFalco commented
Hey, and welcome to the repository! :wave:

I checked Tutlane out, but these look more like books rather than interactive tutorials?
Maybe we should move them over to a books list instead? 

Also, could we use the names as given by the resource, there's no need to attribute to Tutlane at the end of each resource's title.

Could you please ensure all lists, categories, and sections or subsections remain in alphabetical order?

2021-05-08 15:04 UTC, tutlane commented
Modified the details. Please check it and merge the details

2021-05-08 18:33 UTC, eshellman commented
I agree with Seth that that these would fit our books category, but we usually defer to whatever the resource describes itself as, so keep this on the interactive tutorials page.
Thanks for changing the title; we place the creator name _after_ the link - check out the other similarly named resources. To distinguish the tutlane resources from identically named items, use 'tutlane' as the creator. Also, note that the title change has caused our linter to change its opinion on how to alphabetize the links, so be sure to check the travis output.

2021-08-24 23:52 UTC, davorpa requested changes
I just propose inline changes to:

- Disambiguate resources adding creator @tutlane
- Fix Travis linting (https://app.travis-ci.com/github/EbookFoundation/free-programming-books/builds/225315532#L225)

as @eshellman suggest

Please merge and check again

2021-08-24 23:52 UTC, davorpa commented on more/free-programming-interactive-tutorials-en.md
> +* [Android Tutorial](https://www.tutlane.com/tutorial/android)
Add creator to disambiguate resources

```suggestion
* [Android Tutorial](https://www.tutlane.com/tutorial/android) - tutlane
```

2021-08-24 23:52 UTC, davorpa commented on more/free-programming-interactive-tutorials-en.md
> +* [C# Tutorial](https://www.tutlane.com/tutorial/csharp)
Add creator to disambiguate resources

```suggestion
* [C# Tutorial](https://www.tutlane.com/tutorial/csharp) - tutlane
* [C# Tutorial](https://www.w3schools.com/cs) - W3Schools
```

2021-08-24 23:52 UTC, davorpa commented on more/free-programming-interactive-tutorials-en.md
> +* [Bootstrap Tutorial](https://www.tutlane.com/tutorial/bootstrap)
Add creator to disambiguate resources

```suggestion
* [Bootstrap Tutorial](https://www.tutlane.com/tutorial/bootstrap) - tutlane
```

2021-08-24 23:52 UTC, davorpa commented on more/free-programming-interactive-tutorials-en.md
> +* [AngularJS Tutorial](https://www.tutlane.com/tutorial/angularjs)
Add creator to disambiguate resources

```suggestion
* [AngularJS Tutorial](https://www.tutlane.com/tutorial/angularjs) - tutlane
```

2021-08-24 23:52 UTC, davorpa commented on more/free-programming-interactive-tutorials-en.md
> +* [Node.js Tutorial](https://www.tutlane.com/tutorial/nodejs)
Add creator to disambiguate resources

```suggestion
* [Node.js Tutorial](https://www.tutlane.com/tutorial/nodejs) - tutlane
* [Node.js Tutorial](https://www.w3schools.com/nodejs) - W3Schools
```

2021-08-24 23:52 UTC, davorpa commented on more/free-programming-interactive-tutorials-en.md
> +* [Python Tutorial](https://www.tutlane.com/tutorial/python)
Add creator to disambiguate resources

```suggestion
* [Python Tutorial](https://www.tutlane.com/tutorial/python) - tutlane
* [Python Tutorial](https://www.w3schools.com/python) - W3Schools
```

2021-08-24 23:52 UTC, davorpa commented on more/free-programming-interactive-tutorials-en.md
> +* [SQL Server Tutorial](https://www.tutlane.com/tutorial/sql-server)
- Add creator to disambiguate resources
- Fix Travis linting (https://app.travis-ci.com/github/EbookFoundation/free-programming-books/builds/225315532#L225)

```suggestion
* [SQL at Codecademy](https://www.codecademy.com/courses/learn-sql)
* [SQL Server Tutorial](https://www.tutlane.com/tutorial/sql-server) - tutlane
* [SQL Tutorial](https://www.w3schools.com/sql) - W3Schools
* [SQLBolt](http://sqlbolt.com)
```

2021-08-25 13:01 UTC, eshellman commented
Be sure to check the output of Travis-CI for linter errors. Alphabetical order and spacing are the most common problems.

2021-08-25 13:19 UTC, eshellman commented
Thanks @tutlane , and welcome to free-programming-books!

2021-08-25 13:19 UTC, merged