fix: broken link
EbookFoundation/free-programming-books pull request #5402
Opened 2021-05-29 11:36 UTC by rkapoor10

Issue No. #5378
## Description: Fixed the broken pdf link of C++ Cheat Sheet.

### New Link :  https://www.cs.ccu.edu.tw/~damon/oop/,c++refcard.pdf

## What does this PR do?
 Adds info | Improve repo

2021-05-29 18:58 UTC, eshellman commented
unauthorized pdfs hosted on personal homepages are likely to go bad, just as the previous one went bad. I'd just remove the link.

2021-08-25 01:22 UTC, davorpa requested changes
Change from HTTPS to HTTP

Resolves EbookFoundation/free-programming-books#5378

2021-08-25 01:27 UTC, davorpa requested changes

2021-08-25 01:27 UTC, davorpa commented on more/free-programming-cheatsheets.md
> +* [C++ Quick Reference](https://www.cs.ccu.edu.tw/~damon/oop/,c++refcard.pdf) (PDF)
- Change initial url from `https` to `http`
- Give credits to authors

```suggestion
* [C++ Quick Reference](http://www.hoomanb.com/cs/quickref/CppQuickRef.pdf) - Hooman Baradaran (PDF)
```

2021-08-25 13:05 UTC, eshellman commented
please resolve conflicts.

2021-09-05 18:32 UTC, merged