Add another Nim book to this list.
EbookFoundation/free-programming-books pull request #5482
Opened 2021-08-14 05:19 UTC by pyautogui

Add the Computer Programming with the Nim Programming Language book to this list.

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [ ] Search for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction)

## Followup

- Check the output of Travis-CI for linter errors!

2021-08-14 22:45 UTC, davorpa requested changes
Hi @pyautogui 

Acording to guidelines, ensure that links guard alphabetical order. I suggest you the inline changes 😉

2021-08-14 22:45 UTC, davorpa commented on books/free-programming-books.md
> +* [Computer Programming with the Nim Programming Language](http://ssalewski.de/nimprogramming.html) - Dr. Stefan Salewski
```suggestion

```

Revert to ensure alphabetical sort

2021-08-14 22:45 UTC, davorpa commented on books/free-programming-books.md
>  * [Nim Basics](https://narimiran.github.io/nim-basics) - narimiran
```suggestion
* [Computer Programming with the Nim Programming Language](http://ssalewski.de/nimprogramming.html) - Dr. Stefan Salewski
* [Nim Basics](https://narimiran.github.io/nim-basics) - narimiran
```

Ensure alphabetical order

2021-08-14 23:42 UTC, eshellman commented
super addition, but you're adding it twice.
Be sure to check the output of Travis-CI for linter errors. Alphabetical order and spacing are the most common problems.

2021-08-15 02:01 UTC, davorpa requested changes
Pay attention at suggested changes to revert line 2213 and then resolve CI/CD errors

2021-08-15 16:42 UTC, davorpa approved these changes
Supe :rocket:

2021-08-16 17:21 UTC, merged

2021-08-16 17:21 UTC, eshellman commented
Thanks, and welcome to free-programming-books!