Added new Javascript Fundamentals Course
EbookFoundation/free-programming-books pull request #5519
Opened 2021-09-02 18:44 UTC by jayeshchoudhary

## What does this PR do?
Add new Javascript Fundamentals Course in English section

## For resources

### Description
Namaste JavaScript is a pure in-depth JavaScript Course released for Free on Youtube. It will cover the core concepts of JavaScript in detail and everything about how JS works behind the scenes inside the JavaScript engine.

### Why is this valuable (or not)?
This course covers the core fundamentals of JavaScript which will help anyone to clear their basics first before jumping into any JS library

### How do we know it's really free?
It is available on YouTube Playlist

### For book lists, is it a book? For course lists, is it a course? etc.
It is a course 

## Checklist:
- [X] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [X] Search for duplicates.
- [X] Include author(s) and platform where appropriate.
- [X] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction)

## Followup

- Check the output of Travis-CI for linter errors!

2021-09-02 22:42 UTC, davorpa requested changes

2021-09-02 22:42 UTC, davorpa commented on courses/free-courses-en.md
> +* [Namaste 🙏 JavaScript | In-Depth JavaScript Fundamentals Course](https://www.youtube.com/playlist?list=PLlasXeu85E9cQ32gLCvAvr9vNaUccPVNP) - Akshay Saini (YouTube)
Nice playlist.

It name is `Namaste Javascript`.

If an excerpt is needed, is better use `:`. Vertical bars make some bugs inside links

```suggestion
* [Namaste 🙏 JavaScript: An In-Depth JavaScript Fundamentals Course](https://www.youtube.com/playlist?list=PLlasXeu85E9cQ32gLCvAvr9vNaUccPVNP) - Akshay Saini (YouTube)
```

2021-09-03 14:46 UTC, davorpa approved these changes
Supe :rocket:. Go ahead :hugs:

2021-09-03 15:21 UTC, jayeshchoudhary commented
@davorpa who will merge this PR ?

2021-09-03 17:06 UTC, davorpa commented
> @davorpa, @ericallam who will merge this PR ?

At this moment I don't have write access rights. I only review, pull, issue a bit

2021-09-05 02:04 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2021-09-05 02:04 UTC, merged