Update free-courses-en.md
EbookFoundation/free-programming-books pull request #5539
Opened 2021-09-15 01:18 UTC by webcleric

Just thought that this freeCodeCamp.org could fit in the list :)

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

Adding resources

## For resources
### Description

### Why is this valuable (or not)?

It's comprehensive and free

### How do we know it's really free?

Uploaded to Youtube

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [ ] Search for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction)

## Followup

- Check the output of Travis-CI for linter errors!

2021-09-15 03:38 UTC, davorpa requested changes
From video description...

> This is a complete 134-part JavaScript tutorial for beginners will teach you everything you need to know to get started with the JavaScript programming language.
> 
> ⭐️Curriculum⭐️
> This is a stand-alone video but it follows the JavaScript curriculum at freecodecamp.org. Access the curriculum here:
> 🔗 Basic JavaScript: https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/
> 🔗 ES6 JavaScript: https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/es6/
> 
> ⭐️Code⭐️
> This course was created using scrimba.com. Access the course there along with the code:
> 🔗 Basic JavaScript: https://scrimba.com/playlist/pny4ghw
> 🔗 ES6 JavaScript: https://scrimba.com/playlist/p7v3gCd

We prefer playlist Youtube videos, although this seems be a single video with timeline chapters covering freecodecamp's JS curriculum path

Also remember [check linter errors](https://github.com/EbookFoundation/free-programming-books/pull/5539/checks?check_run_id=3605241630#step:7:1).
```log
Run fpb-lint ./courses/
/home/runner/work/free-programming-books/free-programming-books/courses/free-courses-en.md
  382:1-396:113  warning  Alphabetical ordering: swap l.396 and l.395  alphabetize-lists  remark-lint
```
So reorder items to complain list alphabetization

2021-09-15 03:38 UTC, davorpa commented on courses/free-courses-en.md
> +* [Learn JavaScript - Full Course for Beginners](https://www.youtube.com/watch?v=PkZNo7MFNFg) - freeCodeCamp.org
Completes main creator.

```suggestion
* [Learn JavaScript - Full Course for Beginners](https://www.youtube.com/watch?v=PkZNo7MFNFg) -  Beau Carnes, freeCodeCamp.org
```

2021-09-15 14:44 UTC, eshellman commented
Be sure to check the output of Travis-CI for linter errors. Alphabetical order and spacing are the most common problems.

2021-09-28 16:48 UTC, LuigiImVector commented on courses/free-courses-en.md
>  * [learn:query](https://learnquery.infinum.co)
a

2021-09-28 18:55 UTC, davorpa commented
@eshellman remember close/reject this. it's fixed by #5566

2021-09-28 18:59 UTC, closed without merging