Added AutoIt, language updates and support
EbookFoundation/free-programming-books pull request #5554
Opened 2021-09-25 22:24 UTC by Existential-nonce

## What does this PR do?
Add resources, Improve repo

## For resources
### Description
- This PR is basically just 2 things at once. I added language support for french and contributed some miscellaneous stuff on the available languages which had outdated hyperlinks to other translation files of the same `.md` file.
- added french translation of CONTRIBUTING.md
> (I admit I kinda abused google translate for the translation but it should be readable and understandable to any french speaking person. I'm aware if I just directly copy pasted everything lazily from google translate then there will be a lot of issues or just generally wrong grammar, so I corrected/guided the faulty translations that were wrong which took me more than an hour.)
- changed small grammatical stuff in the main CONTRIBUTING.md file 
- fixed the guideline links in the vietnamese .md file
- Included newer language files in the HOWTO.md files
- added AutoIt language playlist in courses and the docs in the books section

### Why is this valuable (or not)?
I believe AutoIt is an extremely useful tool and language for windows users, as it can practically do anything when it comes to automation. It can basically do the same things as AutoHotKey but Its syntax is harder to learn (imo) than AutoIt and should serve as an alternative to AHK. 

### How do we know it's really free?
It's the official documentation website for AutoIt. It does not require anything other than an internet connection.

### For book lists, is it a book? For course lists, is it a course? etc.
I added both a course and a book.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction)

## Followup

- Check the output of Travis-CI for linter errors!

2021-09-25 22:53 UTC, Existential-nonce commented
Sorry about the weird changes I've made in `free-courses-en.md` and `free-programming-books.md`, I'm not entirely sure how I even managed to change all asterisks into hyphens for 250+ lines. But anyway, the PR should be good now.

2021-09-26 13:28 UTC, davorpa commented
Thanks for explain huge changes minutely  :smile:

> Sorry about the weird changes I've made in `free-courses-en.md` and `free-programming-books.md`, I'm not entirely sure how I even managed to change all asterisks into hyphens for 250+ lines. But anyway, the PR should be good now.

I suggest to disable editor linter addons like vscode `markdown-all-in-one`. We use one built on top of @remarkjs.

I see you could solve it in the 5th commit :+1:.

---

If you accept an advice, try to don't overscope PRs :wink:... It makes hard to review it, especially when mixing additions and deletions of if implies many files.

If you want submit more than one at same time, making branches (one branch per PR) instead work on master is the best option. Fetch and checkout them from upstream master.

This has also the advantage of unnecesary extra merge commits/conflicts by your side (e.g. commits 2nd https://github.com/EbookFoundation/free-programming-books/pull/5554/commits/a8f4bffbd521e419d765eb3131cde010097eacf5, 4th https://github.com/EbookFoundation/free-programming-books/pull/5554/commits/6f60e7170389c2d8c4bee34b5a46e78cc5526421) :rocket:

2021-09-26 13:34 UTC, Existential-nonce commented
I see, thanks for the explanation. I'll try to be a bit more careful next time.

2021-09-26 16:03 UTC, davorpa requested changes
Thanks for complete #5024 and #5454.

Some minor changes :wink: :arrow_down:

Could you find some other interesting AutoIt resources in both listings (books/course)? We try to avoid single items sections especially in these two which are too big (see #5092)

Thanks in advance.

2021-09-26 16:08 UTC, Existential-nonce commented on courses/free-courses-en.md
> +* [AutoIt Scripting Tutorial](https://www.youtube.com/playlist?list=PL4Jcq5zn02jKpjX0nqI1_fS7mEEb5tw6z) - TutsTeach (HTML)
Oh yeah my bad, I think I added the HTML indication in the wrong section. I was gonna add it in the courses section. Thanks for pointing it out.

2021-09-27 01:01 UTC, eshellman commented
Formidable!

2021-09-27 01:01 UTC, merged

2021-09-27 07:53 UTC, davorpa commented on HOWTO.md
> +Read this in other languages: [Français](CONTRIBUTING-fr.md), [Español](HOWTO-es.md), [简体中文](HOWTO-zh.md), [हिन्दी](HOWTO-hi.md), [繁體中文](HOWTO-zh-TW.md), [Português (BR)](HOWTO.pt_BR.md), [فارسی](HOW
Fixed by #5556