split language agnostic to a separate file
EbookFoundation/free-programming-books pull request #5563
Opened 2021-09-27 23:36 UTC by eshellman

## What does this PR do?
It moves the "Language Agnostic" books to a separate file.
Implements #5249 

## Checklist:
- [ x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [ x] Put lists in alphabetical order, correct spacing.
- [x ] Add needed indications (PDF, access notes, under construction)

## Followup

- Check the output of Travis-CI for linter errors!

2021-09-27 23:38 UTC, eshellman commented
hmmm seems to break the link checker.
we should settle on a crosslink syntax so the obvious cross-links can be made.

2021-09-27 23:40 UTC, eshellman commented
as this will be a massive conflict creator, we should decide whether to procede with it before friday.

2021-09-28 00:54 UTC, davorpa commented
> hmmm seems to break the link checker.
> we should settle on a crosslink syntax so the obvious cross-links can be made.

This is a known issue the first time when a new branch is created. It's produced by the github action in charge of find what files was change and then, scope the links to search with the bot.

https://github.com/EbookFoundation/free-programming-books/blob/b76cdd789a68b30062b6628cadb80f9c0c7de41a/.github/workflows/main.yml#L6-L12

2021-09-28 16:59 UTC, davorpa requested changes
All `####` headings should be fixed to `###` with the propose of mantaining TOC synchronized. :hugs:

/labelthis: breaking changes

2021-09-28 16:59 UTC, davorpa commented on books/free-programming-books-subjects.md
> +#### Algorithms & Data Structures
After moving, **heading dept should be decremented by one `###`** to be at the same level that metalist section and then, mantain the TOC synchronized :rocket:

**Apply on all headers with `####`** :wink:

2021-09-28 16:59 UTC, davorpa commented on books/free-programming-books-subjects.md
> +### Graphical User Interfaces
Nice! Another with level 3.

2021-09-28 16:59 UTC, davorpa commented on books/free-programming-books-subjects.md
> +### Graphics Programming
It's OK using level 3.

2021-09-28 16:59 UTC, davorpa commented on books/free-programming-books-subjects.md
> +#### Misc
Maybe move entire section to the top, below `0 - Metalists` :question:

2021-09-28 16:59 UTC, davorpa commented on books/free-programming-books-subjects.md
> +#### MOOC
Maybe move entire section to the top, below `0 - Metalists` :question:

Its more like platforms than subject

2021-09-28 16:59 UTC, davorpa commented on books/free-programming-books-subjects.md
> +* [Reverse Engineering for Beginners](http://beginners.re) - Dennis Yurichev (PDF)
Remember remove it. See:
- #5558 

I'm working on add those localized versions that are free

2021-09-28 16:59 UTC, davorpa commented on books/free-programming-books-subjects.md
> +### Web Services
It's OK. Other with level 3.

2021-09-28 16:59 UTC, davorpa commented on books/free-programming-books-subjects.md
> +### Workflow
It's right. Level 3.

2021-09-28 19:26 UTC, davorpa approved these changes

2021-09-29 13:17 UTC, merged