Added Two new resources in free-courses-en.md
EbookFoundation/free-programming-books pull request #5578
Opened 2021-09-29 18:33 UTC by kraticodes

## What does this PR do?
Added two new resources to free-courses-en.md ,one for Git and other for PHP.

## For resource
### Description
Courses are open to all and are from geeksgod.com

### Why is this valuable (or not)?
These are great courses for beginners.

### How do we know it's really free?
Confirmed myself

### For book lists, is it a book? For course lists, is it a course? etc.
These are courses
## Checklist:
- [ :white_check_mark:] Read our [contributing guidelines]
- [ :white_check_mark:] Search for duplicates.
- [ :white_check_mark:] Include author(s) and platform where appropriate.
- [ :white_check_mark:] Put lists in alphabetical order, correct spacing.
- [ :white_check_mark:] Add needed indications (PDF, access notes, under construction)

## Followup

- Check the output of Travis-CI for linter errors!

2021-09-29 18:47 UTC, kraticodes commented
Hey ! Plz can you explain what's  the fault here?

2021-09-29 19:00 UTC, eshellman commented
Be sure to check the free-programming-books-lint output for linter errors. Alphabetical order and spacing are the most common problems.

2021-09-29 22:49 UTC, davorpa requested changes
> Hey ! Plz can you explain what's the fault here?

@kraticodes, I give you deep feedback of this faults 

![image](https://user-images.githubusercontent.com/3125580/135358241-fa5c2342-246f-496a-bd8a-c165f5ef9a4c.png)
<details><summary>As linter report us (click to see details) :</summary>

```log
Run fpb-lint ./courses/
free-courses-en.md
      3:1-71:38  warning  Alphabetical ordering: swap l.4 and l.3      alphabetize-lists            remark-lint
       3:1-3:18  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
       4:1-4:24  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
       5:1-5:63  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
       6:1-6:22  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
       7:1-7:24  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
       8:1-8:20  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
       9:1-9:31  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     10:1-10:26  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     11:1-11:10  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     12:1-12:22  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     13:1-13:22  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     14:1-14:26  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     15:1-15:16  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     16:1-16:16  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     17:1-17:32  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     18:1-20:16  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     19:3-19:20  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     20:3-20:16  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     21:1-21:34  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     22:1-22:20  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     23:1-23:22  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     24:1-24:40  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     25:1-25:14  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     26:1-26:12  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     27:1-27:22  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     28:1-28:27  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     29:1-29:14  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     30:1-30:16  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     31:1-40:21  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     32:3-32:28  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     33:3-33:19  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     34:3-34:22  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     35:3-35:23  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     36:3-36:22  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     37:3-37:20  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     38:3-38:34  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     39:3-39:20  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     40:3-40:21  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     41:1-41:20  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     42:1-42:28  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     43:1-43:18  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     44:1-44:14  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     45:1-45:40  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     46:1-46:24  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     47:1-47:20  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     48:1-48:16  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     49:1-49:15  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     50:1-50:18  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     51:1-51:16  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     52:1-52:14  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     53:1-53:80  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     54:1-54:28  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     55:1-57:20  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     56:3-56:22  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     57:3-57:20  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     58:1-58:16  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     59:1-59:10  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     60:1-60:16  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     61:1-61:16  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     62:1-62:18  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     63:1-63:24  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     64:1-65:20  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     65:3-65:20  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     66:1-66:20  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     67:1-69:18  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     68:3-68:24  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     69:3-69:18  warning  Marker style should be `*`                   unordered-list-marker-style  remark-lint
     70:1-70:66  warning  Marker style sho [...]

2021-09-29 22:49 UTC, davorpa commented on courses/free-courses-en.md
> +* [Learn Version Control system with GIT](https://geeksgod.com/udemy-free-course/git-for-beginners/)
Following guidelines:
- tracking sites / parameters are not accepted. The right link is https://www.eduonix.com/git-for-beginners and then, the title `GIT for beginners`
- should give creator attributions: `Maksym Rudnyi`
- should anotate platform: `Eduonix Learning Solutions`

So, try to fix it with:

```markdown
* [GIT for beginners](https://geeksgod.com/udemy-free-course/git-for-beginners/) - Maksym Rudnyi (Eduonix Learning Solutions)
```
And then, reorder to satisfy the list alphabetization rule.

2021-09-29 22:49 UTC, davorpa commented on courses/free-courses-en.md
> +* [Learn Top Ten Frameworks In PHP By Building Projects](https://geeksgod.com/udemy-free-course/learn-top-ten-frameworks-in-php-by-building-projects/)
Please:
- Reorder with the purpose of accomplish with the list alphabetization rule.
- Tracking sites / parameters are not accepted. Right link is https://www.eduonix.com/courses/Web-Development/learn-top-ten-frameworks-in-php-by-building-projects
- Should give platform / creator attributions: `Eduonix Learning Solutions`

```markdown
* [Learn Top Ten Frameworks In PHP By Building Projects](https://www.eduonix.com/courses/Web-Development/learn-top-ten-frameworks-in-php-by-building-projects) - Eduonix Learning Solutions
```

2021-09-30 10:17 UTC, davorpa requested changes
Nice! List alphabetization was fixed :rocket:

- Now some minor changes.
- Remember also fix pending TOC suggested changes.

2021-09-30 10:17 UTC, davorpa commented on courses/free-courses-en.md
> +* [GIT for beginners](https://geeksgod.com/udemy-free-course/git-for-beginners/) - Maksym Rudnyi (Eduonix Learning Solutions)
Following guidelines:
- tracking sites / parameters are not accepted. The right link is https://www.eduonix.com/git-for-beginners
- maybe complete it with note about need platform sign up

So, try to fix it with:

```markdown
* [GIT for beginners](https://www.eduonix.com/git-for-beginners) - Maksym Rudnyi (Eduonix Learning Solutions) *(account or email address required)*
```

2021-09-30 10:17 UTC, davorpa commented on courses/free-courses-en.md
> +* [Learn Top Ten Frameworks In PHP By Building Projects](https://www.eduonix.com/courses/Web-Development/learn-top-ten-frameworks-in-php-by-building-projects) - Eduonix Learning Solutions
Maybe complete it with note about need platform sign up

```markdown
* [Learn Top Ten Frameworks In PHP By Building Projects](https://www.eduonix.com/courses/Web-Development/learn-top-ten-frameworks-in-php-by-building-projects) - Eduonix Learning Solutions *(account or email address required)*
```

2021-09-30 18:26 UTC, davorpa requested changes
@kraticodes a last effort :wink:...

2021-09-30 18:26 UTC, davorpa commented on courses/free-courses-en.md
> -* [C](#c)
Restore

2021-09-30 18:26 UTC, davorpa commented on courses/free-courses-en.md
> +* [Index](#index)
Remove

2021-09-30 19:34 UTC, kraticodes commented
FINALLY! Thankyou @davorpa for guiding me all the way. 😄 🔥

2021-09-30 19:51 UTC, davorpa requested changes
> FINALLY! Thankyou @davorpa for guiding me all the way. smile fire

Yes, we get it. No lint errors. But.... last step... this is easy :grinning:

2021-09-30 19:51 UTC, davorpa commented on courses/free-courses-en.md
> +
Maybe I should have said "remove line" in https://github.com/EbookFoundation/free-programming-books/pull/5578#discussion_r719655588 😶‍🌫️😣

If applied, it prevents conflicts with other PR #5581

2021-09-30 19:57 UTC, davorpa approved these changes
@kraticodes, Forget last review (https://github.com/EbookFoundation/free-programming-books/pull/5578#pullrequestreview-768273086). I mistake due to not ui refresh with last changes.

Erick, ready to merge

2021-09-30 23:40 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2021-09-30 23:40 UTC, merged