Added Redis for Dummies from Redis site
EbookFoundation/free-programming-books pull request #5585
Opened 2021-09-30 10:49 UTC by mfvitale

## What does this PR do?
Add resource

## For resources
### Description
- Added Redis for Dummies book from Redis official site

### Why is this valuable (or not)?
- Valuable for beginners

### How do we know it's really free?
It's available from Redis site leaving a mail address, Then there will be a download link

### For book lists, is it a book? For course lists, is it a course? etc.
- book

## Checklist:
- [x ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction)

## Followup

- Check the output of Travis-CI for linter errors!

2021-09-30 16:47 UTC, davorpa commented
Recover

2021-09-30 16:54 UTC, mfvitale commented
I opened by mistake before hacktoberfest. I will open another tomorrow.

2021-09-30 16:56 UTC, davorpa requested changes

2021-09-30 16:56 UTC, davorpa commented on books/free-programming-books-langs.md
> +* [Redis-For-Dummies](https://redis.com/redis-for-dummies/) (PDF) *(email address or account required)*
```suggestion
* [Redis for Dummies](https://redis.com/redis-for-dummies/) - Redis Ltd ([PDF](https://redis.com/wp-content/uploads/2021/09/Redis-For-Dummies_FINAL.pdf)) *(email address or account required)*
```

2021-09-30 17:12 UTC, davorpa commented
> I opened by mistake before hacktoberfest. I will open another tomorrow.

If is your preference, **close it again**.  But I do not see much sense.

Anyways, you can integrate the review suggestion meanwhile :wink:

2021-09-30 17:23 UTC, closed without merging

2021-10-01 15:54 UTC, davorpa commented
Resubmitted at #5625