Add Hebrew online courses
EbookFoundation/free-programming-books pull request #5590
Opened 2021-09-30 15:47 UTC by tomer

## What does this PR do?
Add Hebrew courses by [campus.gov.il](https://campus.gov.il)

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [X] Search for duplicates.
- [x] Include author(s) and platform where appropriate.
- [X] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction)

## Followup

- Check the output of Travis-CI for linter errors!

2021-09-30 16:16 UTC, LuigiImVector reviewed
There weren't the [correct number of black lines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md#formatting).

2021-09-30 16:16 UTC, LuigiImVector commented on courses/free-courses-he.md
> +### C++
```suggestion
### C++

```

2021-09-30 16:16 UTC, LuigiImVector commented on courses/free-courses-he.md
> +### Python
```suggestion
### Python

```

2021-09-30 16:16 UTC, LuigiImVector commented on courses/free-courses-he.md
> +### R
```suggestion
### R

```

2021-09-30 16:16 UTC, LuigiImVector commented on courses/free-courses-he.md
> +* [מבוא לתכנות ועיבוד נתונים בשפת R](https://campus.gov.il/course/telhai-acd-rfp4-telhai-r/) (קמפוסIL ומכללת תל־חי)
```suggestion
* [מבוא לתכנות ועיבוד נתונים בשפת R](https://campus.gov.il/course/telhai-acd-rfp4-telhai-r/) (קמפוסIL ומכללת תל־חי)

```

2021-09-30 16:39 UTC, davorpa requested changes
Thanks @tomer. Having a new localized listing is always a nice feature.

Please, solve minor bugs about TOC.

2021-09-30 16:39 UTC, davorpa commented on courses/free-courses-he.md
> +* [C++](C++)
Fix TOC entry pointing to an alias

```suggestion
* [C++](#cpp)
```

2021-09-30 16:39 UTC, davorpa commented on courses/free-courses-he.md
> +* [R](#R)
Like in other listings, anchor goes in lowecase

```suggestion
* [R](#r)
```

2021-09-30 16:39 UTC, davorpa commented on courses/free-courses-he.md
> +### C++
Add TOC alias
```suggestion
### <a name="cpp"></a>C++
```

2021-09-30 17:02 UTC, davorpa approved these changes
Ready to merge :tada:

2021-10-01 00:43 UTC, eshellman commented
love it. 
Thanks, and welcome to free-programming-books!

2021-10-01 00:43 UTC, merged