Add some learning reference in ID
EbookFoundation/free-programming-books pull request #5593
Opened 2021-09-30 17:28 UTC by lenfaire

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2021-09-30 18:14 UTC, LuigiImVector commented
To access these resources is required an account so you need to add this `(account *requested*)` to the end of each string.

Maybe you could also add the name of the course authors (example: `* [Flutter Membangun Website](https://buildwithangga.com/kelas/flutter-membangun-website-sederhana?thumbnail=nk4neM2UyG.110&main_leads=browse) - Rifqi Eka, BuildWithAngga (account *requested*)`

2021-09-30 20:59 UTC, davorpa requested changes
Following CONTRIBUTING format guidelines.
- Links can't have tracking parameters, so clean it.
- Give attributions to the creator/mentor/platform
- For resource name, use the title as is published in the website
- Add notes about platform registering: email and phone is required.

Please, apply following snippets to solve it.

2021-09-30 20:59 UTC, davorpa commented on courses/free-courses-id.md
> +* [Flutter Membangun Website](https://buildwithangga.com/kelas/flutter-membangun-website-sederhana?thumbnail=nk4neM2UyG.110&main_leads=browse) - BuildWithAngga
Creator: Rifqi Eka
Cleaned link: https://buildwithangga.com/kelas/flutter-membangun-website-sederhana

Use this snippet to also merge pull #5589 and as main fix:
```markdown
* [Flutter for Designer: Design to Code](https://buildwithangga.com/kelas/flutter-for-designer-design-to-code) - Rifqi Eka *(BuildWithAngga account and email address required)*
* [Flutter Membangun Website](https://buildwithangga.com/kelas/flutter-membangun-website-sederhana) - Rifqi Eka *(BuildWithAngga account and email address required)*
```

2021-09-30 20:59 UTC, davorpa commented on courses/free-courses-id.md
> +* [Golang Fundamental](https://buildwithangga.com/kelas/golang-fundamental?thumbnail=nk4neM2UyG.54&main_leads=browse) - BuildWithAngga
Creator: Agung Setiawan
Right link: https://buildwithangga.com/kelas/golang-fundamental

Use this snippet as fix:
```markdown
* [Golang Fundamental](https://buildwithangga.com/kelas/golang-fundamental) - Agung Setiawan *(BuildWithAngga account and email address required)*
```

2021-09-30 20:59 UTC, davorpa commented on courses/free-courses-id.md
> +* [CSS Tailwind](https://buildwithangga.com/kelas/css-tailwind-web-design?thumbnail=nk4neM2UyG.46&main_leads=browse) - BuildWithAngga
Creator: Yein Narayana
Right title: CSS Tailwind Web Design
Right link: https://buildwithangga.com/kelas/css-tailwind-web-design

Use this snippet as fix:
```markdown
* [CSS Tailwind Web Design](https://buildwithangga.com/kelas/css-tailwind-web-design) - Yein Narayana *(BuildWithAngga account and email address required)*
```

2021-09-30 20:59 UTC, davorpa commented on courses/free-courses-id.md
> +* [Node.js Dasar](https://buildwithangga.com/kelas/node-javascript-dasar?thumbnail=nk4neM2UyG.36&main_leads=browse) - BuildWithAngga
Creator: Elfin Sanjaya
Right title: Node JavaScript Dasar
Right link: https://buildwithangga.com/kelas/node-javascript-dasar

Use this snippet as fix:
```markdown
* [Node JavaScript Dasar](https://buildwithangga.com/kelas/node-javascript-dasar) - Elfin Sanjaya *(BuildWithAngga account and email address required)*
```

2021-09-30 20:59 UTC, davorpa commented on courses/free-courses-id.md
> +* [Microservice Architecture Web Development](https://buildwithangga.com/kelas/microservice-architecture-web-development?thumbnail=nk4neM2UyG.49&main_leads=browse) - BuildWithAngga
Creator: Widada
Right link: https://buildwithangga.com/kelas/microservice-architecture-web-development

Use this snippet as fix:
```markdown
* [Microservice Architecture Web Development](https://buildwithangga.com/kelas/microservice-architecture-web-development) - Widada *(BuildWithAngga account and email address required)*
```

2021-10-01 00:47 UTC, eshellman commented
Nice teamwork. 
Thanks, and welcome to free-programming-books!

2021-10-01 00:47 UTC, merged

2021-10-01 02:37 UTC, lenfaire commented
Thank you sir. Glad being contributor on this project.