fix a java course link by programmerzamannow
EbookFoundation/free-programming-books pull request #5595
Opened 2021-09-30 17:43 UTC by nurulramadhona

## What does this PR do?
Add resource(s) | Remove resource(s)

## For resources
### Description
The existing link is no longer available. So, I updated with the new one.
### Why is this valuable (or not)?

### How do we know it's really free?
You can directly access it.
### For book lists, is it a book? For course lists, is it a course? etc.
It's a course
## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2021-09-30 21:11 UTC, davorpa requested changes
Nice catch.

Helps to improve:
- #5470

2021-09-30 21:11 UTC, davorpa commented on courses/free-courses-id.md
> +* [JAVA TUTORIAL - BAHASA INDONESIA](https://www.youtube.com/playlist?list=PL-CtdCApEFH-p_Q2GyK4K3ORoAT0Yt7CX) - Programmer Zaman Now
- Although channel is named `Programmer Zaman Now` the creator is @khannedy
- We also take the opportunity to complete with the resource platform

```markdown
* [JAVA TUTORIAL - BAHASA INDONESIA](https://www.youtube.com/playlist?list=PL-CtdCApEFH-p_Q2GyK4K3ORoAT0Yt7CX) - Eko Kurniawan Khannedy, Programmer Zaman Now (YouTube)
```

2021-10-01 00:25 UTC, nurulramadhona commented
I've updated the creator's name. Not only on the resource I fixed the link, but all resources that use the same creator.

2021-10-01 00:49 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2021-10-01 00:49 UTC, merged