Added new Java Course
EbookFoundation/free-programming-books pull request #5614
Opened 2021-10-01 03:49 UTC by Nandan-18

## What does this PR do?
Add resource(s) | Add info | Improve repo

## For resources
### Description

Free Java course offered by Sololearn.

### Why is this valuable (or not)?

Platform has an interactive and clean interface.

### How do we know it's really free?

I've used it myself to learn concepts.

### For book lists, is it a book? For course lists, is it a course? etc.

It is a course.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2021-10-01 14:42 UTC, eshellman commented
add an access note indicating registration required

2021-10-01 20:54 UTC, davorpa requested changes

2021-10-01 20:54 UTC, davorpa commented on courses/free-courses-en.md
> +* [Learn Java](https://www.sololearn.com/learning/1068) - (Sololearn) (Registration Required)
Following [CONTRIBUTING format guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md#formatting):
>- if an email address or account setup is requested before download is enabled, add language-appropriate notes in parentheses, e.g.: (email address *requested*, not required)

Maybe better

```markdown
* [Learn Java](https://www.sololearn.com/learning/1068) - Sololearn *(email address required)*
```

2021-10-01 22:58 UTC, eshellman commented on courses/free-courses-en.md
> +* [Learn Java](https://www.sololearn.com/learning/1068) - (Sololearn) (Registration Required)
yes

2021-10-02 05:46 UTC, davorpa approved these changes
Sololearn, a good platform with courses for beginners, code playgrounds and interesting challenges. Maybe, Q&A and competitive community would be the best of it.

### Ready to merge :fireworks: :tada:

2021-10-02 12:14 UTC, merged