add one more c # book
EbookFoundation/free-programming-books pull request #5668
Opened 2021-10-01 15:52 UTC by Debajyotighosh654

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [ ] Search for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2021-10-01 15:58 UTC, eshellman commented on books/free-programming-books-ar.md
> +*( https://www.introprogramming.info/wp-content/uploads/2013/07/Books/CSharpEn/Fundamentals-of-Computer-Programming-with-CSharp-Nakov-eBook-v2013.pdf)-Svetlin Nakov
check your markdown syntax- there's no title?? and missing an author?

2021-10-01 22:47 UTC, davorpa requested changes
:warning: This resource is written in English. 

**Move it right listing**: [`free-programming-books-langs.md#c-sharp`](https://github.com/Debajyotighosh654/free-programming-books/blob/patch-2/books/free-programming-books-langs.md#c-sharp)

2021-10-01 22:47 UTC, davorpa commented on books/free-programming-books-ar.md
> +* Fundamentals-of-Computer-Programming-with-CSharp - ( https://www.introprogramming.info/wp-content/uploads/2013/07/Books/CSharpEn/Fundamentals-of-Computer-Programming-with-CSharp-Nakov-eBook-v2013.p
I could help you with resources format :wink:. Use this snippet

```markdown
* [FUNDAMENTALS OF COMPUTER PROGRAMMING WITH C# (The Bulgarian C# Programming Book)](https://www.introprogramming.info/wp-content/uploads/2013/07/Books/CSharpEn/Fundamentals-of-Computer-Programming-with-CSharp-Nakov-eBook-v2013.pdf) - Svetlin Nakov, Veselin Kolev et al. (PDF)
```

:information_source: Main authoritative site https://introprogramming.info/english-intro-csharp-book/ which this PDF can be found in.


:warning: But the **most important**. this resource is written in English. **Move it right listing**: [`free-programming-books-langs.md#c-sharp`](https://github.com/Debajyotighosh654/free-programming-books/blob/patch-2/books/free-programming-books-langs.md#c-sharp)

2021-10-01 23:04 UTC, eshellman commented
still wrong markdown syntax

2021-10-02 18:03 UTC, davorpa commented
This was merged at #5712. Please, avoid to reopen in the future

2021-10-02 18:03 UTC, closed without merging