added new resource in data science
EbookFoundation/free-programming-books pull request #5681
Opened 2021-10-01 17:29 UTC by kraticodes

## What does this PR do?
Added resource

## For resources
### Description
Data science course (free)
### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [ ] Search for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2021-10-01 17:36 UTC, kraticodes commented
plz help me with the conflicting file issue

2021-10-01 23:15 UTC, eshellman commented
please resolve conflicts.

2021-10-02 01:37 UTC, davorpa commented
> plz help me with the conflicting file issue

Some ways to solve PR merge conflicts:
- [Github docs: Resolving a merge conflict on GitHub](https://docs.github.com/en/github/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github)
- Make a upstream master merge
- Use [Github web based editor](https://docs.github.com/es/codespaces/the-githubdev-web-based-editor#opening-the-web-based-editor) to solve it.

Next time, I recomend you create branches instead work on main/master.

2021-10-02 17:17 UTC, kraticodes commented
plz have a look!

2021-10-02 20:03 UTC, merged

2021-10-02 20:16 UTC, davorpa requested changes
**TIP**: Rerequest a review when done, sometimes no needs make comments. Use icon buttons placed near who review to do this :wink:

2021-10-02 20:16 UTC, davorpa commented on more/free-programming-interactive-tutorials-en.md
> +* [Data Science Foundations - IBM SkillBuild](https://skillsbuild.org/students/course-catalog/data-science) *(Email login reqired to access the course)*
An insignificant misspelling in notes: `reqired`

but better normalize format according to CONTRIBUTING guidelines.

`*(email address required)*`

:rocket::rocket: