➕ add ML books and courses
EbookFoundation/free-programming-books pull request #5726
Opened 2021-10-02 07:55 UTC by yashppawar

## What does this PR do?
- Add resource(s) 
- Add info

## For resources
### Description
- Add [The Mechanics of Machine Learning](https://mlbook.explained.ai/) book
- Add [Made with ML](https://madewithml.com/) course
- Add Mathematics for Machine Learning By Imperial College London on YouTube
- Change URL for Introduction to Statistical Learning to a more direct URL
- Change URL for Mining of Massive Datasets to a more direct URL 

### Why is this valuable (or not)?
The added resources help to learn Machine Learning, MLOps.
The changed URL makes it one click to access the pdf.

### How do we know it's really free?
The resources do not ask for any email/credit card info to get access and the site is either a trusted site or an official site.

### For book lists, is it a book? For course lists, is it a course? etc.
* Books
    - The Mechanics of Machine Learning
    - Introduction to Statistical Learning 
    - Mining of Massive Datasets
 * Courses
   - Mathematics for Machine Learning (Video)
   - Made With ML (misc)

## Checklist:
- [ x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [ x] Search for duplicates.
- [ x] Include author(s) and platform where appropriate.
- [ x] Put lists in alphabetical order, correct spacing.
- [ x] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2021-10-02 08:22 UTC, yashppawar commented
ok, all checks passed now 😌

2021-10-02 12:39 UTC, eshellman commented on books/free-programming-books-langs.md
> +* [An Introduction to Statistical Learning with Applications in R](https://web.stanford.edu/~hastie/ISLR2/ISLRv2_website.pdf) - Gareth James, Daniela Witten, Trevor Hastie and Robert Tibshirani [webs
no links for authors

2021-10-02 12:40 UTC, eshellman commented on books/free-programming-books-subjects.md
> +* [Mining of Massive Datasets](http://infolab.stanford.edu/~ullman/mmds/book.pdf) - Jure Leskovec, Anand Rajaraman, Jeffrey D. Ullman [website](https://www.mmds.org) (PDF)
no author links please

2021-10-02 12:40 UTC, eshellman commented on books/free-programming-books-subjects.md
> +* [An Introduction to Statistical Learning](https://web.stanford.edu/~hastie/ISLR2/ISLRv2_website.pdf) - Gareth James, Daniela Witten, Trevor Hastie and Robert Tibshirani [website](https://www.statle
no author links please

2021-10-02 12:41 UTC, eshellman requested changes

2021-10-02 12:41 UTC, eshellman commented on courses/free-courses-en.md
> +* [Mathematics for Machine Learning - Linear Algebra](https://www.youtube.com/playlist?list=PLiiljHvN6z1_o1ztXTKWPrShrMrBLo5P3)
creator?

2021-10-02 12:41 UTC, eshellman commented on courses/free-courses-en.md
> +* [Mathematics for Machine Learning - Multivariate Calclus](https://www.youtube.com/playlist?list=PLiiljHvN6z193BBzS0Ln8NnqQmzimTW23)
creator?

2021-10-02 13:44 UTC, yashppawar commented
Removed links, and added author to MML course.

2021-10-02 15:08 UTC, yashppawar commented on courses/free-courses-en.md
> +* [Mathematics for Machine Learning - Linear Algebra](https://www.youtube.com/playlist?list=PLiiljHvN6z1_o1ztXTKWPrShrMrBLo5P3)
Added in the latest commit

2021-10-03 20:39 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2021-10-03 20:39 UTC, merged