Added some necessary Youtube playlist of Bengali Language
EbookFoundation/free-programming-books pull request #5760
Opened 2021-10-02 15:58 UTC by noobSrijon

## What does this PR do?
Add resource(s)

## For resources
### Description
Added some necessary resources for newbie programmers of Bengali language. Even I added some playlists from where I learnt how to code.
### Why is this valuable (or not)?
This PR contains some necessary Youtube Playlists in Bengali Language which may helps a newbie programmer to build up his/her skills

### How do we know it's really free?
Added resources are from Youtube which is completely free

### For book lists, is it a book? For course lists, is it a course? etc.
It is some Youtube Playlist

## Checklist:
- [ *] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [ *] Search for duplicates.
- [ *] Include author(s) and platform where appropriate.
- [ *] Put lists in alphabetical order, correct spacing.
- [ *] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2021-10-02 21:57 UTC, davorpa commented
TIP: use `[x]` to fill tasklisk steps

2021-10-02 22:14 UTC, davorpa requested changes
ℹ️ Apply CONTRIBUTE guideline notes on the other added resources.

⚠️ Check CI linter logs to ensure list alphabetization

2021-10-02 22:14 UTC, davorpa commented on books/free-programming-books-bl.md
> +* [JavaScript Bangla Tutorial](https://www.youtube.com/playlist?list=PLHiZ4m8vCp9OkrURufHpGUUTBjJhO9Ghy) - Learn with Sumit Bangladesh
Please, ensure fullfill author attributions @learnwithsumit

ℹ️ From his LinkedIn profile: `Sumit Saha`

⚠️ Needs real title: `JavaScript Bangla Tutorial | JS Bangla Tutorial Series for Beginners`

2021-11-03 14:44 UTC, eshellman commented
added to books list in another PR

2021-11-03 14:44 UTC, closed without merging

2022-08-13 18:35 UTC, davorpa commented
Duplicate of #7002

2022-08-13 18:44 UTC, davorpa commented on books/free-programming-books-bl.md
> +* [Bangla Python Tutorial for Beginners](https://www.youtube.com/playlist?list=PLlBKlxyCgmsCYJLq9qc5QzaU-oBFJN79B) - StartBit
Resolved by commit 922e371ff8322268fb50635090326a852d9a499d made at PR #7002