Adding Module Patterns book
EbookFoundation/free-programming-books pull request #5789
Opened 2021-10-02 23:55 UTC by AbderrahimSoubaiElidrissi

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

Add resoruce

## For resources
### Description

Adding module patterns book by Pedro Teixeira

### Why is this valuable (or not)?

 module patterns book is one of the most valuable books to learn modules in javascript especially in node.js

### How do we know it's really free?

It's coast $0 on leanpub.com platform (leanpub is a platform to sell books)

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x Put lists in alphabetical order, correct spacing.
- [x Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2021-10-03 18:06 UTC, davorpa requested changes
It's a good moment to make some changes, When done, please request for a rewiew again using :arrows_clockwise: button.

2021-10-03 18:06 UTC, davorpa commented on books/free-programming-books-langs.md
> +* [Module Patterns](https://leanpub.com/modulepatterns) - Pedro Teixeira
CONTRIBUTING guidelines needs to be enforced. Be sure next time to satisfy them :wink: 
- resource formats
- leanpub notes

```suggestion
* [Module Patterns](https://leanpub.com/modulepatterns) - Pedro Teixeira (HTML, PDF, EPUB, Kindle) *(Leanpub account or valid email requested)*
```

2021-10-05 12:02 UTC, davorpa approved these changes

2021-10-06 00:57 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2021-10-06 00:57 UTC, merged