translating HOWTO.md to Dutch
EbookFoundation/free-programming-books pull request #5831
Opened 2021-10-03 15:29 UTC by JenniX3

## What does this PR do?
Improve repo

## For resources
### Description

Translated HOWTO to Dutch

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2021-10-03 15:31 UTC, SethFalco approved these changes

2021-10-04 02:28 UTC, eshellman commented
I would separate the translation and the links to it into two separate PRs. The links generate the conflicts, and we can do a cleanup PR after things have settled a bit.

2021-10-05 21:29 UTC, davorpa requested changes

2021-10-05 21:29 UTC, davorpa commented on HOWTO-nl.md
> +* [Youtube - Markdown Crash Course](https://www.youtube.com/watch?v=HUBNt18RFbo)
Take into account to add a note according to this links are in english. Translate `in english`

Example:
```markdown
* [Over pull-verzoeken](https://help.github.com/articles/about-pull-requests/) *(in english)*
```

2021-10-05 21:30 UTC, davorpa commented on HOWTO-nl.md
> +Tot slot, als je niet zeker weet of de bron die je wilt toevoegen geschikt is voor gratis programmeerboeken, lees dan de richtlijnen in [CONTRIBUTING](CONTRIBUTING.md).
Help us with CONTRIBUTING translation if you want

2021-11-02 18:02 UTC, davorpa requested changes
Users should be warned about the language used in external links content (https://github.com/EbookFoundation/free-programming-books/pull/5831/files#r722720638).

2021-11-02 18:03 UTC, davorpa commented on HOWTO-nl.md
> +Lees dit in andere talen [English](HOWTO.md), [Français](HOWTO-fr.md), [Español](HOWTO-es.md), [简体中文](HOWTO-zh.md), [हिन्दी](HOWTO-hi.md), [繁體中文](HOWTO-zh_TW.md), [Português (BR)](HOWTO-pt_BR.md), [ف
```suggestion
Lees dit in andere talen: [English](HOWTO.md), [Français](HOWTO-fr.md), [Español](HOWTO-es.md), [简体中文](HOWTO-zh.md), [हिन्दी](HOWTO-hi.md), [繁體中文](HOWTO-zh_TW.md), [Português (BR)](HOWTO-pt_BR.md), [فارسی](HOWTO-fa_IR.md), [Русский](HOWTO-ru.md), [Deutsch](HOWTO-de.md), [Bahasa Indonesia](HOWTO-id.md), [Tiếng Việt](HOWTO-vi.md), [عربي](HOWTO-ar.md).
```

2021-11-05 20:44 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2021-11-05 20:44 UTC, merged