add flutter learning id
EbookFoundation/free-programming-books pull request #5864
Opened 2021-10-04 06:37 UTC by Dicky1

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [ ] Search for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2021-10-04 11:17 UTC, LuigiImVector commented
The new category is not ordered alphabetically. Check [CONTRIBUTING.md](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)

2021-10-04 15:23 UTC, davorpa commented
:writing_hand: It's a good practice to fill Pull Request fields. It helps a bit we can understand your contribution better :hugs:.

2021-10-04 15:49 UTC, davorpa requested changes
It's a good moment to make some changes. When done, request for a review again using GitHub :arrows_clockwise: button.

Closes #5870

2021-10-04 15:49 UTC, davorpa commented on books/free-programming-books-id.md
> +* [Flutter Widget](https://belajarflutter.com/flutter-widget-elevatedbutton/)
It seems like a blog post / article... 🤔. I need some feedback about

2021-10-04 15:49 UTC, davorpa commented on books/free-programming-books-id.md
> +* [Flutter](#flutter)
Fix list alphabetize-lists lint rule moving between 

https://github.com/EbookFoundation/free-programming-books/blob/699d51c27291eff63d2a86a02e5fb45494d4bce9/books/free-programming-books-id.md#L7-L8

Do the same with related section 😉

2021-11-01 16:45 UTC, davorpa commented
Domain already listed

https://github.com/EbookFoundation/free-programming-books/blob/eee3067457bb0a2fc2ad0b46cf5dadc3a2b70302/books/free-programming-books-id.md#L62

2021-11-01 16:46 UTC, davorpa commented
Duplicate of #6167

2021-11-01 16:46 UTC, closed without merging