Changes made to Blockchain resources to free-courses-en
EbookFoundation/free-programming-books pull request #5891
Opened 2021-10-04 15:40 UTC by rkmurthy366

Added Blockchain resources to free-courses-en

## What does this PR do?
Add resource(s) about Blockchain in free-courses-en.md

## For resources
### Description

### Why is this valuable (or not)?
Previously there were no resources related to blockchain, so I added few of the best tutorials, courses, and websites where one could learn about blockchain development

### How do we know it's really free?
All resources are available on either YouTube, Coursera, or on websites which are free to browse and learn

### For book lists, is it a book? For course lists, is it a course? etc.
course list

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2021-10-05 02:01 UTC, eshellman requested changes

2021-10-05 02:01 UTC, eshellman commented on courses/free-courses-en.md
> +* [Cryptodevhub](https://cryptodevhub.io)
not really a course. recommends cryptozombies

2021-10-05 03:02 UTC, trk286 commented on courses/free-courses-en.md
> +* [Build 5 Dapps on the Ethereum Blockchain - Beginner Tutorial](https://www.youtube.com/watch?v=8wMKq7HvbKw) - EatTheBlocks (Freecodecamp)
you mean change text from YouTube to playlist, I have made changes to change it as YouTube Playlist

2021-10-11 15:31 UTC, davorpa commented
> wow this awesome! Not sure how I got tagged here, but this is so cool!!

Sorry for the mention @PatrickAlphaC . You enter in our list here https://github.com/EbookFoundation/free-programming-books/pull/5891#discussion_r725740076

2021-10-12 13:57 UTC, merged