Added new NoSQL resource
EbookFoundation/free-programming-books pull request #5948
Opened 2021-10-05 20:59 UTC by rgreen324

## What does this PR do?
Add resource(s)

## For resources
### Description
This book aims to provide an approachable introduction to Redis concepts by outlining many of the key-value store’s commands
### Why is this valuable (or not)?
Recent book about managing Redis database
### How do we know it's really free?
This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0
### For book lists, is it a book? For course lists, is it a course? etc.
Book
## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2021-10-05 21:33 UTC, davorpa requested changes

2021-10-05 21:33 UTC, davorpa commented on books/free-programming-books-langs.md
> +* [How To Manage a Redis Database](https://www.digitalocean.com/community/books/how-to-manage-a-redis-database-ebook) - Mark Drake (PDF, Epub)
```suggestion
* [How To Manage a Redis Database](https://www.digitalocean.com/community/books/how-to-manage-a-redis-database-ebook) - Mark Drake (PDF, EPUB)
```

2021-10-06 11:45 UTC, davorpa requested changes

2021-10-06 11:45 UTC, davorpa commented on books/free-programming-books-langs.md
> +* [How To Manage a Redis Database](https://www.digitalocean.com/community/books/how-to-manage-a-redis-database-ebook) - Mark Drake (PDF, EPUB)
It was well in NoSQL. In other listings with several resources there are a category apart.

Could you restore it into this category?

2021-10-06 17:17 UTC, rgreen324 commented
I moved it back to NoSQL. Thanks

2021-10-06 17:58 UTC, davorpa approved these changes

2021-10-07 02:43 UTC, merged

2021-10-07 02:43 UTC, eshellman commented
Thanks, and welcome to free-programming-books!