added Django python web devlopment courses
EbookFoundation/free-programming-books pull request #6081
Opened 2021-10-08 16:08 UTC by ichbinmeraj

added Django python web devlopment courses from youtube

2021-10-09 01:46 UTC, eshellman commented
fix conflicts

2021-10-31 02:20 UTC, davorpa requested changes

2021-10-31 02:20 UTC, davorpa commented on courses/free-courses-en.md
> +* [Python web development Tutorial series-Django](https://www.youtube.com/playlist?list=PLEsfXFp6DpzRMby_cSoWTFw8zaMdTEXgL) - CodingEntrepreneurs
Use titles as-is + complete instructor

```suggestion
* [Try Django 3.2 - Python Web Development Tutorial Series](https://www.youtube.com/playlist?list=PLEsfXFp6DpzRMby_cSoWTFw8zaMdTEXgL) - Justin Mitchel, CodingEntrepreneurs
```

2021-10-31 02:20 UTC, davorpa commented on courses/free-courses-en.md
> +* [Django 3.0 crash course tutorials](https://www.youtube.com/playlist?list=PL-51WBLyFTg2vW-_6XBoUpE7vpmoR3ztO) - Dennis Ivy
Use titles as-is
```suggestion
* [Django 3.0 Crash Course Tutorials \| Customer Management App](https://www.youtube.com/playlist?list=PL-51WBLyFTg2vW-_6XBoUpE7vpmoR3ztO) - Dennis Ivy
```

2021-10-31 18:09 UTC, merged