Removed link to MATLAB as the link does not work anymore.
EbookFoundation/free-programming-books pull request #6229
Opened 2021-10-13 20:32 UTC by jonasbjork

## What does this PR do?
I've removed link to MATLAB pdf file as the file is missing now.

2021-10-13 22:48 UTC, davorpa commented
Scope PR: https://github.com/EbookFoundation/free-programming-books/pull/6229/commits/bac91c6aa1c94f3134bc8e00c3f8f39930cfd3b1

2021-10-14 01:18 UTC, eshellman commented
In other words, start from a fresh branch because the PR had twice the changes you meant.

2021-10-31 03:22 UTC, davorpa requested changes
ISO language code for swedish is `sv` see #6036.

Sorry for the conflicts due to it. Merge with upstream after apply suggestions

2021-10-31 03:22 UTC, davorpa commented on books/free-programming-books-se.md
> -
An alternative hosted at LINKÖPINGS UNIVERSITET: https://www.cvl.isy.liu.se/education/undergraduate/TSKS08/matlab-1/resurser/


Apply this patch to restore resource
```suggestion
### MATLAB

* [Introduktion till MATLAB (2004)](https://www.cvl.isy.liu.se/education/undergraduate/TSKS08/matlab-1/Matlabintro_sve.pdf) - Liber AB, Lennart Harnefors, Johnny Holmberg, Joop Lundqvist (PDF)


```

2021-11-06 22:21 UTC, davorpa commented on books/free-programming-books-se.md
> -
Suggestion applied at #6595

2021-11-06 22:22 UTC, davorpa commented
Conflicts solved at #6595

2021-11-06 22:22 UTC, davorpa commented
Duplicate of #6595

2021-11-06 22:22 UTC, closed without merging