Add Let's Data Podcast on Podcasts pt_BR
EbookFoundation/free-programming-books pull request #6492
Opened 2021-10-28 17:44 UTC by lucassmacedo

Add Let's Data Podcast on Podcasts pt_BR

## What does this PR do?
Add Let's Data Podcast on Podcasts pt_BR

## For resources
### Description
O Let's Data Podcast traz pessoas interessantes para conversar sobre ciência de dados e inteligência articificial e outras aleatoriedades da vida. Criado e apresentado por Bernardo Lago, Felipe Schiavon e Leon Silva, com o objetivo de divulgar conhecimento aliando dois enfoques: técnico e humano. Os episódios são transmitidos ao vivo pelo canal no YouTube. Junte-se a nós e venha aprender mais sobre ciência de dados e IA!

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2021-10-29 22:51 UTC, davorpa requested changes
It's a good moment to apply some changes. When done, request for a review again using GitHub :arrows_clockwise: button. Meanwhile, draft status can be used to work on it if you want.

2021-10-29 22:51 UTC, davorpa commented on casts/free-podcasts-screencasts-pt_BR.md
> +* [Teste de Turing](https://castbox.fm/channel/Teste-de-Turing-id2546538) (podcast)
- Complete with author to satisfy licensing
- Better multi broadcast platforms like `anchor.fm`. They have various target sources linking to common ones.

```suggestion
* [Teste de Turing](https://anchor.fm/testedeturing) - Erick Fonseca (podcast)
```

2021-10-29 23:17 UTC, davorpa commented on casts/free-podcasts-screencasts-pt_BR.md
> +* [Let's Data](https://www.youtube.com/channel/UCS58303Tmd0wIKTddmRskdQ) (podcast)
What we think about add podcast team authoring?

Bernardo Lago, Felipe Schiavon e Leon Silva

Considere use another platform where we can select various sources. It's sure can be found in their website

2021-10-30 17:14 UTC, lucassmacedo commented on casts/free-podcasts-screencasts-pt_BR.md
> +* [Let's Data](https://www.youtube.com/channel/UCS58303Tmd0wIKTddmRskdQ) (podcast)
Nice, i think it's good idea

2021-10-30 19:56 UTC, davorpa commented on casts/free-podcasts-screencasts-pt_BR.md
> +* [Let's Data](https://www.youtube.com/channel/UCS58303Tmd0wIKTddmRskdQ) (podcast)
```suggestion
* [Let's Data](https://www.youtube.com/playlist?list=PLn_z5E4dh_Lj5eogejMxfOiNX3nOhmhmM) - Bernardo Lago, Felipe Schiavon, Leon Silva (screencast)
```

2021-11-09 19:40 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2021-11-09 19:40 UTC, merged