Update free-programming-books-langs.md
EbookFoundation/free-programming-books pull request #6496
Opened 2021-10-28 19:40 UTC by vineetsingh0809

## What does this PR do?
Add resource(s)

## For resources
### Description
Here we added books on python practical programming.

### Why is this valuable (or not)?
Because we can prepare practicals with these books.

### How do we know it's really free?
I have attached the free link to the ebook.

### For book lists, is it a book? For course lists, is it a course? etc.
Book

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2021-10-29 20:24 UTC, davorpa commented on books/free-programming-books-langs.md
> +* [Obey the Testing Goat!](https://www.obeythetestinggoat.com/pages/book.html) - Harry Percival (HTML, PDF, Exercises sources)
Yes. you are right.

Remove this line and complete the other:

https://github.com/EbookFoundation/free-programming-books/blob/8b725705715ab48354c6340bd56a71d20859ab15/books/free-programming-books-langs.md#L1940

2021-10-29 20:42 UTC, davorpa commented on books/free-programming-books-langs.md
> +* [PHP Essentials](https://www.techotopia.com/index.php/PHP_Essentials) - Krzysztof Kowalczyk(HTML, PDF, Exercises sources)
If author is really Krzysztof Kowalczyk, the right site would be: https://www.programming-books.io/essential/php/ , another StackOverflow documentation rip-off

2021-10-30 06:00 UTC, vineetsingh0809 commented
Hey @eshellman Sir, I made all the changes that you told me. Check it again

2021-10-30 08:59 UTC, davorpa commented on books/free-programming-books-langs.md
> +* [Learn Enough Git to Be Dangerous](https://www.learnenough.com/git-tutorial/getting_started) - Michael Hartl(HTML, PDF, Exercises sources)
Freemium: only free 2 chapters of

2021-10-30 09:05 UTC, davorpa commented on books/free-programming-books-langs.md
> -* [Test-Driven Web Development with Python](http://www.obeythetestinggoat.com/pages/book.html) - Harry Percival (3.3 - 3.x)
Why remove this? The wrong was the other!

2021-10-30 09:26 UTC, davorpa commented on books/free-programming-books-langs.md
> +* [Obey the Testing Goat!](https://www.obeythetestinggoat.com/pages/book.html) - Harry Percival (HTML, PDF, Exercises sources)
Removing patch to complete https://github.com/EbookFoundation/free-programming-books/pull/6496/files#r739629120 suggestion
```suggestion
```

2021-10-30 09:33 UTC, davorpa requested changes

2021-10-30 09:33 UTC, davorpa commented on books/free-programming-books-langs.md
> +* [Obey the Testing Goat!](https://www.obeythetestinggoat.com/pages/book.html) - Harry Percival (HTML, PDF, Exercises sources)
Removing patch to complete https://github.com/EbookFoundation/free-programming-books/pull/6496#discussion_r739629120 suggestion
```suggestion
```

2021-10-30 18:36 UTC, davorpa commented on books/free-programming-books-langs.md
> -* [Test-Driven Web Development with Python](http://www.obeythetestinggoat.com/pages/book.html) - Harry Percival (3.3 - 3.x)
Not resolved yet https://github.com/EbookFoundation/free-programming-books/pull/6496/files#r739629120

2021-10-30 18:37 UTC, davorpa requested changes

2021-10-30 18:37 UTC, davorpa commented on books/free-programming-books-langs.md
> -* [Test-Driven Web Development with Python](http://www.obeythetestinggoat.com/pages/book.html) - Harry Percival (3.3 - 3.x)
https://github.com/EbookFoundation/free-programming-books/pull/6496/files#r739629120

2021-10-30 18:38 UTC, davorpa commented on books/free-programming-books-langs.md
> -* [Test-Driven Web Development with Python](http://www.obeythetestinggoat.com/pages/book.html) - Harry Percival (3.3 - 3.x)
Not resolved yet https://github.com/EbookFoundation/free-programming-books/pull/6496#discussion_r739629120

2021-10-31 13:37 UTC, davorpa requested changes
**PLEASE! Apply following patches as-is**

It will resolve all your summited dups PRs.

2021-10-31 13:37 UTC, davorpa commented on books/free-programming-books-langs.md
> +* [Learn Enough Git to Be Dangerous](https://www.learnenough.com/git-tutorial/getting_started) - Michael Hartl(HTML, PDF, Exercises sources)
Only free 38%...

Apply following delete patch here:
```suggestion
```

2021-10-31 13:37 UTC, davorpa commented on books/free-programming-books-langs.md
>  * [Supporting Python 3: An In-Depth Guide](http://python3porting.com) (2.6 - 2.x & 3.1 - 3.x)
**PLEASE! Apply following patch as-is** to recover deleted resource at next line (L1940)
```suggestion
* [Supporting Python 3: An In-Depth Guide](http://python3porting.com) (2.6 - 2.x & 3.1 - 3.x)
* [Test-Driven Web Development with Python: Obey the Testing Goat! using Django, Selenium and Javascript](http://www.obeythetestinggoat.com/pages/book.html) - Harry J.W. Percival (HTML) *(3.3 - 3.x)*
```
It also resolve ALL previous suggestions proposed before about it: `Test-Driven Web Development with Python: Obey the Testing Goat! using Django, Selenium and Javascript`

2021-10-31 13:55 UTC, vineetsingh0809 commented
Hey @davorpa, Firstly, thanks a lot for this kind of help that you did and guided me in the right way. Thank you so much.
BTW I made the changes you told me to do...So please check it again and merge it if this PR is eligible for merge...

2021-10-31 13:57 UTC, vineetsingh0809 commented
And please review this PR as well ...... #6547
please.....please

2021-10-31 17:10 UTC, davorpa approved these changes

2021-10-31 17:58 UTC, merged