Add Course Playlists to free-courses-hi.md
EbookFoundation/free-programming-books pull request #6502
Opened 2021-10-29 10:37 UTC by MalevolentStrix

## What does this PR do?
Add 17 courses to the Hindi Courses section for C++, DevOps, Java, ReactJS, PHP as well as Django
Also added extra information to an ambiguous set of two courses in which one is a playlist and another is not

## For resources
### Description

### Why is this valuable (or not)?

This will help beginners to find useful and relevant courses for learning these languages in one place instead of going through all the trash.

### How do we know it's really free?

All of them are youtube playlists which are obviously free and also even I have followed some of these tutorials.

## Checklist:
- [X] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [X] Search for duplicates.
- [X] Include author(s) and platform where appropriate.
- [X] Put lists in alphabetical order, correct spacing.
- [X] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2021-10-29 18:03 UTC, eshellman requested changes
please double check each item. Thanks!

2021-10-29 18:03 UTC, eshellman commented on courses/free-courses-hi.md
> +* [React JS Tutorial in Hindi | React JS for Beginner to Advanced | Step by Step Video Tutorials](https://www.youtube.com/playlist?list=PLjVLYmrlmjGdnIQKgnTeR1T9-1ltJEaJh) - WsCubeTech
escape the |s

2021-10-30 01:06 UTC, davorpa commented on courses/free-courses-hi.md
> +* [React JS Tutorial in Hindi | React JS for Beginner to Advanced | Step by Step Video Tutorials](https://www.youtube.com/playlist?list=PLjVLYmrlmjGdnIQKgnTeR1T9-1ltJEaJh) - WsCubeTech
```suggestion
* [React JS Tutorial in Hindi \| React JS for Beginner to Advanced \| Step by Step Video Tutorials](https://www.youtube.com/playlist?list=PLjVLYmrlmjGdnIQKgnTeR1T9-1ltJEaJh) - WsCubeTech
```

2021-10-30 01:09 UTC, davorpa commented on courses/free-courses-hi.md
> +* [React Js Tutorials in Hindi(Playlist)](https://youtube.com/playlist?list=PLu0W_9lII9agx66oZnT6IyhcMIbUMNMdt) - Haris Ali Khan, CodeWithHarry
```suggestion
* [React Js Tutorials in Hindi](https://youtube.com/playlist?list=PLu0W_9lII9agx66oZnT6IyhcMIbUMNMdt) - Haris Ali Khan, CodeWithHarry
```

2021-10-30 01:10 UTC, davorpa commented on courses/free-courses-hi.md
> +* [Java Programming Tutorial(HINDI/URUDU)](https://www.youtube.com/playlist?list=PLiOa6ike4WAHljIOitb3vR0nXQgneUedR) - Vikas Pandey, Easytuts4you
```suggestion
* [Java Programming Tutorial (HINDI/URDU)](https://www.youtube.com/playlist?list=PLiOa6ike4WAHljIOitb3vR0nXQgneUedR) - Vikas Pandey, Easytuts4you
```

2021-10-30 01:46 UTC, davorpa requested changes
Maybe some resource needs to be reordered after.

No squash is needed while PR is iterated

2021-10-30 01:46 UTC, davorpa commented on courses/free-courses-hi.md
> +* [C++ Programming in Hindi](https://www.youtube.com/playlist?list=PLbGui_ZYuhijXuOfBSdQgK296Y7wUDWLn) - Geeky Shows
Add real instructor name

```suggestion
* [C++ Programming in Hindi](https://www.youtube.com/playlist?list=PLbGui_ZYuhijXuOfBSdQgK296Y7wUDWLn) - Rajesh Kumar, Geeky Shows
```

2021-10-30 01:46 UTC, davorpa commented on courses/free-courses-hi.md
> +* [C++ Tutorial for Beginners | C++ Tutorials In Hindi](https://www.youtube.com/playlist?list=PLmGElG-9wxc8VMy1nNHDQldH2dU8Y08s7) - Manish Gehlot, WsCube Tech Programming Concepts
Escape pipes

```suggestion
* [C++ Tutorial for Beginners \| C++ Tutorials In Hindi](https://www.youtube.com/playlist?list=PLmGElG-9wxc8VMy1nNHDQldH2dU8Y08s7) - Manish Gehlot, WsCube Tech Programming Concepts
```

2021-10-30 01:46 UTC, davorpa commented on courses/free-courses-hi.md
> +* [DevOps Tutorials in Hindi/Urdu | Complete Devops including Git,Jenkins,Maven,Chef,docker,Ansible and Kubernetes](https://www.youtube.com/playlist?list=PLBGx66SQNZ8aPsFDwb79JrS2KQBTIZo10) - Bhupind
Complete title + escape pipes

```suggestion
* [DevOps Tutorials in Hindi/Urdu \| Devops सीखने का सबसे आसान तरीका \| Complete Devops including Git,Jenkins,Maven,Chef,docker,Ansible and Kubernetes](https://www.youtube.com/playlist?list=PLBGx66SQNZ8aPsFDwb79JrS2KQBTIZo10) - Bhupinder Rajput, Technical Guftgu
```

2021-10-30 01:46 UTC, davorpa commented on courses/free-courses-hi.md
> +* [Core Java Programming (Hindi)](https://www.youtube.com/playlist?list=PLbGui_ZYuhij8Oplrvjt_RlDliZQgdxoV) - Geeky Shows
Add real instructor name

```suggestion
* [Core Java Programming (Hindi)](https://www.youtube.com/playlist?list=PLbGui_ZYuhij8Oplrvjt_RlDliZQgdxoV) - Rajesh Kumar, Geeky Shows
```

2021-10-30 01:46 UTC, davorpa commented on courses/free-courses-hi.md
> +* [React JS(Hindi)](https://www.youtube.com/playlist?list=PLbGui_ZYuhignjLLXTJWkRJKN-SgAqClL) - Geeky Shows
Complete with instructor real name + exact title name

```suggestion
* [React JS (Hindi)](https://www.youtube.com/playlist?list=PLbGui_ZYuhignjLLXTJWkRJKN-SgAqClL) - Rajesh Kumar, Geeky Shows
```

2021-10-30 01:46 UTC, davorpa commented on courses/free-courses-hi.md
> +* [Core PHP(Hindi)](https://www.youtube.com/playlist?list=PLbGui_ZYuhigFdLdbSI2EM2MrJB7I0j-B) - Geeky Shows
Complete with instructor real name + exact title

```suggestion
* [Core PHP (Hindi)](https://www.youtube.com/playlist?list=PLbGui_ZYuhigFdLdbSI2EM2MrJB7I0j-B) - Rajesh Kumar, Geeky Shows
```

2021-10-30 01:46 UTC, davorpa commented on courses/free-courses-hi.md
> +* [PHP Tutorial in Hindi/Urudu](https://www.youtube.com/playlist?list=PL0b6OzIxLPbyrzCMJOFzLnf_-_5E_dkzs) - Yahoo Baba
Fix title typos

```suggestion
* [PHP Tutorial in Hindi / Urdu](https://www.youtube.com/playlist?list=PL0b6OzIxLPbyrzCMJOFzLnf_-_5E_dkzs) - Yahoo Baba
```

2021-10-30 01:46 UTC, davorpa commented on courses/free-courses-hi.md
> +* [Django(Hindi)](https://www.youtube.com/playlist?list=PLbGui_ZYuhigchy8DTw4pX4duTTpvqlh6) - GeekyShows
Complete with instructor real name + exact title

```suggestion
* [Django(Hindi)](https://www.youtube.com/playlist?list=PLbGui_ZYuhigchy8DTw4pX4duTTpvqlh6) - Rajesh Kumar, GeekyShows
```

2021-10-30 17:40 UTC, MalevolentStrix commented
I have applied the changes as mentioned in the review :slightly_smiling_face:

2021-10-30 20:42 UTC, davorpa approved these changes
Well done. It's enough to me. Let's wait for Eric decision

2021-10-30 21:14 UTC, MalevolentStrix commented
> Well done. It's enough to me. Let's wait for Eric decision

Sure, Thank you for spending time to review my PR

2021-10-31 15:36 UTC, MalevolentStrix commented
Hacktoberfest is going to end in about 3 hours according my country's time  :cry:. 
I don't know whether it is following the local time or not.
Can I get the label for now? I will make any changes to the pr if it is required.

2021-10-31 18:25 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2021-10-31 18:25 UTC, merged