Update in online compiler
EbookFoundation/free-programming-books pull request #6533
Opened 2021-10-30 15:13 UTC by veerbhadrasolanki

Add Compiler in Java and C section

## What does this PR do?
Add resources in compilers.

## For resources
### Description
Update compiler in java and c.

### Why is this valuable (or not)?
Because this provide us neat and clean in environment to do code.

### How do we know it's really free?
I was using this from last 2 year of my college and I never paid.

### For book lists, is it a book? For course lists, is it a course? etc.
No, it is not a book.

## Checklist:
- [x ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [ x] Search for duplicates.
- [ x] Include author(s) and platform where appropriate.
- [ x] Put lists in alphabetical order, correct spacing.
- [ x] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2021-10-30 23:59 UTC, davorpa requested changes

2021-10-30 23:59 UTC, davorpa commented on more/free-programming-playgrounds.md
> +* [Jdoodle](https://www.jdoodle.com/online-java-compiler/)
```suggestion
* [JDoodle - Online Java Compiler IDE](https://www.jdoodle.com/online-java-compiler/)
* [JDoodle - Online Java Compiler Advanced IDE](https://www.jdoodle.com/online-java-compiler-ide/)
* [Programiz - Online Java Compiler](https://www.programiz.com/java-programming/online-compiler/)
```

2021-10-30 23:59 UTC, davorpa commented on more/free-programming-playgrounds.md
> +* [Programiz - C Compiler](https://www.programiz.com/c-programming/online-compiler/)
```suggestion
* [JDoodle - Online C Compiler IDE](https://www.jdoodle.com/c-online-compiler/)
* [Programiz - Online C Compiler](https://www.programiz.com/c-programming/online-compiler/)
```

2021-10-31 00:01 UTC, davorpa requested changes
Restore removed lines to fix linter faults

2021-10-31 00:01 UTC, davorpa commented on more/free-programming-playgrounds.md
```suggestion


```

2021-10-31 00:01 UTC, davorpa commented on more/free-programming-playgrounds.md
```suggestion


```

2021-10-31 19:35 UTC, davorpa requested changes
Swap Java lines 138-139 to solve remaining linter faults: alphabetize list have to be ensured

2021-11-01 05:33 UTC, veerbhadrasolanki reviewed
Please Review

2021-11-01 11:00 UTC, davorpa approved these changes

2021-11-01 13:00 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2021-11-01 13:00 UTC, merged