Add course to courses\free-courses-en.md
EbookFoundation/free-programming-books pull request #6540
Opened 2021-10-30 19:52 UTC by cireneirbo

## What does this PR do?
Add resource to courses

## For resources
### Description
A free, non-profit bootcamp's curriculum for learning web development.

### Why is this valuable (or not)?
It teaches a variety of skills, has many projects to work on, and can help bring a beginner up to a level where they can look for a job as a web developer.

### How do we know it's really free?
It has a creative commons license (https://education.launchcode.org/intro-to-professional-web-dev/appendices/about-this-book.html)

### For book lists, is it a book? For course lists, is it a course? etc.
It is a course, as there is a significant number of assignments and free resources available to learn through.

## Checklist:
- [X] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [X] Search for duplicates.
- [X] Include author(s) and platform where appropriate.
- [X] Put lists in alphabetical order, correct spacing.
- [X] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2021-10-31 00:58 UTC, davorpa commented
**TIP :rocket::** Thanks for taking your time on fill Pull Request fields in your first contribution :heart: 

It's always a good practice which it use to increase the mantainers productivity.

2021-10-31 01:06 UTC, davorpa requested changes
Both are books

2021-11-03 23:38 UTC, cireneirbo commented
I'll make some changes! To me it was a course, but you're right - definitely books

2021-11-04 01:22 UTC, cireneirbo commented
whoops! I need to delete the courses! One sec and I'll resend

2021-11-04 02:57 UTC, eshellman commented
I looked a bit closer at these and noticed that many of the chapters include videos. So maybe "course" is a better category. (@cireneirbo sorry to not look more closely sooner; now that Hacktoberfest is over we have more time for thoughtful consideration.) We weight you opinion highly - compare these resources to others in books and in courses.

2021-11-04 13:06 UTC, davorpa commented on books/free-programming-books-langs.md
> +* [Java Web Development](https://education.launchcode.org/java-web-development/) - Chris Bay, Jim Flores, Carly Langlois, Sally Steuterman (The LaunchCode Foundation)
As Eric says... 

Although most is text and is called itself "book", it has some videos that cant' replace text. E.g:

https://education.launchcode.org/java-web-development/chapters/orm-part1/background.html

2021-11-04 13:13 UTC, davorpa commented on books/free-programming-books-langs.md
> +* [Introduction to Professional Web Development in JavaScript](https://education.launchcode.org/intro-to-professional-web-dev/) - Chris Bay, Jim Flores, Blake Mills, Sally Steuterman, Paul Matthews,
More or less the same... It has some non-printable content like gif / animations. E.g:

https://education.launchcode.org/intro-to-professional-web-dev/chapters/angular-lsn3/studio.html

So.. you are right at first time.

2021-11-04 22:03 UTC, davorpa approved these changes
LGTM :+1:. Thanks for the effort

2021-11-04 22:03 UTC, davorpa commented on books/free-programming-books-langs.md
> +* [Introduction to Professional Web Development in JavaScript](https://education.launchcode.org/intro-to-professional-web-dev/) - Chris Bay, Jim Flores, Blake Mills, Sally Steuterman, Paul Matthews,
Resolved in https://github.com/EbookFoundation/free-programming-books/pull/6540/commits/106eb8583651375a54400e43261e4d2930b5d4df

2021-11-04 22:03 UTC, davorpa commented on books/free-programming-books-langs.md
> +* [Java Web Development](https://education.launchcode.org/java-web-development/) - Chris Bay, Jim Flores, Carly Langlois, Sally Steuterman (The LaunchCode Foundation)
Resolved in https://github.com/EbookFoundation/free-programming-books/pull/6540/commits/106eb8583651375a54400e43261e4d2930b5d4df

2021-11-05 19:26 UTC, eshellman commented
Thanks, and welcome to free-programming-books! And thanks for tolerating the back and forth, it's essential for developing consensus.

2021-11-05 19:26 UTC, merged