Add "Hard Rock CoffeeScript"
EbookFoundation/free-programming-books pull request #6543
Opened 2021-10-31 01:15 UTC by chauxvive

Added "Hard Rock CoffeeScript" and link

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [ ] Search for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2021-10-31 04:27 UTC, davorpa requested changes

2021-10-31 04:27 UTC, davorpa commented on books/free-programming-books-langs.md
>  * [The Little Book on CoffeeScript](http://arcturo.github.io/library/coffeescript/)
```suggestion
* [The Little Book on CoffeeScript](http://arcturo.github.io/library/coffeescript/) - Alex Chaplinsky (gitbook)
```

2021-10-31 04:30 UTC, davorpa commented
It's nice see welcome back!! #2480

2021-10-31 21:05 UTC, davorpa requested changes
Sorry for the mistake in latest review. https://github.com/EbookFoundation/free-programming-books/pull/6543#commitcomment-59012610

2021-10-31 21:05 UTC, davorpa commented on books/free-programming-books-langs.md
> +* [The Little Book on CoffeeScript](http://arcturo.github.io/library/coffeescript/) - Alex Chaplinsky (gitbook)
Sorry for the mistake in latest review.

Revert or complete with real authors:

 ```suggestion
* [The Little Book on CoffeeScript](http://arcturo.github.io/library/coffeescript/) - Alex MacCaw, David Griffiths, Satoshi Murakami, Jeremy Ashkenas
```

2021-10-31 21:31 UTC, davorpa approved these changes

2021-11-01 01:15 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2021-11-01 01:15 UTC, merged