move the translated documentation files to a docs folder
EbookFoundation/free-programming-books pull request #6614
Opened 2021-11-16 21:32 UTC by eshellman

- add translation section in Readme
- replace multilinks with a  single link to translation section

Will the (../filename) syntax work?

2021-11-17 22:17 UTC, davorpa commented
> Will the (../filename) syntax work?

It should!

Maybe needs some checks after merge:
- Insights -> Community: have a green status
- start a navigation from assistive links provided by github (eg in issues or PR).

2021-11-18 00:16 UTC, davorpa requested changes
A bit hard due to file amount.

I hope works well. Take a look how GH render md of each file after apply changes.

2021-11-18 00:16 UTC, davorpa commented on docs/HOWTO-ko.md
> +*[다른언어](../README.md#translations))
complete cursive, remove extra parenthesis

```suggestion
*[다른언어](../README.md#translations)*
```

2021-11-18 00:16 UTC, davorpa commented on docs/HOWTO-pl.md
> +*[Przeczytaj to w innych językach([translations](../README.md#translations)*
Unfinished copy/paste :thinking:?

```suggestion
*[Przeczytaj to w innych językach](../README.md#translations)*
```

2021-11-18 00:16 UTC, davorpa commented on docs/HOWTO-th.md
> +*[อ่านไฟล์นี้ในภาษาอื่น([translations](../README.md#translations)*
```suggestion
*[อ่านไฟล์นี้ในภาษาอื่น](../README.md#translations)*
```

2021-11-18 02:48 UTC, eshellman commented
Awesome proofreading, @davorpa

2021-11-18 11:53 UTC, davorpa commented
> Awesome proofreading, @davorpa

Reviewing is one of my specialties. I suppouse you are in the middle of changes but there are still 29 suggestions (collapsed in web UI) to be applied :wink:

2021-11-18 19:16 UTC, eshellman commented
I think I got them all now

2021-11-18 20:12 UTC, davorpa commented on README.md
> + - [How-to](docs/HOWTO-ar.md)
Resolved in f93e0bfc99895e4f1d817aaed414fa74dc0f44f3

2021-11-18 20:13 UTC, davorpa commented on README.md
> +- Chinese / 繁體中文]
Resolved in 8cae2e9d01eccedc548d3dc183a802bce3e3eb2d

2021-11-18 20:14 UTC, davorpa commented on README.md
> +  - [Code of Conduct](docs/CODE_OF_CONDUCT.md)
Resolved in c8f566b574a54e3eef5f1b41ac0bc34505d82f04

2021-11-18 20:14 UTC, davorpa commented on README.md
> +  - [Code of Conduct](docs/CODE_OF_CONDUCT-fil.md)
Resolved in 79cc4e769ab4ce5eeefd391de0842301e65e15c7

2021-11-18 20:15 UTC, davorpa commented on README.md
> +  - [Code of Conduct](docs/CODE_OF_CONDUCT-id.md)
Resolved in 889fafc1290ce60e58dfe704afd69b80e146dd4f

2021-11-18 20:16 UTC, davorpa commented on docs/HOWTO-fa_IR.md
> +</div> ([translations](../README.md#translations))
Resolved in b62712331fc7b9632487c369a4bd20d92b7cfd31

2021-11-18 20:17 UTC, davorpa commented on docs/HOWTO-hi.md
> +अंत में, यदि आप सुनिश्चित नहीं हैं कि जिस संसाधन को आप जोड़ना चाहते हैं, वह फ्री-प्रोग्रामिंग-बुक्स के लिए उपयुक्त है,[CONTRIBUTING](CONTRIBUTING.md). में दिशानिर्देशों के माध्यम से पढ़ें। ([translat
Resolved in d952df69245aa9c517eb6857466bb109af78ccfb

2021-11-18 20:17 UTC, davorpa commented on docs/HOWTO-ko.md
> +*[다른언어](../README.md#translations))
Resolved in 56932381b0718971d5c910b1a13640f6e62621b6

2021-11-18 20:18 UTC, davorpa commented on docs/HOWTO-pl.md
> +*[Przeczytaj to w innych językach([translations](../README.md#translations)*
Resolved in 9771350928c524a115877d3421d486a6090ebddc

2021-11-18 20:19 UTC, davorpa commented on docs/HOWTO-th.md
> +*[อ่านไฟล์นี้ในภาษาอื่น([translations](../README.md#translations)*
Resolved in 425c18e7eef03c9cc13eaee11780c6ed16d85e6e

2021-11-18 20:22 UTC, davorpa commented on README.md
> +  - [Code of Conduct](docs/CODE_OF_CONDUCT-uk.md)
Resolved in 28af70feee994686d582e7542e2e8fe7bbfb139d

2021-11-18 20:23 UTC, davorpa commented on README.md
> +  - [Code of Conduct](docs/CODE_OF_CONDUCT-hi.md)
Resolved in 7a1cd600a8e23407c71ecfdf4a73c2f952b221cb

2021-11-18 20:23 UTC, davorpa commented on README.md
> +  - [How-To](docs/HOWTO.md)
Resolved in d42fe57043b6282d19248d6025ac7cd500025a4a

2021-11-18 20:24 UTC, davorpa commented on docs/CONTRIBUTING-ru.md
> +*[Доступно на других языках: ](../README.md#translations)*
Resolved in 89d918ed0955e468e86611272a663429bdd19fb1

2021-11-18 20:26 UTC, davorpa commented on README.md
> +Please read [CONTRIBUTING](docs/CONTRIBUTING.md) . If you're new to GitHub, [welcome](docs/HOWTO.md)! Please abide by our [Code of Conduct](docs/CODE_OF_CONDUCT.md). ([translations](#translations))
Resolved in b5ae663bcac51164644bfe0dd6dfb98921940e42

2021-11-18 20:28 UTC, davorpa commented on docs/CODE_OF_CONDUCT-es.md
> +[Translations](../README.md#translations)
Resolved in 349631e25fb5a9c53ada650579d3faf076e8a20a

2021-11-18 20:31 UTC, davorpa commented on docs/CODE_OF_CONDUCT-fil.md
> +
Solved in 8cb1fb7f6dcefb48f54c0887334182aaf4c7e5f6

2021-11-18 20:32 UTC, davorpa commented on docs/CODE_OF_CONDUCT-fr.md
> +
Solved in 9360b2f6d9df6c7c8aa043f9a2a56d236093ce3b

2021-11-18 20:32 UTC, davorpa commented on docs/CONTRIBUTING-de.md
> +*[Diese Anleitung in anderen Sprachen](../README.md#translations))*
Solved in e2eb43cabc8ef9d4bd42ae8ddfefc710cd579c19

2021-11-18 20:33 UTC, davorpa commented on docs/CONTRIBUTING-de.md
> +Durch Deine Mitwirkung verpflichtest Du Dich, dem [Verhaltenskodex](../CODE_OF_CONDUCT-de.md) dieses Repositorys zu folgen. ([translations](../README.md#translations))
Solved in 3647b3663b467fbcc91f6b806908d1ffa1d0bfdc

2021-11-18 20:33 UTC, davorpa commented on docs/CONTRIBUTING-el.md
> +Συνεισφέροντας συμφωνείτε να σέβεστε τον [Κώδικα Δεοντολογίας](../CODE_OF_CONDUCT-el.md) αυτού του αποθετηρίου.
Solved in 702c8852b38d96c352e67a3dedf66eb5e95479d9

2021-11-18 21:00 UTC, davorpa commented on docs/CONTRIBUTING-fa_IR.md
> +*[این متن را در زبان‌های دیگر بخوانید](../README.md#translations)*
Resolved in dd25f9d47d24432cd42051d65f0544fba672cfe8

2021-11-18 21:03 UTC, davorpa commented on docs/CONTRIBUTING-fa_IR.md
> +مشارکت در این پروژه به معنی موافقت با احترام به [مرام‌نامه‌ی](../CODE_OF_CONDUCT-fa_IR.md) این مخزن است. ([translations](../README.md#translations))
Resolved in 1b463fb2af4ee18ef2b7ceb96209275a3563b2d0

2021-11-18 21:03 UTC, davorpa commented on docs/CONTRIBUTING-fil.md
> +Sa pamamagitan ng pag-aambag sumasang-ayon kang igalang ang [Code of Conduct](../CODE_OF_CONDUCT-fil.md) ng repositoryong ito. ([translations](../README.md#translations))
Resolved in cfedb7d3dd3067bdf94aeb76cffcce312c818a02

2021-11-18 21:07 UTC, davorpa commented on docs/CONTRIBUTING-es.md
> +Al contribuir, acepta respetar el [Código de Conducta][CODE_OF_CONDUCT-es.md] presente en el repositorio. ([translations](../README.md#translations))
Partial resolved at 0716e98856e46bd8a51bfbcbe9e2ceaa004a2998

2021-11-18 21:12 UTC, davorpa commented on docs/CONTRIBUTING-ko.md
> +이 리포지토리 기여함으로서, 모든 기여자는 이 [행동강령](../CODE_OF_CONDUCT-ko.md) 에 동의한 것으로 간주됩니다. ([translations](../README.md#translations))
Resolved in 351eeb87d82f05d3c74d565ebc457e806b446e0b

2021-11-18 21:14 UTC, davorpa commented on docs/CONTRIBUTING-id.md
> +Dengan partisipasi Anda, Anda berjanji untuk mengikuti [Kode Etik](../CODE_OF_CONDUCT-id.md) dari repositori ini. ([translations](../README.md#translations))
Resolved at 7c30f610d6a197dec6a3d30dafb76679a9438146

2021-11-18 21:34 UTC, davorpa commented on docs/CONTRIBUTING-es.md
> +Al contribuir, acepta respetar el [Código de Conducta][CODE_OF_CONDUCT-es.md] presente en el repositorio. ([translations](../README.md#translations))
Resolved definitely at c2d033666d5d929ba0d124f80e19805e1727cc51

2021-11-18 22:32 UTC, davorpa reviewed
From the previous review: **pending issues related with links**

2021-11-18 22:32 UTC, davorpa commented on docs/CONTRIBUTING-it.md
> +I collaboratori accettano di rispettare il [Codice di Comportamento](../CODE_OF_CONDUCT-it.md) di questa repository. ([translations](../README.md#translations))
Still broken. https://github.com/EbookFoundation/free-programming-books/pull/6614#discussion_r751716155 not applied yet

2021-11-18 22:32 UTC, davorpa commented on docs/CONTRIBUTING-pt_BR.md
> +Ao contribuir você concorda em respeitar o [Código de Conduta](../CODE_OF_CONDUCT-pt_BR.md) deste repositório. ([translations](../README.md#translations))
Still broken. https://github.com/EbookFoundation/free-programming-books/pull/6614#discussion_r751718020 not applied yet

2021-11-18 22:32 UTC, davorpa commented on docs/CONTRIBUTING-zh.md
> +请同意并遵循此[行为准则](../CODE_OF_CONDUCT.md)参与贡献。([translations](../README.md#translations))
Still broken. https://github.com/EbookFoundation/free-programming-books/pull/6614#discussion_r751720384 not applied yet

2021-11-18 22:32 UTC, davorpa commented on docs/CONTRIBUTING-zh_TW.md
> +請同意並遵循此 [行為準則](../CODE_OF_CONDUCT.md) 參與貢獻。([translations](../README.md#translations))
Still broken. https://github.com/EbookFoundation/free-programming-books/pull/6614#discussion_r751722654 not applied yet

2021-11-18 22:32 UTC, davorpa commented on docs/CONTRIBUTING.md
> +By contributing you agree to respect the [Code of Conduct](https://github.com/EbookFoundation/free-programming-books/blob/master/CODE_OF_CONDUCT.md) of this repository. ] ([translations](../README.md
Still broken. [#6614 (comment)](https://github.com/EbookFoundation/free-programming-books/pull/6614#discussion_r751724533) not applied yet

2021-11-18 22:47 UTC, davorpa reviewed
From the first review: **pending typos** & **translate "`translations`"**

2021-11-18 22:47 UTC, davorpa commented on docs/CONTRIBUTING-pt_BR.md
> +*[Leia em outros idiomas: ](../README.md#translations)*
Pending to aply: https://github.com/EbookFoundation/free-programming-books/pull/6614/files#r751717367

2021-11-18 22:47 UTC, davorpa commented on docs/CONTRIBUTING-vi.md
> +*[Đọc bằng ngôn ngữ khác: ](../README.md#translations)*
Pending to apply: https://github.com/EbookFoundation/free-programming-books/pull/6614/files#r751719308

2021-11-18 22:47 UTC, davorpa commented on docs/CONTRIBUTING-zh.md
> +*[阅读本文的其他语言版本：](../README.md#translations)**
Pending to apply: https://github.com/EbookFoundation/free-programming-books/pull/6614/files#r751720008

2021-11-18 22:47 UTC, davorpa commented on docs/CONTRIBUTING-zh_TW.md
> +*[閱讀其他語言版本的文件：](../README.md#translations)*
Pending to apply: https://github.com/EbookFoundation/free-programming-books/pull/6614/files#r751721054

2021-11-18 22:47 UTC, davorpa commented on docs/HOWTO-bn.md
> +*[অন্য ভাষায় এটা পড়ুন ](../README.md#translations)*
Pending to apply: https://github.com/EbookFoundation/free-programming-books/pull/6614/files#r751726672

2021-11-18 22:47 UTC, davorpa commented on docs/HOWTO-es.md
> +Por último, si no está del todo seguro de si el recurso que desea agregar es apropiado para *Free-Programming-Books*, lea detenidamente las pautas que puede encontrar en [CONTRIBUTING](CONTRIBUTING-e
Pending translatation using: https://github.com/EbookFoundation/free-programming-books/pull/6614/files#r751731693

2021-11-19 17:59 UTC, eshellman commented
I think that's all...

2021-11-20 00:08 UTC, davorpa approved these changes
LGTM too :+1:

2021-11-20 18:25 UTC, merged

2021-11-20 18:42 UTC, davorpa commented
> > Will the (../filename) syntax work?
> 
> It should!
> 
> Maybe needs some checks after merge:
> 
> * Insights -> Community: have a green status
> * start a navigation from assistive links provided by github (eg in issues or PR):
>   `Remember, contributions to this repository should follow its **contributing guidelines** and **code of conduct**.`
>   ![image](https://user-images.githubusercontent.com/3125580/142410107-553a6efe-d66c-4592-8edd-d81e6266bd6b.png)
> * Try links `(../README.md#translations)` from rendered Github Pages. Maybe would be better  `(../#translations)` as target, or make a README.md in `docs` too moving section added in root

**ALL RIGHT** :rocket: