Fixed Markdown In Bangla Books List
EbookFoundation/free-programming-books pull request #6621
Opened 2021-11-19 04:34 UTC by HridoyHazard

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [ ] Search for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2021-11-19 13:23 UTC, davorpa commented
Thanks for helping to address with #4579

2021-11-19 13:34 UTC, davorpa commented on books/free-programming-books-bn.md
> +### C++
See how it's addresed in other files to be synced with index entry: https://github.com/EbookFoundation/free-programming-books/pull/6621/files#R8

```markdown
* <a href="#cpp">C++</a>
```

Headings with only one letter and symbols makes some problem with rendering bugs across GitHub auto ToC, GMF markdown preview and the HTML rendered by GitHub pages.

```markdown
### <a name="cpp"></a>C++
```

2021-11-19 15:10 UTC, HridoyHazard commented
check now fixed according to your idea @davorpa

2021-11-19 23:47 UTC, davorpa commented on books/free-programming-books-bn.md
> +### C++
Now link doesn't work.

Needs change `href="cpp"` too to have a working Index-To-Section linking.

Check it clicking in `C++` Index item.

2021-11-19 23:49 UTC, davorpa requested changes
Not resolved yet

2021-11-20 11:30 UTC, davorpa commented on books/free-programming-books-bn.md
> +### <a href="#cpp"></a>C++
Sorry if I explain wrong. It was well with `name`

```suggestion
### <a name="#cpp"></a>C++
```

2021-11-20 18:28 UTC, davorpa commented on books/free-programming-books-bn.md
> +### <a name="#cpp"></a>C++
Sorry, I fail in suggestion :worried:. Anchors haven't hash

```suggestion
### <a name="cpp"></a>C++
```

2021-11-20 18:30 UTC, davorpa approved these changes

2021-11-21 15:49 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2021-11-21 15:49 UTC, merged