Update .Net Url
EbookFoundation/free-programming-books pull request #6673
Opened 2022-01-15 14:45 UTC by MahmoudHamdy00

As the previose was 404 not found

## What does this PR do?
Add resource(s) or just correct it for the same resource

## For resources
### Description
 it's the same resource used for C# and it was already added but the url is wrong

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md)
- [ ] Search for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-01-15 15:00 UTC, LuigiImVector reviewed
I think that this resource should be moved to the C# category on the file [`free-programming-books-langs.md`](https://github.com/EbookFoundation/free-programming-books/blob/main/books/free-programming-books-langs.md)

2022-01-15 15:03 UTC, MahmoudHamdy00 commented
@LuigiImVector it already exists in C# category but on the same file

2022-01-15 17:03 UTC, LuigiImVector commented
We are waiting for a response from some other staffer to figure out what to do. If you need to move it to the other file you also delete the link in the C# category of this file.

2022-01-15 18:40 UTC, davorpa commented
@LuigiImVector comparing with archived version but it carry on having a handbook and interactive content so... I think leave it in the courses file. Moreover, the matrix `Epicodus` is like a learning platform.

LATEST BROKEN BACKUP: https://web.archive.org/web/20190115121159/https://www.learnhowtoprogram.com/net

I agree with move it to `C#` section and if this is the last remove `.NET` section and also from index

2022-01-15 21:30 UTC, eshellman commented
This might be a good place to use the crosslink syntax #5535 that lets us remove the dead link and leave the heading.

2022-01-15 21:48 UTC, davorpa commented
> This might be a good place to use the crosslink syntax #5535 that lets us remove the dead link and leave the heading.

Nice good point. Preparing suggestion :wink:

2022-01-15 21:59 UTC, davorpa requested changes

2022-01-15 21:59 UTC, davorpa commented on courses/free-courses-en.md
```suggestion
### .NET

> :information_source: See also &#8230; [C#](#c-sharp)

```

It lefts moving record to `C Sharp` section (line 237) and adding below it heading...

```md
### C Sharp

> :information_source: See also &#8230; [.NET](#net)


````

Empty lines of above template are important

2022-01-16 15:18 UTC, eshellman commented
Sorry if we were not clear; since it's a duplicate, the link to the course should be removed, and replaced with the crosslink to c#. Alternatively, if the course is more a .net course than a c# course, and use the updated link in .net and remove it from c# (adding a crosslink to c#)

2022-01-16 18:22 UTC, davorpa commented on courses/free-courses-en.md
@MahmoudHamdy00 not resolved yet

Crosslinks goes before lists (see for example Angular and Angular JS)

2022-01-16 18:32 UTC, davorpa requested changes

2022-01-16 18:32 UTC, davorpa commented on courses/free-courses-en.md
> +* [Learn how to program: C# and .NET](https://www.learnhowtoprogram.com/c-and-net) - Epicodus Inc.
Removing duplicated link as Eric tell us

```suggestion
```

Is already present in C# section

2022-01-17 11:22 UTC, davorpa commented on courses/free-courses-en.md
> +* [Learn how to program: C# and .NET](https://www.learnhowtoprogram.com/c-and-net) - Epicodus Inc.
Resolved by commit: [`b106347` (#6673)](https://github.com/EbookFoundation/free-programming-books/pull/6673/commits/b106347269925bfe72e559be653461e20b4ef1b8)

2022-01-17 11:24 UTC, davorpa commented on courses/free-courses-en.md
Resolved by commit: [`b106347` (#6673)](https://github.com/EbookFoundation/free-programming-books/pull/6673/commits/b106347269925bfe72e559be653461e20b4ef1b8)

2022-01-17 11:25 UTC, davorpa approved these changes
LGTM :wink:

2022-01-17 14:25 UTC, merged