Add Italian Spring Framework video course
EbookFoundation/free-programming-books pull request #6738
Opened 2022-02-27 14:50 UTC by mcicolella

## What does this PR do?
Add resource

## For resources
### Description
Italian video course about Java Spring Framework
### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [X ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md)
- [X ] Search for duplicates.
- [X ] Include author(s) and platform where appropriate.
- [X ] Put lists in alphabetical order, correct spacing.
- [X ] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-02-27 16:58 UTC, davorpa requested changes

2022-02-27 16:58 UTC, davorpa commented on courses/free-courses-it.md
> +* [Corso di Java Spring Framework](https://www.youtube.com/playlist?list=PLCbSCJEIR6CqgCLyVzqp49xOm8A5YDTKA) (M. Cicolella)
Use right resources format for courses: `TITLE - INSTRUCTOR LIST (Platform) *(Notes)*`

```suggestion
* [Corso di Java Spring Framework](https://www.youtube.com/playlist?list=PLCbSCJEIR6CqgCLyVzqp49xOm8A5YDTKA) - Mauro Cicolella
```

2022-02-27 19:45 UTC, davorpa approved these changes

2022-02-27 22:18 UTC, blaisy commented
Grazie per l'aggiornamento, penso che vue.js sia l'opzione migliore per il
nostro caso d'uso. Aspetto aggiornamenti, buona serata e buona
continuazione in ufficio.


-Elia, team reparto informatico Nascè Logistik

Il giorno dom 27 feb 2022 alle ore 16:00 Mauro Cicolella <
***@***.***> ha scritto:

> What does this PR do?
>
> Add resource
> For resources Description
>
> Italian video course about Java Spring Framework
> Why is this valuable (or not)? How do we know it's really free? For book
> lists, is it a book? For course lists, is it a course? etc. Checklist:
>
>    - [X ] Read our contributing guidelines
>    <https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md>
>    - [X ] Search for duplicates.
>    - [X ] Include author(s) and platform where appropriate.
>    - [X ] Put lists in alphabetical order, correct spacing.
>    - [X ] Add needed indications (PDF, access notes, under construction)
>
> Follow-up
>
>    - Check the status of GitHub Actions and resolve any reported warnings!
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/EbookFoundation/free-programming-books/pull/6738
> Commit Summary
>
>    - 5cca5f3
>    <https://github.com/EbookFoundation/free-programming-books/pull/6738/commits/5cca5f3f10f5e52d72dbe17ff1d19501cc306b5c>
>    Add Italian Spring Framework course
>
> File Changes
>
> (1 file
> <https://github.com/EbookFoundation/free-programming-books/pull/6738/files>
> )
>
>    - *M* courses/free-courses-it.md
>    <https://github.com/EbookFoundation/free-programming-books/pull/6738/files#diff-be578aa72c3f526943a1043438748ea968b31af27235163a6ba9142565e56d20>
>    (1)
>
> Patch Links:
>
>    -
>    https://github.com/EbookFoundation/free-programming-books/pull/6738.patch
>    -
>    https://github.com/EbookFoundation/free-programming-books/pull/6738.diff
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/EbookFoundation/free-programming-books/pull/6738>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOOFB4OWYYTYTFGXABCLCTLU5I4ABANCNFSM5PPBEI4A>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-02-28 16:13 UTC, eshellman commented
Thank you Mauro!

2022-02-28 16:14 UTC, merged