Add Arduino books in pt-BR
EbookFoundation/free-programming-books pull request #6749
Opened 2022-03-05 19:59 UTC by Samuel-de-Oliveira

I saw it's was missing books about Arduino in Brazilian Portuguese language, so i decided to add them.

2022-03-06 12:46 UTC, LuigiImVector commented on books/free-programming-books-pt_BR.md
```suggestion


### Arduino

* [Apostilas da Eltrogate](https://www.eletrogate.com/pagina/apostilas.html) - Eletrogate (No site é possivel escolher entre 9 apostilas diferentes dependendo do seu nível, e será pedido seu email para a obtenção do documento, todas elas são em formato PDF)
* [Arduino Guia Iniciante](https://edisciplinas.usp.br/pluginfile.php/3252633/mod_resource/content/1/Guia_Arduino_Iniciante_Multilogica_Shop.pdf) - Multilógica Shop (PDF)
* [Física com Arduino para iniciantes](https://www.scielo.br/j/rbef/a/rrPFbrjsDdtkKKRPDPTJXnn/?format=pdf&lang=pt) - Marisa Almeida Cavalcante, Cristiane Rodrigues Caetano Tavolaro, Elio Molisani (PDF)


```

You didn't respect the [formatting guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md#formatting), two blank lines were missed.

Next time fill in the default PR template.

2022-03-08 13:55 UTC, eshellman commented on books/free-programming-books-pt_BR.md
> +* [30 Projetos com Arduino](https://www.academia.edu/36112333/30_Projetos_com_Arduino_pdf) - Simon Monk (É necessario uma conta na Academia.edu para baixar o PDF)
We will accept links to Academia.edu only if they have been posted there by the author. So we won't link to this one.

2022-03-08 21:20 UTC, Samuel-de-Oliveira commented
I don't found the original source of the book, so I decided to remove.

P. S.  the first commit I understood wrong, so I fixed it.

2022-03-08 22:49 UTC, eshellman requested changes
When submitting a PR, please answer the questions in the form!

2022-03-08 22:49 UTC, eshellman commented on books/free-programming-books-pt_BR.md
> +* [Física com Arduino para iniciantes](https://www.scielo.br/j/rbef/a/rrPFbrjsDdtkKKRPDPTJXnn/?format=pdf&lang=pt) - Marisa Almeida Cavalcante, Cristiane Rodrigues Caetano Tavolaro, Elio Molisani (PD
This is a 9 page article published in i journal. It's not a book.

2022-03-09 07:20 UTC, davorpa approved these changes
LGTM. Thanks for changes

2022-03-09 13:21 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2022-03-09 13:21 UTC, merged