Adding a free complete course in Arabic
EbookFoundation/free-programming-books pull request #6752
Opened 2022-03-06 20:04 UTC by ezz444

this course is totally free, detailed up to 55 hours

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md)
- [ ] Search for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-03-07 08:53 UTC, davorpa approved these changes

2022-03-07 08:53 UTC, davorpa commented on books/free-programming-books-ar.md
> +*  [AWS] (#aws)
```suggestion
* [AWS] (#aws)
```

And needs moving to line 6 to preserve alphabetization

2022-03-07 08:53 UTC, davorpa commented on books/free-programming-books-ar.md
> +* [كورس كامل بالعربى مع المهندس عيسى أبوشريف] (https://www.youtube.com/playlist?list=PLOoZRfEtk6kWSM_l9xMjDh-_MJXl03-pf)
Categories have headings of 3th level, and 2 blank line before and 1 after. See more reasons at linter task logs or CONTRIBUTING guidelines.

```suggestion

### AWS

* [كورس كامل بالعربى مع المهندس عيسى أبوشريف] (https://www.youtube.com/playlist?list=PLOoZRfEtk6kWSM_l9xMjDh-_MJXl03-pf)
```

Alphabetize again moving to line 34 more or less

2022-03-07 08:53 UTC, davorpa commented on books/free-programming-books-ar.md
> +* [كورس كامل بالعربى مع المهندس عيسى أبوشريف] (https://www.youtube.com/playlist?list=PLOoZRfEtk6kWSM_l9xMjDh-_MJXl03-pf)
Categories have headings of 3th level, and 1 blank line after. See more reasons at linter task logs or CONTRIBUTING guidelines.

```suggestion

### AWS

* [كورس كامل بالعربى مع المهندس عيسى أبوشريف] (https://www.youtube.com/playlist?list=PLOoZRfEtk6kWSM_l9xMjDh-_MJXl03-pf)
```

Alphabetize again moving to line 34 more or less

2022-03-07 12:45 UTC, davorpa requested changes
It's a good moment to apply some changes. When done, request for a review again using GitHub :arrows_clockwise: button. Meanwhile, draft status can be used to work on it if you want.

2022-03-28 22:30 UTC, CleanMachine1 commented
Considering that @ezz444 closed the PR originally I think its most likely a good idea to finish this PR making the relevant suggestions or to close it.

2022-03-29 06:14 UTC, davorpa requested changes
Remove extra spaces between title and link markdown markup

2022-03-29 06:14 UTC, davorpa commented on books/free-programming-books-ar.md
> +* [AWS] (#aws)
```suggestion
* [AWS](#aws)
```

2022-03-29 06:14 UTC, davorpa commented on books/free-programming-books-ar.md
> +* [كورس كامل بالعربى مع المهندس عيسى أبوشريف] (https://www.youtube.com/playlist?list=PLOoZRfEtk6kWSM_l9xMjDh-_MJXl03-pf)
```suggestion
* [كورس كامل بالعربى مع المهندس عيسى أبوشريف](https://www.youtube.com/playlist?list=PLOoZRfEtk6kWSM_l9xMjDh-_MJXl03-pf)
```

2022-03-29 06:18 UTC, davorpa commented on books/free-programming-books-ar.md
> +* [كورس كامل بالعربى مع المهندس عيسى أبوشريف](https://www.youtube.com/playlist?list=PLOoZRfEtk6kWSM_l9xMjDh-_MJXl03-pf)
Add instructor / course platform

```suggestion
* [كورس كامل بالعربى مع المهندس عيسى أبوشريف](https://www.youtube.com/playlist?list=PLOoZRfEtk6kWSM_l9xMjDh-_MJXl03-pf) - AWS Riyadh User Group
```

2022-03-29 06:25 UTC, davorpa requested changes
Alphabetize attempt 1

2022-03-29 06:25 UTC, davorpa commented on books/free-programming-books-ar.md
> +* [كورس كامل بالعربى مع المهندس عيسى أبوشريف](https://www.youtube.com/playlist?list=PLOoZRfEtk6kWSM_l9xMjDh-_MJXl03-pf) - AWS Riyadh User Group
```suggestion
```

2022-03-29 06:25 UTC, davorpa commented on books/free-programming-books-ar.md
```suggestion

### AWS

* [كورس كامل بالعربى مع المهندس عيسى أبوشريف](https://www.youtube.com/playlist?list=PLOoZRfEtk6kWSM_l9xMjDh-_MJXl03-pf) - AWS Riyadh User Group
```

2022-03-29 06:25 UTC, davorpa commented on books/free-programming-books-ar.md
> +* [AWS](#aws)
```suggestion
* [AWS](#aws)
* [SQL](#sql)
  * [PostgreSQL](#postgresql)
* [UI/UX](#uiux)
```

2022-03-29 06:29 UTC, davorpa requested changes
🚧  Alphabetize attemp 2

2022-03-29 06:29 UTC, davorpa commented on books/free-programming-books-ar.md
>  * [احترف الأردوينو](https://www.ev-center.com/uploads/2/1/2/6/21261678/arduino.pdf) - Working Group (PDF)
```suggestion
### Arduino

* [احترف الأردوينو](https://www.ev-center.com/uploads/2/1/2/6/21261678/arduino.pdf) - Working Group (PDF)


### AWS

* [كورس كامل بالعربى مع المهندس عيسى أبوشريف](https://www.youtube.com/playlist?list=PLOoZRfEtk6kWSM_l9xMjDh-_MJXl03-pf) - AWS Riyadh User Group
```

2022-03-29 06:29 UTC, davorpa commented on books/free-programming-books-ar.md
> +* [AWS](#aws)
```suggestion
* [AWS](#aws)
* [Ruby](#ruby)
* [Security](#security)
* [SEO](#seo)
```

2022-03-29 06:34 UTC, davorpa requested changes
:construction: Alphabetize attempt 3

2022-03-29 06:34 UTC, davorpa commented on books/free-programming-books-ar.md
Moving below Arduino resources

```suggestion
* [اردوينو ببساطة](https://simplyarduino.com/%D9%83%D8%AA%D8%A7%D8%A8-%D8%A7%D8%B1%D8%AF%D9%88%D9%8A%D9%86%D9%88-%D8%A8%D8%A8%D8%B3%D8%A7%D8%B7%D8%A9/) - عبدالله علي عبدالله, Abdallah Ali Abdallah Elmasry (PDF)
* [AVR ببساطة: من تشغيل دايود ضوئي إلى أنظمة الوقت الحقيقي](https://github.com/abdallah-ali-abdallah/Simply-AVR-Book) - عبدالله علي عبدالله, Abdallah Ali Abdallah Elmasry (ODT, PDF)


### AWS

* [كورس كامل بالعربى مع المهندس عيسى أبوشريف](https://www.youtube.com/playlist?list=PLOoZRfEtk6kWSM_l9xMjDh-_MJXl03-pf) - AWS Riyadh User Group

```

2022-03-29 06:34 UTC, davorpa commented on books/free-programming-books-ar.md
> +* [AWS](#aws)
Moving near to Arduino...

```suggestion
* [AWS](#aws)
* [Programming in Scratch](#programming-in-scratch)
* [Python](#python)
* [Raspberry Pi](#raspberry-pi)
```

2022-03-29 06:36 UTC, davorpa commented on books/free-programming-books-ar.md
> +* [AWS](#aws)
```suggestion
* [AWS](#aws)
* [Operating System](#operating-systems)
* [PHP](#php)
  * [Symfony](#symfony)
```

2022-03-29 06:37 UTC, davorpa commented on books/free-programming-books-ar.md
> +* [AWS](#aws)
```suggestion
* [AWS](#aws)
* [JavaScript](#javascript)
* [Linux](#linux)
* [Open Source Software](#open-source-software)
```

2022-03-29 06:37 UTC, davorpa commented on books/free-programming-books-ar.md
> +* [AWS](#aws)
```suggestion
* [AWS](#aws)
* [C#&lrm;](#csharp)
* [HTML/CSS](#htmlcss)
* [Introduction to Programming in Arabic](#introduction-to-programming-in-arabic)
```

2022-03-29 06:39 UTC, davorpa commented on books/free-programming-books-ar.md
>  * [مدخل إلى الذكاء الاصطناعي وتعلم الآلة](https://academy.hsoub.com/files/17-%D9%85%D8%AF%D8%AE%D9%84-%D8%A5%D9%84%D9%89-%D8%A7%D9%84%D8%B0%D9%83%D8%A7%D8%A1-%D8%A7%D9%84%D8%A7%D8%B5%D8%B7%D9%86%D8%A
```suggestion
### Artificial Intelligence

* [مدخل إلى الذكاء الاصطناعي وتعلم الآلة](https://academy.hsoub.com/files/17-%D9%85%D8%AF%D8%AE%D9%84-%D8%A5%D9%84%D9%89-%D8%A7%D9%84%D8%B0%D9%83%D8%A7%D8%A1-%D8%A7%D9%84%D8%A7%D8%B5%D8%B7%D9%86%D8%A7%D8%B9%D9%8A-%D9%88%D8%AA%D8%B9%D9%84%D9%85-%D8%A7%D9%84%D8%A2%D9%84%D8%A9/) - Mohamed Lahlah (PDF)


### AWS

* [كورس كامل بالعربى مع المهندس عيسى أبوشريف](https://www.youtube.com/playlist?list=PLOoZRfEtk6kWSM_l9xMjDh-_MJXl03-pf) - AWS Riyadh User Group
```

2022-03-29 06:41 UTC, davorpa approved these changes

2022-03-29 06:46 UTC, davorpa commented
> Considering that @ezz444 closed the PR originally I think its most likely a good idea to finish this PR making the relevant suggestions or to close it.

Done @CleanMachine1!!

I suppose that seeing at a glance the PR was linter faults, he/she closes it. It's a normal situation for newbies working with GitHub. I only recover it because is a interesant resource and with it we fill step by step this listing with few items

Could you review again?

2022-03-30 22:37 UTC, CleanMachine1 approved these changes

2022-03-31 11:02 UTC, davorpa commented on books/free-programming-books-ar.md
> +* [كورس كامل بالعربى مع المهندس عيسى أبوشريف](https://www.youtube.com/playlist?list=PLOoZRfEtk6kWSM_l9xMjDh-_MJXl03-pf) - AWS Riyadh User Group
Add course instructor seen at first video and delegate current metadata as platform

```suggestion
* [كورس كامل بالعربى مع المهندس عيسى أبوشريف](https://www.youtube.com/playlist?list=PLOoZRfEtk6kWSM_l9xMjDh-_MJXl03-pf) - Eissa AbuSherif (AWS Riyadh User Group)
```

2022-03-31 14:09 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

It's usually not helpful to add a category for a single resource. But I'm going to merge this, because the category headings for this list need some work, perhaps translating to arabic. Would welcome help from interested arabic users.

2022-03-31 14:09 UTC, merged

2022-08-05 21:34 UTC, AhmedElTabarani commented
@davorpa, @eshellman  this is a course, not a book
We should move it to courses folder

2022-08-05 21:53 UTC, davorpa commented
> @davorpa, @eshellman this is a course, not a book We should move it to courses folder

Go ahead then!