Add Quantum Computing
EbookFoundation/free-programming-books pull request #6767
Opened 2022-03-11 17:14 UTC by iremddemir

## What does this PR do?
Create a subject and add resource(s) for Quantum Computing

## For resources
### Description
Free Quantum Computing books are added
### Why is this valuable (or not)?
QC is an important area of interest in computer science
### How do we know it's really free?
Published as open access or free book
### For book lists, is it a book? For course lists, is it a course? etc.
yes
## Checklist:
- [+ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md)
- [ +] Search for duplicates.
- [+ ] Include author(s) and platform where appropriate.
- [+ ] Put lists in alphabetical order, correct spacing.
- [+] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-03-11 18:19 UTC, davorpa requested changes
Complete some info is required. Apply suggestions as is :wink:

2022-03-11 18:19 UTC, davorpa commented on books/free-programming-books-subjects.md
> +* [Quantum Computing for the Quantum Curious](https://link.springer.com/content/pdf/10.1007%2F978-3-030-61601-4.pdf) - C Hughes,J Isaacson, A Perry, R F. Sun, J Turner (PDF)
Fit with CC license

```suggestion
* [Quantum Computing for the Quantum Curious](https://link.springer.com/content/pdf/10.1007%2F978-3-030-61601-4.pdf) - Ciaran Hughes, Joshua Isaacson, Anastasia Perry, Ranbel F. Sun, Jessica Turner (PDF)
```

2022-03-11 18:19 UTC, davorpa commented on books/free-programming-books-subjects.md
> +* [Learn Quantum Computation using Qiskit](https://qiskit.org/textbook/preface.html)
Add contact name as author. More contributors at https://qiskit.org/textbook/preface.html#Contributors

```suggestion
* [Learn Quantum Computation using Qiskit](https://qiskit.org/textbook/preface.html) - Frank Harkins et al. (HTML)
```

2022-03-11 18:33 UTC, iremddemir commented
I have made the changes. Thank you for suggestions!

2022-03-11 20:22 UTC, davorpa approved these changes

2022-03-14 14:48 UTC, eshellman requested changes
Excellent additions!

2022-03-16 17:12 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2022-03-16 17:12 UTC, merged