Update free-courses-en.md
EbookFoundation/free-programming-books pull request #6778
Opened 2022-03-15 08:46 UTC by chalakjeevan

Angular 5 course added

## What does this PR do?
Add resource(s) 

## For resources
### Description
Angular 5 course 
### Why is this valuable (or not)?
Free course from Udemi
### How do we know it's really free?
From udemi description
### For book lists, is it a book? For course lists, is it a course? etc.
course
## Checklist:
- [☑] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md)
- [☑] Search for duplicates.
- [☑] Include author(s) and platform where appropriate.
- [☑] Put lists in alphabetical order, correct spacing.
- [☑] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-03-15 14:09 UTC, davorpa requested changes
Alphabetize to solve linter faults and fix Udemy typo

2022-03-15 14:09 UTC, davorpa commented on courses/free-courses-en.md
> +* [Introduction to Assembly Programming with ARM](https://www.udemy.com/course/introduction-to-assembly-programming-with-arm/) - Scott Cosetino (Udemi)
```suggestion
* [Introduction to Assembly Programming with ARM](https://www.udemy.com/course/introduction-to-assembly-programming-with-arm/) - Scott Cosetino (Udemy)
* [Introduction To Reverse Engineering Software](http://opensecuritytraining.info/IntroductionToReverseEngineering.html) - Matt Briggs (OpenSecurityTraining)
* [Introductory Intel x86: Architecture, Assembly, Applications, & Alliteration](http://opensecuritytraining.info/IntroX86.html) - Xeno Kovah (OpenSecurityTraining)
```

2022-03-16 19:39 UTC, davorpa approved these changes

2022-03-16 19:41 UTC, davorpa requested changes
There are an Instructor name typo

2022-03-16 19:41 UTC, davorpa commented on courses/free-courses-en.md
> +* [Introduction to Assembly Programming with ARM](https://www.udemy.com/course/introduction-to-assembly-programming-with-arm/) - Scott Cosetino (Udemy)
```suggestion
* [Introduction to Assembly Programming with ARM](https://www.udemy.com/course/introduction-to-assembly-programming-with-arm/) - Scott Cosentino (Udemy)
```

2022-03-16 19:42 UTC, davorpa approved these changes

2022-03-16 19:46 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2022-03-16 19:46 UTC, merged