New Additions to This List
EbookFoundation/free-programming-books pull request #6814
Opened 2022-04-04 06:19 UTC by letscode-17

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md)
- [ ] Search for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-04-04 13:28 UTC, eshellman commented
Be sure to check the free-programming-books-lint output for linter errors. Alphabetical order and spacing are the most common problems.

2022-04-05 11:41 UTC, davorpa requested changes
As Eric says... needs list alphabetization. Here some of suggestions to be applied

2022-04-05 11:41 UTC, davorpa commented on more/free-programming-playgrounds.md
> +* [InterviewBit - Online C Compiler](https://www.interviewbit.com/online-c-compiler/)
```suggestion
* [InterviewBit - Online C Compiler](https://www.interviewbit.com/online-c-compiler/)
* [JDoodle - Online C Compiler IDE](https://www.jdoodle.com/c-online-compiler/)
* [Programiz - Online C Compiler](https://www.programiz.com/c-programming/online-compiler/)
* [SoloLearn](https://code.sololearn.com/c)
```

2022-04-05 11:41 UTC, davorpa commented on more/free-programming-playgrounds.md
> +* [InterviewBit - Online C++ Compiler](https://www.interviewbit.com/online-cpp-compiler/)
```suggestion
* [InterviewBit - Online C++ Compiler](https://www.interviewbit.com/online-cpp-compiler/)
* [LabStack](https://code.labstack.com/cpp)
* [OnlineGDB](https://www.onlinegdb.com/online_c++_compiler)
* [SoloLearn](https://code.sololearn.com/cpp)
```

2022-04-05 11:41 UTC, davorpa commented on more/free-programming-playgrounds.md
> +* [InterviewBit - Online Java Compiler](https://www.interviewbit.com/online-java-compiler/)
```suggestion
* [InterviewBit - Online Java Compiler](https://www.interviewbit.com/online-java-compiler/)
* [Programiz - Online Java Compiler](https://www.programiz.com/java-programming/online-compiler/)
* [repl.it](https://repl.it) (_including a separate Java/Swing_)
* [SoloLearn](https://code.sololearn.com/java)
```

2022-04-05 11:41 UTC, davorpa commented on more/free-programming-playgrounds.md
> +* [InterviewBit - Online JavaScript Compiler]([InterviewBit - Online Java Compiler](https://www.interviewbit.com/online-java-compiler/))
Fix Markdown syntax and alphabetize list a bit transfering up

```suggestion
* [InterviewBit - Online JavaScript Compiler](https://www.interviewbit.com/online-java-compiler/)
* [JSFiddle](https://jsfiddle.net)
* [Plunker](https://plnkr.co)
* [SoloLearn](https://code.sololearn.com/web#javascript)
```

2022-04-05 11:41 UTC, davorpa commented on more/free-programming-playgrounds.md
> +* [InterviewBit - Online Python Compiler](https://www.interviewbit.com/online-python-compiler/)
```suggestion
* [InterviewBit - Online Python Compiler](https://www.interviewbit.com/online-python-compiler/)
* [Repl.it - NiceDualPoint](https://repl.it/repls/NiceDualPoint#main.py)
* [SoloLearn](https://code.sololearn.com/python)
* [Try Python](https://trypython.jcubic.pl) - Jakub T. Jankiewicz
```

2022-04-05 14:48 UTC, letscode-17 commented
Hey, Thanks for response. Have created another pull-request basis on the changes suggested.

2022-04-05 15:54 UTC, davorpa commented
Work has been continued at #6817

2022-04-05 15:54 UTC, closed without merging