config: add Visual Studio Code config compatible with fpb-lint
EbookFoundation/free-programming-books pull request #6829
Opened 2022-04-15 19:33 UTC by davorpa

## What does this PR do?
Improve repo

## For resources
### Description

In the past, somebody had used VisualStudioCode to edit files with the bad lucky that this project doesn't have config compatible with fpb-lint. Moreover, people usually have installed markdownlint or markdown all-in-one to speed up somethings like TOC index or other stuff

### Why is this valuable (or not)?

This PR adds the config necessary to minimize this kind of issues again. The config is parametrized (there where could be applied) according to remark config selected to free-programming-books-lint project

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md)
- [ ] Search for duplicates.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-04-18 16:49 UTC, eshellman commented
yes, need someone with expertise to review

2022-04-18 16:49 UTC, eshellman commented
yes, need someone with expertise to review

2023-08-06 19:13 UTC, GH05T-HUNTER5 commented
@davorpa 
do you remember me 😅

2023-08-06 19:19 UTC, GH05T-HUNTER5 requested changes
{
  "default": false,
  "MD001": true,
  "MD002": {
    "level": 1
  },
  "MD003": {
    "style": "atx"
  },
  "MD004": {
    "style": "asterisk"
  },
  "MD005": true,
  "MD006": true,
  "MD007": {
    "indent": 4,
    "start_indented": false
  },
  "MD009": {
    "br_spaces": 4,
    "list_item_empty_lines": false,
    "strict": false
  },
  "MD010": {
    "code_blocks": true,
    "spaces_per_tab": 4
  },
  "MD011": true,
  "MD012": {
    "maximum": 2
  },
  "MD014": true,
  "MD018": true,
  "MD019": true,
  "MD020": true,
  "MD021": true,
  "MD022": {
    "lines_above": 2,
    "lines_below": 1
  },
  "MD023": true,
  "MD024": {
    "allow_different_nesting": false,
    "siblings_only": false
  },
  "MD025": {
    "level": 1,
    "front_matter_title": "^\\s*title\\s*[:=]"
  },
  "MD026": {
    "punctuation": ".,;:!。，；：！"
  },
  "MD027": true,
  "MD028": true,
  "MD029": {
    "style": "one_or_ordered"
  },
  "MD030": {
    "ul_single": 1,
    "ol_single": 1,
    "ul_multi": 1,
    "ol_multi": 1
  },
  "MD031": {
    "list_items": true
  },
  "MD032": true,
  "MD033": {
    "allowed_elements": [
      "a",
      "abbr",
      "div",
      "span",
      "details",
      "summary"
    ]
  },
  "MD037": true,
  "MD038": true,
  "MD039": true,
  "MD040": true,
  "MD041": {
    "level": 1,
    "front_matter_title": "^\\s*title\\s*[:=]"
  },
  "MD042": true,
  "MD043": {
    "headings": null,
    "headers": null
  },
  "MD044": {
    "names": [
      ".github",
      ".gitlab",
      ".markdown",
      ".mega",
      ".html",
      ".css",
      ".sass",
      ".html",
      ".json",
      ".yaml",
      "align=",
      "dir=",
      "markdown=",
      "próximo",
      "GitHub",
      "GitLab",
      "BitBucket",
      "Pull Request",
      "PRÓXIMO",
      "PR",
      "Google",
      "Google Drive",
      "YouTube",
      "Dropbox",
      "Mega",
      "Scribd",
      "Issuu",
      "Leanpub",
      "StackOverflow",
      "Markdown",
      "HTML",
      "CSS",
      "SASS",
      "JavaScript",
      "JSON",
      "YAML"
    ],
    "code_blocks": true
  },
  "MD046": {
    "style": "fenced"
  },
  "MD047": true,
  "MD048": {
    "style": "backtick"
  }
}

2023-11-03 02:44 UTC, Thenlie commented
I haven't noticed any issues using VS Code. Maybe this is no longer relevant?

2025-05-21 00:17 UTC, closed without merging