Update free-courses-en.md
EbookFoundation/free-programming-books pull request #6863
Opened 2022-06-08 10:07 UTC by Aqilzeka

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md)
- [ ] Search for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-06-08 10:09 UTC, Aqilzeka commented
Add Docker list two resource

2022-06-08 12:15 UTC, eshellman commented
For youtube, we prefer "playlist" links and the name of the producer/creator. https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md#platforms-and-access-notes

Pleas close the other PR

2022-06-09 06:19 UTC, davorpa requested changes

2022-06-09 06:19 UTC, davorpa commented on courses/free-courses-en.md
> +* [Docker Tutorial for Beginners | Full Course [2021]](https://www.youtube.com/watch?v=p28piYY_wv8) - Amigoscode
Remove video timing param from ulrs and escape pipes from titles

```suggestion
* [Docker Tutorial for Beginners [FULL COURSE in 3 Hours]](https://www.youtube.com/watch?v=3c-iBn73dDE) - TechWorld with Nana
* [Docker Tutorial for Beginners \| Full Course [2021]](https://www.youtube.com/watch?v=p28piYY_wv8) - Amigoscode
```

2022-06-09 06:21 UTC, davorpa commented
> For youtube, we prefer "playlist" links and the name of the producer/creator. [https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md#platforms-and-access-notes](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md?rgh-link-date=2022-06-08T12%3A15%3A32Z#platforms-and-access-notes)

Both are 3h lvideos with chapters integrated in timeline, so it's ok for me :wink: 

> Pleas close the other PR

PR #6862 closed as duplicated

2022-07-24 07:47 UTC, davorpa commented on courses/free-courses-en.md
> +* [Docker Tutorial for Beginners \| Full Course [2021]](https://www.youtube.com/watch?v=p28piYY_wv8) - Amigoscode
Escape markdown tokens

```suggestion
* [Docker Tutorial for Beginners \[FULL COURSE in 3 Hours\]](https://www.youtube.com/watch?v=3c-iBn73dDE) - TechWorld with Nana
* [Docker Tutorial for Beginners \| Full Course \[2021\]](https://www.youtube.com/watch?v=p28piYY_wv8) - Amigoscode
```

2022-07-24 07:50 UTC, davorpa approved these changes

2022-07-24 07:52 UTC, davorpa commented on courses/free-courses-en.md
> +* [Docker Tutorial for Beginners | Full Course [2021]](https://www.youtube.com/watch?v=p28piYY_wv8) - Amigoscode
Resolved by commit 8908450b2aadef2af88b881f2ed5d3578182e8c4

2022-07-25 12:39 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2022-07-25 12:39 UTC, merged