Added Tailwindcsss ,Vue and Svelte structured properly
EbookFoundation/free-programming-books pull request #6882
Opened 2022-06-19 10:06 UTC by Mdkawsarislam2002

## Added 3 Courses (locale: BN)

### Add 10 Bangla Courses | Remove   1 Book   Because that website does not exist right now

### Bangla resources 
### Description

### Add 10 Bangla Courses 

 * Vue.JS
 * Tailwindcsss 
 * Svelte 

### Why is this valuable (or not)?
 In Bengal resources, that's not enough, so I added the 2most helpful free resources And 

### How do we know it's really free?
 These resources are from YouTube for its totally free 

## Checklist:
* [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md)
* [x] Search for duplicates.
* [x] Include author(s) and platform where appropriate.
* [x] Put lists in alphabetical order, correct spacing.
* [x] Add needed indications (PDF, access notes, under construction)

## Follow-up

* Check the status of GitHub Actions and resolve any reported warnings!

2022-06-20 16:10 UTC, LuigiImVector requested changes

2022-06-20 16:10 UTC, LuigiImVector commented on courses/free-courses-bn.md
> +* [Introduction to Vue.js in Bangla বাংলা  with a full Project - Vue Crash Course](https://youtu.be/iIvN7upsLoA) - Learn with Sumit - LWS - Bangladesh
```suggestion
* [Introduction to Vue.js in Bangla বাংলা  with a full Project - Vue Crash Course](https://www.youtube.com/watch?v=iIvN7upsLoA) - Sumit Saha
```
Shortened URLs are not allowed

2022-06-20 16:10 UTC, LuigiImVector commented on courses/free-courses-bn.md
> +* [Tailwind CSS Bangla Tutorial Series](https://youtube.com/playlist?list=PLHiZ4m8vCp9P23SqlHL0QAqiwS_oCofV2) - Learn with Sumit - LWS - Bangladesh
```suggestion
* [Tailwind CSS Bangla Tutorial Series](https://youtube.com/playlist?list=PLHiZ4m8vCp9P23SqlHL0QAqiwS_oCofV2) - Sumit Saha
```

2022-06-20 19:17 UTC, eshellman commented
This is a judgment call. We could use "Learn With Sumit" or "Sumit Saha". Depends on how the creator uses the name. If for example, emails from the creator are signed "Learn with Sumit", then that's an indication of how the creator wants to be identified, especially if "Learn With Sumit" is more than just Sumit. If all the videos start with "Hello I'm Sumit Suha", then clearly the creator is "Sumit Suha". If a user needs to work to discover the "Suha" part, then "Learn with Sumit" more clearly identifies the creator for potential students. I doubt the verbose "Learn with Sumit - LWS - Bangladesh" is an appropriate thing to list as the creator. So @Mdkawsarislam2002 please consider the suggestions and use the phrase that you think best identifies the creator, and thank you for bearing with us!

2022-06-21 03:43 UTC, Mdkawsarislam2002 commented
**Thanks.** 
Now it's ok, I think?

2022-06-21 10:17 UTC, LuigiImVector commented
Checking the CONTRIBUTING file
https://github.com/EbookFoundation/free-programming-books/blob/a7558f56b8ffcd27571a8ff3fa4d6d11538a0755/docs/CONTRIBUTING.md#L163
and course listings there are no short youtube links (youtu.be)
I think it could be discussed whether to accept official short links or not.

2022-06-21 13:43 UTC, eshellman requested changes

2022-06-21 13:43 UTC, eshellman commented on courses/free-courses-bn.md
> +* [Introduction to Vue.js in Bangla বাংলা  with a full Project - Vue Crash Course](https://youtu.be/iIvN7upsLoA) - Learn with Sumit
We do NOT accept shortened links.

2022-06-21 13:43 UTC, eshellman commented on courses/free-courses-bn.md
> +* [Svelte Bangla Overview Tutorial with examples - How Svelte is different from React & others](https://youtu.be/DdFcbIsqPh8) - Learn with Sumit
We do NOT accept shortened links.

2022-06-21 18:37 UTC, eshellman requested changes

2022-06-21 18:39 UTC, Mdkawsarislam2002 commented on courses/free-courses-bn.md
> +* [Svelte Bangla Overview Tutorial with examples - How Svelte is different from React & others](https://www.youtube.com/watch?v=DdFcbIsqPh8&list=PLHiZ4m8vCp9MrJGkaQGLJHapIz5goTqgl&index=11&t=820s) -
???

2022-06-23 16:16 UTC, LuigiImVector requested changes
in the url after the question mark ? there are parameters separated by the symbol &, you have to keep only the essential parameters, in this case the ones that redirect to the video/playlist

this required @eshellman

2022-06-23 16:16 UTC, LuigiImVector commented on courses/free-courses-bn.md
> +* [Svelte 3: The Game Changer (Bangla Crash Course)](https://www.youtube.com/playlist?list=PL_XxuZqN0xVDJOOYnZxK-fbKxjxFHfc-H) - Stack Learner
```suggestion
* [Explore Programming in Bangla ( বাংলা )](https://www.youtube.com/playlist?list=PLHiZ4m8vCp9MrJGkaQGLJHapIz5goTqgl) - Learn with Sumit
* [Svelte 3: The Game Changer (Bangla Crash Course)](https://www.youtube.com/playlist?list=PL_XxuZqN0xVDJOOYnZxK-fbKxjxFHfc-H) - Stack Learner
```

2022-07-01 17:51 UTC, eshellman requested changes

2022-07-01 17:51 UTC, eshellman commented on courses/free-courses-bn.md
> +  * [Vue](#Vue)
use lower case in fragment ids

2022-07-01 17:51 UTC, eshellman commented on courses/free-courses-bn.md
> +  * [Tailwind](#Tailwind)
use lower case in fragment ids

2022-07-31 21:19 UTC, davorpa commented on courses/free-courses-bn.md
> +  * [Vue](#Vue)
```suggestion
  * [Vue](#vue)
```

2022-07-31 21:20 UTC, davorpa commented on courses/free-courses-bn.md
> +  * [Tailwind](#Tailwind)
Patch suggested by Eric

```suggestion
  * [Tailwind](#tailwind)
```

2022-08-12 15:14 UTC, davorpa commented
Conflicts are with indentation made in #6988 merge

2022-08-12 15:45 UTC, davorpa commented
Some Vue & Svelte was lost. Maybe due to some bad merge. I'll review it later as last step previous to merge this PR

2022-08-12 17:03 UTC, davorpa commented on courses/free-courses-bn.md
> +* [Introduction to Vue.js in Bangla বাংলা  with a full Project - Vue Crash Course](https://www.youtube.com/playlist?&list=PLHiZ4m8vCp9O5_QoMvQbOAOR5WolyZ4OS) - Learn with Sumit
Revert to video url, which is 1h length enough

```suggestion
* [Introduction to Vue.js in Bangla বাংলা  with a full Project - Vue Crash Course](https://www.youtube.com/watch?v=iIvN7upsLoA) - Learn with Sumit
```

2022-08-12 17:12 UTC, davorpa commented
> Some initial Vue & Svelte was lost. Maybe due to some bad merge in commits. I'll review it later as last step previous to merge this PR

This resources was removed due to haven't the minimum length of 1h

2022-08-12 17:16 UTC, davorpa approved these changes
Review chop is enough for me

2022-08-13 08:18 UTC, LuigiImVector approved these changes
LGTM

2022-08-13 16:07 UTC, merged