docs(CONTRIBUTING): Apply #6878 to the rest of the CONTRIBUTING files
EbookFoundation/free-programming-books pull request #6890
Opened 2022-06-23 16:27 UTC by LuigiImVector

## What does this PR do?
Improve repo

## For resources
### Description

Apply to the rest of the CONTRIBUTING files the changes made on #6878 about the alphabetical order.
Inspired by @davorpa (#6824).

## Checklist:
- [X] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md)
- [X] Put lists in alphabetical order, correct spacing.
- [X] Add needed indications (PDF, access notes, under construction)
- [X] Translated into English
- [X] Translated into Deutch: @lupinitylabs
- [ ] Translated into Greek
- [ ] Translated into Persian
- [ ] Translated into Filipino
- [X] Translated into French: @lorrding
- [ ] Translated into Indonesian
- [X] Translated into Italian: @LuigiImVector
- [ ] Translated into Korean
- [ ] Translated into Portuguese
- [ ] Translated into Russian
- [X] Translated into Spanish: @davorpa 
- [ ] Translated into Vietnamese
- [ ] Translated into Chinese (simplified)
- [X] Translated into Chinese (traditional): @AlanSyue

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-06-23 19:05 UTC, davorpa reviewed
I provide the Spanish translation 🎉

2022-06-24 09:42 UTC, LuigiImVector commented on docs/CONTRIBUTING-es.md
> +- No emojis.
Thanks <3

2022-06-26 10:34 UTC, LuigiImVector commented
@AlanSyue, @bluetata, @tronghieu60s, @ricardokojo, @andylang8445, @amirmojiry, @lupinitylabs, @Existential-Kernel, @kang8 sorry for the inconvenience, it would be great if you would help translate these parts of files.

2022-06-26 10:52 UTC, AlanSyue commented
@LuigiImVector 
Sure! I can help translate to traditional Chinese.

2022-06-27 18:25 UTC, amirmojiry commented
I can work on the Persian (fa_IR) translation.

2022-06-29 09:06 UTC, lorrding requested changes
Hi, I provided French translations :)
Tell me if something feels off.

2022-06-29 09:06 UTC, lorrding commented on docs/CONTRIBUTING-fr.md
> +- No emojis.
```suggestion
- N'utilisez pas d'émoticônes.
```

2022-06-29 11:17 UTC, LuigiImVector commented on docs/CONTRIBUTING-fr.md
> +
In the title insert the anchor link: `### <a id="alphabetical-order"</a> Ordre...`

2022-06-29 12:42 UTC, lorrding commented on docs/CONTRIBUTING-fr.md
> +
It's updated 👍

2022-06-29 13:07 UTC, LuigiImVector commented on docs/CONTRIBUTING-fr.md
> +
thank you for your contribution❤

2022-06-29 13:16 UTC, LuigiImVector commented
> I can work on the Persian (fa_IR) translation.

let's wait for his translation first

2022-07-13 18:12 UTC, LuigiImVector commented
No one else has replied so I think it's ready to be merged

2022-07-14 11:39 UTC, merged