add new free-programming-interactive-tutorials in ru
EbookFoundation/free-programming-books pull request #6892
Opened 2022-06-30 08:51 UTC by shapito27

add Go, Solidity, Microsoft azure tutorials in Russian language

## What does this PR do?
Add resource(s)

## For resources
free-programming-interactive-tutorials-ru
### Description
add Go, Solidity, Microsoft azure tutorials in Russian language
### Why is this valuable (or not)?
it's popular languages and technologies 
### How do we know it's really free?
it's a well know tutuorials
### For book lists, is it a book? For course lists, is it a course? etc.
it's a interactive courses
## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md)
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-06-30 15:47 UTC, eshellman requested changes

2022-06-30 15:47 UTC, eshellman commented on more/free-programming-interactive-tutorials-ru.md
>  * [Веб-разработка](#Веб-разработка)
If you look at the static version of the site (https://ebookfoundation.github.io/free-programming-books/more/free-programming-interactive-tutorials-ru.html) you'll see that the id's are all lower case; which means that the links don't work: `<h3 id="веб-разработка">Веб-разработка</h3>` Change all href fragments to lower case.

2022-06-30 15:47 UTC, eshellman commented on more/free-programming-interactive-tutorials-ru.md
>  * [Python](#Python)
lower case

2022-06-30 15:47 UTC, eshellman commented on more/free-programming-interactive-tutorials-ru.md
> +* [Solidity](#Solidity)
lower case

2022-06-30 15:47 UTC, eshellman commented on more/free-programming-interactive-tutorials-ru.md
> +* [CryptoZombies.io](https://cryptozombies.io/ru/) - Ethereum DApps
it's fine like this, but remove trailing slash

2022-06-30 15:47 UTC, eshellman commented on more/free-programming-interactive-tutorials-ru.md
> +* [Облачные вычисления](#Облачные-вычисления)
lower case

2022-06-30 15:47 UTC, eshellman commented on more/free-programming-interactive-tutorials-ru.md
>  * [SQL](#SQL)
` [SQL](#sql)`

2022-06-30 16:04 UTC, eshellman commented
This content could easily be made into a book, and I encourage you to do so! Currently it's more of a blog, which is out of scope for this list.

2022-07-04 04:38 UTC, shapito27 commented
Hi, shall I create a new pull request? It seems, that I can't add changes to the current pull request because it has closed.

2022-07-05 17:55 UTC, eshellman commented
Thanks, and welcome to free-programming-books! Sorry for the mistake in closing the PR - I had two PRs mixed up!

2022-07-05 17:55 UTC, merged