add vue.js website free lean for line 80
EbookFoundation/free-programming-books pull request #6917
Opened 2022-07-13 19:58 UTC by Amirrezaheydari81

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md)
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-07-13 20:00 UTC, Amirrezaheydari81 commented
add vue.js website free lean for line 80

2022-07-14 11:46 UTC, eshellman commented
Be sure to check the free-programming-books-lint output for linter errors. Alphabetical order and spacing are the most common problems.
I think this should go on the courses page, not the books page.
If you add a category, also add it to the index at the top of the page.

2022-07-24 08:22 UTC, davorpa commented on books/free-programming-books-fa_IR.md
Only one blank line at the end of document

```suggestion

```

2022-07-24 08:30 UTC, davorpa commented on books/free-programming-books-fa_IR.md
> +* [آموزش Vue.js از صفر تا صد با 8 درس رایگان](https://sariasan.com/featured/vue-free-full-lessons)
Solve linter faults:

```
/free-programming-books/books/free-programming-books-fa_IR.md
76:1-78:96  warning  Incorrect number of blank lines between last section and next heading  blank-lines-1-0-2  remark-lint
80:1-80:11  warning  Incorrect number of blank lines between heading and section            blank-lines-1-0-2  remark-lint

⚠ 2 warnings
```

Apply following patch :arrow_down:
```suggestion

### Vue.js

* [آموزش Vue.js از صفر تا صد با 8 درس رایگان](https://sariasan.com/featured/vue-free-full-lessons)
```

2022-07-24 08:40 UTC, davorpa requested changes
Like Eric says in https://github.com/EbookFoundation/free-programming-books/pull/6917#issuecomment-1184350008...

- [x] Linter faults was solved :rocket:
- [ ] See if this resource fits better in course listing
- [x] Adds the corresponding entry in the TOC (see at the documment beginning) also preserving the alphabetization of said section / list. **Added at 09f5ebb4a40f756341fba6105a4f7de06e9df3c0**

2022-08-12 15:51 UTC, davorpa commented
Conflicts are with #6988 which introduces some indentation at TOC section

2022-08-12 17:36 UTC, davorpa commented
> * See if this resource fits better in course listing

**NOTE** This definitely goes in courses since the resource has videos that cannot be kept as part of it printed version

2022-08-12 17:37 UTC, davorpa requested changes
> * See if this resource fits better in course listing

**NOTE** This definitely goes in `courses/free-courses-fa_IR.md` since the resource has videos that cannot be kept as part of it printed version

2022-08-12 17:40 UTC, davorpa commented on books/free-programming-books-fa_IR.md
> +* [آموزش Vue.js از صفر تا صد با 8 درس رایگان](https://sariasan.com/featured/vue-free-full-lessons)
Add resource author

```suggestion
* [آموزش Vue.js از صفر تا صد با 8 درس رایگان](https://sariasan.com/featured/vue-free-full-lessons) - میلاد حیدری
```

2022-08-25 18:05 UTC, davorpa approved these changes

2022-09-14 02:45 UTC, davorpa commented
@eshellman I move it to courses in 4f1086d09cd596fa84f0e24e9432e7fb8372f1fc so all is resolved

2022-09-14 13:25 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2022-09-14 13:25 UTC, merged