Added a useful resource
EbookFoundation/free-programming-books pull request #6959
Opened 2022-07-22 10:27 UTC by Vaishnaviamirayada

Have added a useful resource about Bootstrap from the Scaler topics in the Bootstrap section.

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md)
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-07-22 14:00 UTC, eshellman commented
Be sure to check the free-programming-books-lint output for linter errors. Alphabetical order and spacing are the most common problems. Also check your spelling.

2022-07-23 07:01 UTC, eshellman commented
Be sure to check the free-programming-books-lint output for linter errors. Alphabetical order and spacing are the most common problems.

2022-07-23 17:39 UTC, davorpa commented on more/free-programming-interactive-tutorials-en.md
> +* [Bootstrap Tutorial](https://www.scaler.com/topics/css/bootstrap/) - Scaler Topics
Alphabetize to solve lint faults

```suggestion
* [Bootstrap Tutorial](https://www.scaler.com/topics/css/bootstrap/) - Scaler Topics
* [Front End Development Libraries Certification: Bootstrap](https://www.freecodecamp.org/learn/front-end-libraries/bootstrap) - freeCodeCamp
```

2022-07-27 17:15 UTC, Vaishnaviamirayada commented
Hi @davorpa,

I have made all the changes as per the guidelines, please check.

Thank You!

2022-07-29 10:45 UTC, eshellman commented
Be sure to check the free-programming-books-lint output for linter errors. Alphabetical order and spacing are the most common problems.

2022-07-31 21:07 UTC, davorpa requested changes

2022-07-31 21:07 UTC, davorpa commented on more/free-programming-interactive-tutorials-en.md
> +* [Operating System Tutorial] (https://www.scaler.com/topics/operating-system/) - Scaler Topics
No spaces between link markup tokens

```suggestion
* [Operating System Tutorial](https://www.scaler.com/topics/operating-system/) - Scaler Topics
```

2022-07-31 21:10 UTC, davorpa reviewed
@eshellman could you recheck again?

2022-08-03 21:00 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2022-08-03 21:00 UTC, merged