Update free-courses-ml.md
EbookFoundation/free-programming-books pull request #6994
Opened 2022-08-13 03:37 UTC by GH05T-HUNTER5

Update malyalam Course

2022-08-13 03:58 UTC, GH05T-HUNTER5 commented
Malayalam New Tutorial Playlist

2022-08-13 11:33 UTC, davorpa requested changes
Nice resources but needs some fixes to adapt them as same as in other listings

2022-08-13 11:33 UTC, davorpa commented on courses/free-courses-ml.md
> +    * [NodeJS](#nodejs)
- Fix `node.js` title like in other listings
- Alphabetize sections

```suggestion
    * [Node.js](#nodejs)
    * [React](#react)
```

2022-08-13 11:33 UTC, davorpa commented on courses/free-courses-ml.md
> +### Bash/Shell
```suggestion
### Bash and Shell
```

2022-08-13 11:33 UTC, davorpa commented on courses/free-courses-ml.md
> +* [Bash/Shell](#bash)
- Expand title of `bash/shell` section and fix its fragment id to get right cross linking.

```suggestion
* [Bash and Shell](#bash-and-shell)
```

2022-08-13 11:33 UTC, davorpa commented on courses/free-courses-ml.md
> +* [HTML and CSS](html-and-css)
- Move `Bootstrap` as subsection of `HTML/CSS` (like in other listings)

```suggestion
* [C](#c)
* [C++](#cpp)
* [Data Structure](#data-structure)
* [Flutter](#flutter)
* [Git](#git)
* [HTML and CSS](html-and-css)
    * [Bootstrap](#bootstrap)
```

2022-08-13 11:33 UTC, davorpa commented on courses/free-courses-ml.md
> +
Move `Bootstrap` section to `HTML / CSS` like in other listings

```suggestion


#### Bootstrap

* [BOOTSTRAP Malayalam Tutorial](https://youtube.com/playlist?list=PL1JrLEBAapUWqs_HbcYngAOmpPbiccqNy) - Yes Tech Media

```

2022-08-13 11:33 UTC, davorpa commented on courses/free-courses-ml.md
> +### C
Move `Bootstrap` section to `HTML / CSS` like in other listings

```suggestion
### C
```

2022-08-13 11:33 UTC, davorpa commented on courses/free-courses-ml.md
> +* [Git Tutorial Malayalam | Best Malayalam Git Tutorial | Date With Git](https://youtube.com/playlist?list=PLY-ecO2csVHdLhAO6TERaMJXP8aqyWVt-) - Brototype Malayalam
- Escape pipes on Markdown (see #5176 for more info)

```suggestion
* [Git Tutorial Malayalam \| Best Malayalam Git Tutorial \| Date With Git](https://youtube.com/playlist?list=PLY-ecO2csVHdLhAO6TERaMJXP8aqyWVt-) - Brototype Malayalam
```

2022-08-13 11:33 UTC, davorpa commented on courses/free-courses-ml.md
> +#### NodeJS
- Fix `node.js` title like in other listings

```suggestion
#### Node.js
```

2022-08-13 11:33 UTC, davorpa commented on courses/free-courses-ml.md
> +* [Python Tutorial Malayalam | Best Malayalam Python Programming Tutorial](https://youtube.com/playlist?list=PLY-ecO2csVHfbpOmWamlb8Mujjdnl1jks) - Brototype Malayalam
- Escape pipes on Markdown (see #5176 for more info)

```suggestion
* [Python Tutorial Malayalam \| Best Malayalam Python Programming Tutorial](https://youtube.com/playlist?list=PLY-ecO2csVHfbpOmWamlb8Mujjdnl1jks) - Brototype Malayalam 
```

2022-08-13 11:42 UTC, davorpa approved these changes
LGTM after apply suggestions

2022-08-13 12:38 UTC, GH05T-HUNTER5 commented
> Nice resources but needs some fixes to adapt them as same as in other listings

Please Update

2022-08-13 12:45 UTC, davorpa approved these changes
Remains LGTM. Commit bca2f468692469ee0095cd7c941128e8ab299f09 doen't introduce changes

2022-08-13 12:49 UTC, davorpa commented on courses/free-courses-ml.md
> +* [HTML and CSS](html-and-css)
Fix TOC entry fragment of `HTML / CSS`

```suggestion
* [HTML and CSS](#html-and-css)
```

2022-08-13 16:55 UTC, davorpa approved these changes

2022-08-14 15:46 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2022-08-14 15:46 UTC, merged