Update free-courses-ml.md
EbookFoundation/free-programming-books pull request #7004
Opened 2022-08-15 03:30 UTC by GH05T-HUNTER5

New Update

Added React , HTML and CSS , Git

2022-08-15 04:11 UTC, davorpa requested changes
It's time to make some minor changes to follow the formatting of listing resources.

Take your time to apply the following suggestions over the same branch where this PR was opened: `patch-11`

Any other intent of submitting incremental PRs will be considered as spam.

2022-08-15 19:07 UTC, davorpa commented
https://github.com/EbookFoundation/free-programming-books/pull/7004#discussion_r945411837 suggestion is not applied yet. 

Why did you resolve the conversation? I'd unhided it again

2022-08-15 19:07 UTC, davorpa commented
https://github.com/EbookFoundation/free-programming-books/pull/7004#discussion_r945411837 suggestion is not applied yet. 

Why did you resolve the conversation? I'd unhided it again

2022-08-15 19:08 UTC, davorpa commented
https://github.com/EbookFoundation/free-programming-books/pull/7004#discussion_r945411837 suggestion is not applied yet. 

Why did you resolve the conversation? I'd unhided it again

2022-08-16 02:24 UTC, GH05T-HUNTER5 commented
> 

Sorry

2022-08-16 04:39 UTC, GH05T-HUNTER5 commented
> [#7004 (comment)](https://github.com/EbookFoundation/free-programming-books/pull/7004#discussion_r945411837) suggestion is not applied yet.
> 
> Why did you resolve the conversation? I'd unhided it again

That's my friend (sry)

2022-08-16 08:18 UTC, GH05T-HUNTER5 commented
> [#7004 (comment)](https://github.com/EbookFoundation/free-programming-books/pull/7004#discussion_r945411837) suggestion is not applied yet.
> 
> Why did you resolve the conversation? I'd unhided it again

- added

2022-08-16 10:26 UTC, merged

2022-08-16 19:26 UTC, davorpa commented on courses/free-courses-ml.md
> +* [React js malayalam tutorial](https://youtube.com/playlist?list=PL4KwFGqvN4nuKJ3bJSP-LcchabWJtPtE8) Debug Media
Fixed by commit 9cef8c2793e9cc2c97d9ab33732ca3390e2a4edd