Update free-programming-books-tr.md
EbookFoundation/free-programming-books pull request #7063
Opened 2022-09-08 10:05 UTC by emraher

r4ds cevirisi eklendi

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-09-08 12:27 UTC, eshellman commented
good addition, but be sure to check the free-programming-books-lint output for linter errors. Alphabetical order and spacing are the most common problems.

2022-09-08 17:56 UTC, davorpa requested changes
As Eric requests...

2022-09-08 17:56 UTC, davorpa commented on books/free-programming-books-tr.md
> +* [R for Data Science](http://tr.r4ds.hadley.nz/) - Garrett Grolemund, Hadley Wickham
- Alphabetize
- We love give also credits to traducers, so... add them to creators list using role anotations :wink:

```suggestion
* [R for Data Science](http://tr.r4ds.hadley.nz/) - Garrett Grolemund, Hadley Wickham, `trad.:` İsmail Bekar, `trad.:` Nurbahar Usta, `trad.:` Bilgecan Şen
* [R ile Programlamaya Giriş ve Uygulamalar (2014)](http://inet-tr.org.tr/inetconf19/sunum/16.pdf) - Mustafa Gökçe Baydoğan, Berk Orbay, Uzay Çetin (PDF)
```

2022-09-09 06:54 UTC, davorpa approved these changes
LGTM.

Well seen this ending slash :rocket: 4874524757226ed6fcd627cf43f5a470da5eb847

2022-09-09 19:27 UTC, merged