Add shell scripting tutorial
EbookFoundation/free-programming-books pull request #7125
Opened 2022-09-28 05:21 UTC by debajyotig466

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-09-28 14:08 UTC, eshellman commented
Be sure to check the free-programming-books-lint output for linter errors. Alphabetical order and spacing are the most common problems.

2022-10-01 01:59 UTC, davorpa requested changes
Not a playlist but +1h video covering a topic

2022-10-01 01:59 UTC, davorpa commented on courses/free-courses-en.md
> +
Expand urls and fix whitespaces

```suggestion
* [Shell Scripting Tutorial](https://www.youtube.com/watch?v=GtovwKDemnI) - edureka!
```

2022-10-01 02:06 UTC, davorpa approved these changes

2022-10-01 04:50 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2022-10-01 04:50 UTC, merged