adicionado curso de docker em pt-br
EbookFoundation/free-programming-books pull request #7138
Opened 2022-09-30 19:13 UTC by wilcleylacerda

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-01 01:50 UTC, davorpa requested changes

2022-10-01 01:50 UTC, davorpa commented on courses/free-courses-pt_BR.md
> +* [Curso de Docker para iniciantes - aprenda Docker em 1 hora](https://www.youtube.com/watch?v=np_vyd7QlXk) - Matheus Battisti - (YouTube)
```suggestion
* [Curso de Docker para iniciantes - aprenda Docker em 1 hora](https://www.youtube.com/watch?v=np_vyd7QlXk) - Matheus Battisti
```

2022-10-02 15:30 UTC, davorpa approved these changes

2022-10-02 20:05 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2022-10-02 20:05 UTC, merged