Update free-courses-hi.md
EbookFoundation/free-programming-books pull request #7145
Opened 2022-09-30 20:23 UTC by decentlearner

added resource for graph playlist

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-01 02:26 UTC, davorpa requested changes

2022-10-01 02:26 UTC, davorpa commented on courses/free-courses-hi.md
> +* [Graph Playlist\| Interview Questions \| Coding \| Tutorials \| Data Structures](https://www.youtube/playlist?list=PLgUwDviBIf0oE3gA41TKO2H5bHpPd7fzn) - takeUforward
- Fixing url
- Using title as it is
- Add instructor as part of the creators

```suggestion
* [Graph Series by Striver \| C++ \| Java \| Interview Centric \| Algorithms \| Problems](https://www.youtube.com/playlist?list=PLgUwDviBIf0oE3gA41TKO2H5bHpPd7fzn) - take U forward, `tch.:` Raj Striver
```

2022-10-01 05:43 UTC, decentlearner commented
Changes made as suggested

2022-10-01 08:43 UTC, davorpa approved these changes

2022-10-01 12:09 UTC, decentlearner commented
Please accept and add label hacktoberfest-accepted if this fulfill all changes suggested.

2022-10-01 15:37 UTC, davorpa commented
> Please accept and add label hacktoberfest-accepted if this fulfill all changes suggested.

Not needed since repo is marked as hacktoberfest. Will count when merged

2022-10-01 18:27 UTC, eshellman commented
could we NOT add tch. here? it's implied by the genre, and probably confusing to most.

2022-10-02 01:08 UTC, davorpa commented on courses/free-courses-hi.md
> +* [Graph Series by Striver \| C++ \| Java \| Interview Centric \| Algorithms \| Problems](https://www.youtube.com/playlist?list=PLgUwDviBIf0oE3gA41TKO2H5bHpPd7fzn) - take U forward, `tch.:` Raj Striv
```suggestion
* [Graph Series by Striver \| C++ \| Java \| Interview Centric \| Algorithms \| Problems](https://www.youtube.com/playlist?list=PLgUwDviBIf0oE3gA41TKO2H5bHpPd7fzn) - take U forward
```

2022-10-02 20:06 UTC, merged