added mathematics and two subheadings-discreteMaths and Stats and pro…
EbookFoundation/free-programming-books pull request #7312
Opened 2022-10-02 08:39 UTC by swastikgithub09

…bability

## What does this PR do?
Add resource(s) 

## For resources
### Description
Math is an important subject for this field so i have added some basic courses in maths for the betterment of students
### Why is this valuable (or not)?

### How do we know it's really free?
free on youtube 
### For book lists, is it a book? For course lists, is it a course? etc.
courses
## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-02 20:52 UTC, eshellman commented
for 3 courses, we only need one category for Mathematics

2022-10-03 11:09 UTC, davorpa requested changes

2022-10-03 11:09 UTC, davorpa commented on courses/free-courses-hi.md
> +* [Discrete Mathematics](https://www.youtube.com/playlist?list=PLxCzCOWd7aiH2wwES9vPWsEL6ipTaUSl3) - Gate Smashers (YouTube)
Add instructors and remove non-needed YT playlist annotations

```suggestion
* [Discrete Mathematics](https://www.youtube.com/playlist?list=PLxCzCOWd7aiH2wwES9vPWsEL6ipTaUSl3) - Gate Smashers, `tch.:` Varun Singla, `tch.:` Naina Wadhwa Singla
```

2022-10-03 11:09 UTC, davorpa commented on courses/free-courses-hi.md
> +* [Discrete Mathematics (Full Course) By Dr.Gajendra Purohit](https://www.youtube.com/playlist?list=PLU6SqdYcYsfJ27O0dvuMwafS3X8CecqUg) - Gajendra Purohit (YouTube)
```suggestion
* [Discrete Mathematics (Full Course) By Dr.Gajendra Purohit](https://www.youtube.com/playlist?list=PLU6SqdYcYsfJ27O0dvuMwafS3X8CecqUg) - Gajendra Purohit
```

2022-10-03 11:09 UTC, davorpa commented on courses/free-courses-hi.md
> +* [Statistics And Probability](https://www.youtube.com/playlist?list=PLU6SqdYcYsfLRq3tu-g_hvkHDcorrtcBK) - Gajendra Purohit (YouTube)
```suggestion
* [Statistics And Probability](https://www.youtube.com/playlist?list=PLU6SqdYcYsfLRq3tu-g_hvkHDcorrtcBK) - Gajendra Purohit
```

2022-10-04 08:25 UTC, davorpa approved these changes

2022-10-04 14:51 UTC, merged