added SortingAlgos in Algorithm in free-courses-hi.md
EbookFoundation/free-programming-books pull request #7315
Opened 2022-10-02 08:53 UTC by swastikgithub09

## What does this PR do?
Add resource(s) 

## For resources
### Description
added a playlist of sorting algos under algo section
### Why is this valuable (or not)?
algo playlist by one of most popular hindi creators
### How do we know it's really free?
it was on YouTube
### For book lists, is it a book? For course lists, is it a course? etc.
t is a course
## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-02 20:56 UTC, eshellman commented
Don't invent titles! Use the title given by the resource.

2022-10-03 11:04 UTC, davorpa requested changes

2022-10-03 11:04 UTC, davorpa commented on courses/free-courses-hi.md
> +* [All Sorting algorithms and Programs](https://www.youtube.com/playlist?list=PLsFNQxKNzefK_DAUwnQwBizOmcY7aDLoY) - Saurabh Shukla (YouTube)
- YT playlists don't need annotations

```suggestion
* [All Sorting algorithms and Programs](https://www.youtube.com/playlist?list=PLsFNQxKNzefK_DAUwnQwBizOmcY7aDLoY) - Saurabh Shukla
```

2022-10-04 08:09 UTC, davorpa approved these changes

2022-10-04 14:52 UTC, merged