added DatabaseSystems in free-course-hi.nd and two courses in it
EbookFoundation/free-programming-books pull request #7318
Opened 2022-10-02 09:11 UTC by swastikgithub09

## What does this PR do?
Add resource(s) 

## For resources
### Description
one heading in index of "Database Systems" was added and two courses under it were inserted
### Why is this valuable (or not)?
one of major pillars of computer science , so students will need this very much
### How do we know it's really free?
free on youtube
### For book lists, is it a book? For course lists, is it a course? etc.
it is a course
## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-02 21:06 UTC, eshellman commented on courses/free-courses-hi.md
> +* [Database Systems](#database-systems)
Use 'database' or 'databases' to align with other lists

2022-10-03 09:36 UTC, davorpa requested changes

2022-10-03 09:36 UTC, davorpa commented on courses/free-courses-hi.md
> +* [DBMS(Database Management System)Placement Series](https://www.youtube.com/playlist?list=PLDzeHZWIZsTpukecmA2p5rhHM14bl2dHU) - CodeHelp (YouTube)
- Don't invent titles! Copy as it is
- YT playlist don't need notes
- Complete course instructors
 
```suggestion
* [DBMS (Database Management System)Complete Playlist](https://www.youtube.com/playlist?list=PLxCzCOWd7aiFAN6I8CuViBuCdJgiOkT2Y) - Gate Smashers, `tch.:` Varun Singla
* [DBMS Placements Series 2022](https://www.youtube.com/playlist?list=PLDzeHZWIZsTpukecmA2p5rhHM14bl2dHU) - CodeHelp, `tch.:` Love Babbar, `tch.:` Lakshay Kumar
```

2022-10-04 08:22 UTC, davorpa commented on courses/free-courses-hi.md
> +* [DBMS(Database Management System)Placement Series](https://www.youtube.com/playlist?list=PLDzeHZWIZsTpukecmA2p5rhHM14bl2dHU) - CodeHelp (YouTube)
Solved at 207d267d2397e99062e811126c72978b7c10016f

2022-10-04 08:22 UTC, davorpa approved these changes

2022-10-04 15:00 UTC, eshellman requested changes
sorry for the back and forth

2022-10-04 15:00 UTC, eshellman commented on courses/free-courses-hi.md
> +* [DBMS Placements Series 2022](https://www.youtube.com/playlist?list=PLDzeHZWIZsTpukecmA2p5rhHM14bl2dHU) - CodeHelp, `tch.:` Love Babbar, `tch.:` Lakshay Kumar
```suggestion
* [DBMS Placements Series 2022](https://www.youtube.com/playlist?list=PLDzeHZWIZsTpukecmA2p5rhHM14bl2dHU) - CodeHelp by Babbar
```

2022-10-05 00:49 UTC, merged