Added Free Certified Course on Game Development by Michigan State University
EbookFoundation/free-programming-books pull request #7383
Opened 2022-10-03 05:29 UTC by arushmangal

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-03 15:26 UTC, eshellman requested changes
Is this course time limited? i.e. would this need to be removed in 6 months? If so, we shouldn't add it.

2022-10-03 15:28 UTC, arushmangal commented
> Is this course time limited? i.e. would this need to be removed in 6 months? If so, we shouldn't add it.

No, it's not limited. Please do let me know what indicated the same to you incase I missed something

2022-10-04 00:33 UTC, davorpa commented on courses/free-courses-en.md
> +* [Low Poly Art For Video Games](https://www.coursera.org/learn/low-poly-art-video-games)
Adding instructors

```suggestion
* [Low Poly Art For Video Games](https://www.coursera.org/learn/low-poly-art-video-games) - Andrew Dennis, Ricardo Guimaraes (Coursera)
```

2022-10-04 02:04 UTC, arushmangal commented on courses/free-courses-en.md
> +* [Low Poly Art For Video Games](https://www.coursera.org/learn/low-poly-art-video-games)
Oops! Sorry, seems that I missed that!

2022-10-04 02:12 UTC, closed without merging

2022-10-04 07:51 UTC, davorpa commented
Duplicated of #7479

2022-10-04 07:53 UTC, davorpa commented
Duplicate of ##7478