Added two courses R PT_BR
EbookFoundation/free-programming-books pull request #7415
Opened 2022-10-03 13:28 UTC by 42kkkkkaren

Hello! I'm trying to help by adding courses that helped me!

## What does this PR do?
Add resource(s)

## For resources
### Description
Added two courses that helped me in learning R

### Why is this valuable (or not)?
I learned a lot by watching this playlists

### How do we know it's really free?
I'ts from youtube!

### For book lists, is it a book? For course lists, is it a course? etc.
It's a course!

## Checklist:
- [ x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x ] Include author(s) and platform where appropriate.
- [ x] Put lists in alphabetical order, correct spacing.
- [x ] Add needed indications (PDF, access notes, under construction).
- [ x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-04 00:18 UTC, davorpa requested changes

2022-10-04 00:18 UTC, davorpa commented on courses/free-courses-pt_BR.md
> +* [R](#R)
- URL fragments goes in lowercase

```suggestion
* [R](#r)
```

2022-10-04 00:18 UTC, davorpa commented on courses/free-courses-pt_BR.md
> +* [Curso de R para iniciantes](https://www.youtube.com/watch?v=tfPsmDzS74c&list=PLyqOvdQmGdTQ5dE6hSD7ZGBu8bud70wYf) - Didática Tech
- lint: leave 2 blank lines between listings and next heading

```suggestion

### R

* [Curso de R com R Studio](https://www.youtube.com/watch?v=2mS-SzVWPZQ&list=PLzWDDw1w8cTS4i_B49WOWtjngjcMqTruG) - Escola de Inteligência Artificial
* [Curso de R para iniciantes](https://www.youtube.com/watch?v=tfPsmDzS74c&list=PLyqOvdQmGdTQ5dE6hSD7ZGBu8bud70wYf) - Didática Tech

```

2022-10-04 00:21 UTC, davorpa commented on courses/free-courses-pt_BR.md
> +* [Curso de R com R Studio](https://www.youtube.com/watch?v=2mS-SzVWPZQ&list=PLzWDDw1w8cTS4i_B49WOWtjngjcMqTruG) - Escola de Inteligência Artificial
We prefer YT playlist URLs

```suggestion
* [Curso de R com R Studio](https://www.youtube.com/playlist?list=PLzWDDw1w8cTS4i_B49WOWtjngjcMqTruG) - Escola de Inteligência Artificial
```

2022-10-04 00:23 UTC, davorpa commented on courses/free-courses-pt_BR.md
> +* [Curso de R para iniciantes](https://www.youtube.com/watch?v=tfPsmDzS74c&list=PLyqOvdQmGdTQ5dE6hSD7ZGBu8bud70wYf) - Didática Tech
- Use titles as same as provided by original source
- We prefer YT playlist URLs

```suggestion
* [Curso R para Iniciantes](https://www.youtube.com/playlist?list=PLyqOvdQmGdTQ5dE6hSD7ZGBu8bud70wYf) - Didática Tech
```

2022-10-30 03:07 UTC, eshellman commented
Thanks, and welcome to free-programming-books! Sorry for dealy - we've had over a thousand PRs!

2022-10-30 03:07 UTC, merged