Added three Data Structure and Algorithms course in Free Courses in English
EbookFoundation/free-programming-books pull request #7457
Opened 2022-10-03 18:38 UTC by moazamdev

## What does this PR do?
This PR will add three Data Structure and Algorithms courses in Free Courses in English under Algorithms & Data Structures section

## For resources
### YouTube

### Why is this valuable (or not)?
Best quality courses provided by top YouTubers 

### How do we know it's really free?
Courses are on YouTube

### For book lists, is it a book? For course lists, is it a course? etc.
These are courses for courses list 

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-04 01:10 UTC, eshellman commented
For youtube, we prefer "playlist" links and the name of the producer/creator. https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md#platforms-and-access-notes
no shortened links

2022-10-04 07:09 UTC, moazamdev commented
Hi @eshellman, I have added video length for the Data Structures Course by Simplilearn, Also I have mentioned the creator and the source of the course.

2022-10-05 08:07 UTC, davorpa requested changes

2022-10-05 08:07 UTC, davorpa commented on courses/free-courses-en.md
> +* [Algorithms and Data Structures Tutorial - Full Course for Beginners](https://youtu.be/8hly31xKli0) - freeCodeCamp (YouTube)
Expand YT shorten urls

```suggestion
* [Algorithms and Data Structures Tutorial - Full Course for Beginners](https://www.youtube.com/watch?v=8hly31xKli0) - Pasan Premaratne, Jay McGavren (freeCodeCamp)
```

2022-10-05 08:07 UTC, davorpa commented on courses/free-courses-en.md
> +* [Data Structures and Algorithms Full Course](https://youtu.be/LcKqYoX8uH4) - Simplilearn (YouTube, Video length 7:13:56)
Expand YT shorten urls

```suggestion
* [Data Structures and Algorithms Full Course](https://www.youtube.com/watch?v=LcKqYoX8uH4) - Simplilearn (YouTube, Video length 7:13:56)
```

2022-10-05 14:33 UTC, davorpa approved these changes

2022-10-05 16:10 UTC, merged