Update free-programming-cheatsheets.md
EbookFoundation/free-programming-books pull request #7500
Opened 2022-10-04 06:38 UTC by fare4z

add others sql cheat sheet by Tomi Mester

## What does this PR do?
**Add resource(s)** | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [/ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [/ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [/ ] Include author(s) and platform where appropriate.
- [/ ] Put lists in alphabetical order, correct spacing.
- [ /] Add needed indications (PDF, access notes, under construction).
- [/ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-04 15:57 UTC, eshellman commented
corrupt markdown syntax. also, one link per resource

2022-10-05 07:02 UTC, fare4z commented
already update the link and md.

2022-10-05 13:51 UTC, davorpa requested changes

2022-10-12 01:01 UTC, davorpa approved these changes

2022-10-12 01:50 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2022-10-12 01:50 UTC, merged