updated free iOS book
EbookFoundation/free-programming-books pull request #7584
Opened 2022-10-05 04:06 UTC by amannayak0007

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-05 05:28 UTC, metabiswadeep commented
Write name in alphabetical order to avoid linter error.

2022-10-05 11:29 UTC, metabiswadeep requested changes
Move line 964 to line 958.

2022-10-05 11:29 UTC, metabiswadeep commented on books/free-programming-books-langs.md
> +* [Develop in Swift Explorations](https://books.apple.com/in/book/develop-in-swift-explorations/id1581182728) - (iBook)
Move line 964 to line 958.

2022-10-05 18:21 UTC, davorpa commented on books/free-programming-books-langs.md
> +* [Develop in Swift Explorations](https://books.apple.com/in/book/develop-in-swift-explorations/id1581182728) - (iBook)
complete with creators

```suggestion
* [Develop in Swift Explorations](https://books.apple.com/in/book/develop-in-swift-explorations/id1581182728) - Apple Education (iBook)
```

2022-10-05 18:28 UTC, davorpa approved these changes

2022-10-05 18:54 UTC, metabiswadeep approved these changes
Fine from my side.

2022-10-06 03:01 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2022-10-06 03:01 UTC, merged