Adding The official Raspberry Pi Handbook 2023 and Beginner's Guide 2020
EbookFoundation/free-programming-books pull request #7591
Opened 2022-10-05 06:28 UTC by ShivamPathak99

## What does this PR do?
Add resource(s) |  | Improve repo

## For resources
I want to add the most recent edition of official Raspberry Pi Handbook and Beginner's Guide 4th Edition. 

### Description
Both of them consists of collection of Inspirational projects which totally belongs to DIY category and a useful guide for starting with RaspberryPi.

### Why is this valuable (or not)?
Yes, it will definitely add value to repo. These handbooks have been prepared by the makers of the MagPi that is the official Raspberry Pi magazine. Here the ideas has been conveyed in very creative way, the authors have used attractive photos and interactive design for quickly dragging the readers attention.

### How do we know it's really free?
It is clearly mentioned on the official TheMagPi Website that the soft copy of the Handbook is freely available to download.

### For book lists, is it a book? For course lists, is it a course? etc.
- [The Official Raspberry Pi Handbook 2023 (204-page PDF)](https://magpi.raspberrypi.com/books/handbook-2023)
- [Raspberry Pi Beginner's Guide 4th Edition (252-pages- PDF)](https://magpi.raspberrypi.com/books/beginners-guide-4th-ed)

## Checklist:
- [X] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [X] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [X] Include author(s) and platform where appropriate.
- [X] Put lists in alphabetical order, correct spacing.
- [X] Add needed indications (PDF, access notes, under construction).
- [X] Used an informative name for this pull request.

## Follow-up
- ***Please consider it for HactoberFest.***
- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-05 06:30 UTC, ShivamPathak99 reviewed
Please consider it for hacktoberfest.

2022-10-05 19:04 UTC, metabiswadeep requested changes

2022-10-05 19:04 UTC, metabiswadeep commented on books/free-programming-books-langs.md
>  ### REBOL
```suggestion


### REBOL
```

2022-10-05 19:04 UTC, metabiswadeep commented on books/free-programming-books-langs.md
> +* [Raspberry Pi Beginner's Guide 4th Edition](https://magpi.raspberrypi.com/books/beginners-guide-4th-ed)
2061 -> 2057
2060 -> 2059

2022-10-24 13:58 UTC, shrn01 reviewed
Please alphabetically sort the resources. that's why you are getting a lint error. Read docs/CONTRIBUTING.md for more informationg

2022-10-24 13:58 UTC, shrn01 commented on books/free-programming-books-langs.md
> +* [The Official Raspberry Pi Handbook 2023](https://magpi.raspberrypi.com/books/handbook-2023)
```suggestion
* [The Official Raspberry Pi Handbook 2023](https://magpi.raspberrypi.com/books/handbook-2023) (PDF)
```

2022-10-24 13:58 UTC, shrn01 commented on books/free-programming-books-langs.md
> +* [Raspberry Pi Beginner's Guide 4th Edition](https://magpi.raspberrypi.com/books/beginners-guide-4th-ed)
```suggestion
* [Raspberry Pi Beginner's Guide 4th Edition](https://magpi.raspberrypi.com/books/beginners-guide-4th-ed) (PDF)
```

2022-10-30 02:54 UTC, eshellman commented
added in another PR

2022-10-30 02:54 UTC, closed without merging