Adding-Resources
EbookFoundation/free-programming-books pull request #7600
Opened 2022-10-05 08:07 UTC by ShivamPathak99

This reverts commit 15926b9682ac0b713e06fb1c7b0128b87022fb1b.

## What does this PR do?
Add resource(s) |  | Improve repo

## For resources
I want to add the most recent edition of official Raspberry Pi Handbook and Beginner's Guide 4th Edition. 

### Description
Both of them consists of collection of Inspirational projects which totally belongs to DIY category and a useful guide for starting with RaspberryPi.

### Why is this valuable (or not)?
Yes, it will definitely add value to repo. These handbooks have been prepared by the makers of the MagPi that is the official Raspberry Pi magazine. Here the ideas has been conveyed in very creative way, the authors have used attractive photos and interactive design for quickly dragging the readers attention.

### How do we know it's really free?
It is clearly mentioned on the official TheMagPi Website that the soft copy of the Handbook is freely available to download.

### For book lists, is it a book? For course lists, is it a course? etc.
- [The Official Raspberry Pi Handbook 2023 (204-page PDF)](https://magpi.raspberrypi.com/books/handbook-2023)
- [Raspberry Pi Beginner's Guide 4th Edition (252-pages- PDF)](https://magpi.raspberrypi.com/books/beginners-guide-4th-ed)

## Checklist:
- [X] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [X] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [X] Include author(s) and platform where appropriate.
- [X] Put lists in alphabetical order, correct spacing.
- [X] Add needed indications (PDF, access notes, under construction).
- [X] Used an informative name for this pull request.

## Follow-up
- ***Please consider it for HactoberFest.***
- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-05 08:19 UTC, ShivamPathak99 reviewed
Please consider it for Hacktoberfest.

2022-10-05 17:12 UTC, metabiswadeep requested changes

2022-10-05 17:12 UTC, metabiswadeep commented on books/free-programming-books-langs.md
>  ### Raspberry Pi
```suggestion
### Raspberry Pi

```

2022-10-05 17:21 UTC, ShivamPathak99 commented on books/free-programming-books-langs.md
>  * [The Official Raspberry Pi Project Book 1 (2015)](https://magpi.raspberrypi.com/books/projects-1) (PDF)
I have been trying to resolve it  from yesterday but even after so many changes and several pull requests, it is kind of hard to understand what is happening. Can you tell me what is the real problem over here.

2022-10-05 17:43 UTC, ShivamPathak99 commented
Learned so many things about pull request and ways of handling errors.

2022-10-05 18:07 UTC, ShivamPathak99 commented
Please consider it for ***Hacktoberfest***.

2022-10-06 03:18 UTC, eshellman commented
please resolve conflicts.

2022-10-06 03:20 UTC, eshellman commented
these resource require? email addresses - are they required or optional?

2022-10-08 04:18 UTC, ShivamPathak99 commented
> > these resource require? email addresses - are they required or optional?
> 
> **It is completely optional, you can download it without giving any personal information. You can directly download the resource by clicking on the given link (_see the image file attached below_).** ![The Magpi](https://user-images.githubusercontent.com/98941325/194298971-6610e4ec-58f3-4335-9339-4376fbd86082.jpg)

pls merge it

2022-10-08 12:17 UTC, ShivamPathak99 commented
Is there any other adjustments needed?

2022-10-08 21:41 UTC, closed without merging