Create free-programming-books-ml.md
EbookFoundation/free-programming-books pull request #7632
Opened 2022-10-05 16:57 UTC by arnavjune2

Added free reading content for all the ml enthusiasts out there!

## What does this PR do?
Add resources

## For resources
### Description

### Why is this valuable (or not)?
This is for all the machine learning enthusiast who are learning and implementing machine learning algorithms

### How do we know it's really free?
I have gone through the resources all by myself.

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-06 07:10 UTC, davorpa commented on books/free-programming-books-ml.md
> +* [Pattern Recognition and Machine Learning\| English](https://www.microsoft.com/en-us/research/uploads/prod/2006/01/Bishop-Pattern-Recognition-and-Machine-Learning-2006.pdf) - M. Jordan J. Kleinberg
```suggestion
* [Pattern Recognition and Machine Learning\| English](https://www.microsoft.com/en-us/research/uploads/prod/2006/01/Bishop-Pattern-Recognition-and-Machine-Learning-2006.pdf) - Christopher M. Bishop (PDF)
```

2022-10-06 07:13 UTC, davorpa requested changes

2022-10-06 07:13 UTC, davorpa commented on books/free-programming-books-ml.md
> +* [Machine Learning For Absolute Beginners \| English](https://bmansoori.ir/book/Machine%20Learning%20For%20Absolute%20Beginners.pdf)) - Oliver Theobald (PDF)
Copyrighted content. Please remove

2022-10-06 07:13 UTC, davorpa commented on books/free-programming-books-ml.md
> +* [Pattern Recognition and Machine Learning\| English](https://www.microsoft.com/en-us/research/uploads/prod/2006/01/Bishop-Pattern-Recognition-and-Machine-Learning-2006.pdf) - Christopher M. Bishop
Not a malayalam resources. could you move to english books listing?

2022-10-11 02:28 UTC, eshellman commented
ml  = malayalam  not machine learnign

2022-10-11 02:28 UTC, closed without merging