Update free-courses-id.md
EbookFoundation/free-programming-books pull request #7634
Opened 2022-10-05 17:13 UTC by candraw

Added Linux Fundamentals Course in Indonesian

## What does this PR do?
Add resource(s)

## For resources
free-courses-id.md

### Description
Linux Fundamentals Course in Indonesian

### Why is this valuable (or not)?
Because it contains about linux fundamentals for beginners

### How do we know it's really free?
Because you can access the course on youtube, so its free

### For book lists, is it a book? For course lists, is it a course? etc.
Is it a Course

## Checklist:
- [*] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [*] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [*] Include author(s) and platform where appropriate.
- [*] Put lists in alphabetical order, correct spacing.
- [*] Add needed indications (PDF, access notes, under construction).
- [*] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-05 19:09 UTC, metabiswadeep requested changes

2022-10-05 19:09 UTC, metabiswadeep commented on courses/free-courses-id.md
> +###
```suggestion
### Linux
```

2022-10-05 19:09 UTC, metabiswadeep commented on courses/free-courses-id.md
```suggestion


```

2022-10-05 19:09 UTC, metabiswadeep commented on courses/free-courses-id.md
> +* [Belajar linux fundamentals](https://youtube.com/playlist?list=PLbLqbqNn7VYpnd7FggSeq18AgE4gdsy2F) - ID-Networkers
279 -> 277

2022-10-05 19:09 UTC, metabiswadeep commented on courses/free-courses-id.md
> +###
Do not change things unnecessarily.

2022-10-06 07:16 UTC, davorpa commented on courses/free-courses-id.md
> +* [Belajar linux fundamentals](https://youtube.com/playlist?list=PLbLqbqNn7VYpnd7FggSeq18AgE4gdsy2F) - ID-Networkers
```suggestion
* [Belajar linux fundamentals](https://youtube.com/playlist?list=PLbLqbqNn7VYpnd7FggSeq18AgE4gdsy2F) - ID-Networkers
* [Linux Pemula](https://www.youtube.com/playlist?list=PLACzo3mGgHK_D2wkGu4AvUAQiqLC30PTz) - LINUXcare
* [Tutorial Terminal Linux Bahasa Indonesia](https://www.youtube.com/playlist?list=PLy1BHEa_Wr-cpjWY5uOqsMxQwiQrRnC8B) - ArtAway
```

2022-10-06 07:18 UTC, davorpa commented on courses/free-courses-id.md
> +* [Belajar linux fundamentals](https://youtube.com/playlist?list=PLbLqbqNn7VYpnd7FggSeq18AgE4gdsy2F) - ID-Networkers
As suggested by @metabiswadeep 

```suggestion
* [Belajar linux fundamentals](https://youtube.com/playlist?list=PLbLqbqNn7VYpnd7FggSeq18AgE4gdsy2F) - ID-Networkers
* [Linux Pemula](https://www.youtube.com/playlist?list=PLACzo3mGgHK_D2wkGu4AvUAQiqLC30PTz) - LINUXcare
* [Tutorial Terminal Linux Bahasa Indonesia](https://www.youtube.com/playlist?list=PLy1BHEa_Wr-cpjWY5uOqsMxQwiQrRnC8B) - ArtAway
```

2022-10-06 07:23 UTC, davorpa approved these changes

2022-10-06 15:14 UTC, merged