Update problem-sets-competitive-programming.md
EbookFoundation/free-programming-books pull request #7789
Opened 2022-10-07 16:58 UTC by Santigio

Added a a website link to competitive programming

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-07 17:00 UTC, Santigio commented
https://exercism.org/ competitive programming

2022-10-07 17:14 UTC, Santigio commented
new

2022-10-07 18:45 UTC, metabiswadeep requested changes

2022-10-07 18:45 UTC, metabiswadeep commented on more/problem-sets-competitive-programming.md
> +* [Exercism](https://exercism.org/)
```suggestion
* [Exercism](https://exercism.org)
```

2022-11-05 22:48 UTC, eshellman commented on more/problem-sets-competitive-programming.md
> +* [Exercism](https://exercism.org/)
```suggestion
* [Exercism](https://exercism.org)
```

2022-11-06 00:46 UTC, merged