Added Angular.js course
EbookFoundation/free-programming-books pull request #7793
Opened 2022-10-07 17:04 UTC by akhilajohnsonc

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-07 18:43 UTC, metabiswadeep requested changes

2022-10-07 18:43 UTC, metabiswadeep commented on courses/free-courses-en.md
> +* [Angular Fundamentals](https://www.udemy.com/course/angular-fundamentals/) - Integrity Training (Udemy)
Move to line 666

2022-10-07 18:43 UTC, metabiswadeep commented on courses/free-courses-en.md
> +* [Angular Fundamentals](https://www.udemy.com/course/angular-fundamentals/) - Integrity Training (Udemy)
Also bring back the space after 668

2022-11-06 00:45 UTC, eshellman commented
not free

2022-11-06 00:45 UTC, closed without merging