Add resources to PHP and JavaScript in Danish
EbookFoundation/free-programming-books pull request #7801
Opened 2022-10-07 20:27 UTC by Aeka123

## What does this PR do?
Add resources to PHP and JavaScript

## For resources
### Description
Necessary resources for beginners to learn JavaScript and PHP in Danish.
And I've removed unused classes in the C++ and C# sections.

### Why is this valuable (or not)?
It expands the variety of resources to include other programming languages as well. Which are both industry standards.

### How do we know it's really free?
There's no pay-wall on any of the resources I've found, and there is nothing on the individual websites to prove otherwise.

### For book lists, is it a book? For course lists, is it a course? etc.
My PR includes 1 book and 5 HTML pages with important beginner resources.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-08 01:55 UTC, eshellman requested changes

2022-10-08 09:55 UTC, Aeka123 commented on books/free-programming-books-da.md
> +### C++
Huh... must've missed something... I'll fix it

2022-10-09 11:32 UTC, Aeka123 commented
@eshellman would you mind having a look at the latest changes? :-)

2022-10-09 22:59 UTC, eshellman reviewed
none of these are books.

2022-10-09 22:59 UTC, eshellman commented on books/free-programming-books-da.md
> +* [JavaScript Promises - Ryd op i de asynkrone kald](http://qed.dk/poul-foged/2014/02/21/javascript-promises-ryd-op-de-asynkrone-kald/) - Poul Foged
this is a blog post, not a book. remove it

2022-10-09 22:59 UTC, eshellman commented on books/free-programming-books-da.md
> +* [PHP og MYSQL](http://samples.pubhub.dk/9788778531636.pdf) - Kristian Langborg-Hansen (PDF)
this is an 18 page sample of a book.

2022-10-09 22:59 UTC, closed without merging