Jenkins courses added in free-courses-en.md
EbookFoundation/free-programming-books pull request #7834
Opened 2022-10-08 10:52 UTC by Manish-Syal123

## What does this PR do?
Add new courses
## For resources
### Description
Added courses from youtube and some free websites  
### Why is this valuable (or not)?
Jenkins is used to build and test the product continuously, so developers can continuously integrate changes into the build. Jenkins is the most popular open source CI/CD tool on the market today and is used in support of DevOps, alongside other cloud native tools.
### How do we know it's really free?
 As the courses are  from youtube so it is free and the other one is the site that provides free courses in English
### For book lists, is it a book? For course lists, is it a course? etc.
It's a course
## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-09 00:34 UTC, eshellman requested changes
Please read docs/CONTRIBUTING.md guidelines!
I've looked at 3 of links; pelease look at the others.

2022-10-09 00:34 UTC, eshellman commented on courses/free-courses-en.md
> +* [FREE Advanced Jenkins in K8s (Docker in Docker)](https://coursesity.com/course-detail/free-advanced-jenkins-in-k8s-docker-in-docker?ref=share-link) - coursesity (Google)
this looks like an Udemy course why "google".
remove tracking attributes from link.

2022-10-09 00:34 UTC, eshellman commented on courses/free-courses-en.md
> +* [Jenkins Full Course | Jenkins Tutorial For Beginners | Jenkins Tutorial | Simplilearn](https://youtu.be/FX322RVNGj4) - Simplilearn (YouTube)
For youtube, we prefer "playlist" links and the name of the producer/creator. docs/CONTRIBUTING.md#platforms-and-access-notes
no shortened links

2022-10-09 16:42 UTC, Manish-Syal123 reviewed
All the changes have made , Please take a look

2022-10-09 23:03 UTC, eshellman commented
please resolve conflicts.

2022-10-10 09:56 UTC, Manish-Syal123 commented
Resolved conflicts 👍

2022-10-11 00:39 UTC, eshellman commented
I think that in resolving conflicts you deleted the newerJulia section

2022-10-11 14:43 UTC, Manish-Syal123 reviewed
* [Learning Jenkins (2018)](https://www.linkedin.com/learning/learning-jenkins-14423877?replacementOf=learning-jenkins-2018) (Linkedin)

2022-10-11 15:15 UTC, Manish-Syal123 reviewed
added the deleted course Julia again

2022-10-11 16:06 UTC, Manish-Syal123 reviewed
* [Julia](#julia)

2022-10-11 16:07 UTC, Manish-Syal123 commented
forgot to add * [Julia](#julia) in index

2022-10-11 20:04 UTC, eshellman requested changes

2022-10-11 20:04 UTC, eshellman commented on courses/free-courses-en.md
> +* [Node.js Tutorials](https://www.youtube.com/playlist?list=PLWKjhJtqVAbmGQoa3vFjeRbRADAOC9drk) - Beau,Pedro Mercado,freeCodeCamp (Youtube)
```suggestion
* [Node.js Tutorials](https://www.youtube.com/playlist?list=PLWKjhJtqVAbmGQoa3vFjeRbRADAOC9drk) - freeCodeCamp.org
```

2022-10-11 20:04 UTC, eshellman commented on courses/free-courses-en.md
> +* [Jenkins Tutorial Step by Step](https://www.youtube.com/playlist?list=PL8VbCbavWfeGt_Hyq0h9Pymi9DTGowd5X) - Pramod Dutta (YouTube)
```suggestion
* [Jenkins Tutorial Step by Step](https://www.youtube.com/playlist?list=PL8VbCbavWfeGt_Hyq0h9Pymi9DTGowd5X) - Pramod Dutta
```

2022-10-13 06:18 UTC, closed without merging