Added hindi book in C programming
EbookFoundation/free-programming-books pull request #7856
Opened 2022-10-08 15:51 UTC by siddharth784

## What does this PR do?
Add resource

## For resources
https://onlineaavedan.com/study_material/1543909480.pdf

### Description
Added hindi book "C in Hindi" by Kuldeep Chand

### Why is this valuable (or not)?
There are limited resources in the repo in Hindi. This is one step towards bridging that.

### How do we know it's really free?
It is publicly available online on a secure website.

### For book lists, is it a book? For course lists, is it a course? etc.
Yes it's a book in pdf format.

## Checklist:
- [ ✅] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ✅] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ✅] Include author(s) and platform where appropriate.
- [ ✅] Put lists in alphabetical order, correct spacing.
- [ ✅] Add needed indications (PDF, access notes, under construction).
- [ ✅] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-09 05:46 UTC, metabiswadeep requested changes

2022-10-09 05:46 UTC, metabiswadeep commented on books/free-programming-books-hi.md
> +
```suggestion


```

2022-11-05 09:51 UTC, shrn01 commented on books/free-programming-books-hi.md
> +### <a id="c"></a>C
```suggestion
### C
```

2022-11-05 09:53 UTC, shrn01 commented on books/free-programming-books-hi.md
> +* [C in Hindi \| Hindi](https://onlineaavedan.com/study_material/1543909480.pdf) - Kuldeep Chand
```suggestion
* [C in Hindi \| Hindi](https://onlineaavedan.com/study_material/1543909480.pdf) - Kuldeep Chand (PDF)
```

2022-11-05 21:42 UTC, merged