Added a Basic Git Tutorial youtube video in Indonesian
EbookFoundation/free-programming-books pull request #7865
Opened 2022-10-08 16:55 UTC by msidiqh991

## What does this PR do?
Added a Basic Git Tutorial Youtube video in Indonesian by Programmer Zaman Now

## For resources
https://www.youtube.com/watch?v=fQbTeNX1mvM

### Why is this valuable (or not)?
1. Learn about how to use basic git to manage files
2. The discussion in the video is complete enough to make it possible to use Git fluently
3. Explained in Indonesian which is easy to understand for the audience

### How do we know it's really free?
it's available on youtube for free

### For book lists, is it a book? For course lists, is it a course? etc.
it's a course

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-09 05:44 UTC, metabiswadeep requested changes

2022-10-09 05:44 UTC, metabiswadeep commented on books/free-programming-books-id.md
```suggestion


```

2022-10-09 06:26 UTC, msidiqh991 commented
can i get re-check for this?

2022-10-11 20:25 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2022-10-11 20:25 UTC, merged