Adding Useful Django Modules
EbookFoundation/free-programming-books pull request #7890
Opened 2022-10-09 06:51 UTC by ShyamSundhar1411

Added handy Django modules which are not known to many users but which when learnt might make their works easy

## What does this PR do?
I have added Django modules which are not known to many people but when put into exercise can make their works easy.

## For resources
### Description
Added handy Django modules which are not known to many users but which when learnt might make their works easy such as Django Filters, Django-Storages, Django-Allauth, Django Autocomplete-light

### Why is this valuable (or not)?

### How do we know it's really free?
It's from open-source platforms like readthedocs.io and open-source GitHub repositories
### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-09 23:12 UTC, eshellman commented
We proably should link to the web versions of readthedocs documentation since they have links to the [df (and often EPUB) versions.

2022-10-14 15:48 UTC, ShyamSundhar1411 commented
I will look on to it

2022-10-18 00:57 UTC, ShyamSundhar1411 commented
I have made the requested Changes. Kindly review it..

2022-10-30 03:52 UTC, eshellman requested changes

2022-10-30 03:52 UTC, eshellman commented on books/free-programming-books-langs.md
> +* [Django Storages](https://django-storages.readthedocs.io/en/latest/)(HTML)
```suggestion
* [Django Storages](https://django-storages.readthedocs.io/en/latest/) (HTML)
```

2022-10-30 03:52 UTC, eshellman commented on books/free-programming-books-langs.md
> +* [Django Tinymce](https://django-tinymce.readthedocs.io/en/latest/)(HTML)
```suggestion
* [Django Tinymce](https://django-tinymce.readthedocs.io/en/latest/) (HTML)
```

2022-10-30 03:52 UTC, eshellman commented on books/free-programming-books-langs.md
> +* [Social Auth App](https://python-social-auth.readthedocs.io/en/latest/)(HTML)
```suggestion
* [Social Auth App](https://python-social-auth.readthedocs.io/en/latest/) (HTML)
```

2022-10-30 03:52 UTC, eshellman commented on books/free-programming-books-langs.md
> +* [All-Auth](https://django-allauth.readthedocs.io/en/latest/overview.html)(HTML)
```suggestion
* [All-Auth](https://django-allauth.readthedocs.io/en/latest/overview.html) (HTML)
```

2022-10-30 03:52 UTC, eshellman commented on books/free-programming-books-langs.md
> +* [AutoComplete-Light](https://django-autocomplete-light.readthedocs.io/en/master/tutorial.html)(HTML)
```suggestion
* [AutoComplete-Light](https://django-autocomplete-light.readthedocs.io/en/master/tutorial.html) (HTML)
```

2022-10-30 03:52 UTC, eshellman commented on books/free-programming-books-langs.md
> +* [Django Filters](https://django-filter.readthedocs.io/en/stable/)(HTML)
```suggestion
* [Django Filters](https://django-filter.readthedocs.io/en/stable/) (HTML)
```

2022-10-31 20:17 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2022-10-31 20:17 UTC, merged