Added few ebooks
EbookFoundation/free-programming-books pull request #7936
Opened 2022-10-09 18:08 UTC by shrn01

## What does this PR do?
- Added Essential Algorithms
- Added Production Go
- Added JavaScript Wikibook
- Added Laravel Tips and Tricks
- Updated The Modern Javascript Tutorial to use HTTPS
- Added Essential SQL
- Added TypeScript Handbook

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-10 00:33 UTC, eshellman requested changes
sometimes it's better to link to the web version which links to a pdf. sometimes this is especially true of wikibooks because sometimes they take a lot of time to generate.

Your comments on other PRs have been very helpful.

2022-10-10 00:33 UTC, eshellman commented on books/free-programming-books-langs.md
> +* [Production Go](https://leanpub.com/productiongo) - Herman Schaaf and Shawn Smith (EPUB, HTML, PDF) (:construction: *in process*)
we add an access note for leanpub - take a look at some of the other titles See also #6852

2022-10-10 14:43 UTC, shrn01 commented
> sometimes it's better to link to the web version which links to a pdf. sometimes this is especially true of wikibooks because sometimes they take a lot of time to generate.
> 
> Your comments on other PRs have been very helpful.

Updated the link to the wikibook also so the user directly lands into the HTML webpage, where he can navigate to the PDF version and printable version.

2022-10-13 02:02 UTC, eshellman commented
you can the 'changes made' label to make sure I notice that a PR has changes to check

2022-10-13 02:03 UTC, merged