Add: C# Course
EbookFoundation/free-programming-books pull request #7950
Opened 2022-10-10 01:42 UTC by renzien

## What does this PR do?
Add resource(s) C# Course

## For resources
Indonesian Course Learning Making Game with CSharp

### Why is this valuable (or not)?
Valuable, because i've been try that course.

### How do we know it's really free?
Only registration and then you can access

### For book lists, is it a book? For course lists, is it a course? etc.
Yes, is it a course

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-10 15:06 UTC, shrn01 requested changes

2022-10-10 15:06 UTC, shrn01 commented on courses/free-courses-id.md
2 blank lines should be present between 2 sections. Please update.  Look at [CONTRIBUTING.md](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md) for more information

2022-10-10 16:05 UTC, LuigiImVector commented
the site tells me that you have to buy the subscription

2022-10-11 00:44 UTC, eshellman commented
Thanks @LuigiImVector for review

2022-10-11 00:44 UTC, closed without merging