Added my courses to free-courses-zh
EbookFoundation/free-programming-books pull request #8038
Opened 2022-10-11 07:33 UTC by chickenCHRISpy

## What does this PR do?
Add resource(s)

## For resources
### Description
Added Computer Network and OSI model in free-courses-zh file.

### Why is this valuable (or not)?

### How do we know it's really free?
All resources are from youtube with high rating.

### For book lists, is it a book? For course lists, is it a course? etc.
A one video tutorial.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-16 13:13 UTC, shrn01 requested changes
This file is for chinese language. Please move the courses to the proper file

Also please provide the Names which are provided in the resources

2022-10-16 13:13 UTC, shrn01 commented on courses/free-courses-zh.md
> +* [Kunal Kushwaha](https://www.youtube.com/watch?v=IPvYjXCsTg8&ab_channel=KunalKushwaha) - Kunal Kushwaha
```suggestion
* [Kunal Kushwaha](https://www.youtube.com/watch?v=IPvYjXCsTg8) - Kunal Kushwaha
```

2022-10-16 13:13 UTC, shrn01 commented on courses/free-courses-zh.md
> +* [Hussein Nasser](https://www.youtube.com/watch?v=eNF9z5JNl-A&ab_channel=HusseinNasser) - Hussein Nasser
```suggestion
* [Hussein Nasser](https://www.youtube.com/watch?v=eNF9z5JNl-A) - Hussein Nasser
```

2022-10-16 13:13 UTC, shrn01 commented on courses/free-courses-zh.md
> +* [NetworkChuck](https://www.youtube.com/watch?v=oIRkXulqJA4&feature=youtu.be&ab_channel=NetworkChuck) - NetworkChuck
```suggestion
* [NetworkChuck](https://www.youtube.com/watch?v=oIRkXulqJA4) - NetworkChuck
```

2022-10-16 18:01 UTC, chickenCHRISpy commented
> 

Sorry but I was asked to put my courses in this file itself previously. A issue was raised with the suggested changes.

2022-10-17 01:08 UTC, eshellman commented
Please read docs/CONTRIBUTING.md guidelines!

2022-10-17 01:08 UTC, closed without merging