Update free-programming-cheatsheets.md
EbookFoundation/free-programming-books pull request #8087
Opened 2022-10-11 15:46 UTC by Tnguyen-learning

## What does this PR do?
Add resource(s) 

## For resources
### Description
Add ggplot2 library  cheat sheet for R 

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-11 15:49 UTC, Tnguyen-learning commented
add R cheat sheet

2022-10-12 02:34 UTC, eshellman commented on more/free-programming-cheatsheets.md
> +* [Data Visualization with ggplot2 : : CHEAT SHEET](https://www.maths.usyd.edu.au/u/UG/SM/STAT3022/r/current/Misc/data-visualization-2.1.pdf) - maths.usyd.edu.au (PDF)
the credit for this should be http://ggplot2.tidyverse.org  Why is the link from ww.maths.usyd.edu.au ?

2022-10-14 18:33 UTC, Tnguyen-learning commented
@eshellman Could you please review my work?

2022-10-15 00:13 UTC, eshellman commented
please resolve conflicts.

2022-10-15 01:37 UTC, Tnguyen-learning commented
@eshellman I have resolved the conflicts.

2022-10-24 13:51 UTC, shrn01 requested changes

2022-10-24 13:51 UTC, shrn01 commented on more/free-programming-cheatsheets.md
> +* [Colors in R](http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf) - Dr. Ying Wei  (PDF)
```suggestion
* [Colors in R](http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf) - Ying Wei  (PDF)
```
We don't allow honorifications like `Dr.`

2022-11-01 15:29 UTC, merged