Added jupyter notebook references english
EbookFoundation/free-programming-books pull request #8135
Opened 2022-10-12 12:43 UTC by rakshith6404

PR-Hactoberfest2022
I have added Jupyter-english reference regarding #8121 
Looking forward to merge it :smile:

2022-10-12 17:04 UTC, eshellman requested changes

2022-10-12 17:04 UTC, eshellman commented on more/free-programming-interactive-tutorials-en.md
> +### Jupyter
these two resources should be in books, as a new category under python

2022-10-12 19:14 UTC, rakshith6404 commented
I have made changes for the following please look into it.
I am looking forward to merge this file

2022-10-13 02:10 UTC, eshellman commented on more/free-programming-interactive-tutorials-en.md
> +### Jupyter
move them to the books list

2022-10-13 06:29 UTC, rakshith6404 commented
Hello Have added/Updated the requested changes yesterday 
i have added jupyter under python as a category , added related youtube tutorial(playlist) , added jupyter cheatsheet and also added jupyter youtube playlist in hindi .
https://github.com/rakshith6404/free-programming-books/blob/added_jupyter_notebook_references_english/more/free-programming-interactive-tutorials-en.md
https://github.com/rakshith6404/free-programming-books/blob/added_jupyter_notebook_references_english/courses/free-courses-hi.md
Looking forward for a review !!!! :smile:

2022-10-31 20:46 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2022-10-31 20:46 UTC, merged