Update Kotlin course for Thais
EbookFoundation/free-programming-books pull request #8231
Opened 2022-10-13 13:08 UTC by parinphatw

## What does this PR do?
Add resource(s)

## For resources
### Description
- Add resource for Kotlin programming language in the Thai language

### Why is this valuable (or not)?
- There is no source for Kotlin in Thai lang.

### How do we know it's really free?
- This course has been released for free since the beginning.

### For book lists, is it a book? For course lists, is it a course? etc.
- It is a course from Thailand ed-tech platform called Skooldio.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-13 14:13 UTC, shrn01 commented on courses/free-courses-th.md
> +* [Getting started with Kotlin](https://www.skooldio.com/courses/getting-started-with-kotlin)
```suggestion
* [Getting started with Kotlin](https://www.skooldio.com/courses/getting-started-with-kotlin) - Somkiat Kijwongwattana
```

2022-10-13 14:13 UTC, shrn01 requested changes

2022-10-13 14:13 UTC, shrn01 commented on courses/free-courses-th.md
> +* [Getting started with Kotlin](https://www.skooldio.com/courses/getting-started-with-kotlin)
Please add the author name

2022-11-01 16:18 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2022-11-01 16:18 UTC, merged