Update free-courses-hi.md
EbookFoundation/free-programming-books pull request #8315
Opened 2022-10-14 13:44 UTC by Utkarsh6004

Added a Tailwind CSS tutorial.

## What does this PR do?
A Complete youtube Tutorial for Tailwind CSS in Hindi

## For resources
### Description
Youtube Tutorial in Hindi for Tailwind CSS.

### Why is this valuable (or not)?
A Complete resource to learn Tailwind CSS.
### How do we know it's really free?
Its a Youtube Tutorial.
### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-14 16:58 UTC, shrn01 approved these changes
LGTM

2022-10-15 00:02 UTC, eshellman requested changes

2022-10-15 00:02 UTC, eshellman commented on courses/free-courses-hi.md
> +*  [Tailwind css hindi](https://www.youtube.com/playlist?list=PLLCu4ndnReXLXfD-iIGBEB6_l8uF6TMNO) - NST Infotech
```suggestion
* [Tailwind css hindi](https://www.youtube.com/playlist?list=PLLCu4ndnReXLXfD-iIGBEB6_l8uF6TMNO) - NST Infotech
```

2022-10-15 00:02 UTC, eshellman commented on courses/free-courses-hi.md
> +*  [Tailwind CSS Tutorials in Hindi](https://www.youtube.com/playlist?list=PLu0W_9lII9ahwFDuExCpPFHAK829Wto2O) - CodeWithHarry
```suggestion
* [Tailwind CSS Tutorials in Hindi](https://www.youtube.com/playlist?list=PLu0W_9lII9ahwFDuExCpPFHAK829Wto2O) - CodeWithHarry
```you have 2 spaces where there should be only one

2022-10-15 19:13 UTC, merged