Update free-courses-hi.md
EbookFoundation/free-programming-books pull request #8340
Opened 2022-10-14 17:30 UTC by wildlucifer

Added a playlist of R programming.

## What does this PR do?
A youtube playlist for R programming in Hindi.

## For resources
### Description
Complete tutorial to learn  R programming.
### Why is this valuable (or not)?
It is complete resource for learning R programming from beginner to advanced.
### How do we know it's really free?
It is a youtube channel.
### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-15 10:37 UTC, LuigiImVector commented
resolve linter problems

2022-10-15 22:59 UTC, bugbunnyy requested changes

2022-10-15 22:59 UTC, bugbunnyy commented on courses/free-courses-hi.md
> +* [Complete R Programming Tutorial for Beginners to Pro [HINDI]](https://www.youtube.com/playlist?list=PLjVLYmrlmjGdmPrz0Lx7smkd0qIKHInOF) - WsCube Tech
```suggestion

* [Complete R Programming Tutorial for Beginners to Pro [HINDI]](https://www.youtube.com/playlist?list=PLjVLYmrlmjGdmPrz0Lx7smkd0qIKHInOF) - WsCube Tech
```

2022-10-16 10:28 UTC, LuigiImVector commented
solve conflicts

2022-10-31 17:51 UTC, shrn01 commented
Closing the PR as there are no changes

2022-10-31 17:51 UTC, closed without merging