Adding Embedded Systems Fundamentals Course pt_BR
EbookFoundation/free-programming-books pull request #8453
Opened 2022-10-16 00:03 UTC by IanFPFerreira

## What does this PR do?
Add resource(s)

## For resources
### Description
Course on embedded systems fundamentals

### Why is this valuable (or not)?
It is important because it clearly presents the first steps to enter the development in Embedded Systems

### How do we know it's really free?
This course is available on YouTube and free for all.

### For book lists, is it a book? For course lists, is it a course? etc.
It is a course.

## Checklist:
- [X] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [X] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [X] Include author(s) and platform where appropriate.
- [X] Put lists in alphabetical order, correct spacing.
- [X] Add needed indications (PDF, access notes, under construction).
- [X] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-16 15:38 UTC, shrn01 requested changes

2022-10-16 15:38 UTC, shrn01 commented on courses/free-courses-pt_BR.md
> +* [Fundamentos de Sistemas Embarcados](https://www.youtube.com/playlist?list=PLqvo6YdcIqXXGY1dLbf_xA-JLMBumTyzG) - Renato Sampaio (YouTube playlist)
```suggestion
* [Fundamentos de Sistemas Embarcados](https://www.youtube.com/playlist?list=PLqvo6YdcIqXXGY1dLbf_xA-JLMBumTyzG) - Renato Sampaio
```

2022-10-16 16:24 UTC, shrn01 approved these changes
The Course is for Embedded systems

2022-10-17 00:46 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2022-10-17 00:46 UTC, merged