Update free-programming-cheatsheets.md
EbookFoundation/free-programming-books pull request #8456
Opened 2022-10-16 01:14 UTC by Lisaluu555

## What does this PR do?
Add resource(s)

## For resources
### Description
Terraform Cheat Sheet

### Why is this valuable (or not)?
Free

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-16 14:29 UTC, shrn01 requested changes
Please collaborate with #8457 and #8458

2022-10-16 14:29 UTC, shrn01 commented on more/free-programming-cheatsheets.md
> +* [Terraform Cheat Sheet](https://www.techbeatly.com/terraform-cheat-sheet/) - Gineesh Madapparambath (HTML)
```suggestion
* [Terraform Cheat Sheet](https://www.techbeatly.com/terraform-cheat-sheet) - Gineesh Madapparambath (HTML)
```

2022-10-17 16:43 UTC, shrn01 commented on more/free-programming-cheatsheets.md
> +* [Terraform Cheat Sheet](https://www.techbeatly.com/terraform-cheat-sheet) - Gineesh Madapparambath (HTML)
alphabetically order the entries. i.e. swap lines 404 with 403

2022-10-18 00:27 UTC, Lisaluu555 commented
Solved

2022-10-18 02:30 UTC, merged