New content for PHP in Spanish
EbookFoundation/free-programming-books pull request #8459
Opened 2022-10-16 02:16 UTC by BrunoGGM

## What does this PR do?
Add resource

## For resources
### Description
Learn PHP with practical examples

### Why is this valuable (or not)?
New content for PHP in Spanish

### How do we know it's really free?
It is available at openlibra.com under a Creative Commons Attribution-ShareAlike 2.5 Spain license.

### For book lists, is it a book? For course lists, is it a course? etc.
A book

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-16 15:44 UTC, shrn01 requested changes

2022-10-16 15:44 UTC, shrn01 commented on books/free-programming-books-es.md
> +* [PHP a través de ejemplos](https://openlibra.com/es/book/programacion-en-php-a-traves-de-ejemplos) - Manuel Palomo Duarte, Ildefonso Montero Pérez (HTML) [(PDF)](https://openlibra.com/es/book/downl
```suggestion
* [Programación en PHP a través de ejemplos](https://openlibra.com/es/book/programacion-en-php-a-traves-de-ejemplos) - Manuel Palomo Duarte, Ildefonso Montero Pérez (HTML) [(PDF)](https://openlibra.com/es/book/download/programacion-en-php-a-traves-de-ejemplos)
```

Don't change the book name

2022-10-16 16:58 UTC, shrn01 commented on books/free-programming-books-es.md
> +* [Programación en PHP a través de ejemplos](https://openlibra.com/es/book/programacion-en-php-a-traves-de-ejemplos) - Manuel Palomo Duarte, Ildefonso Montero Pérez (HTML) [(PDF)](https://openlibra.c
Change the ordering to make it alphabetically ordered

2022-10-16 17:08 UTC, shrn01 approved these changes

2022-10-17 00:48 UTC, eshellman commented on books/free-programming-books-es.md
> +* [Programación en PHP a través de ejemplos](https://openlibra.com/es/book/programacion-en-php-a-traves-de-ejemplos) - Manuel Palomo Duarte, Ildefonso Montero Pérez (HTML) [(PDF)](https://openlibra.c
just one link please - these are both from the same site

2022-10-17 01:29 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2022-10-17 01:29 UTC, merged