Updated free-course-en.md
EbookFoundation/free-programming-books pull request #8482
Opened 2022-10-16 08:24 UTC by pcodex

Added a free Perl Programming Course under the Perl section

## What does this PR do?
Add resource(s) 

## For resources
### Description
Added the free Complete Perl Programming course from Udemy under the Perl section

### Why is this valuable (or not)?
Perl is the most versatile of scripting languages and is still very relevant

### How do we know it's really free?
Udemy lists this as a free course and anyone can enrol

### For book lists, is it a book? For course lists, is it a course? etc.
Course

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-16 16:13 UTC, shrn01 requested changes

2022-10-16 16:13 UTC, shrn01 commented on courses/free-courses-en.md
> +* [Complete Perl Programming Course The Ultimate Guide ( 2022 )](https://www.udemy.com/course/complete-perl-programming-course-the-ultimate-guide-2022) - Rahul Sohday
```suggestion
* [Complete Perl Programming Course The Ultimate Guide ( 2022 )](https://www.udemy.com/course/complete-perl-programming-course-the-ultimate-guide-2022) - Rahul Sohday (Udemy)
```

Platform attribution

2022-10-16 21:38 UTC, pcodex commented
Accepted review comments and committed

2022-10-17 01:51 UTC, eshellman commented
web pAGE SUGGESTS ITS NOT FREE

2022-10-17 01:51 UTC, closed without merging