Update free-programming-books-hi.md
EbookFoundation/free-programming-books pull request #8484
Opened 2022-10-16 08:43 UTC by aniket-2002

## What does this PR do?
a complete guide for java in hindi

## For resources
### Description

### Why is this valuable (or not)?
this is a complete course for java in hindi
### How do we know it's really free?
it is a free website
### For book lists, is it a book? For course lists, is it a course? etc.
it is a complete course
## Checklist:
- [☑️ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ☑️] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ☑️] Include author(s) and platform where appropriate.
- [ ☑️] Put lists in alphabetical order, correct spacing.
- [ ☑️] Add needed indications (PDF, access notes, under construction).
- [ ☑️] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-16 15:20 UTC, aniket-2002 commented
pls merge !

2022-10-16 16:15 UTC, shrn01 requested changes

2022-10-16 16:15 UTC, shrn01 commented on books/free-programming-books-hi.md
> +### <a id="java"></a>Java
```suggestion
### Java
```

2022-10-16 16:15 UTC, shrn01 commented on books/free-programming-books-hi.md
> +* [Java Notes in Hindi – जावा के हिंदी नोट्स](https://ehindistudy.com/2020/12/05/java-notes-in-hindi/) - eHindiStudy
```suggestion
* [Java Notes in Hindi – जावा के हिंदी नोट्स](https://ehindistudy.com/2020/12/05/java-notes-in-hindi) - eHindiStudy
```

2022-10-16 16:38 UTC, aniket-2002 commented on books/free-programming-books-hi.md
> +* [Java Notes in Hindi – जावा के हिंदी नोट्स](https://ehindistudy.com/2020/12/05/java-notes-in-hindi/) - eHindiStudy
done please check .

2022-10-16 16:57 UTC, shrn01 approved these changes
LGTM

2022-10-17 00:57 UTC, eshellman commented
Maybe its all the ads, but this seems like not a book

2022-10-17 00:57 UTC, closed without merging