Ajs1220 patch 1 7
EbookFoundation/free-programming-books pull request #8527
Opened 2022-10-17 04:07 UTC by ajs1220

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo
added the book "Mathematics for Computer Science"
## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?
link available online
### For book lists, is it a book? For course lists, is it a course? etc.
book
## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-17 16:15 UTC, shrn01 requested changes

2022-10-17 16:15 UTC, shrn01 commented on books/free-programming-books-ar.md
> + * [ورقة الغش مشاكل الرسم البياني](https://github.com/EbookFoundation/free-programming-books/files/9795564/javascript.cheatsheat.txt)
Please provide official links to the books

2022-10-17 16:15 UTC, shrn01 commented on books/free-programming-books-ar.md
> +    *[الرياضيات لعلوم الكمبيوتر] (https://courses.csail.mit.edu/6.042/spring18/mcs.pdf)
Check the spacing

2022-10-18 00:03 UTC, eshellman commented
not arabic either

2022-10-18 00:03 UTC, closed without merging