Add Node.js and PHP learning resource in Indonesian
EbookFoundation/free-programming-books pull request #8613
Opened 2022-10-18 14:22 UTC by zakihaha

## What does this PR do?
Add resource(s) 

## For resources
### Description
I added a reference resource for learning Node JS and the PHP programming language in Indonesian

### Why is this valuable (or not)?
Yes I'm sure it will be useful for other people's learning because the resources I added are quite relevant.

### How do we know it's really free?
It's 100% free I've tried it myself, it's not paid at all. You can see it too.

### For book lists, is it a book? For course lists, is it a course? etc.
Yes this is a course list for Node JS and PHP in Indonesian.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-19 13:24 UTC, shrn01 requested changes

2022-10-19 13:24 UTC, shrn01 commented on books/free-programming-books-id.md
Add an extra new line here. Read the [contribution guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md) for more information about the formatting

2022-10-25 16:28 UTC, shrn01 requested changes

2022-10-25 16:28 UTC, shrn01 commented on books/free-programming-books-id.md
```suggestion


```
2 new lines after each section

2022-10-27 16:47 UTC, zakihaha commented
Hello, please re-review my PR. Thank you :)

2022-10-28 06:17 UTC, eshellman requested changes
3 of 5 resources look ok

2022-10-28 06:17 UTC, eshellman commented on books/free-programming-books-id.md
> +* [Node.js Series](https://medium.easyread.co/nodejs-series-belajar-expressjs-dari-awal-yok-400d9a88e73a) - Musliadi
looks like only 2 chapters done after 5 years. Not complete enough to include

2022-10-28 06:17 UTC, eshellman commented on books/free-programming-books-id.md
> +* [Tutorial Node.JS: Belajar Dasar-Dasar Node JS](https://halovina.com/tutorial-node-js-belajar-dasar-dasar-node-js/) - Halovina
more of a blog post than a book. remove it

2022-10-28 17:08 UTC, shrn01 commented
@zakihaha please remove the resources mentioned by Eric

2022-10-29 05:40 UTC, zakihaha commented
@shrn01 I have deleted it now, please review again. Thank you.

2022-10-29 05:42 UTC, zakihaha reviewed
remove irrelevant resources

2022-11-01 16:02 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2022-11-01 16:02 UTC, merged