Update free-courses-hi.md
EbookFoundation/free-programming-books pull request #8622
Opened 2022-10-18 16:04 UTC by dkboss23

Best tutorials for assembly language programming, in urdu, hindi, Assembly language programming tutorial in urdu, hindi,,

## What does this PR do?
A Youtube Tutorial for Assembly Language.

## For resources
### Description
Best tutorials for assembly language programming, in urdu, hindi,
Assembly language programming tutorial in urdu, hindi,,
### Why is this valuable (or not)?
A Complete resource to learn Assembly Language.
### How do we know it's really free?
It is Youtube Tutorial
### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-19 06:05 UTC, Abinashbunty requested changes

2022-10-19 06:05 UTC, Abinashbunty commented on courses/free-courses-hi.md
> +* [Assembly Language Programming Tutorials in Urdu Hindii](https://www.youtube.com/playlist?list=PLR2FqYUVaFJpHPw1ExSVJZFNlXzJYGAT1)
- Sort them alphabetically.
- Spell check: Hindi

2022-10-19 14:09 UTC, shrn01 requested changes

2022-11-09 17:23 UTC, shrn01 requested changes

2022-11-09 17:23 UTC, shrn01 commented on courses/free-courses-hi.md
> +* [Assembly Language Programming Tutorials in Urdu Hindii](https://www.youtube.com/playlist?list=PLR2FqYUVaFJpHPw1ExSVJZFNlXzJYGAT1)
```suggestion
* [Assembly Language Programming Tutorials in Urdu Hindi](https://www.youtube.com/playlist?list=PLR2FqYUVaFJpHPw1ExSVJZFNlXzJYGAT1) - Programology
* [x64 Assembly Language](https://www.youtube.com/playlist?list=PL-DxAN1jsRa-3KzeQeEeoL_XpUHKfPL1u) - The Cyber Expert
```

- Sort
- Fix Spelling
- Add channel name

2022-11-11 16:03 UTC, merged