Update free-programming-books-hi.md
EbookFoundation/free-programming-books pull request #8634
Opened 2022-10-18 17:46 UTC by huzefaTaj

Adding a Python in Hindi

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-18 22:30 UTC, Abinashbunty requested changes

2022-10-18 22:30 UTC, Abinashbunty commented on books/free-programming-books-hi.md
> +
1 more blank line to be inserted.

2022-10-18 22:30 UTC, Abinashbunty commented on books/free-programming-books-hi.md
> +* [Python DataTypes \| Hindi](https://www.tutorialinhindi.com/python/python-data-types-hindi/)
Sort these in alphabetical order.

2022-10-19 13:25 UTC, shrn01 commented
Please fix the lint errors as specified by @Abinashbunty

2022-11-15 16:51 UTC, eshellman commented
these are 3 pages of a website, not really a book. also intrusive advertising

2022-11-15 16:51 UTC, closed without merging