Added Carbon language and a book
EbookFoundation/free-programming-books pull request #8645
Opened 2022-10-18 23:44 UTC by UjjwalAggarwal-1

## What does this PR do?
Add resource(s) | Improve repo

## For resources
### Description
added the carbon language in languages(alphabetically) and a book(Carbon Compiler Manual)
### Why is this valuable (or not)?
yes
### How do we know it's really free?
it is available on a legit website 
### For book lists, is it a book? For course lists, is it a course? etc.
a book
## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-21 17:09 UTC, UjjwalAggarwal-1 commented
there are no reported warnings so nothing to change, Please see to the PR and merge it
thank you

2022-10-22 00:39 UTC, eshellman commented
please make the requested changes

2022-10-22 01:18 UTC, UjjwalAggarwal-1 commented
Done

2022-10-22 02:29 UTC, eshellman requested changes
sorry, it seems I didn't complete my review with changes

2022-10-22 11:10 UTC, UjjwalAggarwal-1 commented on books/free-programming-books-langs.md
> +### <a id="carbon"></a>Carbon
okay

2022-10-22 11:11 UTC, UjjwalAggarwal-1 commented on books/free-programming-books-langs.md
> +* [Carbon Compiler Manual](https://documentation-service.arm.com/static/5ed10fa8ca06a95ce53f8dc5?token=)
I have not yet removed the word "manual" since it is a part of the title.

2022-10-22 17:13 UTC, eshellman commented on books/free-programming-books-langs.md
> +* [Carbon Compiler Manual](https://documentation-service.arm.com/static/5ed10fa8ca06a95ce53f8dc5?token=)
"Carbon Compiler User Manual" then

2022-10-24 07:26 UTC, UjjwalAggarwal-1 commented on books/free-programming-books-langs.md
> +* [Carbon Compiler Manual](https://documentation-service.arm.com/static/5ed10fa8ca06a95ce53f8dc5?token=)
please see to #8899

2022-10-24 13:25 UTC, shrn01 commented
Since you have raised a new PR, you can close this PR. Generally you can just make the change, commit and push it to your fork and it gets updated in the PR directly

2022-10-24 19:29 UTC, closed without merging