Adding book about go lang
EbookFoundation/free-programming-books pull request #8688
Opened 2022-10-20 01:33 UTC by LuizHenriqueLobo1

## What does this PR do?
Add resource(s)

## For resources
### Description

Interesting study material on go lang, helps to take the first steps in the language.

### Why is this valuable (or not)?

I believe that go lang is a very interesting language to produce micro services, the more material about it the better.

### How do we know it's really free?

It is an academic article.

### For book lists, is it a book? For course lists, is it a course? etc.

This is not a book, it is a PDF document.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-20 13:34 UTC, shrn01 requested changes

2022-10-20 13:34 UTC, shrn01 commented on books/free-programming-books-pt_BR.md
> +* [Go Lang - A linguagem do Google](https://www.ime.usp.br/~gold/cursos/2015/MAC5742/reports/GoLang.pdf)
Please add author name and `(PDF)` tag

2022-11-09 17:31 UTC, shrn01 commented on books/free-programming-books-pt_BR.md
> +* [Go Lang - A linguagem do Google](https://www.ime.usp.br/~gold/cursos/2015/MAC5742/reports/GoLang.pdf)
```suggestion
* [Go Lang - A linguagem do Google](https://www.ime.usp.br/~gold/cursos/2015/MAC5742/reports/GoLang.pdf) - Suelen Goularte Carvalho (PDF)
```

2022-11-15 17:18 UTC, eshellman commented
added in #9203

2022-11-15 17:18 UTC, closed without merging