Updated free-courses-bn.md
EbookFoundation/free-programming-books pull request #8713
Opened 2022-10-20 13:07 UTC by Asrarul-Hoque-Eusha

Added Django and Restapi courses.

## What does this PR do?
Add resources.

## For resources
### Description
Django and Restapi Bengali Course Tutorial.

### Why is this valuable (or not)?
One can learn Django and Restapi in Bengali and use them further.

### How do we know it's really free?
All of them are youtube playlists, that's why it is free.

### For book lists, is it a book? For course lists, is it a course? etc.
They are Courses.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-20 13:40 UTC, shrn01 requested changes

2022-10-20 13:40 UTC, shrn01 commented on courses/free-courses-bn.md
> +### Django
Can you move Django under python?

2022-10-20 17:11 UTC, Asrarul-Hoque-Eusha reviewed
I have moved Django to Python.

2022-10-20 17:12 UTC, Asrarul-Hoque-Eusha commented on courses/free-courses-bn.md
> +### Django
I have moved Django to Python.

2022-10-20 17:55 UTC, shrn01 approved these changes

2022-10-20 17:58 UTC, shrn01 commented on courses/free-courses-bn.md
> +### Restapi
Move this after python

2022-10-21 02:13 UTC, eshellman commented on courses/free-courses-bn.md
> +* [Restapi Bangla Tutorial](https://www.youtube.com/playlist?list=PLbC4KRSNcMnoQONzuNtFlhEzegTYadoBY) - Learn Hunter
this seems to be a laravel tutorial

2022-10-21 17:49 UTC, shrn01 commented on courses/free-courses-bn.md
> +* [Restapi](#restapi)
```suggestion
```

Remove this line

2022-10-22 00:45 UTC, merged