Update free-programming-books-langs.md
EbookFoundation/free-programming-books pull request #8762
Opened 2022-10-21 11:01 UTC by Khushi-Shukla

## What does this PR do?
Adds resource

## For resources
### Description
This PR adds a book on React which is JavaScript library. The book is suitable for beginner who are interested in learning React.

### Why is this valuable (or not)?
The book is divided into lessons and uses simple language to explain important concepts. This book can also be considered as a 30 days routine for people who want to start their journey in React.

### How do we know it's really free?
The link provided directly opens the pdf which can be downloaded on any device of choice.

### For book lists, is it a book? For course lists, is it a course? etc.
This is a book.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-21 17:12 UTC, shrn01 requested changes

2022-10-21 17:12 UTC, shrn01 commented on books/free-programming-books-langs.md
> +* [30 days of React: An introduction to React in 30 bite-size morsels](https://www.newline.co/fullstack-react/assets/media/sGEMe/MNzue/30-days-of-react-ebook-fullstackio.pdf) (PDF)
```suggestion
* [30 days of React: An introduction to React in 30 bite-size morsels](https://www.newline.co/fullstack-react/assets/media/sGEMe/MNzue/30-days-of-react-ebook-fullstackio.pdf) - Ari Lerner (PDF)
```
Please provide author attribution

2022-10-27 18:25 UTC, Khushi-Shukla commented
Please merge this PR or add the label of ready to merge @shrn01

2022-10-28 06:19 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2022-10-28 06:19 UTC, merged

2022-10-28 06:20 UTC, Khushi-Shukla commented
Thank you so much. Please add the "hacktoberfest-accepted" label.