Update free-courses-hi.md
EbookFoundation/free-programming-books pull request #8787
Opened 2022-10-21 18:06 UTC by prasha23

Added machine learning tutorial in python in Hindi

## What does this PR do?
Add resource(s) | Improve repo

## For resources
### Description

### Why is this valuable (or not)?
Simple and step by step explanation.

### How do we know it's really free?
It is available on Youtube.
### For book lists, is it a book? For course lists, is it a course? etc.
Course.
## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-22 10:20 UTC, shrn01 requested changes

2022-10-22 10:20 UTC, shrn01 commented on courses/free-courses-hi.md
> +* [Machine Learning Tutorial in Hindi 2022](https://www.youtube.com/playlist?list=PLfP3JxW-T70Hh7j17_NLzjZ8CejSPx40V) - Indian AI Production (YouTube)
```suggestion
* [Machine Learning Tutorial using Python in Hindi 2022](https://www.youtube.com/playlist?list=PLfP3JxW-T70Hh7j17_NLzjZ8CejSPx40V) - Indian AI Production
```
Dont change the resource name

2022-10-22 10:20 UTC, shrn01 commented on courses/free-courses-hi.md
> +
```suggestion
```

2 lines are required between sections

2022-10-28 05:33 UTC, prasha23 commented on courses/free-courses-hi.md
> +
All changes made as per your suggestion.

2022-10-28 06:11 UTC, prasha23 commented
@shrn01 Rectified linter error. Kindly merge the PR.

2022-10-28 06:24 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2022-10-28 06:25 UTC, merged