Add Digital Image Processing Course
EbookFoundation/free-programming-books pull request #8790
Opened 2022-10-21 18:51 UTC by MasterSaptak009

## What does this PR do?
Add resource(s) 

## For resources
### About Digital Image Processing 

### Why is this valuable (or not)? 

### How do we know it's really free?  

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-22 10:15 UTC, shrn01 requested changes

2022-10-22 10:15 UTC, shrn01 commented on courses/free-courses-en.md
> +* [IMAGE PROCESSING USING MATLAB](https://youtube.com/playlist?list=PLEo-jHOqGNyUWoCSD3l3V-FjX9PnHvx5n) - Dr. Rashi Agarwal
```suggestion
* [Image Processing using Matlab](https://youtube.com/playlist?list=PLEo-jHOqGNyUWoCSD3l3V-FjX9PnHvx5n) - Rashi Agarwal
```

Dont put the title in all caps. Also we dont allow honorifications like `Dr.`

2022-10-22 10:16 UTC, shrn01 commented on courses/free-courses-en.md
Add 2 spaces after each section

2022-10-22 10:16 UTC, shrn01 commented on courses/free-courses-en.md
Add 2 spaces after each section

2022-10-22 17:31 UTC, eshellman commented on courses/free-courses-en.md
> +* [Digital Image processing](#digital-image-processing)
It's usually not helpful to add a category for a single resource. Try to find another category, or see if there are other books in our lists that would fit into your category.

Use MATLAB or Misc categories, or start a "Graphics Programming" category, moving the "Computer Grephics" couse from Misc.

2022-10-22 20:34 UTC, MasterSaptak009 commented
please check now 
I think I have solved the issues as you said ☺

2022-10-28 06:23 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2022-10-28 06:23 UTC, merged