Added Computer Network Book in Hindi
EbookFoundation/free-programming-books pull request #8792
Opened 2022-10-21 19:41 UTC by KryptonGuy

## What does this PR do?
This PR adds resource to the repository

## For resources
### Description
This is a Book about computer Networks in Hindi language.

### Why is this valuable (or not)?
This Book can help any Hindi reader to understand and learn concept of Computer Networks.

### How do we know it's really free?

This book is published by [AICTE-India](https://www.aicte-india.org), which is a saturated body under Indian Government. Materials are freely available to help students to learn.

### For book lists, is it a book? For course lists, is it a course? etc.
It's a Book (PDF)

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-22 01:47 UTC, eshellman requested changes
Aligns with name in other lists; only need anchors for C++ because of the pluses

2022-10-22 01:47 UTC, eshellman commented on books/free-programming-books-hi.md
> +* [Computer Networks](#cn)
```suggestion
* [Networking](#networking)
```

2022-10-22 01:47 UTC, eshellman commented on books/free-programming-books-hi.md
> +### <a id="cn"></a>Computer Networks
```suggestion
### Networking
```

2022-10-23 06:05 UTC, KryptonGuy commented on books/free-programming-books-hi.md
> +### <a id="cn"></a>Computer Networks
I have made those changes as suggested

2022-10-31 20:31 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2022-10-31 20:31 UTC, merged