Added iOS courses
EbookFoundation/free-programming-books pull request #8830
Opened 2022-10-22 18:27 UTC by PuneetTri

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-22 18:52 UTC, PuneetTri commented
Alphabetical order is correct, its just is iOS instead of being IOS

2022-10-23 11:05 UTC, shrn01 requested changes

2022-10-23 11:05 UTC, shrn01 commented on courses/free-courses-hi.md
> +* [iOS Development Course For Beginners](https://www.youtube.com/playlist?list=PLtCBuHKmdxOcmrDx2pM4qNvzWF2NI_Qlo) - Fahad Hussain
```suggestion
* [IOS Mobile App Development Tutorial for beginners](https://www.youtube.com/playlist?list=PLtCBuHKmdxOcmrDx2pM4qNvzWF2NI_Qlo) - Fahad Hussain
```
Better to put the starting title

2022-10-23 11:05 UTC, shrn01 commented on courses/free-courses-hi.md
> +* [iOS Development (Crash course)](https://www.youtube.com/watch?v=n7qOGHWunUY) - Akash Padhiyar
```suggestion
* [iOS App Development Crash Course in Hindi](https://www.youtube.com/watch?v=n7qOGHWunUY) - Akash Padhiyar
```
Dont change the resource name

2022-10-23 22:29 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2022-10-23 22:29 UTC, merged