Added Matlab courses in hindi
EbookFoundation/free-programming-books pull request #8833
Opened 2022-10-22 19:05 UTC by PuneetTri

## What does this PR do?
Added courses for Matlab, both a one-shot course and a self-paced playlist course.

## For resources
### Description

### Why is this valuable (or not)?
A great resource for learning Matlab, recommended by a lot of college professors

### How do we know it's really free?
It's available on YouTube!

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-23 11:10 UTC, shrn01 requested changes

2022-10-23 11:10 UTC, shrn01 commented on courses/free-courses-hi.md
> +* [Matlab for Beginners (Playlist)](https://www.youtube.com/playlist?list=PLjVLYmrlmjGfdIlwG649bdzVHM4iLbD_H) - WsCube Tech, `tch.:` VK Singh
```suggestion
* [MATLAB Complete Tutorial in Hindi](https://www.youtube.com/playlist?list=PLjVLYmrlmjGfdIlwG649bdzVHM4iLbD_H) - WsCube Tech, `tch.:` VK Singh
```
Do not change the resource name

2022-10-23 22:35 UTC, eshellman commented on courses/free-courses-hi.md
> +* [MATLAB Complete Tutorial in Hindi](https://www.youtube.com/playlist?list=PLjVLYmrlmjGfdIlwG649bdzVHM4iLbD_H) - WsCube Tech, `tch.:` VK Singh
```suggestion
* [MATLAB Complete Tutorial in Hindi](https://www.youtube.com/playlist?list=PLjVLYmrlmjGfdIlwG649bdzVHM4iLbD_H) - WsCube Tech
``` just use attribution on the playlist page

2022-10-24 13:42 UTC, shrn01 commented on courses/free-courses-hi.md
> +``` just use attribution on the playlist page
Remove this line 
```suggestion
```

2022-10-24 14:44 UTC, PuneetTri commented
@shrn01 I'm sorry I thought that was just a comment and can be left in. But I've now committed your suggestions

2022-10-25 00:43 UTC, merged