Added Game development courses
EbookFoundation/free-programming-books pull request #8834
Opened 2022-10-22 19:29 UTC by PuneetTri

## What does this PR do?
Added game development courses meant for complete beginners

## For resources
### Description

### Why is this valuable (or not)?
Great insight into how we develop games as well, as how to use our newly learned skills to earn through freelancing.

### How do we know it's really free?
It's available on YouTube!

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-23 11:14 UTC, shrn01 requested changes

2022-10-23 11:14 UTC, shrn01 commented on courses/free-courses-hi.md
> +* [Python Game Development Course](https://www.youtube.com/watch?v=Wg9J5kiX0wY) - Techonical Infotech Pvt. Ltd.
```suggestion
* [Complete Course on Python Game Development](https://www.youtube.com/watch?v=Wg9J5kiX0wY) - Techonical Infotech Pvt. Ltd.
```
Do not change the resource name

2022-10-23 11:14 UTC, shrn01 commented on courses/free-courses-hi.md
> +* [Game Development using Unity3D](https://www.youtube.com/playlist?list=PLBh8phtAyHPUY9fqgs1w6aHJALJ3_fMSc) - Farhan Aqeel
```suggestion
* [Game Development Course](https://www.youtube.com/playlist?list=PLBh8phtAyHPUY9fqgs1w6aHJALJ3_fMSc) - Farhan Aqeel
```
Do not change the resource name

2022-10-24 13:43 UTC, shrn01 approved these changes

2022-10-24 14:43 UTC, PuneetTri commented
@shrn01 if you're fine with the changes, please merge the PR

2022-10-25 00:44 UTC, merged