Added new CTF and problem set sites
EbookFoundation/free-programming-books pull request #8835
Opened 2022-10-22 19:37 UTC by Omega-Centauri-21

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-23 11:18 UTC, shrn01 requested changes

2022-10-23 11:18 UTC, shrn01 commented on more/problem-sets-competitive-programming.md
> +* [PentestIT](https://lab.pentestit.ru)
```suggestion
* [PentestIT](https://lab.pentestit.ru) (email address *requested*)
```

2022-10-23 11:18 UTC, shrn01 commented on more/problem-sets-competitive-programming.md
> +* [Root-Me](https://www.root-me.org) (Language choosing option is available once the website loads completely) - (email address required to login)
```suggestion
* [Root-Me](https://www.root-me.org) (email address *requested*)
```

2022-10-23 11:18 UTC, shrn01 commented on more/problem-sets-competitive-programming.md
> +* [SmashtheStack](http://www.smashthestack.org/wargames.html) (Fun games like OverTheWire)
```suggestion
* [SmashtheStack](http://www.smashthestack.org/wargames.html)
```

2022-11-15 18:16 UTC, eshellman commented on more/problem-sets-competitive-programming.md
> +* [PentestIT](https://lab.pentestit.ru)
```suggestion
```

2022-11-16 14:55 UTC, merged