feat: add python tkinter book
EbookFoundation/free-programming-books pull request #8837
Opened 2022-10-22 19:48 UTC by arielroque

## What does this PR do?
Add Python book on Brazilian books

## For resources
### Description
Add the book "Pensando Tkinter" to Brazilian books

### Why is this valuable (or not)?

### How do we know it's really free?
This content is created and freely distributed by a Python group from Universidade Estadual Paulista - UNESP

### For book lists, is it a book? For course lists, is it a course? etc.
It is a book

2022-10-23 11:25 UTC, shrn01 requested changes

2022-10-23 11:25 UTC, shrn01 commented on books/free-programming-books-pt_BR.md
> +* [Pensando Tkinter](https://www.dcc.ufrj.br/~fabiom/mab225/PensandoTkinter.pdf) (PDF)
```suggestion
* [Pensando Tkinter](https://www.dcc.ufrj.br/~fabiom/mab225/PensandoTkinter.pdf) - Steven Ferg (PDF)
```
Please provide author attribution

2022-10-24 20:46 UTC, arielroque commented on books/free-programming-books-pt_BR.md
> +* [Pensando Tkinter](https://www.dcc.ufrj.br/~fabiom/mab225/PensandoTkinter.pdf) (PDF)
Thanks so much! I forgot about it.

2022-10-25 02:58 UTC, shrn01 approved these changes

2022-10-25 18:06 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2022-10-25 18:06 UTC, merged