added redhat courses
EbookFoundation/free-programming-books pull request #8844
Opened 2022-10-23 04:40 UTC by SyedAahana

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-23 04:43 UTC, SyedAahana commented
i have added the redhat courses which are free

2022-10-23 13:54 UTC, shrn01 requested changes

2022-10-23 13:54 UTC, shrn01 commented on courses/free-courses-en.md
Please add 2 new lines after each section

2022-10-23 13:54 UTC, shrn01 commented on courses/free-courses-en.md
> +* [Fundamentals of Red Hat Enterprise Linux](https://www.edx.org/course/fundamentals-of-red-hat-enterprise-linux) - edX
Move it into Linux

2022-10-23 13:54 UTC, shrn01 commented on courses/free-courses-en.md
> +* [Fundamentals of Containers, Kubernetes, and Red Hat OpenShift](https://www.edx.org/course/fundamentals-of-containers-kubernetes-and-red-hat) - edX
Move to kubernetes

2022-10-23 13:54 UTC, shrn01 commented on courses/free-courses-en.md
> +* [Fundamentals of Java EE Development](https://www.edx.org/course/fundamentals-of-java-ee-development) - edX
Move to java

2022-11-15 18:41 UTC, eshellman commented on courses/free-courses-en.md
> +* [Fundamentals of Java EE Development](https://www.edx.org/course/fundamentals-of-java-ee-development) - edX
```suggestion
* [Fundamentals of Java EE Development](https://www.edx.org/course/fundamentals-of-java-ee-development) -  Will Dinyes (edX)
```

2022-11-15 18:42 UTC, eshellman commented on courses/free-courses-en.md
> +* [Fundamentals of Containers, Kubernetes, and Red Hat OpenShift](https://www.edx.org/course/fundamentals-of-containers-kubernetes-and-red-hat) - edX
```suggestion
* [Fundamentals of Containers, Kubernetes, and Red Hat OpenShift](https://www.edx.org/course/fundamentals-of-containers-kubernetes-and-red-hat) - Zach Gutterman, Richard Allred (edX)
```

2022-11-15 18:44 UTC, eshellman commented on courses/free-courses-en.md
> +* [Fundamentals of Red Hat Enterprise Linux](https://www.edx.org/course/fundamentals-of-red-hat-enterprise-linux) - edX
```suggestion
* [Fundamentals of Red Hat Enterprise Linux](https://www.edx.org/course/fundamentals-of-red-hat-enterprise-linux) - Chris Caillouet (edX)
```

2022-11-15 18:52 UTC, merged