added a new data structure course in python
EbookFoundation/free-programming-books pull request #8853
Opened 2022-10-23 09:04 UTC by SurabhiSuresh22

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?
One of the best available free resource to learn data structures in python.

### How do we know it's really free?
Please do check the link. It is a youtube course.

### For book lists, is it a book? For course lists, is it a course? etc.
It is a course.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-23 13:59 UTC, shrn01 requested changes

2022-10-23 13:59 UTC, shrn01 commented on courses/free-courses-en.md
> +* [Data Structures in Python](https://www.youtube.com/playlist?list=PLzgPDYo_3xukPJdH6hVQ6Iic7KiJuoA-l) - Amulya's Academy (YouTube)
```suggestion
* [Data Structures \| Python](https://www.youtube.com/playlist?list=PLzgPDYo_3xukPJdH6hVQ6Iic7KiJuoA-l) - Amulya's Academy
```
Use the name provided by the resource, Youtube attribution is not required

2022-10-24 07:41 UTC, shrn01 requested changes

2022-10-24 07:41 UTC, shrn01 commented on courses/free-courses-en.md
> +* [Data Structures in Python](https://www.youtube.com/playlist?list=PLzgPDYo_3xukPJdH6hVQ6Iic7KiJuoA-l) - Amulya's Academy
```suggestion
* [Data Structures \| Python](https://www.youtube.com/playlist?list=PLzgPDYo_3xukPJdH6hVQ6Iic7KiJuoA-l) - Amulya's Academy
```
Do not change the resource name

2022-11-03 17:51 UTC, shrn01 reviewed
Looks like the linter is failing, but is not showing proper error

2022-11-03 17:59 UTC, eshellman commented
I think it's something with the ' character

2022-11-03 18:46 UTC, eshellman commented
OK, it seems it was the pipe character, which apparently sorts as if it's not there. but apparently the linter can't emit a useful error message.

2022-11-03 19:45 UTC, merged