Cursos
EbookFoundation/free-programming-books pull request #9029
Opened 2022-10-28 11:03 UTC by LuisFelipeCracco

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-28 14:35 UTC, shrn01 requested changes

2022-10-28 14:35 UTC, shrn01 commented on courses/free-courses-pt_BR.md
> +* [Curso Dart](https://www.youtube.com/playlist?list=PLAqdhPoZdJtBnMfZtpExJlFTuuXE0TabS/) - Luis Claudio Leite Pereira (YouTube)
```suggestion
* [Curso Dart](https://www.youtube.com/playlist?list=PLAqdhPoZdJtBnMfZtpExJlFTuuXE0TabS) - Luis Claudio Leite Pereira
```

Youtube attribution not required

2022-10-28 14:35 UTC, shrn01 commented on courses/free-courses-pt_BR.md
> +* [Curso de Programação C Completo](https://www.youtube.com/playlist?list=PLqJK4Oyr5WSjjEQCKkX6oXFORZX7ro3DA) - Programe seu futuro (YouTube)
```suggestion
* [Curso de Programação C Completo](https://www.youtube.com/playlist?list=PLqJK4Oyr5WSjjEQCKkX6oXFORZX7ro3DA) - Programe seu futuro
```
Youtube attribution not required

2022-10-29 23:42 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2022-10-29 23:42 UTC, merged