Added Scratch book.  Added authors to a couple existing Scratch books
EbookFoundation/free-programming-books pull request #9044
Opened 2022-10-28 19:24 UTC by brianleemcqueen

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-28 19:38 UTC, brianleemcqueen commented
Adding Scratch books and added some missing authors to other Scratch books. 
I only worked in the Scratch section and verified that all the books listed there were free and were indeed books per the definition on your Contributions guideline.

2022-10-29 14:50 UTC, shrn01 requested changes

2022-10-29 14:50 UTC, shrn01 commented on books/free-programming-books-langs.md
> +* [code club Book of Scratch](https://www.linuxlinks.com/wp-content/uploads/2021/09/magpi-cc-book-of-scratch-v1_compress.pdf) - Rik Cross, Tracy Gardner (PDF)
```suggestion
* [Code Club Book of Scratch](https://magpi.raspberrypi.com/books/book-of-scratch) - Rik Cross, Tracy Gardner (PDF)
```

Please provide the official links to resources

2022-10-30 03:59 UTC, brianleemcqueen commented
Thank you for the suggested change!

2022-10-30 17:14 UTC, merged