Added "Free rust Ebook"
EbookFoundation/free-programming-books pull request #9046
Opened 2022-10-28 19:55 UTC by gregE21

Add Monte Carlo's "Building Data Products: The Ultimate Guide"

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

Add resources 

## For resources
Books

### Description
Added a free rust eBook created by stackoverflow contributors 

### Why is this valuable (or not)?
Provides information on rust programming from a problem/solution perspective, rather than just a reference book.

### How do we know it's really free?
Book is unaffiliated and has several authors, and is not available for sale by any publishers or websites. 

### For book lists, is it a book? For course lists, is it a course? etc.

It is a book in PDF format.

## Checklist:
- [ x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ x] Include author(s) and platform where appropriate.
- [x ] Put lists in alphabetical order, correct spacing.
- [x ] Add needed indications (PDF, access notes, under construction).
- [x ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-29 14:56 UTC, shrn01 requested changes

2022-10-29 14:56 UTC, shrn01 commented on books/free-programming-books-langs.md
> +* [Learning Rust Ebook]((https://riptutorial.com/ebook/rust)) (PDF)
```suggestion
* [Learning Rust Ebook](https://riptutorial.com/ebook/rust) - StackOverflow Contributors (PDF)
```

2022-10-29 23:58 UTC, eshellman commented on books/free-programming-books-langs.md
> +* [Learning Rust Ebook](https://riptutorial.com/ebook/rust) - StackOverflow Contributors (PDF)
look at other riptutorial listings. we link to the pdf directly

2022-10-31 01:14 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2022-10-31 01:14 UTC, merged