Update free-programming-books-fr.md
EbookFoundation/free-programming-books pull request #9110
Opened 2022-10-30 04:57 UTC by cuitlazotlac

hey ! just adding minor changes in french translations

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-31 01:21 UTC, eshellman commented
changes break links in index. please change index as well - your translation is better

2022-10-31 02:56 UTC, cuitlazotlac commented
hey @eshellman - sorry forgot to modify that, it's done now :) let me know if I can help somewhere else

2022-11-01 17:56 UTC, eshellman requested changes

2022-11-01 17:56 UTC, eshellman commented on books/free-programming-books-fr.md
> +    * [Pédagogie pour les enfants et adolescents](#pédagogie-pour-enfants-et-adolescents)
```suggestion
    * [Pédagogie pour les enfants et adolescents](#pédagogie-pour-les-enfants-et-adolescents)
```

2022-11-01 17:56 UTC, eshellman commented on books/free-programming-books-fr.md
> +    * [IDE et éditeurs de texte](#ide-and-editors)
```suggestion
    * [IDE et éditeurs de texte](#ide-et-editeurs-de-texte)
```

2022-11-03 16:59 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2022-11-03 16:59 UTC, merged