Gautham/ios resource
EbookFoundation/free-programming-books pull request #9154
Opened 2022-10-31 07:20 UTC by GauthamG2

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-10-31 17:28 UTC, shrn01 reviewed
Please make the requested changes

2022-10-31 17:28 UTC, shrn01 commented on books/free-programming-books-en.md
> +### Swift
Please move this change to the english books file free-programming-books-langs.md

2022-10-31 17:28 UTC, shrn01 commented on courses/free-courses-en.md
> +* [iOS Development Course - Use Swift 5 and UIKit to Build a Netflix Clone](https://www.youtube.com/watch?v=KCgYDCKqato) - freeCodeCamp.org (Youtube)
```suggestion
* [iOS Development Course - Use Swift 5 and UIKit to Build a Netflix Clone](https://www.youtube.com/watch?v=KCgYDCKqato) - freeCodeCamp.org
```
Youtube attribution is not required

2022-10-31 17:28 UTC, shrn01 commented on courses/free-courses-en.md
> +* [Build Great IOS Apps (Swift)](https://www.udemy.com/course/build-great-ios-apps-with-swift/?ranMID=39197&ranEAID=JVFxdTr9V80&ranSiteID=JVFxdTr9V80-ApSDs.hyUFklgG3FVVuVLA&LSNPUBID=JVFxdTr9V80&utm_s
```suggestion
* [Build Great IOS Apps (Swift)](https://www.udemy.com/course/build-great-ios-apps-with-swift) - Hamad Fouad (Udemy)
```

2022-10-31 17:28 UTC, shrn01 commented on courses/free-courses-en.md
> +* [100 days of SwiftUI](https://www.hackingwithswift.com/100/swiftui) - Hacking With Swift UI
This is already added in 1277

2022-10-31 19:43 UTC, GauthamG2 commented
Final change also done. Removed the course from the list.

2022-11-01 06:05 UTC, shrn01 requested changes

2022-11-01 06:05 UTC, shrn01 commented on books/free-programming-books-en.md
> +* [Swift algorithms and data structures](https://englishonlineclub.com/pdf/Data%20Structures%20and%20Algorithms%20in%20Swift%20-%20Implementing%20practical%20data%20structures%20with%20Swift%204%20[E
Please remove the changes from this file

2022-11-01 06:51 UTC, GauthamG2 commented
Changes removed from the file.

On Tue, Nov 1, 2022 at 11:35 AM Sharan J ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In books/free-programming-books-en.md
> <https://github.com/EbookFoundation/free-programming-books/pull/9154#discussion_r1010097971>
> :
>
> > @@ -7,4 +7,7 @@
>
>  * [English, By Programming Language](free-programming-books-langs.md)
>  * [English, By Subject](free-programming-books-subjects.md)
> +* [Swift algorithms and data structures](https://englishonlineclub.com/pdf/Data%20Structures%20and%20Algorithms%20in%20Swift%20-%20Implementing%20practical%20data%20structures%20with%20Swift%204%20[EnglishOnlineClub.com].pdf <https://englishonlineclub.com/pdf/Data%20Structures%20and%20Algorithms%20in%20Swift%20-%20Implementing%20practical%20data%20structures%20with%20Swift%204%20%5BEnglishOnlineClub.com%5D.pdf>) (PDF)
>
> Please remove the changes from this file
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/EbookFoundation/free-programming-books/pull/9154#pullrequestreview-1162865374>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIWHFKTYUPOY4KRSTBQQOZTWGCXLJANCNFSM6AAAAAARSZHHCQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> .com>
>

2022-11-01 06:53 UTC, shrn01 commented on books/free-programming-books-en.md
> +
These new lines too

2022-11-01 07:14 UTC, GauthamG2 commented
I didn't add these, but I removed them now.

On Tue, Nov 1, 2022 at 12:24 PM Sharan J ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In books/free-programming-books-en.md
> <https://github.com/EbookFoundation/free-programming-books/pull/9154#discussion_r1010127469>
> :
>
> > @@ -8,3 +8,5 @@
>  * [English, By Programming Language](free-programming-books-langs.md)
>  * [English, By Subject](free-programming-books-subjects.md)
>    (The list of books in English is here for historical reasons.)
> +
>
> These new lines too
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/EbookFoundation/free-programming-books/pull/9154#pullrequestreview-1162909938>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIWHFKVWEUQSQXETJQKF2HTWGC5A5ANCNFSM6AAAAAARSZHHCQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> .com>
>

2022-11-01 07:17 UTC, GauthamG2 commented
Done, Please check now.

On Tue, Nov 1, 2022 at 12:45 PM Sharan J ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In books/free-programming-books-en.md
> <https://github.com/EbookFoundation/free-programming-books/pull/9154#discussion_r1010150759>
> :
>
> > @@ -8,3 +8,5 @@
>  * [English, By Programming Language](free-programming-books-langs.md)
>  * [English, By Subject](free-programming-books-subjects.md)
>    (The list of books in English is here for historical reasons.)
> +
>
> Please leave this file as it was before.
>
> Do
>
> git restore <filename>
> git commit
> git push
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/EbookFoundation/free-programming-books/pull/9154#discussion_r1010150759>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIWHFKQC7XBPK65KIHZKHDTWGC7QPANCNFSM6AAAAAARSZHHCQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> .com>
>

2022-11-02 00:27 UTC, GauthamG2 commented
The PR/MR is still in NOT ACCEPTED state in my Hacktobefest profile. Could
you please check it.

On Tue, Nov 1, 2022 at 12:47 PM Gautham Sritharan <
***@***.***> wrote:

> Done, Please check now.
>
> On Tue, Nov 1, 2022 at 12:45 PM Sharan J ***@***.***> wrote:
>
>> ***@***.**** commented on this pull request.
>> ------------------------------
>>
>> In books/free-programming-books-en.md
>> <https://github.com/EbookFoundation/free-programming-books/pull/9154#discussion_r1010150759>
>> :
>>
>> > @@ -8,3 +8,5 @@
>>  * [English, By Programming Language](free-programming-books-langs.md)
>>  * [English, By Subject](free-programming-books-subjects.md)
>>    (The list of books in English is here for historical reasons.)
>> +
>>
>> Please leave this file as it was before.
>>
>> Do
>>
>> git restore <filename>
>> git commit
>> git push
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/EbookFoundation/free-programming-books/pull/9154#discussion_r1010150759>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AIWHFKQC7XBPK65KIHZKHDTWGC7QPANCNFSM6AAAAAARSZHHCQ>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> <EbookFoundation/free-programming-books/pull/9154/review/1162932249@
>> github.com>
>>
>

2022-11-03 04:02 UTC, GauthamG2 commented
The PR/MR is still in NOT ACCEPTED state in my Hacktobefest profile. Could
you please check it

On Wed, Nov 2, 2022 at 5:56 AM Gautham Sritharan ***@***.***>
wrote:

> The PR/MR is still in NOT ACCEPTED state in my Hacktobefest profile. Could
> you please check it.
>
> On Tue, Nov 1, 2022 at 12:47 PM Gautham Sritharan <
> ***@***.***> wrote:
>
>> Done, Please check now.
>>
>> On Tue, Nov 1, 2022 at 12:45 PM Sharan J ***@***.***>
>> wrote:
>>
>>> ***@***.**** commented on this pull request.
>>> ------------------------------
>>>
>>> In books/free-programming-books-en.md
>>> <https://github.com/EbookFoundation/free-programming-books/pull/9154#discussion_r1010150759>
>>> :
>>>
>>> > @@ -8,3 +8,5 @@
>>>  * [English, By Programming Language](free-programming-books-langs.md)
>>>  * [English, By Subject](free-programming-books-subjects.md)
>>>    (The list of books in English is here for historical reasons.)
>>> +
>>>
>>> Please leave this file as it was before.
>>>
>>> Do
>>>
>>> git restore <filename>
>>> git commit
>>> git push
>>>
>>> —
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/EbookFoundation/free-programming-books/pull/9154#discussion_r1010150759>,
>>> or unsubscribe
>>> <https://github.com/notifications/unsubscribe-auth/AIWHFKQC7XBPK65KIHZKHDTWGC7QPANCNFSM6AAAAAARSZHHCQ>
>>> .
>>> You are receiving this because you were mentioned.Message ID:
>>> <EbookFoundation/free-programming-books/pull/9154/review/1162932249@
>>> github.com>
>>>
>>

2022-11-03 16:26 UTC, eshellman commented on books/free-programming-books-en.md
> +
```suggestion
```

2022-11-03 16:27 UTC, eshellman commented on books/free-programming-books-en.md
> +
```suggestion
```

2022-11-03 16:27 UTC, eshellman commented on books/free-programming-books-en.md
> +
```suggestion
```

2022-11-03 17:35 UTC, merged

2022-11-04 05:09 UTC, GauthamG2 commented
Thanks for merging the commit. But in the Hacktoberfest profile page, this
PR/MR is still in NOT ACCEPTED state.

On Thu, Nov 3, 2022 at 11:05 PM Eric Hellman ***@***.***>
wrote:

> Merged #9154
> <https://github.com/EbookFoundation/free-programming-books/pull/9154>
> into main.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/EbookFoundation/free-programming-books/pull/9154#event-7734539805>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIWHFKVNBNTOQSBRZ7QAKI3WGPZXDANCNFSM6AAAAAARSZHHCQ>
> .
> You are receiving this because you were mentioned.Message ID:
> <EbookFoundation/free-programming-books/pull/9154/issue_event/7734539805@
> github.com>
>

2022-11-04 11:29 UTC, shrn01 commented
Hey @GauthamG2 hacktoberfest is done. The time limits are October only. This pr was merged in Nov 3. So that's why you're not seeing it