Update free-courses-bn.md
EbookFoundation/free-programming-books pull request #9184
Opened 2022-11-04 14:38 UTC by NeamulIslamFahim

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-11-04 15:27 UTC, shrn01 commented on courses/free-courses-bn.md
> +* [Java Course! Full Course Bangla](https://youtube.com/playlist?list=PLysy6TYSMvpJmMN0ElbC936RmmFustDiy) - Online Course
alphabetically order the resources

2022-11-04 16:19 UTC, NeamulIslamFahim reviewed
Please check

2022-11-04 17:33 UTC, eshellman commented
look at linter results - it still wants spacing fixed

2022-11-05 07:03 UTC, NeamulIslamFahim reviewed
Please check

2022-11-05 09:47 UTC, shrn01 requested changes

2022-11-05 09:47 UTC, shrn01 commented on courses/free-courses-bn.md
> +
```suggestion
```

Only 2 lines between sections

2022-11-05 12:40 UTC, NeamulIslamFahim reviewed
Is it ok?

2022-11-05 14:02 UTC, shrn01 commented on courses/free-courses-bn.md
> +* [Java Course!Full Course Bangla](https://www.youtube.com/playlist?list=PLysy6TYSMvpJmMN0ElbC936RmmFustDiy) - Online Course
```suggestion
* [Java Course! Full Course Bangla](https://www.youtube.com/playlist?list=PLysy6TYSMvpJmMN0ElbC936RmmFustDiy) - Online Course
```

2022-11-05 15:17 UTC, NeamulIslamFahim reviewed
Now check.
Thanks a lot for helping and apology for the errors

2022-11-05 16:06 UTC, merged