Add TypeScript Books to free-programming-books-ko.md
EbookFoundation/free-programming-books pull request #9244
Opened 2022-12-27 01:29 UTC by tomriddle7

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2022-12-31 17:07 UTC, Thenlie approved these changes
These look good to me. All of the links seem useful and relevant. My only suggestion would be to squash these commits, which can be done on merge if nothing else.

2023-01-02 17:09 UTC, eshellman requested changes
Please add author names where appropriate.

2023-01-02 17:09 UTC, eshellman commented on books/free-programming-books-ko.md
> +* [한눈에 보는 타입스크립트](https://heropy.blog/2020/01/27/typescript)
```suggestion
* [한눈에 보는 타입스크립트](https://heropy.blog/2020/01/27/typescript) - HEROPY
Tech
```

2023-01-02 17:09 UTC, eshellman commented on books/free-programming-books-ko.md
> +* [타입스크립트 핸드북](https://joshua1988.github.io/ts)
```suggestion
* [타입스크립트 핸드북](https://joshua1988.github.io/ts) - Captain Pangyo
```

2023-01-03 19:02 UTC, eshellman commented
Thanks!

2023-01-03 19:02 UTC, merged