Updating links and adding a resource for R
EbookFoundation/free-programming-books pull request #9319
Opened 2023-03-27 13:41 UTC by olivroy

## What does this PR do?
Added Tidy modelling with R and updating links to latest versions.

## For resources
### Description

### Why is this valuable (or not)?
tidy models is a new framework to make modelling work

### How do we know it's really free?

The source code is all available on GitHub.

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2023-03-27 19:21 UTC, eshellman commented
I don't understand why it fails the alphabetization check. Will need to look more closely - everything looks ok to me

2023-03-27 19:24 UTC, eshellman requested changes
sometimes the linter doesn't point to the real error

2023-03-27 19:24 UTC, eshellman commented on books/free-programming-books-langs.md
> +* [R Packages]((https://r-pkgs.org) - Hadley Wickham, Jenny Bryan
Aha! here's the problem!
```suggestion
* [R Packages](https://r-pkgs.org) - Hadley Wickham, Jenny Bryan
```

2023-03-27 19:24 UTC, eshellman commented on books/free-programming-books-langs.md
> +* [R for Data Science](https://r4ds.hadley.nz) - Hadley Wickham, Mine Çetinkaya-Rundel, and Garrett Grolemund
```suggestion
* [R for Data Science](https://r4ds.hadley.nz) - Hadley Wickham, Mine Çetinkaya-Rundel, Garrett Grolemund
```

2023-03-27 20:05 UTC, olivroy reviewed
Thanks.

2023-03-28 01:31 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2023-03-28 01:31 UTC, merged