Adding Brazilian Portuguese books
EbookFoundation/free-programming-books pull request #9347
Opened 2023-04-20 13:23 UTC by heltonricardo

## What does this PR do?
Add resource(s)

## For resources
### Description

Brazilian Portuguese Books:
- Linguagem Assembly: Introdução ao padrão Intel 8086 - José Augusto N. G. Manzano (@J-AugustoManzano)
- Programação de Computadores com Linguagem Julia - José Augusto N. G. Manzano (@J-AugustoManzano)
- Linguagem LISP - Primeiros passos com Common LISP (CL) - José Augusto N. G. Manzano (@J-AugustoManzano)
- Academia da Tartaruga - José Augusto N. G. Manzano (@J-AugustoManzano)
- Linguagem Logo: Introdução com UCBLogo 6.2.2 - José Augusto N. G. Manzano (@J-AugustoManzano)
- Programação de computadores para iniciantes com Small Basic - José Augusto N. G. Manzano (@J-AugustoManzano)

### Why is this valuable (or not)?

Books with high quality content used even in universities

### How do we know it's really free?

The author has published them on his GitHub and he is aware of publishing them in this repository. I used to be his student.

### For book lists, is it a book? For course lists, is it a course? etc.

All are books.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2023-04-20 13:36 UTC, J-AugustoManzano commented
To Whom It May Concern: I am aware of the indication and free distribution of these books of my authorship. Authorized distribution.

2023-04-20 18:08 UTC, eshellman requested changes
Nice additions. Other than using the more direct url for the Lisp book, consider whether students are going to find the Small Basic book under "Small Basic" if they are looking for a Basic book. Remember our headings are to help people find what they want - they are not for experts who already understand the difference between dialects.

2023-04-21 18:31 UTC, eshellman requested changes
If we had a bunch of Basic books, having a subcategory for Small Basic would be ok. But the title is "Small Basic, so having the subcategory is overkill. Imagine if you only have "WATFIV Fortran" and no other FORTRAN books. You would just expect a singular category for FORTRAN without a WATFIV subcategory.

2023-04-21 18:31 UTC, eshellman commented on books/free-programming-books-pt_BR.md
> +#### Small Basic
just one heading please "Basic" is close enough

2023-04-21 18:31 UTC, eshellman commented on books/free-programming-books-pt_BR.md
> +    * [Small Basic](#small-basic)
just one heading please "Basic" is close enough

2023-04-21 19:08 UTC, heltonricardo commented
Thanks for the feedback. Correction has been made and pull request is updated.

2023-04-21 19:11 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2023-04-21 19:11 UTC, merged