Update free-courses-ml.md
EbookFoundation/free-programming-books pull request #9375
Opened 2023-05-11 02:31 UTC by RijoKsd

Ordered playlist in alphabetic order
Added a new Malayalam playlist of
* Android
* Angular
* Bootstrap
* C
* CSS
* CPP
* C#
* Flask
* Flutter
* Game Development
* Git
* HTML
* JAVA
* JavaScript
* Linux
* Laravel
* MYSQL
* Next JS
* Node JS
* PHP

## What does this PR do?

Added resources and improved repo

## For resources
### Description

### Why is this valuable (or not)?

This open-source contribution is valuable because it allows Malayali students to learn coding in their native language, Malayalam. By making coding more accessible to students in their native language, this open-source contribution can help to increase access to coding resources and potentially open up a new world of opportunities for Malayali students.
NB: Malayalam is the native language of Kerala. Kerala is situated in INDIA

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

This is an online course

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2023-05-11 14:32 UTC, eshellman requested changes
Please make edits on this PR (don't close it - that wipes out the comments)

2023-05-11 14:32 UTC, eshellman commented on courses/free-courses-ml.md
> +* [Index](#index)
remove this

2023-05-11 14:32 UTC, eshellman commented on courses/free-courses-ml.md
> +* [C# (C Sharp) Malayalam Tutorial](https://www.youtube.com/playlist?list=PL1JrLEBAapUW5ijzyEqYxRawB73rsjHW9) - Yes Tech Media
L > C

2023-05-11 14:32 UTC, eshellman commented on courses/free-courses-ml.md
> +* [Docker Tutorial](https://www.youtube.com/playlist?list=PLmFap_OoBJh7Z5tTSkeXciuIMZnKdJ1uu) - Tech Trivandrum
It's usually not helpful to add a category for a single resource. Try to find another category, or see if there are other books in our lists that would fit into your category.

2023-05-11 14:32 UTC, eshellman commented on courses/free-courses-ml.md
> +* [Flutter Beginner Tutorials](https://www.youtube.com/playlist?list=PLr11YFCnWCCMQYU8z3Gol2gVA2nBtoKVo) - Mallu Developer
B < M

2023-05-11 14:32 UTC, eshellman commented on courses/free-courses-ml.md
> +* [Game development challenge tutorial series](https://www.youtube.com/playlist?list=PLY-ecO2csVHegnXkm4aLAZTRF_3nTMJMW) - Brototype Malayalam
T > c

2023-05-11 14:32 UTC, eshellman commented on courses/free-courses-ml.md
> +* [Java](https://www.youtube.com/playlist?list=PLY-ecO2csVHeKaBI7lAM1jbIPU8K6fUxY) - Brototype
'java' < 'java p'

2023-05-11 14:32 UTC, eshellman commented on courses/free-courses-ml.md
> +* [React in malayalam](https://www.youtube.com/playlist?list=PLCOzHVsG8mkrePHYn73VBEK4dqwa4W7LU) - Web Diar
i < j

2023-05-11 14:32 UTC, eshellman commented on courses/free-courses-ml.md
> +* [Learn Linux Malayalam](https://www.youtube.com/playlist?list=PLQzHWfiB9fWcImNxiu-wgnurqLM3fKNDY) - Learn Programming In Malayalam
Le < Li

2023-05-11 14:32 UTC, eshellman commented on courses/free-courses-ml.md
> +* [Mysql Malayalam tutorial series](https://www.youtube.com/playlist?list=PLBKJGko2JEdFKFGGVaveL5IOxxSNq3eBS) - Tintu Vlogger
tutorial < tutorials

2023-05-11 14:32 UTC, eshellman commented on courses/free-courses-ml.md
> +* [Python Django malayalam](https://www.youtube.com/playlist?list=PLFUS7KFPLkNYStmg2qIUGctQ2OOO0Mw63) - DotPy Media
D < P

2023-05-11 16:02 UTC, RijoKsd commented
🎉 Added playlist in alphabetic order

2023-05-12 14:39 UTC, eshellman requested changes
Almost!

2023-05-12 14:39 UTC, eshellman commented on courses/free-courses-ml.md
> +* [C programming](https://www.youtube.com/playlist?list=PLY-ecO2csVHeKaBI7lAM1jbIPU8K6fUxY) - Brototype malayalam
needs to move up to the other one with the same title

2023-05-12 18:16 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2023-05-12 18:16 UTC, merged