Add course: Python for OSINT. 21 day course for beginners (#9362)
EbookFoundation/free-programming-books pull request #9483
Opened 2023-07-25 19:44 UTC by KairoQalb

## What does this PR do?
Add resource(s) 

## For resources
Python
### Description
This pull request is solving issue #9362 

### Why is this valuable (or not)?
This is a course for beginners who want to learn Python for OSINT. It's beginner-friendly with full of details and valuable insights. Anyone can download the PDF for free and without any signup. 

### How do we know it's really free?
It's an open-source course repository on GitHub with a free PDF.

### For book lists, is it a book? For course lists, is it a course? etc.
It's a course.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2023-07-25 20:46 UTC, KairoQalb commented
Sorry, I think I made a mistake in alphabetical ordering.

2023-07-26 16:02 UTC, eshellman commented on courses/free-courses-en.md
> +* [Python for OSINT. 21 day course for beginners](https://github.com/cipher387/python-for-OSINT-21-days) - cyb_detective (GitHub Repository with PDF)
```suggestion
* [Python for OSINT. 21 day course for beginners](https://github.com/cipher387/python-for-OSINT-21-days/raw/main/Python%20for%20OSINT.%2021%20day%20course%20for%20beginners.pdf) - cyb_detective (PDF)
```

2023-07-26 20:22 UTC, eshellman requested changes
Be sure to check the free-programming-books-lint output for linter errors. Alphabetical order and spacing are the most common problems.

2023-07-26 22:05 UTC, KairoQalb commented
> Be sure to check the free-programming-books-lint output for linter errors. Alphabetical order and spacing are the most common problems.

First, the error indicated swapping l.1220 and l.1219  alphabetize-lists  remark-lint 
Now it's: swap l.1221 and l.1220  alphabetize-lists  remark-lint
I'm sorry for these errors.
Should I close this pull request?

2023-07-27 11:33 UTC, innovation-machine commented
> First, the error indicated swapping l.1220 and l.1219 alphabetize-lists remark-lint Now it's: swap l.1221 and l.1220 alphabetize-lists remark-lint I'm sorry for these errors. Should I close this pull request?

No no @KairoQalb. Just make the stated changes You are good to go! 👍

2023-07-27 11:45 UTC, KairoQalb commented
> > First, the error indicated swapping l.1220 and l.1219 alphabetize-lists remark-lint Now it's: swap l.1221 and l.1220 alphabetize-lists remark-lint I'm sorry for these errors. Should I close this pull request?
> 
> No no @KairoQalb. Just make the stated changes You are good to go! 👍

Thanks! Okay, I get it. All checks are cleared now.

2023-07-27 14:05 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2023-07-27 14:05 UTC, merged