feat: added web development free courses for beginners
EbookFoundation/free-programming-books pull request #9598
Opened 2023-10-01 04:46 UTC by Jeyaprabakar01

## What does this PR do?
Add resource(s)

## For resources

### Description
These resources are for those who want to get started with Front-end web development. It covers such things as Git,GitHub, HTML, CSS, JavaScript, and React.

### Why is this valuable (or not)?
The provided resources are easy to follow and fully free. They can learn by following step-by-step instructions. so as beginners, they can easily learn these skills.

### How do we know it's really free?
The provided courses are from YouTube and Microsoft Learn. Always, they both are fully free.

### For book lists, is it a book? For course lists, is it a course? etc.
It's a course.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2023-10-01 14:40 UTC, eshellman commented
For microsoft Learn, I think we'll want to list the paths and not the modules.

2023-10-01 15:17 UTC, Jeyaprabakar01 commented
> For microsoft Learn, I think we'll want to list the paths and not the modules.

yeah that's correct. Now I modified the courses with the paths

2023-10-01 23:20 UTC, eshellman commented
For youtube, we prefer "playlist" links and the name of the producer/creator. docs/CONTRIBUTING.md#platforms-and-access-notes

2023-10-03 10:13 UTC, Jeyaprabakar01 commented
> I modified the courses with the paths

 I modified the youtube videos with the playlists and pushed

2023-10-03 10:13 UTC, Jeyaprabakar01 commented
> For youtube, we prefer "playlist" links and the name of the producer/creator. docs/CONTRIBUTING.md#platforms-and-access-notes

I modified the youtube videos with the playlists and pushed

2023-10-07 18:31 UTC, eshellman requested changes
Don't invent titles! Use the title given by the resource.
Remove tracking ids from urls
when you've made changes, please add `(changes made)` to the title of your PR

2023-10-07 18:31 UTC, eshellman commented on courses/free-courses-en.md
> +* [A Collaborate with others with Markdown and GitHub Pages](https://learn.microsoft.com/en-us/training/paths/collaborate-markdown-github-pages/) - Microsoft Learn
```suggestion
* [Collaborate with others with Markdown and GitHub Pages](https://learn.microsoft.com/en-us/training/paths/collaborate-markdown-github-pages/) - Microsoft Learn
```

2023-10-07 18:31 UTC, eshellman commented on courses/free-courses-en.md
> +* [30 JavaScript Projects For Beginners](https://youtube.com/playlist?list=PLjwm_8O3suyOgDS_Z8AWbbq3zpCmR-WE9&si=fofo8k2c5sjQPOKq) - GreatStack
```suggestion
* [30 Days, 30 JavaScript Projects For Beginners to Practice](https://youtube.com/playlist?list=PLjwm_8O3suyOgDS_Z8AWbbq3zpCmR-WE9&si=fofo8k2c5sjQPOKq) - GreatStack
```

2023-10-07 18:31 UTC, eshellman commented on courses/free-courses-en.md
> +* [React Course For Beginners](https://www.youtube.com/playlist?list=PLpPqplz6dKxW5ZfERUPoYTtNUNvrEebAR) - PedroTech
```suggestion
* [ReactJS Course For Beginners 2023](https://www.youtube.com/playlist?list=PLpPqplz6dKxW5ZfERUPoYTtNUNvrEebAR) - PedroTech
```

2023-10-07 18:31 UTC, eshellman commented on courses/free-courses-en.md
> +* [JavaScript tutorial for beginners](https://youtube.com/playlist?list=PL9bD98LkBR7P16BndaNtP4x6Wf5Ib85Hm&si=u_pP2hpNXqa2_2QY) - Tech2 etc
****
```suggestion
* [JavaScript Projects For Beginners \| Easy To Advance](https://youtube.com/playlist?list=PL9bD98LkBR7P16BndaNtP4x6Wf5Ib85Hm) - Tech2 etc
```

2023-11-21 18:29 UTC, merged