added Sinhala translation of the code of conduct
EbookFoundation/free-programming-books pull request #9611
Opened 2023-10-01 07:46 UTC by Viraj121

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2023-10-01 08:09 UTC, samithkavishke reviewed
Yeah looks good

2023-10-01 08:11 UTC, samithkavishke commented on docs/CODE_OF_CONDUCT-si.md
> +මෙම චර්යාධර්ම සංග්‍රහය ව්‍යාපෘති අවකාශයන් තුළ මෙන්ම පොදු අවකාශයන්හිද අදාළ වේ
does not give the correct meaning

2023-10-01 08:12 UTC, samithkavishke commented on docs/CODE_OF_CONDUCT-si.md
> +සහභාගිවන්නන් විසින් පිළිගත නොහැකි හැසිරීම් සඳහා උදාහරණ ඇතුළත් වේ:
state as below is the correct one, පහත දක්වා ඇත. change it

2023-10-01 08:15 UTC, Viraj121 commented on docs/CODE_OF_CONDUCT-si.md
> +මෙම චර්යාධර්ම සංග්‍රහය ව්‍යාපෘති අවකාශයන් තුළ මෙන්ම පොදු අවකාශයන්හිද අදාළ වේ
okay I'll look into it

2023-10-01 08:15 UTC, samithkavishke requested changes

2023-10-01 08:15 UTC, samithkavishke commented on docs/CODE_OF_CONDUCT-si.md
> +
Above paragraph is not accurate

2023-10-01 08:15 UTC, samithkavishke commented on docs/CODE_OF_CONDUCT-si.md
> +විවෘත සහ පිළිගැනීමේ ප්‍රජාවක් පෝෂණය කරමින්, සියලු මිනිසුන්ට ගරු කිරීමට අපි ප්‍රතිඥා දෙමු
state all the sentence in simple Sinhala don't use a translator

2023-10-01 08:15 UTC, samithkavishke commented on docs/CODE_OF_CONDUCT-si.md
> +තර්ජනාත්මක, ආක්‍රමණශීලී හෝ හානිකර.
Not correct in grammar

2023-10-01 14:20 UTC, eshellman commented
thank you @samithkavishke for helping with review.

2023-10-09 16:06 UTC, eshellman commented
@Viraj121 please address the comments

2024-03-27 14:08 UTC, closed without merging