add in free-courses-hi frameworks like spring boot,spring core,spring…
EbookFoundation/free-programming-books pull request #9612
Opened 2023-10-01 07:49 UTC by Himanshusinghtomar

… mvc,Hibernate,servlet jsp , hosting on aws java

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2023-10-01 07:50 UTC, Himanshusinghtomar commented
Provided few more framework courses on java

2023-10-01 07:57 UTC, Himanshusinghtomar commented
include all inside java index

2023-10-01 08:23 UTC, Himanshusinghtomar commented
add java hindi courses

2023-10-01 19:19 UTC, Himanshusinghtomar commented
Resolved Conflict

2023-10-01 23:40 UTC, eshellman commented on courses/free-courses-hi.md
> +* [AWS Hosting Tutorial | Deploying Java Applications on Amazon EC2 in Hindi](https://youtube.com/playlist?list=PL0zysOflRCek6D-kLRM48rhyvTEbc60nc&si=9ILVhPNVuvemweEJ) - Learn Code With Durgesh
escape the `|`

2023-10-01 23:42 UTC, eshellman commented
when you've made changes, please add `(changes made)` to the title of your PR

2023-10-03 17:47 UTC, eshellman requested changes
also remove tracking code for last to spring tutorials.
when you've made changes, please add `(changes made)` to the title of your PR

2023-10-03 17:47 UTC, eshellman commented on courses/free-courses-hi.md
> +* [AWS Hosting Tutorial | Deploying Java Applications on Amazon EC2 in Hindi](https://youtube.com/playlist?list=PL0zysOflRCek6D-kLRM48rhyvTEbc60nc&si=9ILVhPNVuvemweEJ) - Learn Code With Durgesh
```suggestion
* [AWS Hosting Tutorial \| Deploying Java Applications on Amazon EC2 in Hindi](https://youtube.com/playlist?list=PL0zysOflRCek6D-kLRM48rhyvTEbc60nc) - Learn Code With Durgesh
```

2023-10-03 17:47 UTC, eshellman commented on courses/free-courses-hi.md
> +* [Hibernate tutorial Basic to Advance in Hindi](https://youtube.com/playlist?list=PL0zysOflRCekX8OO7V7pGQ9kxZ28JyJlk&si=thD-RnaLu6VPDpDr) - Learn Code With Durgesh
```suggestion
* [Hibernate tutorial Basic to Advance in Hindi](https://youtube.com/playlist?list=PL0zysOflRCekX8OO7V7pGQ9kxZ28JyJlk) - Learn Code With Durgesh
```

2023-10-03 17:47 UTC, eshellman commented on courses/free-courses-hi.md
> +* [Spring Boot tutorial basic in Hindi](https://youtube.com/playlist?list=PL0zysOflRCelmjxj-g4jLr3WKraSU_e8q&si=nZizMDReuxWBM3hB) - Learn Code With Durgesh
```suggestion
* [Spring Boot tutorial basic in Hindi](https://youtube.com/playlist?list=PL0zysOflRCelmjxj-g4jLr3WKraSU_e8q) - Learn Code With Durgesh
```

2023-10-03 17:47 UTC, eshellman commented on courses/free-courses-hi.md
> +* [Servlet and Jsp](https://youtube.com/playlist?list=PL0zysOflRCel5BSXoslpfDawe8FyyOSZb&si=pyUQrpB8bp-pbrR7) - Learn Code With Durgesh
```suggestion
* [Servlet and Jsp](https://youtube.com/playlist?list=PL0zysOflRCel5BSXoslpfDawe8FyyOSZb) - Learn Code With Durgesh
```

2023-10-03 18:32 UTC, Himanshusinghtomar reviewed
change made

2023-10-03 18:46 UTC, Himanshusinghtomar commented
all change made

2023-10-03 18:47 UTC, Himanshusinghtomar commented on courses/free-courses-hi.md
> +* [Hibernate tutorial Basic to Advance in Hindi](https://youtube.com/playlist?list=PL0zysOflRCekX8OO7V7pGQ9kxZ28JyJlk&si=thD-RnaLu6VPDpDr) - Learn Code With Durgesh
change made

2023-10-04 00:49 UTC, eshellman requested changes
please be careful rsolving conflicts

2023-10-04 00:49 UTC, eshellman commented on courses/free-courses-hi.md
> -* [Java and DSA Foundation Course](https://youtube.com/playlist?list=PLxgZQoSe9cg00xyG5gzb5BMkOClkch7Gr&si=ctLRknqelKTSI5Lh) - College Wallah
did you mean to remove this?

2023-10-04 00:49 UTC, eshellman commented on courses/free-courses-hi.md
> +* [Java Foundation Course | Hindi](https://www.youtube.com/playlist?list=PL-Jc9J83PIiFj7YSPl2ulcpwy-mwj1SSk) - Pepcoding
did you mean to revert this

2023-10-10 07:20 UTC, Himanshusinghtomar commented on courses/free-courses-hi.md
> +* [Java Foundation Course | Hindi](https://www.youtube.com/playlist?list=PL-Jc9J83PIiFj7YSPl2ulcpwy-mwj1SSk) - Pepcoding
yes

2023-10-16 02:43 UTC, Himanshusinghtomar commented
change done

2023-10-16 17:24 UTC, eshellman commented
It looks to me like you inadvertently removed good resources while trying to resolve conflicts. when resolving conflicts, please do not undo the work that others have done.

2023-11-13 05:16 UTC, eshellman commented
course added in fe15c9c738c82b1d7c032585304ef63c7b6fa15e

2023-11-13 05:16 UTC, closed without merging