Guide to Discrete Mathematics Book Add
EbookFoundation/free-programming-books pull request #9628
Opened 2023-10-01 10:32 UTC by SenukDias

## What does this PR do?
Add resource

## For resources

Guide to Discrete Mathematics.pdf

### Description

Guide to practice mathematics

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2023-10-01 10:38 UTC, SenukDias reviewed
new

2023-10-01 13:57 UTC, Ashu104 commented
423:1-544:192  warning  Alphabetical ordering: swap l.544 and l.543  alphabetize-lists  remark-lint
  423:1-544:192  warning  Incorrect number of blank lines between last section and next heading  blank-lines-1-0-2  remark-lint
  550:1-55[6](https://github.com/EbookFoundation/free-programming-books/actions/runs/6369968862/job/17290659312?pr=9628#step:5:7):149  warning  Incorrect number of blank lines between last section and next heading  blank-lines-1-0-2  remark-lint

** for this error change alphabet order of your commit on line 192 and you too some blank lines, go emit them.

2023-10-01 14:21 UTC, eshellman commented
Thanky you @Ashu104 for helping

2023-10-03 02:14 UTC, Thenlie requested changes
I believe this link is wrong and should not link to the free-programming-books GitHub repo. I think this should link to https://core.ac.uk/download/pdf/326762636.pdf instead or another external resource.

Also, please check the output of free-programming-books-lint and fix the errors. Update the title with `(changes made)` once the lint check is passing. Thanks!

2023-10-04 15:54 UTC, SenukDias reviewed
new

2023-10-04 16:02 UTC, SenukDias reviewed
new

2023-10-04 16:08 UTC, SenukDias commented
now?!!

2023-10-04 16:11 UTC, SenukDias reviewed
link update

2023-10-04 16:30 UTC, Thenlie requested changes
Thank you for the contribution! It does not look like the word "book" is actually in the title. Once that is fixed I believe this is ready to merge.

Please update the PR title with `(changes made)` once you have made this change.

2023-10-04 16:30 UTC, Thenlie commented on books/free-programming-books-subjects.md
> +* [Guide to Discrete Mathematics Book](https://core.ac.uk/download/pdf/326762636.pdf) - David Gries, Fred B. Schneider (PDF)
```suggestion
* [Guide to Discrete Mathematics](https://core.ac.uk/download/pdf/326762636.pdf) - David Gries, Fred B. Schneider (PDF)
```

2023-10-04 17:05 UTC, Thenlie approved these changes

2023-11-05 19:14 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2023-11-05 19:14 UTC, merged