React course modified
EbookFoundation/free-programming-books pull request #9691
Opened 2023-10-02 06:40 UTC by OmKanhe

## What does this PR do?
Add resources

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2023-10-03 01:49 UTC, Thenlie requested changes
Please check the output of free-programming-books-lint and fix the errors. Update the title with `(changes made)` once the lint check is passing. Thanks!

2023-10-03 01:49 UTC, Thenlie commented on more/free-programming-interactive-tutorials-en.md
> +* [React Tutorial](https://react-tutorial.app) - React Tutorial
This looks like a duplicate of line 263

2023-10-03 01:51 UTC, Thenlie commented on more/free-programming-interactive-tutorials-en.md
> +* [React Tutorial](https://react-tutorial.app) - React Tutorial
Maybe we could update this to credit the author, Jad Joubran.

2023-11-13 05:47 UTC, eshellman commented
added in fe15c9c738c82b1d7c032585304ef63c7b6fa15e

2023-11-13 05:47 UTC, closed without merging