add more ptbr courses
EbookFoundation/free-programming-books pull request #9725
Opened 2023-10-02 15:13 UTC by rubenmarcus

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2023-10-03 00:11 UTC, eshellman commented
For youtube, we prefer "playlist" links and the name of the producer/creator. docs/CONTRIBUTING.md#platforms-and-access-notes
when you've made changes, please add `(changes made)` to the title of your PR

2023-10-03 09:32 UTC, rubenmarcus commented
@eshellman I see but some of the videos arent playlists they full courses in only 1 video

2023-10-03 14:56 UTC, eshellman commented on courses/free-courses-pt_BR.md
> +* [Curso Lógica de Programação Completo 2023 [Iniciantes] + Desafios + Muita prática](https://www.youtube.com/watch?v=iF2MdbrTiBM) - Jonathan de Souza
3 hours. ok.

2023-10-03 14:56 UTC, eshellman commented on courses/free-courses-pt_BR.md
> +* [Nest.js do zero aos microsserviços](https://www.youtube.com/watch?v=VP5-RKpfHIg) - Full Cycle
what? you have to subscribe to see the course. declined.

2023-10-03 14:56 UTC, eshellman commented on courses/free-courses-pt_BR.md
> +* [Curso Javascript Completo 2023 [Iniciantes] + 14 Mini-Projetos](https://www.youtube.com/watch?v=i6Oi-YtXnAU) - Jhonatan de Souza
4 hours. ok

2023-10-03 14:58 UTC, eshellman commented on courses/free-courses-pt_BR.md
> +* [Kubernetes para Devs Javascript](https://www.youtube.com/watch?v=Co1xmcQS6Bw&list=PLqFwRPueWb5ccEFVx5vOvrKlYT_uQ3aQw) - Erick Wendel e Lucas Santos
use the playlist

2023-10-03 15:00 UTC, eshellman requested changes
For youtube, we prefer "playlist" links and the name of the producer/creator. docs/CONTRIBUTING.md#platforms-and-access-notes
we'll accept single videos > 1 hr if there's no playlist
when you've made changes, please add `(changes made)` to the title of your PR

2023-10-04 16:15 UTC, rubenmarcus commented
thanks @eshellman  done the changes

2023-10-04 20:39 UTC, eshellman requested changes
a few more changes

2023-10-04 20:39 UTC, eshellman commented on courses/free-courses-pt_BR.md
> +* [Next js 13.4 Masterclass Prático c/ Stripe e Shadcn-ui](https://www.youtube.com/watch?v=b0AinejyevM&list=PLR8OzKI52ppWoTRvAmB_FQPPlHS0otV7V&index=19) - DeveloperDeck101
I think you want https://www.youtube.com/playlist?list=PLR8OzKI52ppWoTRvAmB_FQPPlHS0otV7V

2023-10-05 00:05 UTC, rubenmarcus commented
@eshellman  thanks for the patience, and also for the detailed review! Done the suggested changes!

2023-10-05 01:43 UTC, eshellman commented
Thanks, and welcome to free-programming-books!

2023-10-05 01:43 UTC, merged