New course Added (hacktoberfest)
EbookFoundation/free-programming-books pull request #9920
Opened 2023-10-06 04:05 UTC by ravi0900

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description
added 2 hi courses
https://www.youtube.com/watch?v=xy138_iUfaI&list=PLAOnhLRjMTMDigfUzaAAQo7lbfScPFtHs
https://www.youtube.com/playlist?list=PLdOT12odxrUrUExBUuM5KoN0fAnOdzH1L

### Why is this valuable (or not)?
game development course is very valuable as I watched, and dbms playlist is helpful for hindi native speaker who starting there jorney in dbms.

### How do we know it's really free?
youtube videos
### For book lists, is it a book? For course lists, is it a course? etc.
Course
## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up
No
- Check the status of GitHub Actions and resolve any reported warnings!
ok

2023-10-06 16:01 UTC, eshellman commented
For youtube, we prefer "playlist" links and the name of the producer/creator. docs/CONTRIBUTING.md#platforms-and-access-notes
when you've made changes, please add `(changes made)` to the title of your PR
"Hacktoberfest" is not a useful PR title

2023-10-06 16:44 UTC, ravi0900 commented
@eshellman I'm sorry, I should not add so many hacktoberfest labels, but ya I really respect this project and your work, I humbly want to contribute here, I have made the changes, please accept my PR, Thank you.

2023-10-07 18:51 UTC, eshellman requested changes
also, use the instructors name OR the channel name, not both

2023-10-07 18:51 UTC, eshellman commented on courses/free-courses-hi.md
> +* [Database Management System (DBMS) in Hindi](https://www.youtube.com/watch?v=xy138_iUfaI&list=PLAOnhLRjMTMDigfUzaAAQo7lbfScPFtHs) - Jitendra Ajmedha, The Crazy Programmer
use the playlist! i.e. https://www.youtube.com/playlist?list=PLAOnhLRjMTMDigfUzaAAQo7lbfScPFtHs

2023-10-08 21:17 UTC, merged