Adding Courses for Hindi Language
EbookFoundation/free-programming-books pull request #9968
Opened 2023-10-07 17:49 UTC by Ravikisha

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## For resources
### Description

### Why is this valuable (or not)?

### How do we know it's really free?

### For book lists, is it a book? For course lists, is it a course? etc.

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

2023-10-08 00:21 UTC, eshellman requested changes
It's easier to get a PR approved if it makes fewer changes

2023-10-08 00:21 UTC, eshellman commented on courses/free-courses-hi.md
> +* [Cyber Security](#cyber-security)
Most of our lists just use "Security"

2023-10-08 00:21 UTC, eshellman commented on courses/free-courses-hi.md
> +* [ASP.NET CORE 6.0 TUTORIALS IN HINDI](https://www.youtube.com/playlist?list=PL18HZjtdIA4DiYGQj1zst6myBAVE3wgMg) - Technology Keeda
no ALL CAPS

2023-10-08 00:21 UTC, eshellman commented on courses/free-courses-hi.md
> +* [ASP.NET CORE TUTORIALS IN HINDI](https://www.youtube.com/playlist?list=PL18HZjtdIA4Al-wYHC-i2TA-lgXLvHVmB) - Technology Keeda
no ALL CAPS

2023-10-08 00:21 UTC, eshellman commented on courses/free-courses-hi.md
> +* [Ethical Hacking Full Couse || Cyber Security in Hindi](https://www.youtube.com/playlist?list=PLa2xctTiNSCibSUhgYI2RT_loUJP9rDN6) - Masters in IT
escape the `|`

2023-10-08 00:21 UTC, eshellman commented on courses/free-courses-hi.md
> +* [Spring Framework Tutorial with SpringBoot | in Hindi| Complete Course | CoderX Ankit](https://www.youtube.com/playlist?list=PLiOIhBfKi8AIYNWEjYy1zZFe1N8GvPRHR) - CoderX Ankit
escape the `|`

2023-10-08 00:21 UTC, eshellman commented on courses/free-courses-hi.md
> +* [Laravel 10 Tutorial Course in Hindi / Urdu](PL0b6OzIxLPbz7JK_YYrRJ1KxlGG4diZHJ) - Yahoo Baba
you forgot the link

2023-10-08 00:21 UTC, eshellman commented on courses/free-courses-hi.md
> +* [ASP.NET CORE 6.0 TUTORIALS IN HINDI](https://www.youtube.com/playlist?list=PL18HZjtdIA4DiYGQj1zst6myBAVE3wgMg) - Technology Keeda
shouldn't this one supercede the following one? Why both?

2023-10-08 04:02 UTC, Ravikisha commented
**Update Requested Changes 👍**

Thank you for addressing the feedback provided in the initial review. I've reviewed the changes you made.

Feel free to reach out if you have any questions or need further clarification on any of these points. Let's work together to ensure the code meets your standards and requirements. Thanks for your effort!

2023-10-08 21:31 UTC, Ravikisha commented
I resolved the conflict and Thanks for your effort.

2023-10-09 03:18 UTC, eshellman commented on courses/free-courses-hi.md
> +* [React Native Tutorials (mobile app development) in hindi](https://www.youtube.com/playlist?list=PLB97yPrFwo5gxB5SuNWzH73t2Su65KN2f) - CODERS NEVER QUIT
no ALL CAPS

2023-10-09 03:38 UTC, Ravikisha commented
Sorry for the issue.

2023-10-09 15:34 UTC, eshellman commented on courses/free-courses-hi.md
> +* [Spring Framework Tutorial with SpringBoot | in Hindi| Complete Course | CoderX Ankit](https://www.youtube.com/playlist?list=PLiOIhBfKi8AIYNWEjYy1zZFe1N8GvPRHR) - CoderX Ankit
```suggestion
* [Spring Framework Tutorial with SpringBoot  in Hindi Complete Course](https://www.youtube.com/playlist?list=PLiOIhBfKi8AIYNWEjYy1zZFe1N8GvPRHR) - CoderX Ankit
```

2023-10-09 16:22 UTC, eshellman commented
Thanks, and welcome to free-programming-books! For future PRs, you can minimize conflicts by working on one section at a time.

2023-10-09 16:22 UTC, merged